### ISSUE TITLE
Update Rubocop

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#1005]
Codeship is failing due to this.

<pre>
Completed all RSpec tests
cd /home/rof/src/github.com/shakacode/react_on_rails && yarn run eslint
yarn run v1.0.2
$ eslint .
e/rof/src/github.com/shakacode/react_on_rails && yarn run flow
yarn run v1.0.2
$ flow check node_package
Found 0 errors
e/rof/src/github.com/shakacode/react_on_rails && bundle exec rubocop .
Inspecting 139 files
W...........C.C...............C..........C.........C.......WC..............................C.WWCCC.C......C.....CWW.......CW.............CW

Offenses:

react_on_rails.gemspec:7:1: W: Lint/MissingCopEnableDirective: Re-enable Metrics/BlockLength cop with # rubocop:enable after disabling it.
# rubocop:disable Metrics/BlockLength
^
react_on_rails.gemspec:26:29: C: Gemspec/RequiredRubyVersion: required_ruby_version (2.0, declared in react_on_rails.gemspec) and TargetRubyVersion (2.3, declared in .rubocop.yml) should be equal.
s.required_ruby_version = ">= 2.0.0"
^^^^^^^^^^
spec/react_on_rails/support/generator_spec_helper.rb:10:1: C: Style/MixinUsage: include is used at the top level. Use inside class or module.
include ReactOnRails::Generators
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
spec/react_on_rails/spec_helper.rb:32:1: C: Style/IfUnlessModifier: Favor modifier unless usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
unless File.basename(ENV["BUNDLE_GEMFILE"] || "") == "Gemfile.rails32"
^^^^^^
spec/dummy_no_webpacker/spec/rails_helper.rb:72:3: C: Style/IfUnlessModifier: Favor modifier unless usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
unless supported_drivers.include?(driver)
^^^^^^
spec/dummy_no_webpacker/config/environment.rb:8:1: C: Style/IfUnlessModifier: Favor modifier if usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
if File.basename(ENV["BUNDLE_GEMFILE"] || "") == "Gemfile.rails32"
^^
spec/dummy_no_webpacker/Gemfile:24:1: C: Style/IfUnlessModifier: Favor modifier if usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
if ENV["DISABLE_TURBOLINKS"].nil? || ENV["DISABLE_TURBOLINKS"].strip.empty?
^^
spec/dummy/spec/requests/console_logging_spec.rb:10:1: W: Lint/MissingCopEnableDirective: Re-enable Layout/IndentHeredoc cop with # rubocop:enable after disabling it.
# rubocop:disable Layout/IndentHeredoc
^
spec/dummy/spec/rails_helper.rb:83:3: C: Style/IfUnlessModifier: Favor modifier unless usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
unless supported_drivers.include?(driver)
^^^^^^
spec/dummy/Gemfile:31:1: C: Style/IfUnlessModifier: Favor modifier if usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
if ENV["DISABLE_TURBOLINKS"].nil? || ENV["DISABLE_TURBOLINKS"].strip.empty?
^^
rakelib/run_rspec.rake:10:1: C: Style/MixinUsage: include is used at the top level. Use inside class or module.
include ReactOnRails::TaskHelpers
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rakelib/run_rspec.rake:12:1: W: Lint/MissingCopEnableDirective: Re-enable Metrics/BlockLength cop with # rubocop:enable after disabling it.
# rubocop:disable Metrics/BlockLength
^
rakelib/release.rake:4:1: C: Style/MixinUsage: include is used at the top level. Use inside class or module.
include ReactOnRails::TaskHelpers
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rakelib/release.rake:10:1: C: Layout/EmptyLinesAroundArguments: Empty line detected around arguments.
rakelib/release.rake:15:1: C: Layout/EmptyLinesAroundArguments: Empty line detected around arguments.
rakelib/release.rake:18:1: C: Layout/EmptyLinesAroundArguments: Empty line detected around arguments.
rakelib/release.rake:22:1: C: Layout/EmptyLinesAroundArguments: Empty line detected around arguments.
rakelib/release.rake:25:1: W: Lint/MissingCopEnableDirective: Re-enable Metrics/BlockLength cop with # rubocop:enable after disabling it.
# rubocop:disable Metrics/BlockLength
^
rakelib/node_package.rake:4:1: C: Style/MixinUsage: include is used at the top level. Use inside class or module.
include ReactOnRails::TaskHelpers
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rakelib/lint.rake:4:1: C: Style/MixinUsage: include is used at the top level. Use inside class or module.
include ReactOnRails::TaskHelpers
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rakelib/examples.rake:11:1: C: Style/MixinUsage: include is used at the top level. Use inside class or module.
include ReactOnRails::TaskHelpers
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
rakelib/dummy_apps.rake:4:1: C: Style/MixinUsage: include is used at the top level. Use inside class or module.
include ReactOnRails::TaskHelpers
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/react_on_rails/utils.rb:105:7: C: Style/IfUnlessModifier: Favor modifier if usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
if @rails_version_less_than.key?(version)
^^
lib/react_on_rails/server_rendering_pool/node.rb:61:13: C: Style/WhileUntilModifier: Favor modifier while usage when having a single-line body.
while result[-eof_symbol.length..-1] != eof_symbol
^^^^^
lib/react_on_rails/server_rendering_pool/exec.rb:101:11: C: Style/RescueStandardError: Avoid rescuing without specifying an error class.
rescue => e # rubocop:disable Lint/RescueWithoutErrorClass
^^^^^^
lib/react_on_rails/server_rendering_pool/exec.rb:101:23: W: Lint/UnneededDisable: Unnecessary disabling of Lint/RescueWithoutErrorClass (unknown cop).
rescue => e # rubocop:disable Lint/RescueWithoutErrorClass
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/react_on_rails/server_rendering_pool/exec.rb:118:11: C: Style/RescueStandardError: Avoid rescuing without specifying an error class.
rescue => e # rubocop:disable Lint/RescueWithoutErrorClass
^^^^^^
lib/react_on_rails/server_rendering_pool/exec.rb:118:23: W: Lint/UnneededDisable: Unnecessary disabling of Lint/RescueWithoutErrorClass (unknown cop).
rescue => e # rubocop:disable Lint/RescueWithoutErrorClass
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/react_on_rails/server_rendering_pool.rb:21:1: W: Lint/MissingCopEnableDirective: Re-enable Style/MethodMissing cop with # rubocop:enable after disabling it.
# rubocop:disable Style/MethodMissing
^
lib/react_on_rails/configuration.rb:65:5: C: Style/IfUnlessModifier: Favor modifier if usage when having a single-line body. Another good alternative is the usage of control flow &&/||.
if @configuration.server_bundle_js_file.present?
^^
lib/react_on_rails/configuration.rb:88:1: C: Layout/EmptyLinesAroundArguments: Empty line detected around arguments.
lib/react_on_rails/configuration.rb:101:1: C: Layout/EmptyLinesAroundArguments: Empty line detected around arguments.
lib/react_on_rails/assets_precompile.rb:105:9: C: Style/RescueStandardError: Avoid rescuing without specifying an error class.
rescue # rubocop:disable Lint/RescueWithoutErrorClass
^^^^^^
lib/react_on_rails/assets_precompile.rb:105:16: W: Lint/UnneededDisable: Unnecessary disabling of Lint/RescueWithoutErrorClass (unknown cop).
rescue # rubocop:disable Lint/RescueWithoutErrorClass
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/react_on_rails/assets_precompile.rb:142:5: C: Style/RescueStandardError: Avoid rescuing without specifying an error class.
rescue # rubocop:disable Lint/RescueWithoutErrorClass
^^^^^^
lib/react_on_rails/assets_precompile.rb:142:12: W: Lint/UnneededDisable: Unnecessary disabling of Lint/RescueWithoutErrorClass (unknown cop).
rescue # rubocop:disable Lint/RescueWithoutErrorClass
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
lib/generators/react_on_rails/base_generator.rb:60:1: C: Layout/EmptyLinesAroundArguments: Empty line detected around arguments.
lib/generators/react_on_rails/base_generator.rb:65:1: C: Layout/EmptyLinesAroundArguments: Empty line detected around arguments.
app/helpers/react_on_rails_helper.rb:3:1: W: Lint/MissingCopEnableDirective: Re-enable Metrics/ModuleLength cop with # rubocop:enable after disabling it.
# rubocop:disable Metrics/ModuleLength
^
app/helpers/react_on_rails_helper.rb:475:1: W: Lint/MissingCopEnableDirective: Re-enable Metrics/AbcSize cop with # rubocop:enable after disabling it.
# rubocop:disable Metrics/AbcSize
^

139 files inspected, 40 offenses detected
</pre>

**Comment by reconstructions** [comment]
@justin pls let me what minimum Ruby version we should be supporting.  

`react_on_rails.gemspec` has [s.required_ruby_version = ">= 2.0.0"](https://github.com/shakacode/react_on_rails/blob/5eea919197cef735a9ba649b97d5a7d3a6b7c9a4/react_on_rails.gemspec#L26), but rubocop can't be set to version 2.0 in [`.rubocop.yml`](https://github.com/shakacode/react_on_rails/blob/5eea919197cef735a9ba649b97d5a7d3a6b7c9a4/.rubocop.yml#L6) because:
```
Error: Unsupported Ruby version 2.0 found in `TargetRubyVersion` parameter 
(in .rubocop.yml). 2.0-compatible analysis was dropped after version 0.50.
Supported versions: 2.1, 2.2, 2.3, 2.4, 2.5
```

Advancing s.required_ruby_version to ">= 2.1.0" fixes this and increases rubocop offenses from 40 to 47, I'll move ahead fixing those.

**Comment by reconstructions** [comment]
@justin here is a [first pass](https://github.com/reconstructions/react_on_rails/commit/ad8c4ffe014c99077d791c59f9d2c51b37d3de4c) on the rubocop errors, `rake` and `rake lint:rubocop` tests are all green, I am still checking otherwise.

There could be a rubocop [false positive](https://github.com/bbatsov/rubocop/issues/5339) in [base_generator.rb](https://github.com/shakacode/react_on_rails/blob/5eea919197cef735a9ba649b97d5a7d3a6b7c9a4/lib/generators/react_on_rails/base_generator.rb#L58):

```
lib/generators/react_on_rails/base_generator.rb:60:1: C: Layout/EmptyLinesAroundArguments: 
Empty line detected around arguments.
lib/generators/react_on_rails/base_generator.rb:65:1: C: Layout/EmptyLinesAroundArguments: 
Empty line detected around arguments.
```

I will post an issue with rubocop asking if that is the case.

In places where code is rescuing nothing or => e I resolved the rubocop warnings by rescuing StandardError.

There is [one place](https://github.com/reconstructions/react_on_rails/blob/ad8c4ffe014c99077d791c59f9d2c51b37d3de4c/spec/react_on_rails/support/generator_spec_helper.rb#L11) where I disabled Style/MixinUsage to allow include outside of a class: 
```
spec/react_on_rails/support/generator_spec_helper.rb:10:1: C: Style/MixinUsage: 
include is used at the top level. Use inside class or module.
include ReactOnRails::Generators
```
Because right now there is no class wrapping those spec helper methods.

**Comment by justin808** [comment]
@reconstructions LGTM. Please create a PR.

**Comment by justin808** [comment]
@reconstructions on the min ruby version, yes, let's bump to 2.1.0

**Comment by reconstructions** [comment]
OK, @justin,  I will create the PR now and do the rest of my checking afterwards.

**Comment by reconstructions** [comment]
OK, @justin_808,  I will push the PR now and do the rest of my checking afterwards.
