### ISSUE TITLE
/client directory never created

### ISSUE THREAD

**Issue by macmartine** [shakacode/react_on_rails#1007]
I followed the docs to install react_on_rails into my existing Rails 5 app. The hello world page loads fine with no errors. Now I'm trying to add a new component to be rendered on the client side.

All the docs mention a /client directory, but that wasn't generated for me.

Where should I put client-rendered components, and where should I register them?

**Comment by macmartine** [comment]
When my new component uses 'prerender', it display fine. I 'prerender' is false, nothing is displayed there:

react_component("CampaignStats", props: { name: "Stranger" }, prerender: false)

**Comment by justin808** [comment]
@macmartine We tried to simplify the install for the "generator" by using Webpacker defaults.

If you want a /client directory setup, see https://github.com/shakacode/react-webpack-rails-tutorial.

**Comment by macmartine** [comment]
Hey @justin808 - Thanks for the response. I don't know if I want that /client directory or not, I just need to know how to get a client to display with prerender: false in the new set up. Any guidance appreciated.
