### ISSUE TITLE
Pack routes not loading in test environment on local machine

### ISSUE THREAD

**Issue by wxmn** [shakacode/react_on_rails#1008]
In Capybara tests, my `javascript_pack_tag "application"` simply won't load (I get an application route error), using the default `config/initializers/react_on_rails.rb`, the default `webpacker.yml` settings, and `ReactOnRails::TestHelper.configure_rspec_to_compile_assets(config)` in my `rails_helper`. 

The files seems to be in the correct place (in `public/packs-test`, there is a `public/packs-test/manifest.json` with correct information in it, and it's looking for the correct route in `public/packs-test/application-#{correct_hash}.js`, but it's not there.

I just installed the latest version of react_on_rails (10.0.2) in an existing Rails 5.1.4 app.
I'm using `Capybara-Webkit`, but I get the same errors with Selenium and Poltergeist. I've updated yarn, webpacker, npm, and every slightly related library to be on the latest versions.

Most mysteriously, the tests actually run successfully on our CircleCI build.

I've tried everything I can imagine to debug it, but I'm out of ideas. Any thoughts? Thanks!

**Comment by justin808** [comment]
@wxmn,

You have some debugging to do.
 
Would you be interested in our ShakaCode Pro Support plan? 

http://www.shakacode.com/work/shakacode-pro-support.pdf

If so, please schedule a complimentary 30-minute consultation:
https://calendly.com/justingordon

Thanks,

Justin
