### ISSUE TITLE
I18n with react-Intl message in variable expression is different

### ISSUE THREAD

**Issue by kkak10** [shakacode/react_on_rails#1021]
Rails I18n variable Expression is %{variable name}, but react-intl variable expression is {variable name}.

Help Please.

**Comment by justin808** [comment]
@kkak10 You need to provide many more details and a reproduction case in order for this report to be helpful.

**Comment by kkak10** [comment]
@justin808 sorry. 

details, I use react-on-rails with i18n.
already written rails i18n yml migrate react i18n js

### rails i18n yml
rails i18n in variable expression is `%{}`
```
label:
  greeting: 'Hello %{name}'
```

I success migrate yml file to react-intl.
but react-intl varaible expression is `{}`.

```javascript
intl.formatMessage({id: 'label.greeting'}, {name: 'justin808'})
// output is '%Hello justin808'
```

How remove react-intl in '%'?

**Comment by justin808** [comment]
@kkak10 if you can write a test case for this, I can look into seeing how we'd fix this.

**Comment by kkak10** [comment]
@justin808 where is react-on-rails with react-intl example project?
I ref to that if being example project.

**Comment by justin808** [comment]
Live at reactrails.com.

https://github.com/shakacode/react-webpack-rails-tutorial

**Comment by kkak10** [comment]
https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/config/locales/en.yml

@justin808 react-webpack-rails-tutorial project include feature i18n, but it's not include variable expression in i18n.


I try react-webpack-rails-tutorial project in variable expression i18n. but occur same issue.

**Comment by justin808** [comment]
@sepehr500 Please submit a PR with tests and a CHANGELOG entry. Can you confirm that you considered the edge cases? @kkak10 any suggestions?

**Comment by sepehr500** [comment]
@justin808 The only edge case I can think of is if somebody actually wants to have `%{` in their code. I am trying to see if https://github.com/svenfuchs/rails-i18n handles this with an escape char or something like that, but I do not think they do.

**Comment by kkak10** [comment]
I don't think the edge case that actually have `%{` we mentioned above is a problem.

@sepehr500 Thank you! This is what I wanted to do.

**Comment by sepehr500** [comment]
@justin808 #1046 is ready for review to fix this issue.
