### ISSUE TITLE
"TypeError: Cannot read property 'prototype' of undefined"

### ISSUE THREAD

**Issue by Overload119** [shakacode/react_on_rails#1024]
js_code was:
(function() {
  var railsContext = {"inMailer":false,"i18nLocale":"en","i18nDefaultLocale":"en","href":"http://localhost:3000/to/bob","location":"/to/bob","scheme":"http","host":"localhost","port":3000,"pathname":"/to/bob","search":null,"httpAcceptLanguage":"en-US,en;q=0.9","serverSide":true};

  var props = {};
  return ReactOnRails.serverRenderReactComponent({
    name: 'PostcardImage',
    domNodeId: 'PostcardImage-react-component-436f824c-5d7d-4537-acab-684cc338c6ed',
    props: props,
    trace: true,
    railsContext: railsContext
  });
})()

How should I go debugging this...

**Comment by justin808** [comment]
@Overload119 this sounds like a debugging issue. My firm can help.

Would you be interested in our ShakaCode Pro Support plan? 

http://www.shakacode.com/work/shakacode-pro-support.pdf

If so, please schedule a complimentary 30-minute consultation:
https://calendly.com/justingordon

Thanks,

Justin
