### ISSUE TITLE
Documentation: config/initializers/react_on_rails.rb

### ISSUE THREAD

**Issue by m5rk** [shakacode/react_on_rails#1027]
The generated initializer has this comment:

```
# See docs/basics/configuration.md for many more options
```

Why not just update the generated initializer to *be* the document of *all* possible configuration values?

There are currently actually three sources (all of which are different) of this documentation:

1. The generated initializer.
2. The tutorial's initializer.
3. The configuration.md file (which is nothing more than the content of ReactOnRails configuration initializer).

**Comment by justin808** [comment]
I'm open to your PR ideas!

**Comment by justin808** [comment]
Generated file contains: 
```ruby
# See https://github.com/shakacode/react_on_rails/blob/master/docs/basics/configuration.md
# for many more options.
```
