### ISSUE TITLE
CommonChunks with prerender

### ISSUE THREAD

**Issue by Overload119** [shakacode/react_on_rails#1030]
I read through https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/code-splitting.md but that didn't really lead me to an answer.  I'm not using React Router.

I'm trying to see how I can get these two to play nice - it should be as trivial as including `common.js` before `server_rendering.js` but it isn't.

Any ideas on how I can get these two to work without having to write a bunch of components all over again?

**Comment by Overload119** [comment]
I think I want something like this:

> If you're serious about server rendering, it's worth the effort to have different entry points for client and server rendering. It's worth the extra complexity.

Is there an example of this anywhere?

**Comment by justin808** [comment]
Check out https://github.com/shakacode/react-webpack-rails-tutorial, live at reactrails.com.

**Comment by justin808** [comment]
@Overload119 feel free to reach out to me directly if you have more questions: justin@shakacode.com.
