### ISSUE TITLE
Option for generate span tag instead of script tag

### ISSUE THREAD

**Issue by bakunyo** [shakacode/react_on_rails#1031]
I'd like to use **not** `script` tag but `span` (or any other tag) in generating react_on_rails helpers.
Because [AMP](https://www.ampproject.org/) rules don't allow any script tag except for tag has special attributes of amp.
I saw the PR https://github.com/shakacode/react_on_rails/pull/660 , but I want to option in react_on_rails to change tag name to other.

Below code is my image of codes.
```
  # prepend the rails_context if not yet applied
  def prepend_render_rails_context(render_value)
    return render_value if @rendered_rails_context

    data = rails_context(server_side: false)

    @rendered_rails_context = true

    replace_tag = ReactOnRails.configuration.instread_of_script_tag
    rails_context_content = if replace_tag
                                   content_tag(replace_tag,                              
                                   json_safe_and_pretty(data).html_safe,
                                   hidden: true,
                                   id: "js-react-on-rails-context")
                                 else
                                   content_tag(:script,
                                   json_safe_and_pretty(data).html_safe,
                                   type: "application/json",
                                   id: "js-react-on-rails-context")

    "#{rails_context_content}\n#{render_value}".html_safe
  end
```
`internal_react_component` and `render_redux_store_data` methods have similar situations.

**Comment by justin808** [comment]
@bakunyo are you 100% sure there's no other way around this issue? We put a lot of work into making the script tag work for better parsing performance.

**Comment by bakunyo** [comment]
@justin808 Thanks for your comment.
`<script type="application/ld+json">` tags are allowed from AMP. but it's not suitable to this content.
I'm not 100% sure, but I don't know any other way to render json for react_on_rails in AMP site.

**Comment by justin808** [comment]
@bakunyo we should figure this out. Any more ideas?

Here's a good article about AMP: https://stratechery.com/2018/the-aggregator-paradox/

CC: @alexfedoseev @robwise

**Comment by justin808** [comment]
Links on JSON/LD. Seems like a superset of JSON:

* https://en.wikipedia.org/wiki/JSON-LD
* http://www.seoskeptic.com/what-is-json-ld/

**Comment by bakunyo** [comment]
@justin808 Yes, I want to use option of old data format.
I agree with you about tag, we can use a hidden div.

**Comment by justin808** [comment]
@bakunyo can you help us with a PR?

**Comment by justin808** [comment]
All the old code is there...just needs good tests to be sure this works and we don't break it.

**Comment by justin808** [comment]
Airbnb does something like this:

```html
<meta content="{&quot;env&quot;:&quot;production&quot;,&quot;client_id&quot;:&quot;5ca541ad-47b9-4b16-8045-2f4c6e830450&quot;,&quot;client_key&quot;:&quot;production_r29fkzj4_pfpfmbt48yh4ht8c&quot;}" id="_bootstrap-amex_checkout">
```

**Comment by justin808** [comment]
![2018-03-08_21-26-25](https://user-images.githubusercontent.com/1118459/37195544-5e8a061a-2317-11e8-85ea-94dfad6480cd.png)

**Comment by justin808** [comment]
Any more requests for AMP? I'll leave this one open for now.
