### ISSUE TITLE
How to get JavaScript backtrace with SSR enabled?

### ISSUE THREAD

**Issue by mkalygin** [shakacode/react_on_rails#1033]
I'm using this gem for a while and everything works fine even with SSR. But there are couple of things I'm really stuck with it. I'm going to post them as separate issues.

Rails 5.1.4, React on Rails 10.0.1, SSR in Ruby.

`react_on_rails` gives no clue what is wrong with SSR. It gives information about state hydration, Rails context and even the error message, but it doesn't show any JavaScript backtrace. It says that the problem in `App` component, but the `App` component is the whole JavaScript codebase.

Here is an example from my app. How to know where I can find this error? I think backtrace should be added for `development` environment.

```
ERROR in SERVER PRERENDERING
Encountered error: "TypeError: Cannot read property 'length' of undefined"
when prerendering App with props: {}
js_code was:
(function() {
  var railsContext = {"inMailer":false,"i18nLocale":"ru","i18nDefaultLocale":"ru","href":"...","location":"/about","scheme":"http","host":"...","port":3000,"pathname":"/about","search":null,"httpAcceptLanguage":"ru-RU,ru;q=0.9,en-US;q=0.8,en;q=0.7","serverSide":true};
      ReactOnRails.clearHydratedStores();
var reduxProps, store, storeGenerator;
reduxProps = {"location":{"path":"/about","search":"","server":true},"auth":{}};
storeGenerator = ReactOnRails.getStoreGenerator('RoadgoStore');
store = storeGenerator(reduxProps, railsContext);
ReactOnRails.setStore('RoadgoStore', store);

  var props = {};
  return ReactOnRails.serverRenderReactComponent({
    name: 'App',
    domNodeId: 'App-react-component-ce3202ae-525f-48d5-b1ff-eb6415814bbf',
    props: props,
    trace: true,
    railsContext: railsContext
  });
})()
```

**Comment by justin808** [comment]
@mkalygin Please study these two files:

https://github.com/shakacode/react_on_rails/blob/master/node_package/src/handleError.js

and

https://github.com/shakacode/react_on_rails/blob/master/node_package/src/serverRenderReactComponent.js

and do some debugging. This used to work.

**Comment by mkalygin** [comment]
@justin808 This is exactly what I did. The error has been related with usage of the middleware for Redux store, specifically `redux-undo`. It has been failing to create store in React on Rails JS code when doing SSR.

**Comment by justin808** [comment]
@mkalygin, Any chance that you can help us figure out why the files I linked above are no longer giving stack traces? Did you check the server logs?

**Comment by justin808** [comment]
@mkalygin Please feel free to ask me to reopen this.
