### ISSUE TITLE
SSR renders blank page with text in case of errors in production environment

### ISSUE THREAD

**Issue by mkalygin** [shakacode/react_on_rails#1034]
I'm using this gem for a while and everything works fine even with SSR. But there are couple of things I'm really stuck with it. I'm going to post them as separate issues.

Rails 5.1.4, React on Rails 10.0.1, SSR in Ruby.

In production when SSR error occurs `react_on_rails` dumps error log to a blank page and shows it to the client. Here is an example:

![image](https://user-images.githubusercontent.com/1662910/36536016-93e9086a-17dc-11e8-83c2-896c0ff7958c.png)

Any way to hide this or redirect to 500 error page?

**Comment by justin808** [comment]
@mkalygin Typically the page still renders. Are you sure you don't have an error in your controller outside of RoR?

**Comment by mkalygin** [comment]
@justin808 well, even if this is not a controller error but an error in JS doing SSR, it still shows a similar blank page for a couple of seconds.

**Comment by justin808** [comment]
@mkalygin Sounds like you need some better debugging. Please reach out to me if you need more help: justin@shakacode.com.
