### ISSUE TITLE
display HTML tag instead script tag

### ISSUE THREAD

**Issue by mlazuardy** [shakacode/react_on_rails#1035]
just 1 hour ago i install this package for my ruby on rails app, but in the short tutorial, all javascript render into html tag but my component is turn into script tag with application/json in script tag attribute like this
```

<script type="application/json" id="js-react-on-rails-context">{"inMailer":false,"i18nLocale":"en","i18nDefaultLocale":"en","href":"http://localhost:3000/@","location":"/@","scheme":"http","host":"localhost","port":3000,"pathname":"/@","search":null,"httpAcceptLanguage":"id,en-US;q=0.9,en;q=0.8","serverSide":false}</script>
--
  | <script type="application/json" class="js-react-on-rails-component" data-component-name="HelloWorld" data-trace="true" data-dom-id="HelloWorld-react-component-7115e4a6-73ea-401e-97d2-2ac32991e47a">{}</script>


```
in fact, i dont want to display that script tag, im expecting to return html tag. what should i do ?
sorry bad english. and thanks if you want to response this issue, or maybe i miss  something

**Comment by justin808** [comment]
We switched from putting data in a HTML tag to a script tag a while back for performance.

**Comment by mlazuardy** [comment]
so there is no way to switch to html tag ? but that make the apps performance good, i think its "OK", thank you sir

**Comment by neelakandan-br** [comment]
Is that a way to change this id? When I am using multiple react components id was not unique on the same page.
