### ISSUE TITLE
Server render two pages using two separate JS files

### ISSUE THREAD

**Issue by fantasydong** [shakacode/react_on_rails#1040]
Hi @justin808 ,

As we know, the gem recommend use one JS file to implement server side render. For us, we want to use two separate JS files to server render two different pages. Finally, we come out a solution of:
```
ReactOnRails.configure do |config|
      if config.server_bundle_js_file != server_render_file
        config.server_bundle_js_file = server_render_file
        ReactOnRails::ServerRenderingPool::Exec.reset_pool
      end
end
```
We call ReactOnRails::ServerRenderingPool::Exec.reset_pool to reset the cached pool for every request. We found this solution work well for us. But our concern was that does this solution will have a potential  issue if there are too many concurrency requests on these two pages? We think the pool was cached in memory and shared. So we are afraid that the reset pool operation will effect each other.

What do you think?

Regards!

**Comment by justin808** [comment]
I'd be concerned about this. Can you explain better on why you need 2 different files for your JS?

**Comment by fantasydong** [comment]
@justin808 Thanks for the quick feedback. 

My case is that, we have two separate pages:
For /page-1, we use page1.js to do server side render
For /page-2, we use page2.js to do server side render

Because the two pages' code structure and Webpack build setting are quite different. It is not easy for us to build them into one file. 

We also try to build them into one, but the result is that the two entry files will effect each others and the JS file only work on one page. It seems that only the last entires file page work meaning the last entry file code build replace the first entry file code.

Hope this can explain my case to you. Thanks for your answer.

**Comment by justin808** [comment]
Your case is definitely unusual. I'd take a look at the source code and see if you can come up with a good solution. I definitely would not do things the way you are doing, as I think you might run into serious concurrency, CPU, and memory issues.

Alternately, would you be interested in our ShakaCode Pro Support plan? If you joined, we could definitely develop something for you.

http://www.shakacode.com/work/shakacode-pro-support.pdf

If so, please schedule a complimentary 30-minute consultation:
https://calendly.com/justingordon

Thanks,

Justin

**Comment by fantasydong** [comment]
@justin808 Thanks you and hope that you can come up a better solution for this case.

**Comment by justin808** [comment]
@fantasydong Please feel free to request me to re-open this one.

I'd be happy to work on a custom solution for you if you like. Let me know.
