### ISSUE TITLE
NoMethodError: undefined method 'closed?' for nil:NilClass

### ISSUE THREAD

**Issue by sepehr500** [shakacode/react_on_rails#1041]
When I try to use spin up the webpack dev-server I get the error `NoMethodError: undefined method 'closed?' for nil:NilClass` which is caused by a conflict between Rack:Proxy(which webpacker is using) and Webmock. Unfortunately we do not have the option of removing Webmock when doing local development. Has anybody found a workaround for this issue?

**Comment by justin808** [comment]
1. Why would you use Webmock in development?
2. Try skipping the webpack-dev-server and just using the option to compile the files as needed.

**Comment by sepehr500** [comment]
We use webmock in development to mock requests to legacy systems we have no control over. And the project has gotten large enough the compile on reload is too slow. We also want to take advantage of live reloading.

**Comment by justin808** [comment]
@sepehr500 Any update on this issue? Should we keep this open?

**Comment by justin808** [comment]
Ping me to reopen if needed, @sepehr500.

**Comment by sepehr500** [comment]
@justin808 Unfortunately I could not figure out how to solve this.
