### ISSUE TITLE
Still need webpacker for Rails 5.1.3 above ?

### ISSUE THREAD

**Issue by AirWick219** [shakacode/react_on_rails#1042]
So in the Readme under ```Steps to a New App with rails/webpacker v3 plus latest React on Rails```, it says 

> First be sure to run rails -v and check that you are using Rails 5.1.3 or above. If you are using an older version of Rails, you'll need to install webpacker with React per the instructions here.

I am on rails version Rails 5.1.4  after setuping everything in ```Basic installation for a new Rails App``` and run it. I got an error for 

undefined method `javascript_pack_tag'  for ```<%= javascript_pack_tag 'hello-world-bundle' %>```

Which as far as I know javascript_pack_tag helper is from webpacker, Do does that mean I will have to add ```gem "webpacker", "~> 3.0"``` even for  Rails 5.1.3 or above

**Comment by justin808** [comment]
Yes to the above.
