### ISSUE TITLE
Can't run the specs from a path with spaces

### ISSUE THREAD

**Issue by andrewmarkle** [shakacode/react_on_rails#1044]
When trying to run my specs I'm getting the following error: 

<img width="597" alt="screen shot 2018-03-10 at 12 42 37 pm" src="https://user-images.githubusercontent.com/2506835/37245126-776171dc-2461-11e8-89aa-adbc9eaa0912.png">

The cause for the error is that my path where I store my project in has a space in it `.../Mobile Documents/...` For the bash command to work properly, the empty space needs to be escaped like so: `.../Mobile\ Documents/...`

Be happy to open up a PR to fix this!

**Comment by justin808** [comment]
@andrewmarkle Yes, please do make a PR!
