### ISSUE TITLE
Back/Forward button does not work with TurboLinks

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#105]
This can be reproduced in the examples:

```sh
cd spec/dummy
foreman start
```

Click on any link to go to a second page. Click back button. Input box to type is missing. Hit forward button. Same issue.

We have 2 potential solutions:

* #102 
* #104 

Looking for opinions on which is preferable.

**Comment by justin808** [comment]
I spoke about this more with @alexfedoseev. I'm going to ensure that we have handlers for page changed and page unloaded. This is far preferable to the eval-always option and we suspect that this will enable react-router to "just work".

```
page:before-unload	[affectedNodes]	Nodes are about to be changed.
page:change	[affectedNodes]	Nodes have changed. Also fires on DOMContentLoaded.
```

CC @ryanaip

**Comment by justin808** [comment]
About to release...https://github.com/shakacode/react_on_rails/pull/68

**Comment by robwise** [comment]
Implemented in https://github.com/shakacode/react_on_rails/issues/69
