### ISSUE TITLE
Suggested Change to Webpack Dev Settings

### ISSUE THREAD

**Issue by Johnfredadams** [shakacode/react_on_rails#1051]
Thanks so much for this brilliant gem! It's what I've been looking for. 
If you're using shakacode in a hybrid app with some standard rails and some react + precompiling before push, it gets exhausting having to re-compile all the bundles that you didn't change because they got overwritten as soon as you started up the dev server. Suggest that you add `public_output_path: dev-packs` to default development config in webpacker.yml. That way dev builds and production builds aren't constantly overwriting each other.

**Comment by justin808** [comment]
@Johnfredadams 

Thank you for your kind words.

Can you submit a PR with what you're thinking of for a doc change?

Please email me if you'd like an invite to our private Slack for React on Rails users.

Thanks,

Justin
justin@shakacode.com

**Comment by justin808** [comment]
@Johnfredadams Please open a PR when you have this ready. I'll close for now.

**Comment by justin808** [comment]
@Johnfredadams are you referring to this one used for testing? https://github.com/shakacode/react_on_rails/blob/a333608e736c81190157fc82ea0d7d4be4c3b6fb/spec/dummy/config/webpacker.yml

or the one used by the webpacker gem which the react on rails tutorial uses?
