### ISSUE TITLE
Set is not defined

### ISSUE THREAD

**Issue by Yamikamisama** [shakacode/react_on_rails#1054]
Has anyone encountered this error im not too sure what I'm looking for to fix

```
ERROR in SERVER PRERENDERING
Encountered error: "ReferenceError: Set is not defined"
```

<img width="616" alt="screen shot 2018-04-06 at 3 28 51 pm" src="https://user-images.githubusercontent.com/8148176/38440527-b660e49a-39af-11e8-9f22-3551baeb3f85.png">

**Comment by justin808** [comment]
Sounds like you need some debugging help. I'm the creator of React on Rails. We have a support plan to help you. See shakacode.com/work/shakacode-pro-support.pdf.

**Comment by Overload119** [comment]
I just ran into this. 

Try adding `mini_racer` to your bundle file as I think you may be using `therubyracer` which uses an old version of JS that doesn't defined "Set"
