### ISSUE TITLE
Replace puts calls with Logger

### ISSUE THREAD

**Issue by railsme** [shakacode/react_on_rails#1058]
This feature will allow us to define output logger and redirect it to whatever we need.
STDOUT, file or nothing.
`puts` is not the best way to output useful information.
If nobody will start work on this feature I'll try to find some time a bit later.

@justin808 any ideas or recommendations? :)

**Comment by justin808** [comment]
Please point me to some places in the code or submit a PR.

**Comment by railsme** [comment]
@justin808 there are also a lot of puts in tests but it is okay for tests.
Runtime output should be under developer's control.

https://github.com/shakacode/react_on_rails/blob/8c8077b3b86680581aef5f49908225aa33ea25fd/lib/react_on_rails/server_rendering_pool/node.rb#L44-L48
https://github.com/shakacode/react_on_rails/blob/8c8077b3b86680581aef5f49908225aa33ea25fd/lib/react_on_rails/assets_precompile.rb#L35-L38
https://github.com/shakacode/react_on_rails/blob/8c8077b3b86680581aef5f49908225aa33ea25fd/lib/react_on_rails/configuration.rb#L51-L58
https://github.com/shakacode/react_on_rails/blob/05b211448fce62a3d2ec704b100ca77f7856a3ee/lib/react_on_rails/server_rendering_pool/exec.rb#L74-L78
https://github.com/shakacode/react_on_rails/blob/a1932d95b25f999d50a1aaa7d476a1b2e04f8e72/lib/react_on_rails/utils.rb#L84

**Comment by justin808** [comment]
Hi @railsme. Please submit a PR. Please consider the type of message and whether it should be info, warn, or error.

Thanks,

Justin

**Comment by justin808** [comment]
@railsme I'm taking care of this one. Thanks for reporting this! #1059
