### ISSUE TITLE
Version checking mismatch bug

### ISSUE THREAD

**Issue by dzirtusss** [shakacode/react_on_rails#1062]
There is a possibility of versions mismatch when version in `package.json` is accidentally specified in non-exact style e.g. `^10.1.3`. If later version is bumped to say `10.1.4` in node packages this is not noticed by the gem.

I guess this could be fixed easily by forcing only exact version in `package.json` by `version_checker.rb`, or at least having a warning that version is not exact.

**Comment by justin808** [comment]
Here is the file to change: https://github.com/shakacode/react_on_rails/blob/49401b2b48aaf397de625f988ab0617ed4499fc4/lib/react_on_rails/version_checker.rb

and the test to update: https://github.com/shakacode/react_on_rails/blob/94868d0810a4f0e51b8e8d7ed79d73d7bcaae342/spec/react_on_rails/version_checker_spec.rb

**Comment by justin808** [comment]
https://github.com/bundler/bundler/issues/6500 to see if I can find out if the ruby gem has a semver wildcard.

**Comment by justin808** [comment]
Fixed in #1063.
