### ISSUE TITLE
Broken link to Josephine in PROJECTS.md

### ISSUE THREAD

**Issue by rodrigobdz** [shakacode/react_on_rails#1073]
The link to [Josephine](https://www.josephine.com/) listed under [Commercial Products Live](https://github.com/shakacode/react_on_rails/blob/b5b49601f2d405eac892c0df0990e508313f83ef/PROJECTS.md#commercial-products-live) in [PROJECTS.md](https://github.com/shakacode/react_on_rails/blob/b5b49601f2d405eac892c0df0990e508313f83ef/PROJECTS.md) is broken.

**Comment by justin808** [comment]
fixed

thanks!

**Comment by rodrigobdz** [comment]
Glad to help!
