### ISSUE TITLE
SSR -- TypeError: Cannot read property 'object' of undefined

### ISSUE THREAD

**Issue by saiwas** [shakacode/react_on_rails#1074]
Hey guys, my project is using `react-on-rails  v8.0.6`. Recently, I tried to update `React` version from 15.x.x to 16.x.x. But I got an error as below. I already tried to upgrade `react-on-rails` to v11.0.3.
But the error still here. I used **server-side-rendering** in my ERB file, and I'm sure it works with React 15. 
Anyone else has this issue and maybe ideas how to properly fix it? Thanks

``` text
ERROR in SERVER PRERENDERING
Encountered error: "TypeError: Cannot read property 'object' of undefined"
when prerendering ArticleHeader with props: {"title":"title","dek":"dek","banner_link":null,"attribution":"attribution"}
js_code was:
(function() {
  var railsContext = {"inMailer":false,"i18nLocale":"en","i18nDefaultLocale":"en","href":"http://localhost:3000/content/british-royal-wedding-traditions","location":"/content/british-royal-wedding-traditions","scheme":"http","host":"localhost","port":3000,"pathname":"/content/british-royal-wedding-traditions","search":null,"httpAcceptLanguage":"en,zh-CN;q=0.9,zh;q=0.8","serverSide":true};

  var props = {"title":"title","dek":"dek","banner_link":null,"attribution":"attribution"};
  return ReactOnRails.serverRenderReactComponent({
    name: 'ArticleHeader',
    domNodeId: 'ArticleHeader-react-component-5bf4576e-2e03-405d-ab1b-f60ca0a58709',
    props: props,
    trace: true,
    railsContext: railsContext
  });
})()
```
/content_pieces/show/_leader.html.erb
```erb
    <%= react_component("ArticleHeader", props: {
      title: apply_no_follow_to_external_links("#{content_piece.headline}"),
      dek: apply_no_follow_to_external_links("#{content_piece.dek}"),
      banner_link: content_piece_banner_link(content_piece.content_hub),
      attribution: "by #{content_piece.author}"
      }, prerender: true) %>
```
article-header.jsx
```jsx
export default function ArticleHeader({ title, dek, banner_link, attribution }) {
  //......
  return (
    <Container>
      <Row>
        <Column>
          <div className={styles['article-header']}>
            <h1 className={classes} dangerouslySetInnerHTML={createTitle()} />
            <div dangerouslySetInnerHTML={createBannerLink()} />
            <div className={styles['article-dek']} dangerouslySetInnerHTML={createDek()} />
            {attr}
          </div>
        </Column>
      </Row>
    </Container>
  )
}
```

**Comment by justin808** [comment]
1. Stick with 11.0.3
1. turn off server rendering and see if you get the same issue
1. go back to v15 of react and see if you get the same issue
1. Do you have a full stack trace of the error? Since "object" is not called like `foobar.object` where foobar is null in your code example, the culprit is in some code you are not showing.

Please see Would you be interested in our ShakaCode Pro Support plan? 

http://www.shakacode.com/work/shakacode-pro-support.pdf

If so, please schedule a complimentary 30-minute consultation:
https://calendly.com/justingordon

Thanks,

Justin
justin@shakacode.com

**Comment by saiwas** [comment]
@justin808  Thanks for your advice. I still strange that why it does not hit the error in React 15, but complied failed in React 16 although there's no code changed. May I know does `react_on_rails` v11.0.3 support React 16 now?

**Comment by justin808** [comment]
My company's product, chttps://www.hawaiichee.com/, uses React 16.3.1 and react-on-rails 10.1.4. There are no JavaScript differences with v11 vs. v10.

**Comment by justin808** [comment]
@saiwas feel free to request re-opening.
