### ISSUE TITLE
Can't verify CSRF token authenticity with Fetch API

### ISSUE THREAD

**Issue by hewrin** [shakacode/react_on_rails#1075]
Hi, so I get this error in the server when I try to do a fetch request in React

```
 Can't verify CSRF token authenticity.
 ActionController::InvalidAuthenticityToken (ActionController::InvalidAuthenticityToken)
 ActionController::InvalidAuthenticityToken - ActionController::InvalidAuthenticityToken
```

Here is my fetch request

```
  onConfirm = () => {
    let headers = {
        'Content-Type':'application/json',
        'Accept': 'application/json',
      }
    fetch('/parcel/booking', {
      method: 'post',
      header: ReactOnRails.authenticityHeaders(headers),
      body: {
        "booking[amount]": this.props.amount,
        "booking[agent_id]": this.props.agent.id
      }
    }).then(function(response) {
      console.log(response)
    })
  }
```

I tried doing `ReactOnRails.authenticityHeaders(headers)` in the console and I got this

```
{Content-Type: "application/json", Accept: "application/json", X-CSRF-Token: "vtlbcJKc9RLJt5GvrTYggItU0RfsfU9vSNGUdmCA3y1pA9MGEC863dz2WyH2K2G9nlGqvvDfR4CsVTAp/AoGBQ==", X-Requested-With: "XMLHttpRequest"}
```

So it seems thats working.

Am I missing something?

**Comment by justin808** [comment]
Take a look at 
* https://github.com/shakacode/react_on_rails/blob/master/node_package/src/ReactOnRails.js#L102
* https://github.com/shakacode/react_on_rails/blob/d5d579e7c1a24667eb5ccfbb34c17c0e898d6bf9/docs/api/javascript-api.md
* https://github.com/shakacode/react_on_rails/blob/57fdc402a67155d3f93bc4f89c5aec064092f26f/README.md#L634

Would you be interested in our ShakaCode Pro Support plan? 

http://www.shakacode.com/work/shakacode-pro-support.pdf

If so, please schedule a complimentary 30-minute consultation:
https://calendly.com/justingordon

Thanks,

Justin
justin@shakacode.com

**Comment by justin808** [comment]
@hewrin My firm has built https://www.hawaiichee.com and we've got lots of experience on the nuances of the CSRF issues.

**Comment by justin808** [comment]
@foo4foo I invited you to our Slack Room. You can ask the group there.

**Comment by acherukuri** [comment]
@foo4foo and @hewrin I'm having the same issue now, did you guys manage to fix the problem?

**Comment by ivanraybuglosa** [comment]
@justin808 Can i also join your slack room? I wanna learn more about react_on_rails

**Comment by foo4foo** [comment]
@ivanraybuglosa @acherukuri I believe I faced this problem using FETCH API only. Sending requests using axios did the trick.
