### ISSUE TITLE
Unable to use Mobx decorators in React On Rails

### ISSUE THREAD

**Issue by 9jaswag** [shakacode/react_on_rails#1076]
Hello,
I'm trying react-on-rails for the first time and I've been struggling to use Mobx decorators such as `@observable` `@action`.
I'm using `gem 'react_on_rails', '11.0.0'`, `"react-on-rails": "11.0.3"`, `Rails 5.1.6`, `ruby 2.4.1p111`. I followed the instruction in the readme to set up the project (and I don't have a `client` folder after installing react-on-rails gem).
I have the following:
```
class UserStore {
  @observable username = 'john';

  constructor() {
    this.Api = new AuthAPI;
  }

  @action login = (userData) => this.Api.loginAction(userData)

}
```

I wrap the components with `<Provider>` and pass in the store. In the component, I inject `UserStore` and decorate the component with `@observer` but I get an empty store object when I do `this.props.UserStore`.
Is there anything I'm doing wrong?

**Comment by justin808** [comment]
@9jaswag Take a look at the example https://github.com/shakacode/react-webpack-rails-tutorial.

Would you be interested in our ShakaCode Pro Support plan? We did and continue to do lots of work for https://egghead.io/. They use Mobx with React on Rails.

http://www.shakacode.com/work/shakacode-pro-support.pdf

If so, please schedule a complimentary 30-minute consultation:
https://calendly.com/justingordon

Thanks,

Justin
justin@shakacode.com
