### ISSUE TITLE
Create new generator that makes the /client type install

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#1089]
When react_on_rails updated to webpacker, we simplified the generator to not build any webpack configuration.

Reasons to offer a /client type install:

* The `/client` type install is _recommended_ (see README.md)
* With Webpack v4, the webpack setup is much simpler.

Is anybody interested in working on this with me?

**Comment by Kacppian** [comment]
Is this still open?

**Comment by justin808** [comment]
#1185
