### ISSUE TITLE
Help wanted with turbolinks capybara test

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#109]
Any volunteer for writing this test case:

1. Be sure turbolinks is running in spec/dummy app
2. Visit root url, then a child link. (one case with server rendered page, one without)
3. Hit back button. The react input fields disappear due to current turoblinks issue.
4. Hit forward button. The react input fields disappeared.

This issue relates to #105

**Comment by robwise** [comment]
Added in https://github.com/shakacode/react_on_rails/commit/648b71c9e094e41f41b2980ea835469b04564b27

**Comment by robwise** [comment]
Too late, merged in https://github.com/shakacode/react_on_rails/pull/68
