### ISSUE TITLE
Too many old gem versions throughout the documentation

### ISSUE THREAD

**Issue by vfonic** [shakacode/react_on_rails#1094]
Every time I come back to the documentation, I see various `react_on_rails` gem versions all over the place. It's confusing and, I guess, it happens because there are too many places to update the version number (in the docs).
Perhaps it would be better to have a generic text referring to "current version" instead?

Something like:

> You can either use the version this tutorial was written for or try latest released version.
> If you make it work with latest version, please take the time to update this tutorial.
> ```ruby
> gem 'react_on_rails', 'X.Y.Z'         # prefer exact gem version to match npm version 
> ```

**Comment by justin808** [comment]
@vfonic can you provide a PR for this? I agree.

**Comment by vfonic** [comment]
Sorry, can't get to it now.
