### ISSUE TITLE
Warning message?

### ISSUE THREAD

**Issue by vassilis** [shakacode/react_on_rails#1096]
ReactOnRails: Set generated_assets_dir to default: public/webpack/development

Is the above message a warning?

Do I have to add something in react_on_rails.rb initializer?

I am using rails 5.2.0 and webpacker 3.5.3.

**Comment by justin808** [comment]
Not a warning. Just informative. You did not set that in your config/initializers.rb, so you're being told what React on Rails thinks you want.
