### ISSUE TITLE
Generator function is not a generator function?

### ISSUE THREAD

**Issue by brandoncc** [shakacode/react_on_rails#1097]
I've been struggling for hours to get access to `railsContext` unsuccessfully. I copied your example generator function, but for some reason it doesn't pass as a generator function. Here is my bundle:

```js
import React from 'react';
import ReactOnRails from 'react-on-rails';

import SharedReduxStore from '@src/store';

import Index from '@src/index';

const AppComponentWithRailsContext = (props, railsContext) => (
  <Index {...{...props, railsContext}}/>
);

console.log(AppComponentWithRailsContext.prototype.isReactComponent);

// This is how react_on_rails can see the HelloWorld in the browser.
ReactOnRails.register({
  AppComponentWithRailsContext
});

ReactOnRails.registerStore({
  SharedReduxStore
});

```

I get:

```
TypeError: AppComponentWithRailsContext.prototype is undefined
```

In the console, which shows why it is failing the generator function check, but I can't figure out *why*, especially since it is a copy-paste of your example. I'm hoping it is something simple. I tried both React 15.4.2 and 16.4.0.

Thanks in advance.

**Comment by brandoncc** [comment]
If it helps, this is what I get when I log the function object itself:

<img width="292" alt="image" src="https://user-images.githubusercontent.com/543973/40898040-9bedeea4-6773-11e8-9452-7e0205d5f727.png">

**Comment by justin808** [comment]
@brandoncc Please run the example in the spec/dummy directory or https://github.com/shakacode/react-webpack-rails-tutorial. I'm quite sure there is no real issue here.

I'm available to help you if you really need it. 

Would you be interested in our ShakaCode Pro Support plan? 

http://www.shakacode.com/work/shakacode-pro-support.pdf

If so, please schedule a complimentary 30-minute consultation:
https://calendly.com/justingordon

Thanks,

Justin
justin@shakacode.com

**Comment by justin808** [comment]
@brandoncc One of my clients sent me this a few days ago: 

![image](https://user-images.githubusercontent.com/1118459/40904855-d0b2bbc0-6777-11e8-9e31-c2c998fb5b5c.png)

**Comment by brandoncc** [comment]
I tried running the dummy app and I get this:

```
No such file or directory @ rb_file_s_mtime - /Users/brandoncc/dev/react_on_rails/spec/dummy/public/webpack/development/server-bundle.js
```

I spent much of the hours I was stuck pouring through the dummy app code though, so I am familiar with it.

I'm wondering if there is something special I need in my babel config or something else in order to have proper "generator functions". That is because MDN says arrow functions do not have `prototype` properties, yet they need to have that in order to pass your generator function check.

Thinking I wasn't writing the generator function correctly, I found [this](https://codepen.io/robwise/pen/wMwzGo) and copied the generator function from there.

Thank gave me this code:

```js
import React from 'react';
import ReactOnRails from 'react-on-rails';

const foobarComponent = React.createClass({
  render: () => {
    return (<div>Component for Generator Function</div>);
  }
});

let AppComponentWithRailsContext = (props, rC) => {
  console.log("HERE")
  console.log(rC);
  return (<foobarComponent/>);
};

console.log("HERE 2");
console.log(AppComponentWithRailsContext.prototype);

ReactOnRails.register({
  AppComponentWithRailsContext
});
```

Which gave me this in the console:

<img width="117" alt="image" src="https://user-images.githubusercontent.com/543973/40923738-779e2d96-67ca-11e8-96e9-5b138042a1bb.png">

I realize you are sure there is no problem, but if you could look at what I provided and tell me why I am experiencing a problem, I would be very grateful.

As for your question about a pro service, I am trying to convert a node app to rails so that I can convince the owner to let me launch that version instead of the node one. At this time, paid support is not an option. I do not know if that would change in the future though.

**Comment by brandoncc** [comment]
Okay, I'm thinking I must have a webpacker or babel config that is breaking things. I went through the process of creating a new app and I used this for my bundle:

```js
import React from 'react';
import ReactOnRails from 'react-on-rails';

import HelloWorld from '../bundles/HelloWorld/components/HelloWorld';

const HelloWorldWithRailsContext = (props, railsContext) => {
  console.log(railsContext);
  return <HelloWorld {...{...props, railsContext}}/>
};


// This is how react_on_rails can see the HelloWorld in the browser.
ReactOnRails.register({
  HelloWorld,
  HelloWorldWithRailsContext
});
```

The `railsContext` object logs out perfectly. Now to keep digging.... Thanks for letting me know that my code itself looked good and getting me to try something else.

**Comment by brandoncc** [comment]
I figured it out, and I hope this helps someone else. I had this in my `.babelrc`:

```js
"presets": [
  [
    "env",
    {
      "modules": false,
      "targets": {
        "node": "current"
      }
    }
  ],
```

but it needed to be:

```js
"presets": [
  [
    "env",
    {
      "modules": false,
      "targets": {
        "browsers": "> 1%",
        "uglify": true
      },
      "useBuiltIns": true
    }
  ],
```

I believe I had changed that when I was trying to deal with `regeneratorRuntime is undefined`.

**Comment by brandoncc** [comment]
Pushing further into this, it turns out that I needed to add `import "babel-polyfill";` to my bundle. After adding that, `useBuiltIns` works properly. The result of that is the `regeneratorRuntime` error being fixed and `railsContext` works now.

I hope this helps you to help someone else. Thanks again!
