### ISSUE TITLE
Is it possible to disable the setTimeout error in dev for SSR?

### ISSUE THREAD

**Issue by brandoncc** [shakacode/react_on_rails#1098]
I use `typestyle` which calls `setTimeout`. I tried defining `global.setTimeout` as a noop, but I still get the error from the gem saying you shouldn't use that on the server side. `typestyle` has a different way to handle SSR, and still seems to call `setTimeout`. Because of that, I just need to suppress the error.

**Comment by justin808** [comment]
I'm open to taking a PR for this. It's pretty easy.

Alternately, would you be interested in our ShakaCode Pro Support plan? I could do this very quickly.

http://www.shakacode.com/work/shakacode-pro-support.pdf

If so, please schedule a complimentary 30-minute consultation:
https://calendly.com/justingordon

Thanks,

Justin
justin@shakacode.com

**Comment by brandoncc** [comment]
I'll look into creating a PR for it. Unfortunately, pro support is not an option at the moment. Thanks for the response.
