### ISSUE TITLE
Webpack configurations error 

### ISSUE THREAD

**Issue by he4amm** [shakacode/react_on_rails#1116]
Hi all I facing this errors in webpack logs for the ReactOnRails project,
the app runs through the port as well except loading any react component in the view and these errors showing in the terminal...
if anyone facing this issue before or know the solution of it, the help will be so far appreciated 
![image](https://user-images.githubusercontent.com/9943043/43026821-9e0c1944-8c77-11e8-9878-7d645b852691.png)

**Comment by justin808** [comment]
Hi @he4amm,

Your image is not showing errors.

Would you be interested in our ShakaCode Pro Support plan? 

http://www.shakacode.com/work/shakacode-pro-support.pdf

If so, please schedule a complimentary 30-minute consultation:
https://meetings.hubspot.com/justingordon/30-minute-consultation

Thanks,

Justin
justin@shakacode.com
