### ISSUE TITLE
Apollo Client ( GraphQL ) integration with react-on-rails

### ISSUE THREAD

**Issue by KKS1** [shakacode/react_on_rails#1124]
Hi team,

First of all, thank you so much for putting in all the hard work, and getting this super useful gem out.
I see as of now, we have 'redux + react + rails' combination feasibility in this. Is there a plan to move forward towards a graphQL based architecture ? As I understand, with Apollo Client 2 version, one can simply use apollo-boost module ( ApolloProvider ), and have the state management work on both client and sever end seamlessly at a single place, without needing Redux. Hence, I feel it can be a great addition for this gem moving forward.
Would be great to know your thoughts on this.

Thanks,
Kanwaljeet

**Comment by justin808** [comment]
@KKS1 Graphql is supported right now, but not with server-rendering.

I've already started on making server-rendering with graphql a React on Rails Pro feature.

Please get in touch with me directly: [justin@shakacode.com](mailto:justin@shakacode.com) and we can discuss this further.

**Comment by KKS1** [comment]
Thanks @justin808 . Glad to hear that! I will connect over the email, to get more details on the GraphQL client end feasibility with current gem.
