### ISSUE TITLE
Debugging using Chrome and VS Code

### ISSUE THREAD

**Issue by zdrummond** [shakacode/react_on_rails#1125]
I use VS Code's integrated debugger with Create React App pretty extensively. I was hoping to get the same experience with react_on_rails.  I was not able to get it going on our current existing project, so I tried it from scratch. No luck. Any advice or suggestions would be appreciated. Thanks!

# react_on_rails
rails: 5.1.6
webpacker: 3.5.5
react_on_rails: 11.0.9
react: 16.4.2

# cra
react: 16.4.2
react-scripts: 1.1.4

# High level steps
1. Base rails with react_on_rails and a vanilla CRA with the HelloWorld component copied in
2. Added a launch.json for attach to Chrome
3. Set a breakpoint in the same place for both projects (line 21 of the HelloWorld component)
4. CRA hits the break point, react_on_rails does not.

# Examples
I pushed up my example projects 
https://github.com/zdrummond/fresh_react_on_rails
https://github.com/zdrummond/cra_hello_world

**Comment by andrewmcodes** [comment]
@zdrummond can you post your launch.json? As an alternative, if you put `debugger;` in one of your components, it will essentially break at that point similar to using a `binding.pry` in your Rails code, but in the chrome debugger.

**Comment by zdrummond** [comment]
Here is the [launch.json](https://github.com/zdrummond/cra_hello_world/blob/master/.vscode/launch.json). My workflow uses the Attach command as I like managing chrome myself. 

Yup, I have used `debugger;` but I find the VS Code integration a nice delight to work with.

**Comment by andrewmcodes** [comment]
Hmm weird. I have been able to recreate the issue with [this](https://github.com/andrewmcodes/react-rails-tailwind-demo) app. Oddly enough, the debugger will catch my breakpoints placed in my ruby code (controllers for instance) but not in my components. I have a feeling this has to do with the way one of the gems we are using is working but I will keep looking into it. Does placing `debugger;` in your component work as expected?

**Comment by andrewmcodes** [comment]
Ok it looks like I am actually getting somewhere. By running a chrome launch and a ruby launch, or even just running the chrome launch and using my terminal to run the rails app, I am am getting the following in my debug console: 
```
Download the React DevTools for a better development experience: https://fb.me/react-devtools
react-dom.development.js:18238
RENDERED Welcome to dom node with id: Welcome-react-component-a20a016b-0d38-43eb-9280-a2ab9b0357ad with props, railsContext:
createReactElement.js:42
Object {name: "Stranger"}
createReactElement.js:42
name:"Stranger"
__proto__:Object {constructor: , __defineGetter__: , __defineSetter__: , …}
createReactElement.js:42
Object {railsEnv: "development", inMailer: false, i18nLocale: "en", i18nDefaultLocale: "en", rorVersion: "11.1.4", …}
createReactElement.js:42
Error processing "source": Error: No script for id: 21
    at Client.processMessage (/Users/andrew.mason/.vscode/extensions/msjsdiag.debugger-for-chrome-4.10.1/node_modules/noice-json-rpc/lib/noice-json-rpc.js:66:36)
```

and here are my launch settings: 
```
{
      "type": "chrome",
      "request": "launch",
      "name": "Launch Chrome against localhost",
      "url": "http://localhost:3000",
      "webRoot": "${workspaceFolder}"
    },
    {
      "name": "Rails server",
      "type": "Ruby",
      "request": "launch",
      "cwd": "${workspaceRoot}",
      "program": "${workspaceRoot}/bin/rails",
      "args": ["server"]
    }
```
Definitely getting close, the debugger is showing my object and its properties, just still not breaking as expected.

**Comment by zdrummond** [comment]
Any luck yet? I am getting pressure to move off React on Rails and use a CRA + copy to `/public` model... so it would be nice to say the two paths are equal.

**Comment by zdrummond** [comment]
@justin808 It's a pretty straight-forward problem. If you build with Create React App, and Dev in VS Code, you can set breakpoints inside your editor and debug in the same place you code (aka act as an IDE)

If you instead build the same thing with React on Rails then breakpoints do not work, and you have to debug inside Chrome.

**Comment by justin808** [comment]
This sounds like an editor configuration issue where the editor needs to know where the source files are. However, I'm not sure the JS editor will understand a Ruby web server.
