### ISSUE TITLE
constant ::TRUE is deprecated

### ISSUE THREAD

**Issue by shepmaster** [shakacode/react_on_rails#1127]
```
gems/react_on_rails-11.1.0/lib/react_on_rails/configuration.rb:12: warning: constant ::TRUE is deprecated
```

https://github.com/shakacode/react_on_rails/blob/75c7408e6d61ca78f4ffafe768dab339270936d4/lib/react_on_rails/configuration.rb#L12

Ruby 2.5.1

**Comment by justin808** [comment]
If you can give me a PR, that would be great. If not, I'll get to this sometime in the next week.
