### ISSUE TITLE
How to integrate react hot loader with react_on_rails?

### ISSUE THREAD

**Issue by Brew-Brew** [shakacode/react_on_rails#1135]
How to integrate react hot loader with react_on_rails? i don't know how to integrate react hot loader with react_on_rails.. also i can't find reference of it. i use react component with ReactOnRails.register

**Comment by justin808** [comment]
@zx6658 Can you poke around and let me know what you find. I think it's mostly just about adjusting the webpacker.yml config file to use hot reloading. That will change the URLs, which you can see if you view a page's source.

Then you also need to start the webpack dev server with your webpack config.

If you can try to create a sample app, I'll help you debug.

I'd actually suggest that you try to make https://github.com/shakacode/react-webpack-rails-tutorial work with hot reloading.

**Comment by rorong** [comment]
@zx6658 

Working on this as confirmed by Evrim.

Gurpreet

**Comment by tahsin352** [comment]
@justin808 i have tried the below way to implement react-hot-loader into react_on_rails:

url: https://gaearon.github.io/react-hot-loader/getstarted/
but after changing react component, it is not reflecting the changes without reload. it is using webpack and babel. I use react-hot-dom. webpack-dev-server checks the file changes. but it is not showing in browser.

url: https://github.com/rmosolgo/react-rails-hot-loader
it is implementing websocket.

url: https://medium.com/@coorasse/react-hot-reload-in-ruby-on-rails-5d534db665d
it is not working also.

i have also checked the spec/dummy/client section for react_hot_loading implementation. 

plz let me know what i am missing. Thanks.

**Comment by RailsCod3rFuture** [comment]
Would be nice if react-hot-loader was added by default.

**Comment by justin808** [comment]
See https://github.com/shakacode/react_on_rails/blob/master/docs/basics/hmr-and-hot-reloading-with-the-webpack-dev-server.md on how to set this up.
