### ISSUE TITLE
Can React on Rails be integrated into an existing Rails 3.x app?

### ISSUE THREAD

**Issue by evanrmurphy** [shakacode/react_on_rails#1137]
The README says "React on Rails supports older versions of Rails back to 3.x" so I was led to believe it could. But then during the install process I see I have to install webpacker. And there's the note "Rails/webpacker requires version 4.2+."

So I'm currently stalled out and wondering if this really does support Rails 3.x or if I misunderstood the documentation.

Is there a way to integrate React on Rails into an existing Rails 3.x app?

Thank you!

**Comment by justin808** [comment]
React on Rails should not require rails/webpacker.

Just use the asset pipeline.

**Comment by evanrmurphy** [comment]
Thanks @justin808! This is great news. I apparently misunderstood that this was a hard dependency.

Trying again now to get react_on_rails working without it.
