### ISSUE TITLE
Component is rendered twice when using Turbolinks

### ISSUE THREAD

**Issue by robinvdvleuten** [shakacode/react_on_rails#1139]
I've noticed while using `turbolinks` with `react_on_rails` that each component is rendered twice on subsequent visits. It seems that by using the `turbolinks:render` event, the listeners are called twice; once for the cache and once for the new state (see [turbolinks#full-list-of-events](https://github.com/turbolinks/turbolinks#full-list-of-events)). 

Is this expected behaviour? Otherwise the `turbolinks:load` event would be a better candidate to prevent React from wasting renders.

**Comment by justin808** [comment]
@robinvdvleuten Please search for related open/closed issues and PRs on "Turbolinks".

I'm open to thoughtful PRs with good tests. 😄

**Comment by robinvdvleuten** [comment]
@justin808 I did some further research on other projects trying to do the same as `react_on_rails`. It looks like the `react-rails` project is using the `turbolinks:load` event as well ([react-rails/blob/master/react_ujs/src/events/turbolinks.js](https://github.com/reactjs/react-rails/blob/master/react_ujs/src/events/turbolinks.js)).

**Comment by justin808** [comment]
OK -- can you reference the other recent change/PR regarding the load event and comment on why that shouldn't have been done. I can find that PR for you if you like.

**Comment by 8398a7** [comment]
I confirmed the same phenomenon.
In my environment I confirmed that it will be improved by rewriting it as `turbolinks: load`.
refs: https://github.com/shakacode/react_on_rails/blob/11.1.8/node_package/src/clientStartup.js#L195

Is it OK to test that render will not be called twice when PR issues this problem?

**Comment by 8398a7** [comment]
@justin808 cc: @szyablitsky
I think that this argument part is related.
https://github.com/shakacode/react_on_rails/pull/764#issuecomment-287596937
However, I may not understand correctly why `turbolinks: render` was adopted in turbolinks 5.

refs: https://github.com/turbolinks/turbolinks#full-list-of-events
> fires after Turbolinks renders the page. This event fires twice during an application visit to a cached location: once after rendering the cached version, and again after rendering the fresh version.

As far as the above is concerned, I understand that it is a specification that there are cases where render is done twice.
Do you know what kind of problem you have with `turbolinks: load` ?

**Comment by szyablitsky** [comment]
As I mentioned in PR description, using `turbolinks:load` causes "The node you're attempting to unmount was rendered by another copy of React." error when navigating to a cached page using Turbolinks.

We can use other turbolinks events to render only once per visit but this will lead to components "flickering". They will disappear during the time Turbolinks is making a request for the new page.

**Comment by justin808** [comment]
@szyablitsky @8398a7 @robinvdvleuten I'm going to close this for now due to inactivity. I'm happy to reopen if somebody has a reproduction case or, even better, a PR.

**Comment by heratyian** [comment]
I had this same issue and removing `require("turbolinks").start()` from application.js fixed the double rendering behavior for me. Hope this helps someone out there.

**Comment by timkrins** [comment]
This same issue was frustrating me. 

My React components were rendering once when first loaded, then once when visiting other pages via Turbolinks, but then clicking the _same_ link twice was causing a double render (one for the Turbolinks 'preview', and the other when the content is replaced).

Discovered this by trawling through the archived Turbolinks issues (https://github.com/turbolinks/turbolinks/issues/480).

Disabling previews seems like the easiest fix. Not sure if this issue is fixed in [Turbo.](https://github.com/hotwired/turbo-rails)
