### ISSUE TITLE
Server Bundle Caching Problem (Again)

### ISSUE THREAD

**Issue by robwise** [shakacode/react_on_rails#114]
Justin and I noticed when pairing that the server bundle was not being reloaded when modified. He said he has noticed it at several other times as well. This was supposed to have been fixed, but apparently not.

**Comment by szyablitsky** [comment]
I confirm this. I have to reload server to get rid of message about difference in server and client rendered component.

**Comment by justin808** [comment]
It's a very high priority to get this fixed, even if a short term fix is a blunt force always reload.

**Comment by robwise** [comment]
@justin808 that's actually not a bad idea, that's what react-rails is doing. Then you just disable that behavior for production since the server bundle shouldn't be changing in production anyway.

**Comment by robwise** [comment]
Fixed in https://github.com/shakacode/react_on_rails/commit/976cd17b8d523ac87e44317fe0c069610bbc398a
