### ISSUE TITLE
reactOnRailsPageLoaded invoked before deferred scripts are completed

### ISSUE THREAD

**Issue by rakelley** [shakacode/react_on_rails#1150]
When Turbolinks is disabled, `clientStartup.js` can invoke `reactOnRailsPageLoaded` in a manner that appears premature and unintentional (and is causing my team no end to grief).

The offending code is the timeout declared [here](https://github.com/shakacode/react_on_rails/blob/master/node_package/src/clientStartup.js#L199) with the condition `if (document.readyState === 'complete' || document.readyState !== 'loading' && !document.documentElement.doScroll) {`.  A readyState of `interactive` while deferred scripts are still being processed will lead to `reactOnRailsPageLoaded` being called before all components have been registered.  From our testing, Chrome seems to be the only browser fast enough to actually trigger this behavior, but it's a serious issue for us, made worse if utilizing preloading/server-push.

By the surrounding debug messages and the choice to use `DOMContentLoaded` event handlers, the intention seems to be that `reactOnRailsPageLoaded` should not be invoked until the page is actually loaded, which is not merely `readyState = interactive` but post-`DOMContentLoaded`.

Is it intentional that `reactOnRailsPageLoaded` is called before `DOMContentLoaded`, if any only if Turbolinks is disabled?

**Comment by justin808** [comment]
@rakelley I'm open to a PR for this. I can push a beta version for you.

> Is it intentional that reactOnRailsPageLoaded is called before DOMContentLoaded, if any only if Turbolinks is disabled?

Certainly not. I really cannot recollect this logic. It's been this way for years.

**Comment by justin808** [comment]
@rakelley please email me justin@shakacode.com and we can probably work this out pretty quickly.

**Comment by justin808** [comment]
Shipped in 11.0.6.

@rakelley can you confirm that it works as expected?

**Comment by rakelley** [comment]
@justin808 Yes, 11.0.6 is working for us in all scenarios, thank you for the quick turn-around.
