### ISSUE TITLE
Camelize props

### ISSUE THREAD

**Issue by devality** [shakacode/react_on_rails#1158]
Can I camalize props? Something like this
= react_component('HelloMessage', props: {name: 'John'}, {camelize_props: true})

**Comment by justin808** [comment]
@devality that sort of functionality is best handled either at the JBuilder level, like 

https://github.com/rails/jbuilder
> You can set this globally with the class method key_format (from inside your environment.rb for example):

`Jbuilder.key_format camelize: :lower`


You can also create a utility method like this:

```rb
def camelize_keys(hash)
  hash.deep_transform_keys! { \|key\| key.to_s.camelize(:lower) }
end
```

**Comment by jesster2k10** [comment]
Hey @justin808 how could we use the Jbuilder partials with the `react_component` function?

**Comment by justin808** [comment]
Hi @jesster2k10, I'm not sure what you're asking for. Prop serialization is best handled outside of the react_component method (ruby methods). You can create your own helper method that wraps react_component.
