### ISSUE TITLE
"Error in" without message Extract text webpack plugin error

### ISSUE THREAD

**Issue by nburt** [shakacode/react_on_rails#1160]
I'm receiving an error that seems to be find in development (dev server works) however it is causing rspec test failures on Circle CI. Without passing --verbose the only message I see is "ERROR in". With verbose there is a bit more output:

```
ERROR in
Child extract-text-webpack-plugin node_modules/extract-text-webpack-plugin/dist node_modules/css-loader/index.js??ref--3-2!node_modules/postcss-loader/lib/index.js??ref--3-3!node_modules/sass-loader/lib/loader.js??ref--3-4!app/javascript/bundles/shared/components/styles/link.scss:
    PublicPath: /packs/
    Entrypoint undefined = extract-text-webpack-plugin-output-filename
```

I've searched for "Entrypoint undefined" and everything I can find is related to a Webpack 4 upgrade while Webpacker is still on v3.

I have a sample repo to recreate the issue: https://github.com/nburt/react_rails_template

Clone it, run `bundle install && yarn install` and then run `bin/webpack --verbose` to see the error.

Any ideas?

Thanks!

**Comment by justin808** [comment]
What version of rails/webpacker?

**Comment by nburt** [comment]
seeing it with webpacker 3.5.5 and rails 5.2.1 and with webpacker 3.5.5 and rails 5.1

**Comment by nburt** [comment]
@justin808 just wanted to follow up - have you had a chance to take a look/been able to reproduce this as well?

**Comment by justin808** [comment]
@nburt My team and I have lots of experience setting up Circle CI and troubleshooting such issues.

However, I didn't get a chance to look into this as I'm booked helping my paying clients. 

Would your company be interested in our [ShakaCode Pro Support plan](http://www.shakacode.com/work/shakacode-pro-support.pdf)? 

If so, please schedule a complimentary 30-minute consultation:
https://meetings.hubspot.com/justingordon/30-minute-consultation

Thanks,

Justin
justin@shakacode.com

**Comment by nburt** [comment]
We unfortunately are a small team without the budget to afford a pro support plan.

I've identified the issue as coming from the flow status webpack plugin. I've decided to just skip prepending that loader if we're building on CI.

This is how we're prepending the plugins currently (development.js). I've just added the if checking process.env.CI which circle adds.

```
if (process.env.CI !== 'true') {
  environment.plugins.prepend(
    'NoEmitOnErrorsPlugin',
    new webpack.NoEmitOnErrorsPlugin()
  );

  environment.plugins.prepend(
    'FlowStatusWebpackPlugin',
    new FlowStatusWebpackPlugin({
      failOnError: true
    })
  );
}
```

**Comment by justin808** [comment]
Thanks @nburt!
