### ISSUE TITLE
Multiple bundles on one page

### ISSUE THREAD

**Issue by brandoncc** [shakacode/react_on_rails#1161]
Is it possible to have more than one bundle on a single page? I tried and I got an error saying my redux store was not registered. After that, I tried registering the same store in both bundles, and now I get an error saying some of my components are not registered. Is it only possible to call `ReactOnRails.register` and `ReactOnRails.registerStore` once each? I would like to import certain components in each bundle  and only include the ones that need to be included on each page.

As I type this out I realized that I think the issue with my entire goal is that we can't control the order in which the javascript loads, so this may not work at all. My goal is smaller files (my client bundle is just over 1MB and I want to get that down) and also not including some admin features that don't need to be on other pages.

**Comment by justin808** [comment]
@brandoncc are you using Webpack v4? It would take some special configuration to make the shared redux store work with Webpack v4 and multiple bundles.

**Comment by justin808** [comment]
btw -- use `defer` rather than `async` for the loading of the bundles.

**Comment by brandoncc** [comment]
No I am not, and I am not using either defer or async, just `<%= javascript_pack_tag 'my-bundle' %>`. Will deferring help me with my issues and allow me to load two bundles on one page? I realize now why you thought I was using async.....I guess I was thinking wrong and the js does load in the right order.
