### ISSUE TITLE
invalid SSL cert

### ISSUE THREAD

**Issue by sharuzzaman** [shakacode/react_on_rails#1165]
Hi, 

When trying to view the documentation, I got the following error message:

shakacode.gitbooks.io uses an invalid security certificate. The certificate expired on Sunday, September 09, 2018, 8:05 PM. The current time is Wednesday, November 07, 2018, 2:07 PM. Error code: SEC_ERROR_EXPIRED_CERTIFICATE

Thank you.

**Comment by justin808** [comment]
@sharuzzaman that was probably a temp issue for gitbooks. Thanks for reporting.
