### ISSUE TITLE
Can't import component when transform react-rails

### ISSUE THREAD

**Issue by Bac3Phi** [shakacode/react_on_rails#1172]
i used to use react-rails it auto import component but when i try import component to html ( js in slim html) like this.
`                ReactDOM.render(
                  React.createElement(Homes, response.data),
                  document.getElementById("homes_data")
                );
`
i got `ReferenceError: Homes is not defined`

**Comment by justin808** [comment]
@Bac3Phi did you call ReactOnRails.register so that React on Rails knows the definition of the component `Homes`?

Please reply and I'll reopen this issue if needed.
