### ISSUE TITLE
How to save JWT in SSR? Best way...

### ISSUE THREAD

**Issue by kvandake** [shakacode/react_on_rails#1177]
I love the work you're doing! However, I did not find a way to save the JWT token in the server render.
For myself, I have formed the following solutions:
- Save JWT token in cookie ((react-cookie)[https://www.npmjs.com/package/react-cookie])
- JWT token to pass through the controller - (redux_store)[https://github.com/shakacode/react_on_rails/blob/master/docs/api/redux-store-api.md#redux-store]

**What way best?**

**Comment by justin808** [comment]
@kvandake This is a better question for our slack discussion group. Send me your email justin@shakacode.com and we'll invite you.
