### ISSUE TITLE
Please add documentation on integrating with Jest

### ISSUE THREAD

**Issue by milieu** [shakacode/react_on_rails#1178]
I [managed](https://github.com/rails/webpacker/issues/416) to get it [working in the end](https://github.com/vuejs/vue-cli/issues/1584#issuecomment-445603990) but it would have been nice to have had an easier experience.

Hopefully what I linked helps someone down the line.

**Comment by justin808** [comment]
@milieu Jest is used for testing JS components. The setup should not be specific to React on Rails. What is the specific aspect that requires documentation? Let me know and I'll reopen this PR. Anyway, thanks for contributing.
