### ISSUE TITLE
React 16.7 use of short syntax <React.Fragment>

### ISSUE THREAD

**Issue by GYTO** [shakacode/react_on_rails#1193]
I just came across an interesting SyntaxError in my project. As we all know React 16.2 gave us an option to simplify `<React.Fragment>` with simple `<>`. In addition, I saw a comment on the [documentation](https://reactjs.org/docs/fragments.html#short-syntax) that:

> Note that many tools don’t support it yet so you might want to explicitly write <React.Fragment> until the tooling catches up.

In this case, I tried to `yarn upgrade @babel/core @babel/plugin-transform-react-jsx` as they recommend, but it didn't fix my problem.

I am really don't mind to use `<React.Fragment>` in my code, but I would prefer to use `<>` to simplify my code without nesting. Anyways, the question is this still possible to do it in react on rails? If yes, am I missing something?

Here is my package.json dependency list
```
"dependencies": {
    "@rails/webpacker": "3.5",
    "babel-preset-react": "^6.24.1",
    "noty": "^3.2.0-beta",
    "prop-types": "^15.6.2",
    "react": "^16.7.0",
    "react-dom": "^16.7.0",
    "react-modal": "^3.8.1",
    "react-on-rails": "11.2.2"
  }
```

**Comment by justin808** [comment]
@GYTO I'm pretty sure that this is not related to react_on_rails. I'd update to the latest libraries and then if that doesn't work, create a super simple reproduction case, and I'll reopen this issue.

**Comment by GYTO** [comment]
@justin808 thank you, I will try it today!
