### ISSUE TITLE
Precompiling assets failed. - ruby 2.6.1 - Heroku

### ISSUE THREAD

**Issue by brentgreeff** [shakacode/react_on_rails#1194]
react_on_rails worked great until I upgraded Ruby & bundler:

remote:        Your app was upgraded to bundler 2.0.1.
remote:        Previously you had a successful deploy with bundler 1.15.2.
remote:        
remote:        If you see problems related to the bundler version please refer to:
remote:        https://devcenter.heroku.com/articles/bundler-version
remote:        
remote: -----> Using Ruby version: ruby-2.6.1
remote: -----> Installing dependencies using bundler 2.0.1
remote:        Ruby version change detected. Clearing bundler cache.
remote:        Old: ruby 2.5.1p57 (2018-03-29 revision 63029) [x86_64-linux]
remote:        New: ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-linux]
remote:        Running: bundle install --without development:test --path vendor/bundle --binstubs vendor/bundle/bin -j4 --deployment

bundle goes fine.

remote:        Bundle completed (178.22s)
remote:        Cleaning up the bundler cache.
remote: -----> Installing node-v8.10.0-linux-x64
remote: -----> Installing yarn-v1.5.1
remote: -----> Detecting rake tasks
remote: -----> Preparing app for Rails asset pipeline
remote:        Running: rake assets:precompile
remote:        cd "/tmp/build_fa1b44aefecf8d4d97d21f9d582bb4b0" && RAILS_ENV=production NODE_ENV=production bin/webpack
remote:        /tmp/build_fa1b44aefecf8d4d97d21f9d582bb4b0/vendor/bundle/ruby/2.6.0/gems/webpacker-3.5.5/lib/webpacker/webpack_runner.rb:11:in `exec': No such file or directory - /tmp/build_fa1b44aefecf8d4d97d21f9d582bb4b0/node_modules/.bin/webpack (Errno::ENOENT)
remote:        	from /tmp/build_fa1b44aefecf8d4d97d21f9d582bb4b0/vendor/bundle/ruby/2.6.0/gems/webpacker-3.5.5/lib/webpacker/webpack_runner.rb:11:in `block in run'
remote:        	from /tmp/build_fa1b44aefecf8d4d97d21f9d582bb4b0/vendor/bundle/ruby/2.6.0/gems/webpacker-3.5.5/lib/webpacker/webpack_runner.rb:10:in `chdir'
remote:        	from /tmp/build_fa1b44aefecf8d4d97d21f9d582bb4b0/vendor/bundle/ruby/2.6.0/gems/webpacker-3.5.5/lib/webpacker/webpack_runner.rb:10:in `run'
remote:        	from /tmp/build_fa1b44aefecf8d4d97d21f9d582bb4b0/vendor/bundle/ruby/2.6.0/gems/webpacker-3.5.5/lib/webpacker/runner.rb:6:in `run'
remote:        	from bin/webpack:15:in `<main>'
remote:        I, [2019-02-15T22:07:43.000559 #2148]  INFO -- : Sending event d73e50e7e1884ab6a97376bb718d6613 to Sentry
remote:        D, [2019-02-15T22:07:43.006734 #2148] DEBUG -- : Raven HTTP Transport connecting to https://sentry.io
remote:        rake aborted!
remote:        Command failed with status (1): [cd "/tmp/build_fa1b44aefecf8d4d97d21f9d582...]
remote:        /tmp/build_fa1b44aefecf8d4d97d21f9d582bb4b0/vendor/bundle/ruby/2.6.0/gems/react_on_rails-11.2.2/lib/tasks/assets.rake:64:in `block (3 levels) in <main>'
remote:        /tmp/build_fa1b44aefecf8d4d97d21f9d582bb4b0/vendor/bundle/ruby/2.6.0/gems/rake-12.3.2/exe/rake:27:in `<top (required)>'
remote:        Tasks: TOP => assets:precompile => react_on_rails:assets:compile_environment => react_on_rails:assets:webpack
remote:        (See full trace by running task with --trace)
remote: 
remote:  !
remote:  !     Precompiling assets failed.
remote:  !
remote:  !     Push rejected, failed to compile Ruby app.
remote: 
remote:  !     Push failed

Seems strange that the webpacker gem would be in : vendor/bundle/ruby/2.6.0
when I am using 2.6.1

**Comment by brentgreeff** [comment]
Heroku buildpack issue.

**Comment by hugoh59** [comment]
How to solve this?
