### ISSUE TITLE
"There are no stores hydrated..." error 

### ISSUE THREAD

**Issue by robbymarston** [shakacode/react_on_rails#1195]
Hello,

Currently, I'm working with this setup (simplified for readability):

### react_on_rails 11.1.4

**Layout Controller (index method)**
`redux_store('appStore', props: { foo: 'bar' })`

**Layout**
`<%= redux_store_hydration_data %>` (before close of body tag)

**View**
`<%= react_component('FooBar') %>`

**JavaScript**
`ReactOnRails.registerStore({ appStore });`

If I inspect the source, the data and the component appear to be present; however, the component itself isn't rendering due to these fatal errors: 

`Uncaught Error: There are no stores hydrated and you are requesting the store managerStore...`
`Uncaught Error: Could not find store registered with name 'managerStore'. Registered store names include...`

So far as I can tell, the setup is inline with what's been outlined in the documentation so I'm wondering if this is a bug of some sort.

**Comment by justin808** [comment]
```js
ReactOnRails.registerStore({ appStore });
```
Note: **appStore**.

# ERROR
```
Uncaught Error: There are no stores hydrated and you are requesting the store managerStore
```

Note: **managerStore**.

**Comment by justin808** [comment]
Correct line:

```js
ReactOnRails.registerStore({ managerStore });
```

**Comment by robbymarston** [comment]
Ah, I forgot to edit the error messages to match the naming in my examples. In reality, they do match and the error is still present. I suppose I’ll just have to keep debugging. Thanks for your attention regardless.

**Comment by justin808** [comment]
You need the register call to run when the bundle loads. Put in some console logs before you call register. However, depending on your app, you may not want to be using the separate redux store. 


```js
ReactOnRails.registerStore({ managerStore });
```
