### ISSUE TITLE
ERROR: Procfile.dev does not exist.

### ISSUE THREAD

**Issue by sugarsyntax** [shakacode/react_on_rails#1197]
Followed [setting up the environment](https://github.com/shakacode/react_on_rails/blob/master/docs/tutorial.md#setting-up-the-environment). On running `foreman start -f Procfile.dev` I got the error `ERROR: Procfile.dev does not exist.`.

**Comment by justin808** [comment]
@sugarsyntax you have to create that file or have used the "generator." Check out the [tutorial](https://github.com/shakacode/react_on_rails/blob/master/docs/tutorial.md).

If you get stuck, please reply.

**Comment by TangMonk** [comment]
> @sugarsyntax you have to create that file or have used the "generator." Check out the [tutorial](https://github.com/shakacode/react_on_rails/blob/master/docs/tutorial.md).
> 
> If you get stuck, please reply.

tutorail link lost

**Comment by ahangarha** [comment]
@TangMonk 
This is the correct link: https://github.com/shakacode/react_on_rails/blob/master/docs/guides/tutorial.md
This issue is already fixed and will be available in the coming release.
