### ISSUE TITLE
[Documentation] Hyperlink for Webpack tips not working.

### ISSUE THREAD

**Issue by lalitha94** [shakacode/react_on_rails#1201]
The hyperlink for Webpack tips(under Javascript) doesn't seem to work/is disabled.

**Comment by justin808** [comment]
@lalitha94 can you give me a link? What page?

**Comment by lalitha94** [comment]
Webpack tips (link on the left side under javascript) in https://shakacode.gitbooks.io/react-on-rails/content/

**Comment by justin808** [comment]
Should be fixed: https://github.com/shakacode/react_on_rails/commit/3fd2eb406ddc7c1665d33398f4512d72cf595dce
