### ISSUE TITLE
Generator function as higher order component doesn't expose railsContext

### ISSUE THREAD

**Issue by nratter** [shakacode/react_on_rails#1204]
If I wrap my generator function as a higher order component, railsContext isn't exposed. A workaround for this is, of course, to wrap the higher order component with the generator function. Any plans to change this?

**Comment by justin808** [comment]
@nratter can you provide a code example? The entry for going from the Rails view to some JavaScript function is to pass two objects:

* Params
* rails_context

Then you do as you want with those.

**Comment by nratter** [comment]
This exposes the railsContext...

`
import React from 'react';

const MyComponent = (props, railsContext) => {
  return <div>{railsContext.somethingUseful}</div>
}

export default MyComponent;
`

The following does not. railsContext in this case is just an empty object...

`
import React from 'react';
import { withStyles } from '@material-ui/core/styles';

const styles = {}

const MyComponent = (props, railsContext) => {
  return <div>{railsContext.somethingUseful}</div>
}

export default withStyles(styles)(MyComponent);
`

**Comment by tahsin352** [comment]
@nratter 
@justin808 

I have checked HOC with railsContents. railsContext is available for each react component as 2nd parameter. But when we implement HOC, then it return empty. Coz, only props can be passed from parent component to child component. So, if you want to pass railsContext to child component, then you need to pass it as props like below:
```
//client/bundles/HelloWorld/components/WithSearch.jsx
import React from 'react';
import SearchContext from './SearchContext';
const WithSearch = (WrappedComponent) => (props, railsContext) => {
    return (
      <div>
        <WrappedComponent {...{...props, railsContext}} />
      </div>
    )
  }
export default WithSearch(SearchContext);

//client/bundles/HelloWorld/components/SearchContext.jsx
import React from 'react';
import { hot } from 'react-hot-loader/root';
const SearchContext = (props) => (
  <div className="ui raised segment no padding">
    Your locale is {props.railsContext.i18nLocale}.<br/>
    Hello, {props.name}!
  </div>
);

export default hot(SearchContext)
```

code example : https://github.com/tahsin352/react-hot-loader-react-on-rails-webpack-hmr#hoc-with-railscontext

Thanks
