### ISSUE TITLE
Error: Cannot resolve module

### ISSUE THREAD

**Issue by marcellosachs** [shakacode/react_on_rails#121]
I received the message "Error: Cannot resolve module ___" for a number of modules, including - 
jquery-ujs
immutable
imports
es5-shim/es5-shim
es5-shim/es5-sham

After going into the client directory, I ran 
`npm install --save jquery-ujs`
and so on and so forth for each of the missing modules, which fixed it.
(Note: it was only after resolving the issue for some of the modules that the errors for the other modules came up)
(Note: for 'imports' the module name used in the command was 'imports-loader' (https://github.com/bline/bootstrap-webpack/issues/5), and for  es5-shim/es5-shim and es5-shim/es5/sham the module name used in the command was just es5-shim.

**Comment by justin808** [comment]
@marcellosachs The generator can only do so much. You need to know how to add any other libraries and configure webpack on your own after the basic install.

Send me an email and I'll invite you to our slack group.

**Comment by marcellosachs** [comment]
@justin808 ok cool, I'll have to take a closer look at webpack and npm. 
Slack group would be great, I'll send an email - thanks!
