### ISSUE TITLE
Documentation for contributions improvement

### ISSUE THREAD

**Issue by kvokka** [shakacode/react_on_rails#1211]
Installing the gem into clean environment I feced up a few different problems, which was small, but frustrating. May be will be good idea to put all this knowledge somewhere or maybe my spent time will be useful for somebody.

All of this was taken from error messages and internal docs. But It will be much better to have all of this in some part of the documentation.

The list of fixes:

```bash
# Setup yarn link

cd react_on_rails
yarn link
cd spec/dummy/client
yarn link react-on-rails

# I had gem thor version 0.20, but it raise an issue until i installed manually previous version
gem install thor -v '0.19.4'

# extra dependencies 
npm i -g webpack
npm i -g webpack-dev-server
brew install selenium-server-standalone
```

What do you think about it?

**Comment by justin808** [comment]
@kvokka Yarn link has pluses and minuses. I've been trying to switch to yalc. The minus of that is that you have to run `yarn` in the `client` directory every time you make a change.

`yarn link` will get the version of packages from the root level. If all the package versions are the same, then no problem. When the React version is different at the top and the bottom, then 💣 .

I don't understand the other suggestions.

**Comment by kvokka** [comment]
@justin808 I'm totally ok with using `yarn` here. The only question is, that this link is mandatory for `dummy` application and you can find this requirement in `spec/dummy/readme.md`. At the same time you have no information in the docs about it. Maybe it will be just enough to put the reference to `dummy/readme`?

About `thor` version missing- looks like i got a mess with `asdf` manager and different rails versions in the bundle and with out it. When i the environment moved to https://github.com/timbru31/docker-ruby-node this problem was gone. Sorry about that.

My laptop did not contain webpack or selenium driver (it was not very useful for api), so i had to install it also. Not a big deal, but it looks like will be good idea to add a few lines to the docs about it, just for further contributions.

**Comment by justin808** [comment]
@kvokka sure. feel free to give add a bit to the docs via a PR.

**Comment by Aeropio** [comment]
Hello @justin808  how can I contribute to the docs?

**Comment by justin808** [comment]
@Aeropio Try using them and submitting PRs that make them better.
