### ISSUE TITLE
WARNING: V8 isolate was forked, it can not be disposed and memory will not be reclaimed till the Ruby process exits.

### ISSUE THREAD

**Issue by jeznag** [shakacode/react_on_rails#1216]
I'm getting these warnings when running rspec tests for my react on rails project.
![image](https://user-images.githubusercontent.com/1034890/58218399-1121f200-7d4a-11e9-937f-cc9e3fa850ce.png)

I can only assume it's due to React on Rails as nothing else uses the mini_racer gem. Any ideas?

**Comment by justin808** [comment]
What does your gemfile and gemfile.lock contain?

This might be related. Using Thin? or Puma?

https://meta.discourse.org/t/development-server-consistently-dying-v8-isolate-was-forked/55878/4

**Comment by jeznag** [comment]
It's only when running tests

**Comment by topstar26** [comment]
one thing that dropping thin did bring up is that our silencer middlewares were not thread safe. That got super annoying in dev mode cause logs would keep getting disabled.

**Comment by marvin-min** [comment]
> What does your gemfile and gemfile.lock contain?
> 
> This might be related. Using Thin? or Puma?
> 
> https://meta.discourse.org/t/development-server-consistently-dying-v8-isolate-was-forked/55878/4

Unicorn have the same issue.
