### ISSUE TITLE
Asset precompilation in production/test misses yarn install

### ISSUE THREAD

**Issue by kstratis** [shakacode/react_on_rails#1217]
Allow me to add some injury to the insult:

Since Rails 5.1 `yarn install` runs as part of the command: 

    RAILS_ENV=production bundle exec rake assets:precompile

However with React On Rails ([here](https://github.com/shakacode/react_on_rails/blob/0e7c86c3153ba02c001f43c4358091c3a675dced/lib/tasks/assets.rake#L37)) the included `assets.rake` task runs its own compilation tasks just before the default ones but this time around it doesn't include a `yarn install` task. The problem is that by running as part of the `assets:precompile` task but before the included default ones it fails to install any node packages with `yarn install` and consequently fails on any fresh installation.

As a result in Capistrano doing `cap production deploy` fails due to the missing `yarn install` task. As a workaround I've included a custom yarn install task just before the `assets:precompile` task however this will run twice as `assets:precompile` will also do the same (but at a later time) as part of its functionality.

Maybe related to #1202

**Comment by justin808** [comment]
@kstratis why not just run yarn install after loading the repo. You do the same for bundle, don't you?

**Comment by kstratis** [comment]
That would be perfectly fine however I’m using Capistrano for my deployments and SSHing into the server just to run yarn install is impractical.

Setting yarn install as a prerequisite of assets.rake would do the trick I think...
