### ISSUE TITLE
Capistrano deployment fails: /usr/bin/env: ‘yarn’ >> No such file or directory

### ISSUE THREAD

**Issue by nrl240** [shakacode/react_on_rails#1221]
I followed the [Capistrano Deployment](https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/capistrano-deployment.md) walkthrough, but I'm not having any luck.

```
cap aborted!
SSHKit::Runner::ExecuteError: Exception while executing as deploy@staging-web0.porterandsail.com: yarn exit status: 127
yarn stdout: Nothing written
yarn stderr: /usr/bin/env: ‘yarn’: No such file or directory
/Users/noelle/.rvm/gems/ruby-2.2.1@companyname/gems/sshkit-1.14.0/lib/sshkit/runners/parallel.rb:15:in `rescue in block (2 levels) in execute'
/Users/noelle/.rvm/gems/ruby-2.2.1@companyname/gems/sshkit-1.14.0/lib/sshkit/runners/parallel.rb:11:in `block (2 levels) in execute'
SSHKit::Command::Failed: yarn exit status: 127
yarn stdout: Nothing written
yarn stderr: /usr/bin/env: ‘yarn’: No such file or directory
```
I also notice that every time I run `cap staging deploy --trace`, the following three files get deleted:
- public/packs/manifest.json
- public/packs/js/hello-world-bundle-ef39be50a958cbbaae10.js
- public/packs/js/hello-world-bundle-ef39be50a958cbbaae10.js.map

Additional information:
**Gemfile**
```
gem 'rails', '4.2.3'
gem 'webpacker', '~> 4.x'
gem 'react_on_rails', '~> 11.3'
gem 'libv8', '~> 6.3.0'
gem 'mini_racer', '~> 0.1.15'
```

**Ruby Version** ruby 2.2.1p85 (2015-02-26 revision 49769)

**Comment by dagi377** [comment]
any updates on this ? 
I think this is something related to running machine host capabilities like cpu and memory allocation, I would love to hear from the team it self.

**Comment by dagi377** [comment]
I am no longer getting this error. It was related to how the ssh bash connects. It doesn't really load paths like the normal bash so just setting the path  [here more ](https://stackoverflow.com/questions/19716131/usr-bin-env-ruby-no-such-file-or-directory-using-capistrano-3-capistrano-rben) . 


so doing the following solved it for me 

`set :default_env, { path: "/home/ubuntu/.nvm/versions/node/v12.0.0/bin" }`
