### ISSUE TITLE
Defer the call to hydrate for use with react-loadable

### ISSUE THREAD

**Issue by jav974** [shakacode/react_on_rails#1222]
Hi,

I would like to know how i could defer the call to ReactDOM.hydrate. I'm using react-loadable library to split components and asynchronously load them on client when necessary. I also do server rendering and following the doc of react loadable i should to something like that on the client code:

Loadable.preloadReady().then(() => {
  ReactDOM.hydrate(<App/>, document.getElementById('app'));
});

but this call is made automatically by ReactOnRails and I don't see how i could wrap it to let react-loadable do its job.

Any help on this ?
Thank you very much for this fantastic lib !

**Comment by jav974** [comment]
Found it ^^ soon after posting the question... here is the link : [https://github.com/shakacode/react_on_rails/blob/master/docs/misc-pending/code-splitting.md](url)

**Comment by Romcol** [comment]
Hi @jav974 , did you actually have success implementing it?
Can you share your code? :grin: 

I don't have many problems with client side rendering. But I have some problems implementing it react-loadable with SSR and React on Rails `require is not a function","TypeError: require is not a function\n    at eval (webpack:///external_%22@loadable/server%22?:1:18)`.

Could we help each other out?

Cheers

**Comment by jav974** [comment]
@Romcol Sure we can help each other ! Indeed i got it implemented, now it is working very very well. But i can not share the code since it bundles a HUGE LOT of things.. but i can help for sure.

What kind of environment are you working with ? node process for the ssr (express or something else) ?

The require error makes me think that the bundle you created is wrong. If you use webpack and then include the resulted build in your node process for ssr, then you should specify these in your webpack config :

config.output.libraryTarget = 'commonjs2';
config.target = 'node';

In my babelrc i also use these two plugins : 
["react-loadable/babel"],
["@babel/plugin-syntax-dynamic-import"]

And finally i added the ssr package to my dependencies and launch the node process (which includes the user code app) with "-r esm" option. (This allows for using import syntax in nodejs, but this step was crucial to me ).

Let me know if you need something else, or if it works for you.
