### ISSUE TITLE
Server rendering in production

### ISSUE THREAD

**Issue by JensDebergh** [shakacode/react_on_rails#1225]
Hey there!

I'm having this issue for a couple of days now and don't know how to fix it.

I'm getting the following error on production:

```
No such file or directory @ rb_sysopen - public/js/server_rendering-7930ba59728fe68ecc97.js
```

This error is correct since no `.js` file is present with that name.

The actual path name is: 

`packs/js/server_rendering-7930ba59728fe68ecc97.js`

Any idea where this problem is coming from? This code works perfectly in development but it seems wrong paths get assigned when deploying.

Any help in the right direction would be extremely helpful.

Kind regards
Jens

**Comment by Judahmeek** [comment]
Sounds like there's a difference between the `public_root_path` and `public_output_path` of your webpacker.yml for the development and production environments

Your `config/initializers/react_on_rails.rb` might also be involved.

**Comment by JensDebergh** [comment]
This is kind of embarrassing. I'm using `react-rails` on my app so this is completely in the wrong issue tracker.

Sorry for the inconvenience.
