### ISSUE TITLE
Webpacker Manifest is empty on deploy after adding react-on-rails

### ISSUE THREAD

**Issue by kundurdzhieva** [shakacode/react_on_rails#1227]
Hi,
We moved to react and react-on-rails. Everything was ok before that but now we have problems on deploy with below log error:

ActionView::Template::Error: Webpacker can't find application.js in /public/packs-test/manifest.json. Possible causes:
1. You want to set webpacker.yml value of compile to true for your environment
unless you are using the webpack -w or the webpack-dev-server.
2. webpack has not yet re-run to reflect updates.
3. You have misconfigured Webpacker's config/webpacker.yml file.
4. Your webpack configuration is not creating a manifest.
Your manifest contains:
{
}
This is the result on deploy to the server with Jenkins. If we remove react-on-rails gem from Gemfile, deploy and assets are ok again. Am I doing something wrong or the problem is in  webpacker and react_on_rails working together?

 @kundurdzhieva

**Comment by justin808** [comment]
@kundurdzhieva Did you solve this issue yet? The possible causes listed above are pretty clear. You have to look at what files changed and do a little debugging.

**Comment by AlexKund** [comment]
@justin808 yes we solved it :)

**Comment by JoseMPena** [comment]
Hi @AlexKund would you share what was your issue and how did u solve it?

Thanks

**Comment by foton** [comment]
Maybe this help https://github.com/rails/webpacker/issues/2211
