### ISSUE TITLE
Unable to push new project to heroku

### ISSUE THREAD

**Issue by hugoh59** [shakacode/react_on_rails#1228]
Why is it so hard to push to Heroku with react on rails? Every-time I create a new project I spend countless hours trying to make it work. Is there no default config that works?

I get:

`ActionView::Template::Error (Webpacker can't find hello-world-bundle in /app/public/packs/manifest.json. Possible causes:`

and 

`bundler: failed to load command: puma (/app/vendor/bundle/ruby/2.5.0/bin/puma)`

**Comment by justin808** [comment]
@hugoh59 Did you solve your problem? If so, what was the solution?

**Comment by justin808** [comment]
@hugoh59 did you follow the steps at https://github.com/shakacode/react_on_rails/blob/master/docs/tutorial.md
