### ISSUE TITLE
Test examples for store, state, actions, reducers

### ISSUE THREAD

**Issue by AlexKund** [shakacode/react_on_rails#1235]
Hi,
Ive implemented react-redux, register_store and etc functionality successfully, but I need a good example for testing store and state in the context of react_on_rails. In the internet Ive just found tests examples with React/redux, dispatchers, connect and etc., but not a single example in react_on_rails context because redux/react-redux implementation there is a bit different. Haven't found such Unit test with Jest for example in react_on_rails repo too.
Ive searched in issues and found [#707](https://github.com/shakacode/react_on_rails/issues/707) with 4 links - two of them broken and other for feature specs but not for Unit tests with redux

**Comment by justin808** [comment]
The react_on_rails context are simply some props that get added to every call to render a component. There's nothing fancy about them.

Don't get that concept confused with the React context, redux, etc. It's just not related.

See https://github.com/shakacode/react_on_rails/blob/master/docs/basics/generator-functions-and-railscontext.md#generator-functions

**Comment by AlexKund** [comment]
@justin808 May be its my fault that I didn't describe things better and there is some misunderstood. I just wanted to know how to test Store and all that redux/actions/store functionality like if store changes it should reflect in component changes. For example:

store.js
```
import {createStore} from 'redux';
import AlertReducer from '../reducers/AlertReducer';

// Create a hydrated redux store, using props and the railsContext (object with
// Rails contextual information).
const configureStore = (props) => createStore(AlertReducer, props);

export default configureStore;
```


confirmationDialogContainer.jsx
```
mport React from 'react';
import {Provider, connect} from 'react-redux';
import ConfirmationDialog from './ConfirmationDialog';
import * as actions from '../../actions/ConsumerPrepaidCardsActions';

// Which part of the Redux global state does our component want to receive as props?
const mapStateToProps = (state) => state;

const ConfirmationDialogConnected = connect(mapStateToProps, actions)(ConfirmationDialog);

export default _props => {
  const appStore = ReactOnRails.getStore('appStore');

  return (<Provider store={ReactOnRails.getStore("myStore")}><ConfirmationDialogConnected {..._props} /></Provider>);
};
```
app.js
```
...
import appStore from '../bundles/store/store';

ReactOnRails.register({
    DatePickerRange, Dpicker, TimeOut, PhoneNumber, SignIn, ConsumerPrepaidCards, Alert
});

ReactOnRails.registerStore({
    appStore
});

```
confirmationDialog.spec.jsx
```
import ConfirmationDialogIntl from 'bundles/components/ConfirmationDialog/ConfirmationDialog';
import appStore from 'bundles/store/store';

console.log('get store', ReactOnRails.getStore('appStore'));

describe('ConfirmationDialog', () => {
...
```

Trying to use store here in test it gives me an error:
  ● Test suite failed to run

    There are no stores hydrated and you are requesting the store appStore.
    This can happen if you are server rendering and either:
    1. You do not call redux_store near the top of your controller action's view (not the layout)
       and before any call to react_component.
    2. You do not render redux_store_hydration_data anywhere on your page.

so I cant imagine how to deal with that error.

**Comment by justin808** [comment]
You are missing controller code:

```
There are no stores hydrated and you are requesting the store appStore.
This can happen if you are server rendering and either:
1. You do not call redux_store near the top of your controller action's view (not the layout)
   and before any call to react_component.
2. You do not render redux_store_hydration_data anywhere on your page.
```

**Comment by AlexKund** [comment]
Yes but during javascript tests controller has nothing to do with that code. May be this ReactOnRails.getStore('appStore')) has to be mocked some how.

**Comment by AlexKund** [comment]
@justin808 "You are missing controller code" - tnx for that hint. Finally I've managed to deal with testing redux and store with this gem. Ive placed controller registration store into js test sand tnx to how flexible you made react_on_rails gem all started to work as expected :). Here is the code:

Ive added this lines in confirmationDialog.spec.js:
```
import ConfirmationDialogIntl from 'bundles/components/ConfirmationDialog/ConfirmationDialog';
import ConfirmationDialogContainer from 'bundles/components/ConfirmationDialog/ConfirmationDialogContainer';
import AlertContainer from 'bundles/components/Alert/AlertContainer';
import * as actions from 'bundles/actions/ConsumerPrepaidCardsActions';
import appStore from 'bundles/store/store';

ReactOnRails.registerStore({appStore});

const propsConfirmDialog = {
        url: 'fake-url',
        action: 'block',
        successMessage: 'A request for blocking the prepaid card was sent successfully.',
        onHandleConfirm: jest.fn()
    },
    token = '1234',
    storeGenerator = ReactOnRails.getStoreGenerator('appStore'),
    store = storeGenerator({set_alert: {}});

ReactOnRails.setStore('appStore', store);
describe('on click confirmation button', () => {
        let ConfirmationDialogComponentIntl, buttonConfirm, AlertContainerComponent, spySetAlert;
        beforeEach(() => {
            axios.patch.mockImplementation(() => Promise.resolve());

            spySetAlert = jest.spyOn(actions, 'setAlert');
            ConfirmationDialogComponentIntl = mountWithIntl(<ConfirmationDialogContainer {...propsConfirmDialog}  />);
            AlertContainerComponent = mount(<AlertContainer/>);

            buttonConfirm = ConfirmationDialogComponentIntl.find(".btn-confirm-block");
            buttonConfirm.simulate('click');
        });

        afterEach(() => axios.mockReset());

        test('should call  action setAlert', done => {
            expect(spySetAlert).toHaveBeenCalled();
            done();
        });

        test('should show alert on setAlert true', done => {
            const store = ReactOnRails.getStore('appStore'),
                state = store.getState(),
                stateSuccess = { set_alert: {
                        shouldShow: true,
                        message: 'A request for blocking the prepaid card was sent successfully.',
                        className: 'alert-success'}};

            AlertContainerComponent.update();

            expect(state).toMatchObject(stateSuccess);
            expect(AlertContainerComponent.find('.alert').length).toEqual(1);
            done();
        });
    });
```
So I can test actions, and changes in state for connected components as ConfirmationDialog and Alert. Tnx once again and I highly appreciate how good you create that gem!
