### ISSUE TITLE
Element ID's are not unique

### ISSUE THREAD

**Issue by milosvukadinovic** [shakacode/react_on_rails#1238]
![Ss1](https://user-images.githubusercontent.com/18657599/71481896-1b383180-2800-11ea-955c-8391572b0129.jpg)

Greetings! I am so excited to open this issue.

## Problem:
* At first glance, I've noticed the design of some components is not finished, and that some components have overlapping IDs which shouldn't happen in HTML, ID's are supposed to be unique.

## Solution:
* I would like to add some style to the components as well as fixing the above problem, while I am doing this I hope to notice more issues to work on.

**Comment by justin808** [comment]
Yes, feel free to submit a PR and I'll review it!

**Comment by justin808** [comment]
@milosvukadinovic feel free to reopen this.
