### ISSUE TITLE
React on Rails v12, 2020

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#1243]
Planned updates for React on Rails and React on Rails Pro for v12
---

# Cleanup
 - [x] Add CircleCI config
- [x] Update all gems and node packages, including linters and formatters (@behraaangm)
  - [x] Requires Ruby 2.5+, since [2.4 is no longer supported](https://www.ruby-lang.org/en/news/2019/03/31/support-of-ruby-2-3-has-ended/). 
  - [x] Updated ruby syntax for newer rubies
  - [x] Require Rails 5+ (See [this commit for rails/webpacker](https://github.com/rails/webpacker/commit/f467cb315679c28293824c32bb567b3481057b0c)
- [x] Requires rails/webpacker, 
  - [x] Remove test directory spec/dummy_no_webpacker, b/c requires only rails/webpacker, [PR 1255](https://github.com/shakacode/react_on_rails/pull/1255)
  - [x] Require the use of the rails/webpacker helpers for referencing webpack created files on the view. No more pushing webpack output through Sprockets.
  - [x] Removal of [env_javavascript_include_tag and  env_stylesheet_link_tag](https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/helper.rb#L48-L71)
  - [x] Remove option symlink_non_digested_assets_regex [PR 1263](https://github.com/shakacode/react_on_rails/pull/1263)

## Other
- [x] Better support with sprockets not installed for rake tasks. See [rails/webpacker](https://github.com/rails/webpacker/blob/master/lib/tasks/webpacker/compile.rake#L38)
- [x] Better support having webpacker's compile run a React on Rails custom webpack setup. Multiple configurations can use the [webpack multi-compiler](https://github.com/webpack/webpack/tree/master/examples/multi-compiler). 
- [x] Maybe Add React on Rails config option if server-rendering file should be provided by the webpack-dev-server (probably hashed) or without a hash always and always provided statically. The reason is that Rails will not easily know. However, so long as we never write to the manifest, and no hash, when creating the server bundle statically, then we can just check the manifest. If there and webpack-dev-server running, then get from webpack-dev-server. Or else, get from the Rails server.
 
# Features
- [x] Hot reloading, HMR with https://github.com/pmmmwh/react-refresh-webpack-plugin
- [x] Easy bundle splitting with https://github.com/gregberge/loadable-components#readme 

# For Discussion
- [ ] Remove the generator option for redux since hooks is now preferred. How about we migrate the redux generator to a hooks generator? or just remove?

**Comment by jasonslate** [comment]
How long would it take to implement bundle splitting? We have a large app that serves three user personas (admin, client, guest). Our current webpack bundle is enormous and we want to split it up for the three sections of the platform to increase performance.

@justin808

**Comment by justin808** [comment]
Hi @jasonslate,

Depending on your current code, it's pretty easy with our "React on Rails Pro".  You can find a few more details here:  [shakacode.com/react-on-rails-pro](https://www.shakacode.com/react-on-rails-pro).

I suggest we have a complimentary call to go over your requirements. Here's my [meeting link](https://meetings.hubspot.com/justingordon/30-minute-consultation). You can also reach me directly at [justin@shakacode.com](mailto:justin@shakacode.com).

**Comment by peterzhu2118** [comment]
Hey @justin808, thanks for this great library! Do you have any plans on making a (beta) release for v12 anytime soon? It's been a year since the last release and I'm hoping to be able to use features like hooks.

**Comment by justin808** [comment]
Hey @peterzhu2118! Gem version: 12.0.0.pre.beta.0 and npm version 12.0.0-beta.0 released! Please try this out!

https://www.npmjs.com/package/react-on-rails
https://rubygems.org/gems/react_on_rails

**Comment by peterzhu2118** [comment]
@justin808 Thanks so much! Functional components now works in my (fairly trivial) app.

**Comment by justin808** [comment]
Hey, hey, React on Rails v12 has shipped!

**Comment by augustosamame** [comment]
Just in time for my first React on Rails project! Awesome gem!

**Comment by justin808** [comment]
Everything was done!

Anything else desired?
