### ISSUE TITLE
Generator should not add server side bundle compliation instructions into assets.rake when server side rendering is not specified in generator params

### ISSUE THREAD

**Issue by szyablitsky** [shakacode/react_on_rails#127]

**Comment by justin808** [comment]
@szyablitsky @robwise This is basically correct that we might not have as server side bundle. But how would we know? Maybe we just change the generated rake task to check for the server webpack config file before trying to run it?

**Comment by robwise** [comment]
@szyablitsky does this issue break the build in production?

**Comment by szyablitsky** [comment]
Yes, it break the build. I had to comment `sh "cd client && npm run build:server"` in `assets.rake`

**Comment by robwise** [comment]
Yeah in that case I'd consider this a bug and it needs to be fixed

**Comment by justin808** [comment]
@yorzi did any of your recent changes address this one?

**Comment by justin808** [comment]
@szyablitsky @yorzi I'm guessing this is still an issue. @rstudner want to take a crack at it? Any volunteers?

**Comment by yorzi** [comment]
@justin808 recent changes didn't cover this one.
