### ISSUE TITLE
Update core-js version.

### ISSUE THREAD

**Issue by VincentLanglet** [shakacode/react_on_rails#1278]
When installing the library I get the following warning
```
react-on-rails > @babel/runtime-corejs2 > core-js@2.6.11: core-js@<3 is no longer maintained and not recommended for usage due to the number of issues. Please, upgrade your dependencies to the actual version of core-js@3.
```

I have no idea but the impact of the change, but it seems like `@babel/runtime-corejs3` should be used instead of `@babel/runtime-corejs2`.

**Comment by justin808** [comment]
@VincentLanglet totally agree. 

I see it's listed here: https://github.com/shakacode/react_on_rails/blob/master/package.json#L52

Would you like to take a try at a PR?
