### ISSUE TITLE
Create NPM module with the API (v2.0.0)

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#128]
I had a detailed discussion with @alexfedoseev.

ASAP, I'm going to do the following:

Introduce this API via a node module, react_on_rails:

```js
import ReactOnRails from 'react_on_rails';
ReactOnRails.register('HelloWorldApp', HelloWorldAppServer);
```

This will work for both `serverGlobals.jsx` and `clientGlobals.jsx`.

We'll put the registered components on `ReactOnRails.components['componentName']` rather than polluting the global namespace.

- [x] Add api `ReactOnRails.register(componentName, component, generator_function = false)`. We can set the fact a component is really a generator_function with the 3rd argument.
- [ ] We'll also make the other ReactOnRails API's available via the node module.
- [x] We'll use the same repo as the gem as we want a single release script that releases both the gem and
- [x] startup will check that /client/package.json contains react_on_rails, and that the version number is the same as the gem, and quit if it is not.
- [x] convert react_on_rails.js to use babel.
- [x] automatically export ReactOnRails to the global namespace (no explicit export in webpack needed). The entry point of ReactOnRails will be required for the client and server bundles.
- [x] OPTIONAL -- for backwards compatibility, do we check if the component is declared on the global namespace? Probably.

CC: @alexfedoseev, @dylangrafmyre, @robwise  

-----

Example places this will be used:

https://github.com/shakacode/react_on_rails-generator-results-v1.0.3/pull/111/files#diff-3f5b3fdbb5756c6fb057f19689e92a1aR2

https://github.com/shakacode/react_on_rails-generator-results-v1.0.3/pull/112/files#diff-d012fe328a02dd847c8241e3d58d6a2aR3

```js
import ReactOnRails from 'react_on_rails';
import HelloWorldAppServer from './HelloWorldAppServer';
ReactOnRails.register('HelloWorldApp', HelloWorldAppServer);
```

**Comment by justin808** [comment]
https://github.com/shakacode/react_on_rails-generator-results-v1.0.3/pull/111/files#diff-3f5b3fdbb5756c6fb057f19689e92a1aR2

**Comment by justin808** [comment]
@alexfedoseev, @jbhatab, @robwise, anybody: Please review this list. What do you think about allowing the specification of the generator_function in the JS code:

- [ ] Add api `ReactOnRails.register(componentName, component, generator_function = false)`. We can set the fact a component is really a generator_function with the 3rd argument.

**Comment by robwise** [comment]
@justin808 

- If we convert the gem's JS code to use Babel we should create some sort of buildtask for compiling it and ensure it is part of the deploy script. Maybe that's obvious.
- One option besides requiring the user to explicitly call `ReactOnRails.register()` is to simply override the `React.createClass` function with our own that first calls the original implementation and then registers the resulting component automatically. If the user wants to use a generator function, then obviously they will need to call it explicitly, so we could call it `ReactOnRails.generatorFunction()`

**Comment by justin808** [comment]
@robwise I'm not following the second comment.

Maybe passing an object is better, as the params are explicit:

```js
ReactOnRails.register({componentName: <componentName>, component: <realComponent>, generator_function: false})
```

**Comment by justin808** [comment]
@yorzi, I could pair with you on this one as well.

**Comment by yorzi** [comment]
@justin808 I need to understand this issue first.

**Comment by rstudner** [comment]
@robwise - while overriding React.createClass would be rather elegant/seamless, it just has that "what could happen someday" scariness to it (or when things go "all es6" etc etc)

**Comment by justin808** [comment]
@yorzi If you're interested, we can ScreenHero and/or Skype and explain what needs to get done. This job is so much fun that I want to do it, but I'd be happy to share!

**Comment by robwise** [comment]
@justin808 I was saying you can essentially override React's `createClass` method to do what it does normally, but then also register the component automatically.

**Comment by justin808** [comment]
@robwise We don't ever override createClass. We have 2 ways to create a react component (ES6 extend React.Component and React.createClass for ES5), and we offer the ability for the developer to provide a "generator function" which takes props and returns an React.Component (using ES6 or ES5 syntax). 

We had to add the generator_function option because we cannot reliably determine a user function from the function created by React.createClass (yes, that returns a function!).

**Comment by robwise** [comment]
@justin808 I know we don't, I was suggesting we do

**Comment by justin808** [comment]
@robwise and I discussed this. We'll go with my original plan.

**Comment by yorzi** [comment]
@justin808 I am not familiar with NPM eco-system, not sure if I can work this out. But I am still interested in learning these things, that'd be great if someone with better experience can guide me to start and work tegother with me on this.

**Comment by robwise** [comment]
@yorzi @justin808 yeah I think Justin has some specific things in mind so that it would be necessary to screen share with him to understand what he's doing, but especially if you aren't as familiar with NPM, I would take him up on his offer if you have the time I'm sure you would learn a lot!

**Comment by yorzi** [comment]
@robwise I've talked with @justin808 on this ticket, I am interested in learning related things. I have started to look things around, if you can help or give me advices when I encounter problems, that'd be super great.

**Comment by robwise** [comment]
@yorzi one of the nice-to-haves would be automatically detecting whether a given argument is a generator function versus a component so that the user doesn't have to worry about it. I think I figured out a way to tell them apart, although it's very ghetto and un-elegant.

http://codepen.io/robwise/pen/wMwzGo?editors=001

**Comment by justin808** [comment]
@rstudner This might have some issues for your old code and migration. Feel free to comment. I think we'll probably make it backwards compat in that we'll support the old API and present warning messages.

**Comment by justin808** [comment]
@yorzi I spoke with @alexfedoseev about a few things:

- [ ] We're going to **ONLY** expose ReactOnRails globally for visibility from execJS and the view helper. Requiring our npm package will install this globally, so no need for Webpack config.
- [ ] We can remove the global expose of React, ReactDom, and ReactDom/Server, as we'll make those internal to ReactOnRails.

So we're totally cleaning up our pollution of the global namespace to only include one symbol, **ReactOnRails**!

**Comment by justin808** [comment]
@alexfedoseev Please review: #148 

 `register` or `registerComponent`?

```js
ReactOnRails.registerComponent('HelloWorld', HelloWorld);
ReactOnRails.registerComponent('HelloWorldWithLogAndThrow', HelloWorldWithLogAndThrow);
```

or 

```js
ReactOnRails.register('HelloWorld', HelloWorld);
ReactOnRails.register('HelloWorldWithLogAndThrow', HelloWorldWithLogAndThrow);
```

**Comment by robwise** [comment]
Is this good now @justin808 ?

**Comment by justin808** [comment]
Closed with v2!
