### ISSUE TITLE
re render component when props has been updated?

### ISSUE THREAD

**Issue by marcosguti** [shakacode/react_on_rails#1282]
i'm using react_on_rails in symfony app, then in html.twig i've added this code:

`        <div id="network-activity-charts">
            {{ react_component('NetworkActivityCharts',{'props': accounts | json_encode, 'rendering':'client_side'}) }}
        </div>`

how this can reload when props has updated?

**Comment by justin808** [comment]
@marcosguti I'd just use an API call from the react component to get new props and to re-render. You could have the component use a timer to poll for new props.
