### ISSUE TITLE
Include TypeScript types in NPM package

### ISSUE THREAD

**Issue by ndbroadbent** [shakacode/react_on_rails#1283]
Hello,

I'm migrating from Flow to TypeScript, and I thought it would also be a good time to upgrade from react_on_rails 8.x to the latest version.

I noticed that there has been some issues and PRs related to TypeScript:

* https://github.com/shakacode/react_on_rails/issues/635
* https://github.com/shakacode/react_on_rails/pull/1250
* https://github.com/shakacode/react_on_rails/pull/1236

I am getting this error from TypeScript:

```
Could not find a declaration file for module 'react-on-rails'. '.../node_modules/react-on-rails/node_package/lib/ReactOnRails.js' implicitly has an 'any' type.
  Try `npm install @types/react-on-rails` if it exists or add a new declaration (.d.ts) file containing `declare module 'react-on-rails';`ts(7016)
```

When I look at the files inside `react-on-rails/node_package/lib`, I can see that these have all been converted from TS to JS with Babel.

I'm still quite new to TypeScript so not sure if this would work, but would it be possible to include the original `.ts` files in the `src` directory? Or is it possible to generate a "declaration" file that I can use?

Thanks!

**Comment by justin808** [comment]
We definitely would like to have the types here: https://definitelytyped.org/

@Judahmeek, @ashgaliyev, @MUTOgen Any ideas on how easy this would be?

**Comment by Judahmeek** [comment]
@ndbroadbent can you try the judahmeek/typescript-support branch & let me know if it resolves your issue?

**Comment by justin808** [comment]
Hi @ndbroadbent, this was done with v12. 

Here's a good example of using TS type checking:

https://github.com/shakacode/react_on_rails_tutorial_with_ssr_and_hmr_fast_refresh/commit/6acb4d3d41236f8b321601d98b6b7786c778f16e

```js
const HelloWorld = (props) => {
``` 

has to change to:
```js
import { useState, FunctionComponent } from 'react';

const HelloWorld: FunctionComponent<Props> = (props: Props) => {
```
