### ISSUE TITLE
anyone see anything wrong with using this useRailsContext custom hook?

### ISSUE THREAD

**Issue by nratter** [shakacode/react_on_rails#1285]
Anyone see anything wrong with using the following to get the Rails Context via hooks for client rendered / non-single page apps?

```
import { useMemo } from 'react';

export const useRailsContextHtmlTag: any | undefined = () => {
  return useMemo(() => {
    try {
      return JSON.parse(
        document.getElementById('js-react-on-rails-context').innerHTML
      );
    } catch {}
  }, []);
};
```

**Comment by justin808** [comment]
@nratter We might need the next release if this is at the top level. Very soon! 

I release a beta version today.

**Comment by justin808** [comment]
@nratter This is an interesting idea! **BUT, this doesn't work for server-side rendering**.

I could add this to the base JS library, or provide it as a doc example...

The new release requires this usage at the top level:

```js
import React from 'react';

export default (props, railsContext) => {
  // Note wrap in a function to make this a React function component
  return () => (
    <div>
      Your locale is {railsContext.i18nLocale}.<br/>
      Hello, {props.name}!
    </div>
  );
};
```

**Comment by nratter** [comment]
@justin808 sounds good!

**Comment by justin808** [comment]
@nratter Please try out!

Gem version: 12.0.0.pre.beta.0 and npm version 12.0.0-beta.0 released!

https://www.npmjs.com/package/react-on-rails
https://rubygems.org/gems/react_on_rails
