### ISSUE TITLE
react_on_rails not refreshing web server

### ISSUE THREAD

**Issue by steveeq1** [shakacode/react_on_rails#1286]
webpack is watching/re-compiling react components, but not "refreshing" the web server after compilation. I followed the instructions in the below link and also set "hmr" in config/webpacker.yml to "true": https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/hot-reloading-rails-development-asset-pipeline.md

What are some common things to check to see what's going? Am I missing something out of the instructions?

**Comment by justin808** [comment]
Yes, we need to update the docs. I recommend using the https://github.com/pmmmwh/react-refresh-webpack-plugin.

If you sign up for [React on Rails Pro](https://www.shakacode.com/react-on-rails-pro/), then  we'll give you direct help to set this up on your project.

**Comment by justin808** [comment]
@steveeq1 I think I may have removed or moved the doc link you're referring to.

**Comment by justin808** [comment]
@steveeq1 please see the setup in the /spec/dummy folder for how to setup up HMR.

I'm hacking on this over the coming week: https://github.com/shakacode/test-react-on-rails-v12
