### ISSUE TITLE
Called register for component that is already registered BallanceSummary after implementing HMR

### ISSUE THREAD

**Issue by AlexKund** [shakacode/react_on_rails#1307]
Hi Justin,
Recently Ive added HMR to our project. For styles it works as expected but after I added HMR for javascript in the browser console I got follow warnings:
ComponentRegistry.js:27 Called register for component that is already registered BallanceSummary
ComponentRegistry.js:27 Called register for component that is already registered DatePickerRange
....
for every registered component
Is there a way to avoid that situations or Am I doing something wrong?

My current configuration is:
1. in config/webpacker.yml
```javascript
development:
  <<: *default
  compile: true
  dev_server:

    host: localhost
    port: 3035
    public: localhost:3035
    hmr: true
    inline: true

```
2. in app/javascript/packs/member.js
```javascript
ReactOnRails.registerStore({ appStore });

ReactOnRails.register({
    BallanceSummary, DatePickerRange, Dpicker, FileUpload, PhoneNumber, SignIn, TimeOut, SignUp, ConsumerPrepaidCards, Alert
});

if (module.hot) {
    module.hot.accept();
}
```
<img width="1680" alt="react_on_rails_hmr" src="https://user-images.githubusercontent.com/5707244/87152659-c8672880-c2be-11ea-872f-21d1d1900720.png">

**Comment by justin808** [comment]
Try switching to https://github.com/pmmmwh/react-refresh-webpack-plugin.

That seems to work much better. 

Did you upgrade to v12?

**Comment by AlexKund** [comment]
Tnx for the advice, Justin,
react-refresh-webpack-plugin works very well as you told, even for state! :).
Here is my configuration:
in package.json
```javascript
  "devDependencies": {
    "@pmmmwh/react-refresh-webpack-plugin": "^0.3.3",
    "react-refresh": "^0.8.3",
```
in config/webpack/environment.js
```javascript
const {environment} = require('@rails/webpacker');
const webpack = require('webpack');
const ReactRefreshWebpackPlugin = require('@pmmmwh/react-refresh-webpack-plugin');
const isDevelopment = process.env.NODE_ENV !== 'production';


environment.mode = isDevelopment ? 'development' : 'production';

//plugins
environment.plugins.append(
    'ReactRefreshWebpackPlugin',
    isDevelopment && new ReactRefreshWebpackPlugin()
);


//loaders
const babelLoader = environment.loaders.get('babel');
babelLoader.use[0].options.plugins = [].filter(Boolean);
isDevelopment &&  babelLoader.use[0].options.plugins.push(require.resolve('react-refresh/babel'));
```

It all works good, but there is one final touch - annoing error message - GET http://localhost:3000/sockjs-node/info?t=1594742262115 404 (Not Found):
<img width="1680" alt="Untitled 4" src="https://user-images.githubusercontent.com/5707244/87449703-3042a980-c606-11ea-9a81-1ab7a0e46b7f.png">

Its not a problem but do you have any idea about that error

**Comment by AlexKund** [comment]
I fix it adding    overlay: false to plugin config
```javascript
//plugins
environment.plugins.append(
    'ReactRefreshWebpackPlugin',
    isDevelopment && new ReactRefreshWebpackPlugin({
        overlay: false
    })
);
```

Tnx once again Justin :),
You could close that discussion

**Comment by justin808** [comment]
@AlexKund Any chance that you can help me with a short readme doc in the `/docs/basics` directory that explains this setup?

**Comment by AlexKund** [comment]
Ofcs :)

**Comment by justin808** [comment]
@AlexKund Looking forward to it!

**Comment by justin808** [comment]
See #1311. Thanks @AlexKund!

**Comment by justin808** [comment]
BTW, the updated doc mentions the setting of the 

```js
 new ReactRefreshWebpackPlugin({
   sockPort: 3035
 })
```

Rather than `overlay: false`.

Right @AlexKund ?

**Comment by AlexKund** [comment]
@justin808 yes thats right. Its better then just errors to be suppressed
