### ISSUE TITLE
Unnecessary gem if not server rendering

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#133]
- [x] [Unnecessary gem if not server rendering](https://github.com/shakacode/react_on_rails-generator-results/pull/123/files#diff-8b7db4d5cc4b8f6dc8feb7030baa2478R51). Let's not add the rubyracer to the Gemfile if not server rendering.
- [x] [generator_function should be true for redux](https://github.com/shakacode/react_on_rails-generator-results/pull/123/files#diff-bd7f583b97e102c11bc35a2c837b9fbeR4) 
- [x] [don't specify trace option](https://github.com/shakacode/react_on_rails-generator-results/pull/123/files#diff-bd7f583b97e102c11bc35a2c837b9fbeR6)

**Comment by justin808** [comment]
@yorzi @robwise These should go in the next release. @yorzi want to try to fix some of these?

**Comment by yorzi** [comment]
@justin808 OK, let me work on this.

**Comment by justin808** [comment]
Thanks @yorzi!

**Comment by robwise** [comment]
@yorzi has now fixed the first two in https://github.com/shakacode/react_on_rails/pull/135
