### ISSUE TITLE
We're not generating the right server react config and need to display helpful warning message if ReactDom not included in the bundle.

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#134]
The bug is that you cannot simply include this to expose a global. You need to make these entry points.

```
  module: {
    loaders: [
      {test: /\.jsx?$/, loader: 'babel-loader', exclude: /node_modules/},

      // React is necessary for the client rendering:
      {test: require.resolve('react'), loader: 'expose?React'},
      {test: require.resolve('react-dom/server'), loader: 'expose?ReactDOMServer'},
    ],
```

### This is correct
See: https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/webpack.server.rails.config.js#L12

```
  entry: ['./app/startup/serverGlobals', 'react-dom/server', 'react'],
```

### bug
It's a bug that it's not here: https://github.com/shakacode/react_on_rails-generator-results/blob/basic-server-rendering-1_1_1/client/webpack.server.rails.config.js#L13

We're only putting this:
```
  entry: ['./app/bundles/HelloWorld/startup/serverGlobals'],
```

### Place to fix react_on_rails.js to add helpful suggestion

In this method of [react_on_rails.js](https://github.com/shakacode/react_on_rails/blob/master/app%2Fassets%2Fjavascripts%2Freact_on_rails.js#L209), we should put in a warning if `React.version` > 0.13 and `ReactDOMServer` is not exposed. The same applies for `ReactDOM`. 

```
  function provideClientReact() {
    if (typeof ReactDOM === 'undefined') {
      return React;
    }

    return ReactDOM;
  }

  function provideServerReact() {
    if (typeof ReactDOMServer === 'undefined') {
      return React;
    }

    return ReactDOMServer;
  }
```

**Comment by justin808** [comment]
@jbhatab Can you coordinate a fix for this? @yorzi might be able to help.

**Comment by yorzi** [comment]
@justin808 @jbhatab how to check React version in `webpack.server.rails.config.js` I want to do something like [this](https://github.com/yorzi/react_on_rails/blob/fix-server-react-config-when-on-react-0-dot-13/lib/generators/react_on_rails/templates/base/server_rendering/client/webpack.server.rails.config.js#L9) . and I also did [this](https://github.com/yorzi/react_on_rails/blob/fix-server-react-config-when-on-react-0-dot-13/app/assets/javascripts/react_on_rails.js#L201-L221) to add warning. Are these the right updates for this issue?

**Comment by justin808** [comment]
Something like `React.version`.

**Comment by justin808** [comment]
@yorzi Nice changes. We might want a file in the docs folder called `webpack.md`. And we can have a header `Entry Points and Globally Exposing Objects`. Then we can put that URL in the code. I love warnings that point me to a help page.
