### ISSUE TITLE
Support Alpine

### ISSUE THREAD

**Issue by EnziinSystem** [shakacode/react_on_rails#1342]
Hi,

I dockerized my rails app to image use Alpine.

'**react_on_rails**' gem require '**mini_racer**' and mini_racer require libv8.

But libv8 can not build with native extensions on Alpine

Finally, I can not build Gemfile with react_on_rails.

Thank you for any idea.

**Comment by justin808** [comment]
Hi @EnziinSystem, why do you think mini_racer is a requirement?

I think only ExecJS is: https://github.com/shakacode/react_on_rails/blob/master/react_on_rails.gemspec.

If you use [React on Rails Pro](https://www.shakacode.com/react-on-rails-pro/), then you'll use Node.js for rendering. Can you run Node.js on Alpine?
