### ISSUE TITLE
Yield React component to old Rails views

### ISSUE THREAD

**Issue by threepete** [shakacode/react_on_rails#1343]
I'm looking to use this gem to only render a layout for my Rails app and would like to yield the main content to my old Rails views. Is there a way to achieve this or does every view in my app have to be converted into a component?

**Comment by justin808** [comment]
Take a look at https://hichee.com/inbox (you need to create an account -- that's my site!)

That screen's body is basic Rails and the header is React. On other pages, we render a single component that includes the same header component.

If you sign up for [React on Rails. Pro](https://www.shakacode.com/react-on-rails-pro/), we can get you setup with all the code examples you need to do what you want.

**Comment by threepete** [comment]
> Take a look at https://hichee.com/inbox (you need to create an account -- that's my site!)
> 
> That screen's body is basic Rails and the header is React. On other pages, we render a single component that includes the same header component.
> 
> If you sign up for [React on Rails. Pro](https://www.shakacode.com/react-on-rails-pro/), we can get you setup with all the code examples you need to do what you want.

Ah, unfortunate

**Comment by justin808** [comment]
@threepete What's unfortunate? The task is relatively straightforward and supported by React on Rails. Do you expect dedicated time from me to create examples for you? 

I have to prioritize requests from sponsors: https://github.com/sponsors/shakacode.

**Comment by threepete** [comment]
@justin808 I didn't mean any offense. Apologies.
