### ISSUE TITLE
Re-using ReactOnRails JS in different packs

### ISSUE THREAD

**Issue by Overload119** [shakacode/react_on_rails#1347]
I have 2 sets of React components in a single app.

The first set are used for the main user-facing app.
The app also has an admin section.

I don't want to include all off the admin-only assets inside of the same `components.js` since that will load it for the user-facing app even though a majority of users won't need these component JS files (they will never be rendered).

I tried creating a new pack so I have:

```
application.js
admin_application.js
```

```
import ReactOnRails from 'react-on-rails';

import CodeEditor from './components/CodeEditor';

ReactOnRails.register({
  CodeEditor,
});
```

This loads 2 instances of `ReactOnRails` and so calling `register()` will wipe out the loaded components of the other. 
How can I prevent this?

**Comment by justin808** [comment]
@Overload119 How do you know that you have have 2 instances of ReactOnRails? They get set on window, so I suspect that is not happening.

**Comment by Overload119** [comment]
`import ReactOnRails from 'react-on-rails';` 

This invokes ReactOnRails twice.

When `ReactOnRails.register` is called, it seems that it initializes all the components. If this is called again, then it will wipe out the previous ones.

**Comment by justin808** [comment]
@Overload119 did you determine the cause of this issue? Maybe it's related to #1350 and Turbolinks? 

> This invokes ReactOnRails twice.

This shouldn't be possible if you've setup your bundle splitting properly.

Can you create a simple example on Github to reproduce this case?

**Comment by mattclough1** [comment]
@justin808 I'm having this same issue on a fresh Rails app. Here's the repo:
https://github.com/mattclough1/react-on-rails-demo

**Comment by justin808** [comment]
Hi @mattclough1, any suggestion for a fix? I don't see this widely reported. 

Why are you doing this:

https://github.com/mattclough1/react-on-rails-demo/blob/main/app/javascript/packs/hello_react.jsx#L21-L26
