### ISSUE TITLE
Turbo Drive compatibility?

### ISSUE THREAD

**Issue by pgruener** [shakacode/react_on_rails#1360]
Hello,
is it planned to establish support for Turbo Drive instead of Turbolinks in the near future?
I quickly tried, to just reference window.Turbolinks = Turbo as a quick try, but the event names
changed and also react_on_rails is considering that as Turbolinks in Version 2 as there is no
*controller* property in Turbo anymore.
Thanks for your response

**Comment by justin808** [comment]
@pgruener would a PR be very simple?

**Comment by pgruener** [comment]
@justin808 It seems like there shouldn't be a too big challenge, but I'm still not into it in depth enough.
But if I'd know, that you would like that, you're not already working on it, and might pull it, I'd consider to make a suggestion PR in the upcoming weeks.

**Comment by justin808** [comment]
@pgruener I'd love a PR. Please keep me posted!

**Comment by justin808** [comment]
@pgruener Please consider joining our community slack channel [with this invite](https://join.slack.com/t/reactrails/shared_invite/enQtNjY3NTczMjczNzYxLTlmYjdiZmY3MTVlMzU2YWE0OWM0MzNiZDI0MzdkZGFiZTFkYTFkOGVjODBmOWEyYWQ3MzA2NGE1YWJjNmVlMGE).

**Comment by pgruener** [comment]
@justin808 You could have a look at https://github.com/shakacode/react_on_rails/pull/1374
