### ISSUE TITLE
Reduce rails dependency

### ISSUE THREAD

**Issue by supremebeing7** [shakacode/react_on_rails#1366]
It would be nice if this gem could depend only on the gems from rails it needs, rather than the full `rails` gem. I'm not sure what specific parts are needed without digging, but I'd guess something like `railties`, `actionview`, `sprockets-rails`?

The whole hoopla with [mimemagic versions getting yanked](https://github.com/mimemagicrb/mimemagic/issues/98) and rails `activestorage` gem depending on it really shined a light on this type of thing.

I'm happy to help in some way, even posting a PR with some changes, though I don't have a ton of time to dig through the internals of this gem.

**Comment by justin808** [comment]
@supremebeing7 Sure...PR would be great!
