### ISSUE TITLE
Generator Warning Messages

### ISSUE THREAD

**Issue by robwise** [shakacode/react_on_rails#138]
Currently the generator warning messages happen at the beginning of the output when running the generator and then quickly get pushed off screen by the noise the generator creates from making all of the files and such. We should probably move them to the end or something.

**Comment by aaronvb** [comment]
@robwise I did some poking around last night and was able to get the InstallGenerator warning messages to output at the end by adding an error attribute to the InstallGenerator class. However, I'm still thinking of a way to get it to work with the rest of the generators.

The problem I see with the Generator classes is that they output top to bottom, and in the order we invoke them in the InstallGenerator. By using the same method above in each Generator, individual errors will output after each invoke, which is still not at the end.

Do you have any ideas?

**Comment by robwise** [comment]
@aaronvb Yeah I was thinking about this problem too, certainly a monkey-patch option would be to make some sort of class in the `task_helper.rb` file and just add any error messages to an array that the `InstallGenerator` prints out at the very end.

**Comment by justin808** [comment]
How about if we keep some variable to to keep an array of string messages to print at the end?

**Comment by aaronvb** [comment]
@justin808 @robwise That's what I was thinking also. Will post an update soon.

**Comment by justin808** [comment]
@aaronvb Any update on this issue? Thanks so much for your help!

**Comment by justin808** [comment]
@aaronvb @robwise Is this ready to go?

**Comment by aaronvb** [comment]
@justin808 @robwise I'm making the changes rob suggested right now. Will be pushing it soon.

**Comment by aaronvb** [comment]
Let's close this issue.

**Comment by justin808** [comment]
@aaronvb Thanks for your help with this one!
