### ISSUE TITLE
unable to use React suspense with react_on_rails gem

### ISSUE THREAD

**Issue by ziploker** [shakacode/react_on_rails#1383]
I'm trying to use the experimental version of react to use suspense for data fetching etc…

i installed the experimental version of react via npm (had to use --force).
_(not sure if the dependency issue i had was react_on_rails related)_

Also, part of the [install process](https://reactjs.org/docs/concurrent-mode-suspense.html) says to change this:

```
ReactDOM.render(
<React.StrictMode>

</React.StrictMode>,
document.getElementById(“root”)
);

```
to this:

```
ReactDOM.unstable_createRoot(document.getElementById(“root”)).render(
<React.StrictMode>

</React.StrictMode>
);
```

However, with react on rails it works different.

How can i enable react experimental mode to be able to use React.suspense

Thanks for any help…

**Comment by justin808** [comment]
Once this feature is non-experimental, I plan to support this.

@ziploker and others, PRs welcome!
