### ISSUE TITLE
Client side hydration called before all the components are registered

### ISSUE THREAD

**Issue by samtgarson** [shakacode/react_on_rails#1392]
We have multiple client-side bundles, each of which registers its own components, e.g.:
```ts
// atoms-bundle.ts
ReactOnRails.register({
  Button: forRails(Button) as FC,
})

// comments-bundle.ts
ReactOnRails.register({
  CommentDrawer: forRails(CommentDrawer) as FC,
})
```

These are loaded all in one call (we plan to use `content_for` to counteract the issue of calling `javascript_pack_tag` multiple times, but it's not done yet):
```erb
<%# layouts/application.html.erb %>
<%= javascript_pack_tag 'application', 'comments-bundle', 'atoms-bundle', 'data-turbolinks-track': 'reload' %>
```
In reality there are 6 bundles.

We get the following error sporadically—not every time, and the order in which we put the different bundles in the pack tag seems to influence which components get registered and which don't:
`Error: ReactOnRails encountered an error while rendering component: X. Original message: Could not find component registered with name X.`

Some investigation shows that in `renderInit`, you check for `document.readyState` which is currently `interactive`, which triggers the call to `reactOnRailsPageLoaded` which in turn hydrates all the components—however using breakpoints, I can see that this happens before some of the bundles have had a chance to register their components causing the error.

This occurs a lot in the local environment, but has recently started occurring frequently in production too.

**This is a critical issue** as the components on the page do not function. Further, we can see that a manual call to `ReactOnRails.reactOnRailsPageLoaded()` after everything has finished loading works without an error, proving this is just a timing issue.

Does this look familiar to you, are we doing something wrong in the way we register our components?

Thanks!

**Comment by justin808** [comment]
@samtgarson can you try to debug this further? or suggest a PR?

There's something specific about your project, or else I'd get lots of reports of this issue surely.

**Comment by justin808** [comment]
@samtgarson any update?

**Comment by samtgarson** [comment]
Hey @justin808 apologies, forgot to get back on this one. We added `defer: false` and it seems to have worked.

Not sure what this means for the library though?

**Comment by justin808** [comment]
I think the issue is that you have the script tag in the head and if you placed the script tag at the bottom of the page with defer, you'd have better performance.

https://developers.google.com/web/fundamentals/performance/critical-rendering-path/adding-interactivity-with-javascript#parser_blocking_versus_asynchronous_javascript

My guess is that you have `javascript_pack_tag` more than once on your final layout.

**Comment by samtgarson** [comment]
We definitely do not have multiple pack tags (this is something that I opened a separate pull request about documenting), but we do have the pack tag in the Head of the document—we will move it.
