### ISSUE TITLE
running generator overwrites application.js incorrectly.

### ISSUE THREAD

**Issue by yorzi** [shakacode/react_on_rails#140]
In my existing application.js, I have something like `//= require_tree ./lh/utility/`, when running generator, it seems all `//= require_tree .` will be removed and messy up all my existing required js, which should not be the original purpose.

**Comment by justin808** [comment]
@yorzi I totally agree! thanks for finding this. We should

1. ONLY comment out, not remove any lines that we need to remove.
2. not touch require_tree for below the top level, as your example suggests.

**Comment by yorzi** [comment]
@justin808 I will fix this later.
