### ISSUE TITLE
Cannot install with rails 3.2, ruby 1.9.3

### ISSUE THREAD

**Issue by raquelhortab** [shakacode/react_on_rails#1406]
Hi, I am trying to install version 11, which is suposed to work with rails 3.x. I am encontering a problem with some dependencies. It seems that react_on_rails depends on rainbow 3.0.0, which depends on ruby 2.1.0. Is there any workaround? I cannot upgrade ruby for now and I'd like to be able to use react.

**Comment by justin808** [comment]
@raquelhortab  you can jump on this [Slack](https://reactrails.slack.com/join/shared_invite/enQtNjY3NTczMjczNzYxLTlmYjdiZmY3MTVlMzU2YWE0OWM0MzNiZDI0MzdkZGFiZTFkYTFkOGVjODBmOWEyYWQ3MzA2NGE1YWJjNmVlMGE) and message me.
