### ISSUE TITLE
Prepping for React 18's render process

### ISSUE THREAD

**Issue by kylemellander** [shakacode/react_on_rails#1408]
In React 18, the render process is triggered differently.  For more reference, see https://github.com/reactwg/react-18/discussions/5.

I have not dug into the internals, but I do know that there are also updates how to do SSR that could help with performance for React 18.  More information is here: https://github.com/reactwg/react-18/discussions/22

I'm going to dig into researching this more and potentially opening a PR.

I think this might possibly be related to https://github.com/shakacode/react_on_rails/issues/1383, but I'm not positive.

**Comment by justin808** [comment]
@kylemellander I definitely want to support this. If you've got any suggestions or a PR, very much appreciated!

**Comment by kylemellander** [comment]
@justin808 I've been exploring the way that the dummy apps are generated for the test suite, but have hit a wall with determining how to test against multiple versions of React so that we can make sure that we have forward and backward compatibility.

Part of the issue here is that I'm struggling to see a few things about the construction of the test suite since it is very dynamic.  My thinking is that if we have multiple react versions that we can set in the package.json, and we can run across multiple versions, then it will ensure that the React versions are compatible.  The package.json, though, seems to be generated in an unconventional way, and I am struggling to determine where the react versions are being pulled from (my local version sets them at React 17.0.2, but I don't see that version used anywhere else in the library).

I'd love to put our brains together on how to make this happen, but for now, I'm going to focus on getting it to work manually for React 18 and have the tests catch React < 18.

**Comment by kylemellander** [comment]
Also, looking at the updates to use `ReactDOMServer.renderToPipeableStream`, it seems like maybe this is something that you would be integrating into your pro version since that version contains the nodeJS connection

**Comment by justin808** [comment]
Released in 12.5.0.
