### ISSUE TITLE
Upcoming changes for rails/webpacker v6, Rails 7, and React 18

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#1410]
- [x] Upgrade to rails/webpacker v6 final
- [ ] Integrate https://github.com/shakacode/react-on-webpacker https://www.npmjs.com/package/react-on-webpacker into spec/dummy
- [x] Upgrade of spec/dummy examples to Rails 7
- [x] Upgrade spec/dummy to React 18 (#1463)

**Comment by Judahmeek** [comment]
@justin808 I closed this because we're using Notion for task management.

**Comment by alexeyr-ci1** [comment]
@justin808 I think the first task is done, just with Shakapacker instead?

**Comment by justin808** [comment]
For 
> integrate https://www.npmjs.com/package/webpacker-react into spec/dummy

Maybe we can consider something for Shakapacker v7?

**Comment by alexeyr-ci1** [comment]
> Maybe we can consider something for Shakapacker v7?

If it's just `spec/dummy` changes, I definitely don't think we need to wait until that.

**Comment by alexeyr-ci1** [comment]
Oh, sorry, I misunderstood. We can look into it.

**Comment by justin808** [comment]
@alexeyr-ci1, sorry, wrong repo. I updated the comments above.

**Comment by justin808** [comment]
All fixed.
