### ISSUE TITLE
React 18 Warning: You are importing hydrateRoot from "react-dom" [...] You should instead import it from "react-dom/client"

### ISSUE THREAD

**Issue by gastonmorixe** [shakacode/react_on_rails#1441]
```
Warning: You are importing hydrateRoot from "react-dom" which is not supported.
You should instead import it from "react-dom/client".
```

https://github.com/shakacode/react_on_rails/blob/0e96cf8a4c6779daf2c671974e93598134162587/node_package/src/reactHydrate.ts#L1

**Comment by justin808** [comment]
Hi @gastonmorixe, Ari Summer is working on this as well. 

We can chat at the [Slack Discusssion](https://join.slack.com/t/reactrails/shared_invite/enQtNjY3NTczMjczNzYxLTlmYjdiZmY3MTVlMzU2YWE0OWM0MzNiZDI0MzdkZGFiZTFkYTFkOGVjODBmOWEyYWQ3MzA2NGE1YWJjNmVlMGE).

**Comment by summera** [comment]
I took a stab at fixing this in https://github.com/shakacode/react_on_rails/pull/1448

**Comment by smeijer** [comment]
Is there a status update for this?

**Comment by justin808** [comment]
I'll soon be trying to do some upgrades.

**Comment by justin808** [comment]
@gastonmorixe @summera @smeijer Completed! I'll ship an updated version soon!

**Comment by smeijer** [comment]
Thanks! Appreciate the ping.
