### ISSUE TITLE
`npm test` breaks my existing project's pass on CircleCI.

### ISSUE THREAD

**Issue by yorzi** [shakacode/react_on_rails#145]
After I initialize my client folder via generator, and I configure circle.yml for correct node version (v5.0.0). Then my CircleCI always gets failed. I think it's because CircleCI will run `npm test` if there is a test script configured in package.json (we do have that by default). 

I also tried to run `npm test` locally, it throws errors as below:

```
0 info it worked if it ends with ok
1 verbose cli [ '/Users/andy/.nvm/versions/node/v5.0.0/bin/node',
1 verbose cli   '/Users/andy/.nvm/versions/node/v5.0.0/bin/npm',
1 verbose cli   'run',
1 verbose cli   'eslint' ]
2 info using npm@3.3.6
3 info using node@v5.0.0
4 verbose stack Error: missing script: eslint
4 verbose stack     at run (/Users/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/run-script.js:148:19)
4 verbose stack     at /Users/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/lib/run-script.js:58:5
4 verbose stack     at /Users/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:345:5
4 verbose stack     at checkBinReferences_ (/Users/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:309:45)
4 verbose stack     at final (/Users/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:343:3)
4 verbose stack     at then (/Users/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:113:5)
4 verbose stack     at ReadFileContext.<anonymous> (/Users/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/read-package-json/read-json.js:297:29)
4 verbose stack     at ReadFileContext.callback (/Users/andy/.nvm/versions/node/v5.0.0/lib/node_modules/npm/node_modules/graceful-fs/graceful-fs.js:76:16)
4 verbose stack     at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:324:13)
5 verbose cwd /Users/andy/workspace/livinghealthy.projects/webapp
6 error Darwin 15.0.0
7 error argv "/Users/andy/.nvm/versions/node/v5.0.0/bin/node" "/Users/andy/.nvm/versions/node/v5.0.0/bin/npm" "run" "eslint"
8 error node v5.0.0
9 error npm  v3.3.6
10 error missing script: eslint
11 error If you need help, you may report this error at:
11 error     <https://github.com/npm/npm/issues>
12 verbose exit [ 1, true ]

```

Anyone can help to explain why this happened and how to resolve the problem? Thanks!

**Comment by justin808** [comment]
@yorzi can you please compare your setup to https://github.com/shakacode/react-webpack-rails-tutorial/ and report back? we have tests there. We have not yet configured the generator to create any tests.

**Comment by justin808** [comment]
@yorzi Maybe this issue can be an enhancement that we address when we add some simple tests, like this:

https://github.com/shakacode/react-webpack-rails-tutorial/tree/master/client/test

If you want to add that generator option (default on), that would be great!

**Comment by yorzi** [comment]
@justin808 to avoid possible generator/testing conflicts, I will do this once we merge `bootstrap option` into master. Maybe it's better to add simple js-test scaffold by default by generator, and we allow to use `--skip-js-test` as an option to ignore js-test. sounds good? cc: @robwise

**Comment by justin808** [comment]
I agree...Let's get bootstrap part done first. Maybe today.

**Comment by justin808** [comment]
@yorzi @robwise Can we close this issue?

**Comment by robwise** [comment]
I say just automatically return a 0 exit code and then put a comment next to it saying that no tests have been implemented yet if this really is an issue.

**Comment by yorzi** [comment]
This is not a problem anymore.
