### ISSUE TITLE
CSS Modules with server rendering

### ISSUE THREAD

**Issue by jerelmiller** [shakacode/react_on_rails#146]
I'm trying to implement server rendering with css modules. All I end up with is an ``Uncaught ReferenceError: window is not defined`` error.

I'm not sure if this is even possible yet. I haven't been able to find a great solution. Any examples/ideas/solutions of how this might work?

**Comment by justin808** [comment]
Woo hoo! @jerelmiller you're a step ahead of @alexfedoseev and me! We're just about to put in css modules with reloading within Rails, and it looks like we need to fix this one as well! If you like, I'll invite you to our Slack room! 

BTW, where is the reference to window coming from?

**Comment by jerelmiller** [comment]
@justin808 that would be great! I have a slightly different setup than what the generator is using. I'm using ``webpack-hot-middleware`` in my node server to serve the assets, but most everything else is similar to the setup. Anyways, here is the important part of the stack trace (apologies for the length).

In rails view (``pages/index.html`` in the stack trace below)
```haml
= render_component 'App'
```

```ruby
ERROR in SERVER PRERENDERING
Encountered error: "ReferenceError: window is not defined"
when prerendering App with props: {}
js_code was:
(function() {
  var props = {};
  return ReactOnRails.serverRenderReactComponent({
    componentName: 'App',
    domId: 'App-react-component-0',
    props: props,
    trace: true,
    generatorFunction: true,
    location: '/'
  });
})()


(execjs):20063:31
(execjs):20058:48
module.exports ((execjs):20080:69)
Object.<anonymous> ((execjs):19952:39)
__webpack_require__ ((execjs):31:30)
Object.<anonymous> ((execjs):19918:2)
__webpack_require__ ((execjs):31:30)
Object.<anonymous> ((execjs):19887:18)
__webpack_require__ ((execjs):31:30)
Object.<anonymous> ((execjs):19836:28)
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:15:in `rescue in block in initialize'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:12:in `block in initialize'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:75:in `block in lock'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:73:in `call'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:73:in `Locker'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:73:in `lock'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/execjs-2.6.0/lib/execjs/ruby_racer_runtime.rb:9:in `initialize'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/execjs-2.6.0/lib/execjs/runtime.rb:44:in `new'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/execjs-2.6.0/lib/execjs/runtime.rb:44:in `compile'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/execjs-2.6.0/lib/execjs/module.rb:27:in `compile'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/react_on_rails-1.1.1/lib/react_on_rails/server_rendering_pool.rb:81:in `create_js_context'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/react_on_rails-1.1.1/lib/react_on_rails/server_rendering_pool.rb:11:in `block in reset_pool'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:169:in `call'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:169:in `try_create'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:81:in `block (2 levels) in pop'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:77:in `loop'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:77:in `block in pop'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:76:in `synchronize'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:76:in `pop'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool.rb:89:in `checkout'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool.rb:61:in `block in with'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/react_on_rails-1.1.1/lib/react_on_rails/server_rendering_pool.rb:65:in `eval_js'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/react_on_rails-1.1.1/lib/react_on_rails/server_rendering_pool.rb:33:in `server_render_js_with_console_logging'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/react_on_rails-1.1.1/app/helpers/react_on_rails_helper.rb:180:in `server_rendered_react_component_html'
/Users/jerelmiller/.rvm/gems/ruby-2.2.3/gems/react_on_rails-1.1.1/app/helpers/react_on_rails_helper.rb:73:in `react_component'
/app/views/pages/index.html.haml:1:in `_app_views_pages_index_html_haml__1134995885750901061_70282238502660'
```

**Comment by justin808** [comment]
@jerelmiller I'm guessing that the server webpack needs to be different than client one. @alexfedoseev I be are about to hit this as well.

**Comment by jerelmiller** [comment]
@justin808 Ya it must be. I am using the `extract-text-webpack-plugin` in my client config which is the only difference from what you see above. I'll keep trying a few things. A lot of this server rendering stuff is new to me so its making my head spin a little bit. 

Hopefully you can make better progress than I can! I didn't realize it would be as tough as it has been. Its not quite as straightforward as I was hoping.

**Comment by jerelmiller** [comment]
@justin808 also wanted to say thank you for all the hard work you guys have put into this. This takes a lot of pain out of setup with the rails world, especially when it comes to server rendering. Great to see this project thriving! Excited to see where it goes!

**Comment by alexfedoseev** [comment]
@jerelmiller @justin808 

Actually I already hit it on node server. The key thing is this: you need to provide different loaders for the client and the server.

```js
// client
{ test: /\.css$/, loader: 'style!css?modules ... ' }

// server
{ test: /\.css$/, loader: 'style!css/locals?modules ... ' }
```

This way webpack won't be importing anything from css file except JS object with classNames.

But I haven't tried it with this gem in Rails environment.

**Comment by jerelmiller** [comment]
@alexfedoseev no luck with that either. It looked promising, but I'm still getting that `ReferenceError: window is not defined` error.

**Comment by alexfedoseev** [comment]
@jerelmiller I'll take a look at it, hope this weekend.

**Comment by jerelmiller** [comment]
@alexfedoseev Sounds great. Hopefully you have better luck than I have

**Comment by jerelmiller** [comment]
@alexfedoseev @justin808 I talked to someone over on the React discord channel and gave me a suggestion that allowed me to get server rendering working properly with CSS modules. The issue was that I was using the `style` loader on the server config. Here is the server loader that I was able to get working

```javascript
{ test: /\.css$/, loader: 'css/locals?modules&localIdentName=[name]__[local]___[hash:base64:5]' }
```

**Comment by alexfedoseev** [comment]
Right, I missed it in this snippet. Here is my full working loaders config for node:

```js
{
  test   : cfg.cssLoaderTest,
  loaders: [
    `css/locals?${cfg.cssLoaderParams({ importLoaders: 0 })}`,
  ],
},
{
  test   : cfg.scssLoaderTest,
  loaders: [
    `css/locals?${cfg.cssLoaderParams({ importLoaders: 1 })}`,
    `sass?${cfg.sassLoaderParams}`,
  ],
},

// p.s. `cfg` contains shared stuff for all webpack configs
```

**Comment by jerelmiller** [comment]
Right on. Thank you so much!

**Comment by justin808** [comment]
We're going to update the generators for this for v2.0, coming soon!

**Comment by jerelmiller** [comment]
Awesome! Can't wait to see it! Thanks for the update.

**Comment by justin808** [comment]
@jerelmiller Once we get just a little further, we'd be so grateful for help with trying out a RC version, and possibly doc help, or really just about anything. @alexfedoseev and I are slammed with our client work plus our product work: http://www.shakacode.com/2015/09/17/who-is-shaka-code.html.

**Comment by justin808** [comment]
Closing for now. Re-open if there's anything pending here.

**Comment by morizyun** [comment]
I hit it & I can not solve the problem... Could you please show me the `webpack.config.js` for CSS Modules with server rendering.

**Comment by justin808** [comment]
@morizyun Try this: https://github.com/shakacode/react-webpack-rails-tutorial

**Comment by morizyun** [comment]
@justin808 Thank you a lot! I am going to see it.
