### ISSUE TITLE
Install script should create `./bin/dev`

### ISSUE THREAD

**Issue by jasonfb** [shakacode/react_on_rails#1482]
- [ ] For parity with JSBundling, the installer script should create a simple shell script at `./bin/dev` with this contents:

```
#!/usr/bin/env bash
if ! command -v foreman &> /dev/null
then
  echo "Installing foreman…"
  gem install foreman
fi
foreman start -f Procfile.dev-static
```
- [ ] remember shell script must be set to be executable (`chmod 0755 ./bin/dev`)

- [ ] use the post-install message to direct people to this option

TODO: @jasonfb says he will PR this.

**Comment by justin808** [comment]
@jasonfb I like the idea. Can you throw in a PR?

**Comment by ahangarha** [comment]
> @jasonfb I like the idea. Can you throw in a PR?

Keep me as backup

**Comment by justin808** [comment]
@ahangarha you can do this if you like. It's simple enough.
