### ISSUE TITLE
Please add support for pnpm

### ISSUE THREAD

**Issue by mattp0123** [shakacode/react_on_rails#1489]
**Is your feature request related to a problem? Please describe.**
When I run `bin/rails generate react_on_rails:install`, it says:
```shell=
ERROR: yarn is required. Please install it before continuing. https://yarnpkg.com/en/docs/install
ERROR: react_on_rails generator prerequisites not met!
```

**Describe the solution you'd like**
Please add support for pnpm, it's a very powerful modern front-end tool.

**Comment by justin808** [comment]
See https://github.com/shakacode/shakapacker/issues/195
