### ISSUE TITLE
Can't resolve 'react-dom/client' warning

### ISSUE THREAD

**Issue by pulkitkkr** [shakacode/react_on_rails#1505]
### Summary:
When using File system based automated registry feature, Rails Compile with warning: 

Stack Trace
```
13:08:14 client.1 | WARNING in ./node_modules/react-on-rails/node_package/lib/reactHydrateOrRender.js 19:25-52
13:08:14 client.1 | Module not found: Error: Can't resolve 'react-dom/client' in '/Users/pulkit-kakkar/Desktop/Github/crm/src/node_modules/react-on-rails/node_package/lib'
13:08:14 client.1 |  @ ./node_modules/react-on-rails/node_package/lib/ReactOnRails.js 34:45-78
13:08:14 client.1 |  @ ./client/app/packs/webpack-bundle.jsx 2:0-42 18:0-21
13:08:14 client.1 | 
```

## Environment

1. Ruby version: ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [x86_64-darwin21]
2. Rails version:
3. Webpacker version: `shakapacker: "6.5.5"`
4. React on Rails version: `13.2.0`

## Expected behavior

The Warning should not be there

## Small, reproducible repo
To Be added later

**Comment by risinglf** [comment]
Same here, any solution?

**Comment by thibaut-decherit** [comment]
Upgrading react and react-router-dom from 16.8.6 to 18.0 fixed it on my side.

**Comment by ahangarha** [comment]
> Upgrading `react` and `react-router-dom` from 16.8.6 to 18.0 fixed it on my side.

This should fix your issue. Since React 18, we need to import from `react-dom/client`.

Please share with us if your issue is resolved.

**Comment by ahangarha** [comment]
@alkesh26 I close the issue for now. If you see the issue persist, feel free to reopen it with some detail.
