### ISSUE TITLE
Refactor `lib/react_on_rails/helper.rb`

### ISSUE THREAD

**Issue by pulkitkkr** [shakacode/react_on_rails#1513]
**Is your feature request related to a problem? Please describe.**
Ruby does not support private members in modules. Presently, there are a lot of undocumented private methods in `lib/react_on_rails/helper.rb`. 

**Describe the solution you'd like**
The private methods should be refactored to separate class/modules. There are many private methods that serve the purpose of SSR, pack generation, etc. The refactor should take care of scope & context instead one bulky Utility like module/class

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by ahangarha** [comment]
@pulkitkkr 
Based on [Ruby docs](https://www.rubydoc.info/stdlib/core/Module:private) we can have private methods in modules.

But may I know what issue we are trying to resolve?

> The refactor should take care of scope & context instead one bulky Utility like module/class

From the above line, I think that is more related to breaking helper methods into separate files rather keeping them all in one big file.

**Comment by Judahmeek** [comment]
@ahangarha the purpose of making methods private is to decrease the chance of users using a method that we don't consider part of our public A.P.I.

Because changes to logic that doesn't create changes to the public A.P.I. are not considered breaking changes.
