### ISSUE TITLE
bin/dev: Please ensure `Procfile.dev` exist in your project!

### ISSUE THREAD

**Issue by TangMonk** [shakacode/react_on_rails#1526]
I have `cp Procfile.dev-static Procfile.dev`, but when run `./bin/dev` still error:

`
Please ensure `Procfile.dev` exist in your project!
`

However when I run `foreman start -f Procfile.dev` manauly it works

**Comment by ahangarha** [comment]
Thanks for reporting.

This issue is already fixed and will be available in the coming release.

**Comment by iantanwx** [comment]
Hello @ahangarha this issue is still occurring in `13.3`. Is there a workaround? Sorry, I'm not very familiar with the Rails ecosystem.

**Comment by ahangarha** [comment]
@iantanwx 
Have you updated the `./bin/dev` based on the latest changes?

If yes, please share
- What OS do you use?
- What error do you get?

---

@TangMonk Is your issue resolved?
