### ISSUE TITLE
Babel 6 support

### ISSUE THREAD

**Issue by mli-max** [shakacode/react_on_rails#153]
Hello  guys, I like your amazing gem. It's incredible better than react-rails

I have tried to use it for my test project. 
Do you plan to upgrade babel up to 6? I've tried manually and failed with presets.
`HelloWorldApp failed in compilation in
```
static props = {}
```
I added `react`, `es2015` and even `stage-0` presets.

**Comment by alexfedoseev** [comment]
Babel 6 has a lot of issues, check out their tracker: https://phabricator.babeljs.io/maniphest/ This can be one of them.

Also with babel 6 we are loosing hot reloading, so update will happen only after [this PR](https://github.com/gaearon/babel-plugin-react-transform/pull/50) will be released. A lot of folks are waiting for this including us.
