### ISSUE TITLE
Drop support for React 0.13

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#154]
We're considering dropping support for React 0.13 for react_on_rails v2.0.0.

Please comment here if it doesn't look like you plan to upgrade React within 3 months and you use react_on_rails.

I'd say that if we don't receive any compelling reasons to continue to support 0.13, then we move, as there's a bunch of code complexity from supporting both.

## Other projects that require 0.14
* https://github.com/rackt/react-redux
* https://github.com/rackt/react-router
* https://github.com/react-bootstrap/react-bootstrap

**Comment by justin808** [comment]
Latest thinking is that with the change to npm for the JS part of ReactOnRails, we'll update the version number to 2.x and remove support for react 0.13.

**Comment by robwise** [comment]
React 0.13 dropped in 2.0.0-beta.1
