### ISSUE TITLE
jspm support possible?

### ISSUE THREAD

**Issue by smargh** [shakacode/react_on_rails#155]
I and my team are starting a new project where we are going to use React for the view layer within a Rails app. I can see the clear advantages of this gem compared to `react-rails`; however, I have heard really good things about `jspm`, especially with respect to developers who don't really have much front-end development. Would this gem, or even this general setup, work with `jspm`?

**Comment by justin808** [comment]
Hmmm...

> especially with respect to developers who don't really have much front-end development

I'm not sure how that plays into the decision.

We're about to release hot reloading of your JS and CSS within your rails app and support for CSS modules. I think that's enough goodness to tilt the balance heavily in favor of Webpack for today.

If you'd like to submit a PR using JSPM, that could work. But what problem does it solve that we have not already solved with Webpack?

@smargh, I can invite you our Slack channel if you like.

**Comment by justin808** [comment]
Closing the issue for now. Please re-open if you feel this is compelling.

**Comment by smargh** [comment]
No, your point is well-made. I'm totally willing to jump whole-hog into Webpack. I was asking more so out of a desire to understand the salient differences that made Webpack the module loader of choice for this project.

**Comment by justin808** [comment]
The best way to learn is to build a simple sample project, push to github, and ask for feedback.

We LOVE getting community contributions, even as simple as any typo in the docs, to full features!
