### ISSUE TITLE
Wrong dependencies?

### ISSUE THREAD

**Issue by andriytyurnikov** [shakacode/react_on_rails#156]
npm ERR! peerinvalid The package webpack@1.12.2 does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer babel-loader@5.3.2 wants webpack@*
npm ERR! peerinvalid Peer sass-loader@3.1.2 wants webpack@^1.12.6
npm ERR! peerinvalid Peer webpack-dev-server@1.14.0 wants webpack@>=1.3.0 <3

**Comment by justin808** [comment]
@andriytyurnikov Please try the following:

1. remove npm-shrinkwrap.json and node_modules under the /client directory
2. be sure you're you're on node > 5 and npm > 3
3. run npm install and npm shrinkwrap
4. If that doesn't work, then you should try upgrading or downgrading libraries by running `npm install --save some-lib@some-ver` or running the instructions that update all libraries. 

Obviously, those are not the literal commands. If you get stuck, let us know.

**Comment by justin808** [comment]
@andriytyurnikov We've got a slack channel as well. Email me for more info.

**Comment by andriytyurnikov** [comment]
@justin808 , hello_world works from master branch even from LTS node 4.2.2.

Latest release works from node 5 (after running `npm install` manually)

Looks like old npm fails to resolve peer dependencies.

Guys it is not that I am not thankful, or something, but when release of my software doesn't work -- I prefer to know that, so I've opened this issue ;)

**Comment by justin808** [comment]
OK -- So the issue is that you need to have the latest npm installed.

BTW, can you please try: https://rubygems.org/gems/react_on_rails/versions/1.2.0.rc1

We're about to ship this and if there is any issue, we can try to include it.

**Comment by andriytyurnikov** [comment]
@justin808 little hint here, looks like one actualy can explicitly define required node version in package.json via
```
"engines":{"node":version}
```

As about 1.2.0.rc1 -- it worked well for node 4+ and npm 2+ (node LTS), except I had to run `npm install` manually (you may want to add it into procfile line, or something  :)

**Comment by justin808** [comment]
@andriytyurnikov We're moving ReactOnRails to npm for v2.0. @yorzi, let's make sure we specify a min node version.
