### ISSUE TITLE
Include Ruby 3 and node 18 to CI workflows

### ISSUE THREAD

**Issue by ahangarha** [shakacode/react_on_rails#1565]
Currently, we only run CI with ruby 2.7 and node: 14.

Besides the fact Node 14 is not supported anymore, we need to ensure the gem works with the recent version of Ruby and Node.

MY proposal:
- ruby: `[2.7, 3.2]`
- node: `[16, 18]`

@justin808 @Judahmeek

**Comment by Judahmeek** [comment]
Sounds good to me.

Regressions regarding Ruby or Node compatibility are rare (since it usually requires using syntax or a module that is only supported by the latest version), but Github is paying for CI, so we might as well take advantage of it. 👍

**Comment by justin808** [comment]
yes, please update
