### ISSUE TITLE
Pack generation runs with nil components_subdirectory

### ISSUE THREAD

**Issue by blackjack26** [shakacode/react_on_rails#1566]
## Environment

1. Ruby version: `2.7.4p191`
2. Rails version: `6.0.4.1`
3. Shakapacker/Webpacker version: `shakapacker@7.0.2`
4. React on Rails version: `13.3.5`

#### React-On-Rails Config
- components_subdirectory: `nil`
- auto_load_bundle: `false`

## Expected behavior

The config indicates that for `config.components_subdirectory`
> The default is nil. You can enable the feature by updating it in the next line.

This gives off the impression that the pack generation can be disabled by leaving the default (or setting `components_subdirectory` to `nil`).

When running `./bin/rake assets:precompile`, i'd expect the `react_on_rails:generate_packs` task to not generate any packs. Maybe there is some configuration setting i'm missing, but following the code it doesn't seem to be the case.

## Actual behavior

Running the `./bin/rake assets:precompile` task with `components_subdirectory = nil`, causes every file (that doesn't match `*.server.*`) to have a pack generated for it.

Also it seems that file names with non-alphanumeric characters in it or reserved JS keywords, do not get generated correctly in the generated server bundle file (like `something.client`, `default`, `my-file`, etc). But this is most likely because it generated packs for files that don't match the expected `ComponentName.(client|server).js` syntax.

## Initial Debugging

This seems to happen because the `PacksGenerator#components_search_path` resolves to `{source_path}/**/` and then has a `*` appended, making it `{source_path}/**/*`.

Also appears to be related to #1509 (and release [13.3.0](https://github.com/shakacode/react_on_rails/releases/tag/13.3.0)) which removed the `verify_setup_and_generate_packs` function that checked if `components_subdirectory.present?` and subsequently did not generate the packs if this directory was not set ([ref](https://github.com/shakacode/react_on_rails/pull/1509/files#diff-ce958005f1f8ae7bb40ae163bea1570934d090b1267a0c89004605bb8c088059L25)).

Adding `return unless ReactOnRails.configuration.components_subdirectory.present?` to the top of `generate_packs_if_stale` seems to prevent this issue.

**Comment by justin808** [comment]
@blackjack26 Sounds good. Can you submit a PR?

@Judahmeek @ahangarha this needs to ship ASAP.

**Comment by ahangarha** [comment]
@blackjack26 Thanks for your report.

> Running the `./bin/rake assets:precompile` task with `components_directory = nil`, causes every file (that doesn't match `*.server.*`) to have a pack generated for it.

I just want to confirm that by `config.components_directory` you mean `config.components_subdirectory`.

**Comment by blackjack26** [comment]
> @blackjack26 Thanks for your report.
> 
> > Running the `./bin/rake assets:precompile` task with `components_directory = nil`, causes every file (that doesn't match `*.server.*`) to have a pack generated for it.
> 
> I just want to confirm that by `config.components_directory` you mean `config.components_subdirectory`.

@ahangarha yes, my bad! I updated the description
