### ISSUE TITLE
How to deal with rubygems that "pull in" jquery-rails & jquery-ui-rails

### ISSUE THREAD

**Issue by rstudner** [shakacode/react_on_rails#157]
This isn't an "issue" for react_on_rails per se (hey, this gem looks to the future!) but I wanted to see if anyone had some thoughts/mindshare on an integration problem.

Some rubygems, like Active Admin, depend on jquery-rails and jquery-ui-rails.  Thus, including them in a project can "force" jquery to be pulled in.  This of course is counter to the design philosophy of react_on_rails.

Is there a decent mental model for how to address this?  I thought of, in the webpack config, declaring externals for jquery and jquery-ui and NOT having them in the package.json.

The real issue this causes, of course, is that in some instances the jquery on a page (2.1.4) from webpack gets literally replaced by say, jquery 1.11.3, but all the widgets/things attached to $.fn then get blown away.

(to note, don't use those dang gem's in the answer -- I get it hah).

**Comment by justin808** [comment]
@rstudner Why would it matter if those gems like jquery and jquery-ui are pulled in? What matters is what you expose in terms of JS files on your layouts. So if Active Admin pulls the world in and take control of the layout, that should be fine. Just don't include your bundle.

Webpack also lets you bundle as you please, and you can easily specify jQuery as an external, etc.
