### ISSUE TITLE
When server-bundle.js register a lot of server render components making the server render performance  reduce big

### ISSUE THREAD

**Issue by MarkWang2** [shakacode/react_on_rails#1574]
**Is your feature request related to a problem? Please describe.**
Our project needs to register  a lot of server render components to server-bundle.js , this way makes the performance drop big(compare to only registering one server render component)

**Describe the solution you'd like**
Do we have some solutions to split the server-bundle.js  file, to make performance better? Thanks.

**Comment by Judahmeek** [comment]
Currently, no.

@justin808 this sounds like a good RoR Pro NodeRenderer feature.

**Comment by justin808** [comment]
@MarkWang2 I'm pretty sure this can work with our https://www.shakacode.com/react-on-rails-pro/ Node renderer.

Please [email me](mailto:justin@shakacode.com) or ping me on the [React Rails Slack discussion](https://join.slack.com/t/reactrails/shared_invite/enQtNjY3NTczMjczNzYxLTlmYjdiZmY3MTVlMzU2YWE0OWM0MzNiZDI0MzdkZGFiZTFkYTFkOGVjODBmOWEyYWQ3MzA2NGE1YWJjNmVlMGE).
