### ISSUE TITLE
Change primary branch name from `master` to `main`

### ISSUE THREAD

**Issue by ologbonowiwi** [shakacode/react_on_rails#1588]
Hey, team, I hope everything is going great!

Since `master` is an offensive term for descendants of enslaved people ([more details here](https://www.theserverside.com/feature/Why-GitHub-renamed-its-master-branch-to-main)), it'd be preferred to use `main` instead.

CC: @justin808 @Judahmeek

**Comment by wwahammy** [comment]
I strongly second this request, @ologbonowiwi.

**Comment by justin808** [comment]
Thank you for raising this critical point, @ologbonowiwi, and for your support, @wwahammy.  

I recognize the value of using inclusive language. However, given our current priorities on higher-impact feature development and bug fixes, this change doesn't fit within our immediate roadmap. 

I'd consider reopening this issue when a community member who feels strongly about it can **champion the effort**. This would involve creating a well-tested PR addressing potential side effects.
