### ISSUE TITLE
Adjustment of Minimum Required Ruby Version for Versions 12.5.x

### ISSUE THREAD

**Issue by gregoryfm** [shakacode/react_on_rails#1602]
Firstly, I want to extend my congratulations to the entire team for the incredible work that has been accomplished with this gem.

I'd like to ask about the possibility of publishing a new version, specifically 12.5.x, wherein the minimum required Ruby version is reverted back to >= 2.5.0.

Upon reviewing the [Changelog](https://github.com/shakacode/react_on_rails/blob/master/CHANGELOG.md#1250---2021-12-26), I noticed that this change was implemented in version 12.5.0, citing alignment with rails/webpacker. However, the latest published version of [webpacker (5.4.4)](https://rubygems.org/gems/webpacker/versions/5.4.4) maintains a minimum required Ruby version of >= 2.4.0.

Currently, I have systems still running on Ruby 2.5.0. While upgrading to the latest version is indeed on our roadmap, it hasn't yet been expedited. Reverting the Ruby requirement, perhaps in version 12.5.3, would facilitate our transition from version 12.4.0 and enable us to leverage the performance enhancements of React 18.

If necessary, I am willing to create the pull request for this adjustment.

**Comment by justin808** [comment]
@gregoryfm would your company be open to signing up for [Sponsorship](https://github.com/sponsors/shakacode) for React on Rails Pro (includes a lot more), and we could keep issuing official releases for you? If you think so, please [book a time to meet](https://meetings.hubspot.com/justingordon/30-minute-consultation).

**Comment by gregoryfm** [comment]
Hey @justin808 thanks for your reply. While we acknowledge the value and effort you guys put into the React on Rails/Cypress projects. At the moment, we're in a period of temporary efforts in cost management, and as such, we're unable to commit to sponsorships. We'll definitely reassess this situation in the future.

Do you reckon would it be possible to push a 12.5.3 version with the Ruby minimum required back to 2.5.0?

**Comment by gregoryfm** [comment]
Hey @justin808, do you think it's possible to publish this update?

**Comment by justin808** [comment]
Why not just use your fork as a dependency in the project?

**Comment by justin808** [comment]
If fork is too difficult, we can consider reopening.
