### ISSUE TITLE
Module not found: Error: Cannot resolve module 'lodash'

### ISSUE THREAD

**Issue by anjolovic** [shakacode/react_on_rails#162]
The `lodash` is not installed at the time of running Rails generate command.

**Comment by justin808** [comment]
@anjolovic This should be easy to add. Thanks for the report.

@yorzi I just confirmed this is an issue. If you can throw in a quick fix, that would be greatly appreciated.

https://github.com/shakacode/react_on_rails-generator-results/pull/144/files#diff-52dbbf94d5c54b68c0cad0702ba94a96R38

**Comment by justin808** [comment]
I'm setting the milestone as 2.0, as there's an easy workaround:

```sh
cd client && npm i --save lodash
```
Then rebuild the shrinkwrap.

**Comment by yorzi** [comment]
@justin808 why do you point out `"babel-core": "^5.8.25"` above? I checked master, `lodash` is only added to package.json when `redux` was enabled.

**Comment by justin808** [comment]
@yorzi Just indicating that we're missing lodash from this spot.

**Comment by robwise** [comment]
Fixed in #175
