### ISSUE TITLE
Running `react_on_rails:install` is not compatible with Shakapacker v8

### ISSUE THREAD

**Issue by timkrins** [shakacode/react_on_rails#1625]
## Environment

1. Ruby version: 3.3.0
2. Rails version: 7.1.3.3
3. Shakapacker/Webpacker version: 8.0.0
4. React on Rails version: 14.0.1

## Expected behavior
I set up a new Rails project.
I follow the installation guide for `shakapacker`, and then follow the Getting Started directions for `react_on_rails`.
The command `rails generate react_on_rails:install` installs the correct files required for this version of Shakapacker.

## Actual behavior
I set up a new Rails project.
I follow the installation guide for `shakapacker`, and then follow the Getting Started directions for `react_on_rails`.
The command `rails generate react_on_rails:install` undoes required changes for Shakapacker v8 (it does not use the required `generateWebpackConfig` exports etc)

**Comment by vaukalak** [comment]
Hello @timkrins and thanks for reporting the issue, it's on our track.

@Judahmeek @justin808 this should be addressed by https://github.com/shakacode/react_on_rails/pull/1622

**Comment by vaukalak** [comment]
@timkrins it should be fixed by https://github.com/shakacode/react_on_rails/pull/1629 , feel free to re-open if it is not.
