### ISSUE TITLE
Utilize shakacode/package_json for Enhanced Package Management Compatibility

### ISSUE THREAD

**Issue by vaukalak** [shakacode/react_on_rails#1635]
**Is your feature request related to a problem? Please describe.**
react-on-rails could benefit from syncronized package management with shakapacker.

**Describe the solution you'd like**
I suggest integrating shakacode/package_json to manage react-on-rails package configurations. This would unify dependency management and enhance project consistency.

**Comment by justin808** [comment]
@G-Rath  can you please make a PR from this? I’d like to ship ASAP.

> turns out I still have my old branch: https://github.com/G-Rath/react_on_rails/tree/use-package_json

> I’ve rebased that with the latest stuff on main and I think it’s almost good to go - the main thing missing is if any tests need to be written
