### ISSUE TITLE
Getting `undefined method `react_component'` error with react_on_rails v12.4.0 in ruby v2.6.9 rails v6.1

### ISSUE THREAD

**Issue by happyvig** [shakacode/react_on_rails#1642]
Hi,
I was trying to integrate react_on_rails gem into my existing rails application, for the very first time.
Ran into `undefined method `react_component'` error with react_on_rails v12.4.0 in ruby v2.6.9 rails v6.1

## Environment

1. Ruby version: 2.6.9
2. Rails version: 6.1.7.6
3. Shakapacker/Webpacker version: 7.2.3
4. React on Rails version: 12.4.0

## Expected behavior
No error, react should be up and running smoothly as demo
## Actual behavior
<img width="1727" alt="image" src="https://github.com/shakacode/react_on_rails/assets/2972622/d3723119-f584-444c-8bf9-058c84b5d1d2">

What am I missing in the above setup ? I tried everything as per documentation - https://www.shakacode.com/react-on-rails/docs/guides/installation-into-an-existing-rails-app/

--
Any help/guidance on this is highly appreciated.
Thanks in advance.

**Comment by justin808** [comment]
Can you update to the latest versions?

**Comment by happyvig** [comment]
Hi @justin808 ,
Thanks for getting back on the issue. 

Unfortunately I am stuck with the ``Ruby and `Rails versions in my Rails app and can't move up further for now. 

Any help for `react_on_rails` v`12.4.0`  itself would be appreciated.

**Comment by happyvig** [comment]
Also, is there any documentation for `react_on_rails v12.4.0` specifically that talks about its integrations into an existing Rails 6 app ?

**Comment by Judahmeek** [comment]
@happyvig we haven't made any changes to our Rails integration architecture in a long time.

It looks like others have experienced this error with Rails 4~6. Please check https://github.com/shakacode/react_on_rails/issues/385
