### ISSUE TITLE
confused about hot reload

### ISSUE THREAD

**Issue by flynfish** [shakacode/react_on_rails#166]
Thanks for the gem! I ran the generators and when I start the server via `foreman start -f Procfile.dev` everything loads correctly and I can access localhost:3000/hello_world

However, if I make any code changes, they aren't picked up unless I restart the foreman process. 

The docs say to visit localhost:4000 for hot reloading, but nothing responds there.

Am I missing something obvious?

**Comment by justin808** [comment]
Hot reloading for react_on_rails only works with running the webpack dev server on port 4000. 

We've updated the tutorial to make this work with rails, by loading assets from port 3500 (rails on port 3000).

Please see https://github.com/shakacode/react-webpack-rails-tutorial/ for how to do that.

You can see this live here: http://www.reactrails.com. 

We'll eventually be updating the generators to support this! If you can help, that's a great way to master this!

**Comment by justin808** [comment]
This is the code that runs the webpack dev server:

```
cd client && npm start
```

https://github.com/shakacode/react_on_rails-generator-results/pull/144/files#diff-10ea5ef17ff7f2e9af7f71be3e682738R2

**Comment by flynfish** [comment]
@justin808 I'd like to help out with the generators to get hot reloading working...but I'm not sure what the main source of truth is as I look at `react_on_rails` vs `react_webpack_rails_tutorial`. 

For instance, the `webpack.client.hot.config.js` has differences between the two repos. Which should I be leaning on as the most correct?

**Comment by justin808** [comment]
@flynfish Send me your email and I'll add you our slack. We'd so much appreciate the help! and there's no better way to learn the system!

**Comment by justin808** [comment]
The tutorial is more up-to-date, and I'm going to make a couple adjustments in the next day or so. Right now, the tutorial ONLY supports hot reloading with Rails during development. I want to give it an alternate option which is what we currently have in the generators (older technique).

**Comment by flynfish** [comment]
@justin808 sent you an email to your gmail!
