### ISSUE TITLE
Display server side rendered text when javascript disabled

### ISSUE THREAD

**Issue by astrauka** [shakacode/react_on_rails#167]
I took the example app https://github.com/shakacode/react-webpack-rails-tutorial

Updated https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/app/views/pages/simple.html.erb#L12 to
```
<%= react_component('SimpleCommentScreen', {}, generator_function: false, prerender: true) %>
```

Turned off javascript support in browser and loading the page got the error:
![image](https://cloud.githubusercontent.com/assets/1308928/11912321/fe91d482-a63f-11e5-82c5-8107d5e11add.png)

Rails server output looks ok:
```
10:52:20 rails.1               | Started GET "/simple" for 127.0.0.1 at 2015-12-19 10:52:20 +0200
10:52:20 rails.1               | Processing by PagesController#simple as HTML
10:52:20 rails.1               | [react_on_rails] RENDERED SimpleCommentScreen to dom node with id: SimpleCommentScreen-react-component-0
10:52:20 rails.1               |   Rendered pages/simple.html.erb within layouts/application (1.2ms)
10:52:20 rails.1               | Completed 200 OK in 23ms (Views: 22.9ms | ActiveRecord: 0.0ms)
```

I expect to see server side rendered text when javascript is disabled.
Am I doing something wrong?

**Comment by justin808** [comment]
There's a lot more to server rendering than just changing an option to false.

Take a look at this: https://github.com/shakacode/react_on_rails-generator-results/pull/151/files

You go to http://www.reactrails.com/ and turn off JS, and it works fine.

@astrauka You do bring up a *GREAT* point. We should enable that page to work with server rendering!

If you make a PR on this one, that's the best way ever to learn how this works!
