### ISSUE TITLE
Deployment in production: more documentation!

### ISSUE THREAD

**Issue by lucke84** [shakacode/react_on_rails#168]
Maybe it's just me, but I think there should be some doc about the usage of this gem in production-like (AKA non-development) environments, including best practices for deployment and maintenance. I understand this gem is quite young but it's a pretty good one and should appear a solid option to newcomers.

**Comment by justin808** [comment]
@lucke84 What sort of extra documentation would be required?

We've only got experience deploying to heroku. You can see a full example here: https://github.com/shakacode/react-webpack-rails-tutorial.

Email me if you'd like an invite to our Slack room.

**Comment by lucke84** [comment]
Well, I think it's limiting the scope of the project to assume everybody will use Heroku. For instance, my team works with machines on AWS or Linode and it'd be nice to see some instructions/gotchas for that kind of environment(s) too. Maybe there's no big difference in the process, in that case it'd be nice to see it documented as well.

**Comment by justin808** [comment]
@lucke84 we have a /docs folder. I'd be happy to take a PR.
