### ISSUE TITLE
Update generators for proper jquery config

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#169]
Simple change to the generators: we don't need jquery-ujs for the webpack dev server.

This issue brought this to light: https://github.com/shakacode/react-webpack-rails-tutorial/issues/185

@yorzi This should be a really simple change to make. Ping me if you need help.

**Comment by justin808** [comment]
I did make this PR: https://github.com/shakacode/react-webpack-rails-tutorial/pull/163. The Webpack Dev Server didn't need jquery-ujs.

**Comment by yorzi** [comment]
@justin808 ok, what do you mean by "The Webpack Dev Server didn't need jquery-ujs" in this issue?

**Comment by yorzi** [comment]
@justin808 I am supposed to see `jquery-ujs` in `/templates/base/base/client/webpack.client.hot.config.js.tt` right? I don't understand this issue now.

**Comment by justin808** [comment]
You should not. the hot.config is for the webpack dev server, serving a "jade" template file (no rails). jquery-ujs is rails specific, so it only goes in the rails webpack configs.
