### ISSUE TITLE
Simpler client side rendering api

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#17]
Rather than:

```erb
<%= react_component('App', {}, prerender: false) %>
```

we'd like to simply do:
```erb
<%= react_component('App', prerender: false) %>
```
Or maybe if prerender is defaulting to false, this already works:

```erb
<%= react_component('App') %>
```

So maybe then we don't need to do anything here...

**Comment by samnang** [comment]
I think it's hard to get it to work like that. Because the second params is also hash which is the props that should pass into the component. We could do `<%= react_component('App') %>` when we just left with the default options.
