### ISSUE TITLE
Feature request: No inline style option for ReactOnRailsHelper#react_component

### ISSUE THREAD

**Issue by TangRufus** [shakacode/react_on_rails#173]
Feature request:
Add a **no inline style** option to `ReactOnRailsHelper#react_component` to skip `style: "display:none"`

Reason: 
Eliminate the needs of `unsafe-line` for [Content Security Policy](https://en.wikipedia.org/wiki/Content_Security_Policy)

Related file:
https://github.com/shakacode/react_on_rails/blob/a9b7d47d0829a0b6ec6c28bfbbbb589a4149296f/app/helpers/react_on_rails_helper.rb#L62

**Comment by justin808** [comment]
Why are display:none lines unsafe?

@TangRufus Would you like to create a PR for this? The option could be "skip_display_none", with a default of false.

I'd like to get some community feedback on the option name. Do we need a CSS style for "js-react-on-rails-component" for "display:none"?

![2015-12-29_11-26-16](https://cloud.githubusercontent.com/assets/1118459/12040587/2d266484-ae1f-11e5-9585-17db974d6e41.png)

**Comment by TangRufus** [comment]
`display:none` lines are safe.

However, if `style-src: 'unsafe-inline'` in content security policy headers, browsers would execute all inline styles from any source. Somebody could hijack the web page. 

PR created. Thanks!

**Comment by justin808** [comment]
See #174. We need to get tests included and we can add this.

**Comment by justin808** [comment]
@TangRufus Any updates?

**Comment by aaronvb** [comment]
@justin808 @TangRufus Closing this. See #218
