### ISSUE TITLE
Remove use of underscore-prefixed methods in generators

### ISSUE THREAD

**Issue by robwise** [shakacode/react_on_rails#177]

**Comment by justin808** [comment]
@robwise still an issue? If so, maybe @aaronvb can help you?

**Comment by aaronvb** [comment]
@robwise @justin808 Sure let me know if you need help with this

**Comment by justin808** [comment]
@aaronvb Awesome. Thanks!

**Comment by aaronvb** [comment]
@robwise Can you give me a little more information on this issue?

**Comment by robwise** [comment]
@aaronvb Oh, well we originally were following a style convention to name all of the methods that we didn't intend to be used outside of the class with and underscore (`_`) character. We've since changed our styles and we no longer do this. Therefore, we need to delete the underscores from all of the methods that have them in the generated javascript.

Basically, we have the opposite of this rule:
https://github.com/airbnb/javascript#22.4

**Comment by aaronvb** [comment]
@robwise I went through all the JS files in the generator template files and did not find any functions starting with an underscore. Just to be safe I ran a regular expression search on that directory and came up with nothing.

**Comment by robwise** [comment]
@aaronvb Roger, thank you for checking that. Someone must have hit this at some point so I'm closing.
