### ISSUE TITLE
Upgrade bootstrap-sass-loader dependency in generators

### ISSUE THREAD

**Issue by robwise** [shakacode/react_on_rails#179]
`npm WARN deprecated bootstrap-sass-loader@1.0.10: Replaced by bootstrap-loader. Please upgrade.`

**Comment by justin808** [comment]
Yep! we need to update. We can do this post 2.0.

**Comment by wyaeld** [comment]
@justin808 have just built a new app with latest releases, and removing this, and adding both

```
"bootstrap-loader": "^1.0.8"
"resolve-url-loader": "^1.4.3"
```

(latter needed because of the peer dependency)

worked without issues, and solved the deprecation notices

**Comment by justin808** [comment]
@wyaeld  We really need to update a few files to get to the new bootstrap-loader. By any chance, could you try to make a PR on that and I'll review it?

**Comment by jbhatab** [comment]
Since we've removed this from the generator, can we close this?

**Comment by justin808** [comment]
Yes.

We're no longer doing styling in the generators. See https://github.com/shakacode/react-webpack-rails-tutorial/ for an example of using CSS Modules to do styling.
