### ISSUE TITLE
Consider hot-reloading with Rails for Generator

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#18]
Turns out there is some work going on here regarding hot reloading on the rails side: https://github.com/rmosolgo/react-rails-hot-loader

It would be interesting if this could be made to work with the webpack setup.

While not a high priority, it's worth saving the idea.

**Comment by diffractometer** [comment]
+1

**Comment by gugl** [comment]
I've finally got a hot reload setup working now and this gist was the key to it: https://gist.github.com/epeli/28c2dbcbe8109a0c5edb

**Comment by alexfedoseev** [comment]
@gugl Nice! Actually it's identical setup with what I'm doing now inside `express` server on Node, but instead `jade` -> `erb`.

**Comment by justin808** [comment]
We've got this working on https://github.com/shakacode/react-webpack-rails-tutorial/.

We may or may not want to support this for the generators.

**Comment by robwise** [comment]
@justin808 I think it would be **awesome** to have this in the generators!

**Comment by justin808** [comment]
@robwise We need to find some community help on that. Maybe @yorzi or @aaronvb ?

**Comment by justin808** [comment]
Closing this as #179 is the one that should do this one.
