### ISSUE TITLE
How to pass Rails constants/variables to client side?

### ISSUE THREAD

**Issue by TangRufus** [shakacode/react_on_rails#180]
I want to put a `img` tag on the client side. Something like this:
```html
<img src="https://localhost:5000/assets/img/header.jpg" />
```

How can I pass [sass-rails](https://github.com/rails/sass-rails) gem's [asset-url](https://github.com/rails/sass-rails#asset-urlrelative-asset-path) to the client side?

In other words, how can I pass Rails constants/variables to the client side?

**Comment by justin808** [comment]
@TangRufus You have 3 options:

1. Use CSS background images.
2. Pass the URL as a prop.
3. Follow this example of using CSS modules: https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client%2Fapp%2Fbundles%2Fcomments%2Fcomponents%2FCommentScreen%2FCommentScreen.scss
