### ISSUE TITLE
Consider integration with react-stdio for server rendering

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#183]
* @mjackson: https://github.com/mjackson/react-stdio
* @hassox: http://blog.overstuffedgorilla.com/render-react-with-phoenix/

@mjackson has created react-stdio. We should look into integrating this with react_on_rails.

@alexfedoseev: this looks promising 
@cowboyd: Any thoughts on this compared to what we currently use: https://github.com/cowboyd/therubyracer

**Comment by mjackson** [comment]
Just for clarification, it's react-stdio, not react-studio :)

**Comment by justin808** [comment]
@mjackson Thanks. Studio sounds kind of cool ;-).

Any thoughts on a Rails integration?

**Comment by mjackson** [comment]
Probably the first step would be to create a Ruby wrapper for react-stdio that knows how to feed its stdin and parse its stdout. After that, integration with Rails should be fairly straightforward.

**Comment by aaronvb** [comment]
I looked into implementing this into react_on_rails(and in react-rails). With our current server rendering method it's not going to work 'out of the box'. react-stdio takes a path to a component whereas we pass a string of JS code(with polyfills) to ExecJS(therubyracer).

I ended up writing a little react-stdio wrapper for Rails that could be helpful in pursuing this option: https://github.com/aaronvb/rails_react_stdio.

**Comment by justin808** [comment]
@aaronvb If you get this working, you will be a

# HERO

**Comment by justin808** [comment]
@aaronvb any word on this one?

**Comment by aaronvb** [comment]
@justin808 I haven't put much work into this. I'm open to pairing up or starting a branch for collaboration on this.

**Comment by justin808** [comment]
@aaronvb Any progress on this one? We really should try this one!

**Comment by justin808** [comment]
Closed by #380
