### ISSUE TITLE
After generator runs, print a helpful message

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#184]
This what I see after running the generator on the v2 branch (CC: @aaronvb) 
```
➜  ~/scratch/test-react-on-rails-2 (master) bundle exec rails generate react_on_rails:install -R -S -H -L                                                                                                                                                          [15:05:37]
Running via Spring preloader in process 65235
       route  get 'hello_world', to: 'hello_world#index'
      create  client/assets
      create  client/assets/stylesheets
      create  client/assets/fonts
      create  client/assets/fonts/.keep
      create  client/assets/images
      create  client/assets/images/.keep
      append  .gitignore
     prepend  app/assets/javascripts/application.js
        gsub  app/assets/javascripts/application.js
        gsub  app/assets/javascripts/application.js
        gsub  app/assets/javascripts/application.js
        gsub  app/assets/javascripts/application.js
      create  client/app/bundles/HelloWorld/components
      create  client/app/bundles/HelloWorld/containers
      create  client/app/bundles/HelloWorld/startup
      create  app/controllers/hello_world_controller.rb
      create  config/initializers/react_on_rails.rb
      create  client/.babelrc
      create  client/index.jade
      create  client/server.js
      create  client/webpack.client.base.config.js
      create  client/webpack.client.rails.config.js
      create  REACT_ON_RAILS.md
      create  client/REACT_ON_RAILS_CLIENT_README.md
      create  package.json
      create  Procfile.dev
      create  Procfile.dev-hot
      create  app/views/hello_world/index.html.erb
      create  client/app/bundles/HelloWorld/components/HelloWorldWidget.jsx
      create  client/webpack.client.hot.config.js
      create  client/package.json
      append  Gemfile
      create  client/app/bundles/HelloWorld/startup/clientRegistration.jsx
      create  client/webpack.server.rails.config.js
      create  client/app/bundles/HelloWorld/startup/serverRegistration.jsx
      create  lib/tasks/linters.rake
      create  lib/tasks/assets.rake
      append  config/initializers/assets.rb
      create  client/app/bundles/HelloWorld/actions
      create  client/app/bundles/HelloWorld/constants
      create  client/app/bundles/HelloWorld/reducers
      create  client/app/bundles/HelloWorld/store
      create  client/app/lib/middlewares
      create  client/app/bundles/HelloWorld/actions/helloWorldActionCreators.jsx
      create  client/app/bundles/HelloWorld/containers/HelloWorld.jsx
      create  client/app/bundles/HelloWorld/constants/helloWorldConstants.jsx
      create  client/app/bundles/HelloWorld/reducers/helloWorldReducer.jsx
      create  client/app/bundles/HelloWorld/reducers/index.jsx
      create  client/app/bundles/HelloWorld/store/helloWorldStore.jsx
      create  client/app/lib/middlewares/loggerMiddleware.js
      create  client/app/bundles/HelloWorld/startup/HelloWorldAppServer.jsx
      create  client/app/bundles/HelloWorld/startup/HelloWorldAppClient.jsx
      create  client/.eslintrc
      create  client/.eslintignore
      create  client/.jscsrc
      append  Gemfile
      create  lib/tasks/brakeman.rake
      create  lib/tasks/ci.rake
      create  .rubocop.yml
      create  .scss-lint.yml
      create  ruby-lint.yml
      create  .buildpacks
      create  Procfile
      create  config/puma.rb
      append  Gemfile
      create  app/assets/stylesheets/_bootstrap-custom.scss
      create  client/assets/stylesheets/_post-bootstrap.scss
      create  client/assets/stylesheets/_pre-bootstrap.scss
      create  client/assets/stylesheets/_react-on-rails-sass-helper.scss
      create  client/bootstrap-sass.config.js
      append  app/assets/stylesheets/application.scss
        gsub  app/assets/stylesheets/application.scss
        gsub  app/assets/stylesheets/application.scss
      append  Gemfile
      append  app/assets/javascripts/application.js
```

**Comment by robwise** [comment]
I think whoever attempts this can leverage the work @aaronvb has done in this PR: https://github.com/shakacode/react_on_rails/pull/158#discussion_r49123390

Perhaps we just rename `errors` to `messages`

**Comment by aaronvb** [comment]
If the message is predefined we can create a file with the helpful message and output it with readme 'filename'.

http://guides.rubyonrails.org/generators.html#readme

That leads me to: what will the helpful message be?

---
Aaron Van Bokhoven
bokhoven@gmail.com
http://aaronvb.com

**Comment by justin808** [comment]
@aaronvb, can you try v2 (preferably the branch, or maybe rc1)?

after the generator runs, we need to:

1. run `cd client && npm i && npm shrinkwrap` (bundle?)
2. experiment with the start up scripts: `cd <top level> && npm run` will show the scripts
3. Show the two URLs to visit: localhost:3000 and localhost:4000

There's probably more...

**Comment by aaronvb** [comment]
@justin808 @robwise if we go with a dynamic helpful message at the end, I think the best approach is another singleton like the errors, that we can populate based on what options were set. 

If you think the message will be static and same for all generator options, a simple text file printed at the end could suffice.

**Comment by robwise** [comment]
@aaronvb sounds good to me

**Comment by aaronvb** [comment]
@robwise @justin808 I'll work on this using @robwise suggestion to use another singleton like GeneratorErrors to create a helpful message at the end. That way we can tailor the helpful message based on the generator options selected.

**Comment by justin808** [comment]
v2 is out. We need to do this. @aaronvb if you check out the tutorial in the /docs, you can see what we should print.

**Comment by aaronvb** [comment]
@justin808 @robwise Here are the two examples explained in my previous comment.

## Using GeneratorMessages

This method uses `GeneratorMessages.add_info` to add helpful messages on specific generators.

### Base Install
`rails generate react_on_rails:install`

<img width="790" alt="screen shot 2016-01-14 at 1 35 21 pm" src="https://cloud.githubusercontent.com/assets/100900/12341159/b677bb38-bac3-11e5-9bd7-a6211d422ecc.png">

### Base Install with Redux

`rails generate react_on_rails:install -R`

<img width="788" alt="screen shot 2016-01-14 at 1 37 04 pm" src="https://cloud.githubusercontent.com/assets/100900/12341183/efb708e0-bac3-11e5-86c5-b3a536b76e17.png">

## Using a README file

http://guides.rubyonrails.org/generators.html#readme

This method is not dynamic as it uses a static README file to print the message at the end.

<img width="786" alt="screen shot 2016-01-14 at 1 46 05 pm" src="https://cloud.githubusercontent.com/assets/100900/12341442/cf22a88a-bac5-11e5-8608-0dc9ef67be33.png">


Styling for the messages taken from https://github.com/plataformatec/devise/blob/master/lib/generators/templates/README

**Comment by justin808** [comment]
@aaronvb Have you got this one. These suggestions look awesome.

**Comment by robwise** [comment]
Dynamic is definitely cooler! Good job Aaron!

**Comment by aaronvb** [comment]
Thanks for the feedback! I'll do a PR for the dynamic version Today. 

---
Aaron Van Bokhoven
bokhoven@gmail.com
http://aaronvb.com

**Comment by aaronvb** [comment]
Closing this :+1:
