### ISSUE TITLE
React dnd can't find installed react

### ISSUE THREAD

**Issue by hakunin** [shakacode/react_on_rails#187]
Hi, sorry if this is a noob question, I am just starting with React.
I am trying to use react-dnd (drag and drop) package and it seems not be able to find react?
```
npm WARN EPEERINVALID react-dnd@2.0.2 requires a peer of react@^0.14.0 but none was installed.
```
I've updated to the latest gem from github, but its the same problem.
Not sure whats the right thing to do here.

**Comment by justin808** [comment]
Run this in the /client folder: `npm i --save react`

NPM dependencies are handled by package.json.
