### ISSUE TITLE
How to include stylesheets of packages?

### ISSUE THREAD

**Issue by hakunin** [shakacode/react_on_rails#190]
Hi, I am using react-select and I had to copy&paste the stylesheet to make it work.

I'd prefer to somehow load/include it somewhere, but didn't find any info on that.

**Comment by justin808** [comment]
@hakunin Good question. However, this is better suited for http://forum.shakacode.com/

The short answer is that you could do a relative reference to the node modules folder. Maybe you can configure your webpack to add that to some SCSS search paths. I think that could be an option for node-sass loader. This also depends on whether or not you're using our way of using CSS modules vs the older way of just keeping the asset pipeline separate from the webpack dev server technique.

**Comment by hakunin** [comment]
Thanks, I'll give it a read. I tried to do `@import` form the after bootstrap scss file, but as I found there are no useful files in the node_modules, just empty folders (or so it seems).

**Comment by justin808** [comment]
@hakunin Please see how we load scss from other npm packages here: https://github.com/shakacode/bootstrap-loader.

**Comment by hakunin** [comment]
I ended up adding sass loader and a relative path to the node module style file. It was easy, but it would be nice to have a bit of info for guys like me who have no previous experience with it.

**Comment by hqt** [comment]
@hakunin can you give me more detail instruction please. I met same problem.

**Comment by hakunin** [comment]
Sorry, I am no longer using the gem.
