### ISSUE TITLE
Anchor link redirects don't load new react component

### ISSUE THREAD

**Issue by joerodrig3** [shakacode/react_on_rails#191]
I'm developing an app that has a "Homepage" react component that is passed props through a controller. The homepage contains a link to another controller view. When I click the link to go to the other view, the erb file for that view loads but the react component doesn't load

ie)
Controller: MainController
React component called from erb view: Homepage
Link: survey/:survey_id/edit ---> When clicked goes to the SurveyController and loads the edit view

After clicking the link above, the erb edit view loads, but the React component I'm calling inside that view doesn't load until I manually refresh the page.

This is probably a simple settings issue but I can't seem to find out whats going wrong

***Update***
It looks like the issue was just caused from turbolinks being enabled. Once I removed it the issue went away. Has anyone experienced this issue before and found a workaround to keep turbolinks enabled while still using this gem? I'm just building a small internal use app so it doesn't really benefit from turbolinks anyway but it would be nice to know if these two gems are compatible

**Comment by justin808** [comment]
Please try updating to v2 and re-open this issue if you like.
