### ISSUE TITLE
Issues with RC3 under Rails 3

### ISSUE THREAD

**Issue by thewoolleyman** [shakacode/react_on_rails#193]
I'm running through the [tutorial on rc3](http://forum.shakacode.com/t/using-react-on-rails/451) using Rails 3.2.22.

Opening this issue as a placeholder for problems I've found, I'll try to investigate root causes and update.

First one is that the dev env failed to start after generate/bundle/npm i. Couldn't find sprockets, probably a load order thing.  Here's the error:

```
→ npm run rails-server

> react-webpack-rails-tutorial@1.1.1 rails-server /Users/woolley/workspace/react-on-rails-test2
> foreman start -f Procfile.dev

22:25:57 web.1    | started with pid 65464
22:25:57 client.1 | started with pid 65465
22:25:57 server.1 | started with pid 65466
22:25:57 client.1 | rm: app/assets/javascripts/generated/*: No such file or directory
22:25:57 server.1 |
22:25:57 server.1 | > react-webpack-rails-tutorial@1.1.0 build:dev:server /Users/woolley/workspace/react-on-rails-test2/client
22:25:57 server.1 | > webpack -w --config webpack.server.rails.config.js
22:25:57 server.1 |
22:25:57 client.1 |
22:25:57 client.1 | > react-webpack-rails-tutorial@1.1.0 build:dev:client /Users/woolley/workspace/react-on-rails-test2/client
22:25:57 client.1 | > webpack -w --config webpack.client.rails.config.js
22:25:57 client.1 |
22:25:58 client.1 | Webpack dev build for Rails
22:26:02 web.1    | /Users/woolley/.rvm/gems/ruby-2.2.3@rails3/gems/bootstrap-sass-3.3.6/lib/bootstrap-sass/engine.rb:11:in `block in <class:Engine>': uninitialized constant Sprockets::Rails (NameError)
22:26:02 web.1    | 	from /Users/woolley/.rvm/gems/ruby-2.2.3@rails3/gems/railties-3.2.22/lib/rails/initializable.rb:30:in `instance_exec'
22:26:02 web.1    | 	from /Users/woolley/.rvm/gems/ruby-2.2.3@rails3/gems/railties-3.2.22/lib/rails/initializable.rb:30:in `run'
22:26:02 web.1    | 	from /Users/woolley/.rvm/gems/ruby-2.2.3@rails3/gems/railties-3.2.22/lib/rails/initializable.rb:55:in `block in run_initializers'
22:26:02 web.1    | 	from /Users/woolley/.rvm/gems/ruby-2.2.3@rails3/gems/railties-3.2.22/lib/rails/initializable.rb:54:in `each'
22:26:02 web.1    | 	from /Users/woolley/.rvm/gems/ruby-2.2.3@rails3/gems/railties-3.2.22/lib/rails/initializable.rb:54:in `run_initializers'
22:26:02 web.1    | 	from /Users/woolley/.rvm/gems/ruby-2.2.3@rails3/gems/railties-3.2.22/lib/rails/application.rb:136:in `initialize!'
22:26:02 web.1    | 	from /Users/woolley/.rvm/gems/ruby-2.2.3@rails3/gems/railties-3.2.22/lib/rails/railtie/configurable.rb:30:in `method_missing'
22:26:02 web.1    | 	from /Users/woolley/workspace/react-on-rails-test2/config/environment.rb:5:in `<top (required)>'

```

**Comment by justin808** [comment]
@thewoolleyman Should we support Rails 3? Rails 5 is about to release. I'm happy to support Rails 3 either if sponsored or by taking pull requests.

**Comment by thewoolleyman** [comment]
@justin808 Well, I initially started trying it because Rails >=3 was mentioned in https://github.com/shakacode/react_on_rails/pull/172

Anyway, this particular issue was bad dependency management in bootstrap-sass, they have Rails 4 as a dev dependency, when they really should have it as a runtime dependency.  

The fix for that error was to add the version spec `gem 'bootstrap-sass', '~> 3.1.1'` to the generated Gemfile line (that's apparently the last version that supported Rails 3.

But, after that, the app started but I got this error when trying to load the view:

```
File to import not found or unreadable: bootstrap-sprockets.
Load paths:
  Sass::Rails::Importer(/Users/woolley/workspace/react-on-rails-test2/app/assets/stylesheets/application.scss)
  /Users/woolley/.rvm/gems/ruby-2.2.3@rails3/gems/bootstrap-sass-3.1.1.1/vendor/assets/stylesheets
  (in /Users/woolley/workspace/react-on-rails-test2/app/assets/stylesheets/application.scss)
```

So, I'm guessing that it would be a yak-shaving exercise to attempt to get Rails 3 working.

My only ulterior motive is that I'd like to propose using React on Rails on my day job app, we need it, but we are still Rails 3, so that would be a blocker until we upgrade to Rails 4.

But, that's not your concern.  All else aside, supporting only Rails >= 4 sounds like a reasonable thing to do.

If you do decide that however, it would be helpful to update https://github.com/shakacode/react_on_rails/pull/172 and any other relevant issues/PRs to make it clear that there's no Rails 3 support.

And also, be good about dependencies and add an explicit non-dev dependency forcing Rails >=4 to the react_on_rails gemspec for 2.0, so nobody can even attempt to use it with Rails 3.

**Comment by flynfish** [comment]
I'm running the current version of this gem on rails 3 just fine. I haven't tried the RC version yet.

**Comment by martyphee** [comment]
I'm running into the same issues as @thewoolleyman with a new Rails project.  I was going to try testing #172.

Are you not using bootstrap?  Are you compiling the assets?

**Comment by thewoolleyman** [comment]
@justin808 So, I removed usage of bootstrap-sass/bootstrap-sprockets and everything works fine.

Is there any reason that bootstrap-sass needs to be included by the generators?  It's not really key to react_on_rails, you can have a single-page-app that doesn't rely on any rails-side view rendering or assets.

So, maybe we could just remove usage of it?

Or, if you want to keep it, add conditional logic to the generator to detect if Rails 3 is being used, and omit it?

**Comment by justin808** [comment]
@thewoolleyman bootstrap-sass is related to using bootstrap with Rails. The https://github.com/shakacode/react-webpack-rails-tutorial uses our new system of CSS modules with bootstrap coming from npm. We'll soon be updating the generators for that. :smile: .

**Comment by thewoolleyman** [comment]
Ok, then there seem to be no fundamental issues under Rails 3, at least with basic usage.

Up to you whether you leave this open to reflect the issue with bootstrap-sass in the generators, or close it.

**Comment by justin808** [comment]
In terms of V2, I'll add a note to the Rails 3 docs. 

Please add comments here: https://github.com/shakacode/react_on_rails/blob/npm-react-on-rails-js/docs/rails3.md

**Comment by thewoolleyman** [comment]
Ah, I didn't realize there was a generator option to skip it.  Sure, that looks great.
