### ISSUE TITLE
Inject Rails configuration var into JS app?

### ISSUE THREAD

**Issue by smargh** [shakacode/react_on_rails#195]
First, let me just say thanks for the great gem! My team and I have been using it in developing a new application and it has been great thus far. I have hit one issue, however, that I can't quite find a way to solve. What I need is to be able to get access to a variable set in our Rails env configs from within the React app. Specifically, we have various base URLs for the API our app hits in our various envs, and I want to use these various base URLs in the React app for client-side fetching. When we originally started writing the app (with jQuery in the `/assets/javascripts/` dir) we simply has a `globals.js.erb` file where we called:
```
sosGlobalConfig = {
  sosApiUrl: '<%= Rails.configuration.sos_api_url %>'
};
```

I tried putting this file in the `client/app/bundles/sos/` directory, but (as I suspected) it didn't convert the ERB template. So, is there any way to get access to Rails configuration variables from within a React app?

stephen

**Comment by justin808** [comment]
@smargh I recommend you add the inclusion of this js.erb file to your application.js before the webpack files, or add this js file to your layout, and then access the variables via a global on window.

**Comment by robwise** [comment]
You could also pass it as a prop to each component, but that is probably inferior to the options Justin has listed.

**Comment by smargh** [comment]
Doh! Totally wasn't thinking that I could still work in `assets/javascripts` to make things accessible to code in the `client/` dir. Great point. Thanks!
