### ISSUE TITLE
Expose mount and unmount methods

### ISSUE THREAD

**Issue by dziulius** [shakacode/react_on_rails#196]
Currently it's not possible to mount components which appear in page in modal loaded via ajax.

So something like: 

```js
ReactOnRails.mountComponents = function($container) {
  var els = $container.getElementsByClassName('js-react-on-rails-component');
  for (var i = 0; i < els.length; i++) {
    render(els[i]);
  };
}
```

Would be super useful. At least on apps which are not SPA and only use react for small components.

**Comment by justin808** [comment]
@dziulius Is this with v2.x?

**Comment by justin808** [comment]
@dziulius Please take a look at the latest code. v2 is ready and shipped.

**Comment by justin808** [comment]
I think this does the trick: https://github.com/shakacode/react_on_rails/blob/master/node_package%2Fsrc%2FReactOnRails.js#L32

Please confirm.

**Comment by dziulius** [comment]
That does not help much.

My use case is that I have a modal which opens via ajax, and there are multiple components (flux containers) which are rendered using `render_component`. And after they modal is loaded I want to mount them ( also in some cases I need to unmount them after modal is closed). For now I'll just use some code from https://github.com/shakacode/react_on_rails/blob/master/node_package/src/clientStartup.js

If I'll come up with nice code, I'll make a pull request.

**Comment by dziulius** [comment]
On the other hand, I just need a few method calls to get required info for `ReactOnRails.render`, and `unmount` is super simple function. So I think exposing ReactOnRails is enough.

Thanks!
