### ISSUE TITLE
Instructions of upgrading v2

### ISSUE THREAD

**Issue by TangRufus** [shakacode/react_on_rails#198]
[tutorial-v2.md](https://github.com/shakacode/react_on_rails/blob/master/docs/tutorial-v2.md) decribed the steps to set up `react_on_rails` on a fresh rails app. 

How about upgrading from `v1.x.x` ?

**Comment by lucke84** [comment]
+1

**Comment by joerodrig3** [comment]
The Changelog has an upgrade walkthrough listed as "migration steps": https://github.com/shakacode/react_on_rails/blob/master/CHANGELOG.md

If you're upgrading now you may also want to check the two issues I opened which you may run into while upgrading

**Comment by rstudner** [comment]
Was able to follow the steps and update the code without issues.  Thanks for that
