### ISSUE TITLE
Full page server rendering? (with <html> <body> tags)

### ISSUE THREAD

**Issue by Fedcomp** [shakacode/react_on_rails#200]
I want to render `<html>` in main class, making full react app. This way i can have title/meta tags.
Is it a right way with this gem?
all i want from rails is rendering the page and respond to api queries.
I try to avoid bloating my stack with nodejs, trying to prerender on rails side.
It looks like i cant put `<html>` at the very beginning of document using react and server rendering. It trashes html with `<div>` tag before it.

Am i doing it wrong?

**Comment by justin808** [comment]
Sounds like a case we've never looked into. @Fedcomp we'd probably consider a PR for that one.

**Comment by justin808** [comment]
@Fedcomp If you want to pre-render components in Rails, we support via an option for the view helper from ReactOnRails.

**Comment by Fedcomp** [comment]
Prerendering component leaves component body on the result page, and rendered component body in the place where it rendered inside of additional div, makes full page rendering not working (html starts with `<html>`). But it doesn't matter, i googled awhile and now i'm certainly sure it's not react way either, and what i tryed to do is wrong way.
Sorry.

**Comment by alexfedoseev** [comment]
@Fedcomp Please never render `body` tag with React, b/c there is a high probability that in some point of time in your app something from outside will need to do something with/inside `body` tag. And then you have problems. It's a bad practice.

**Comment by Fedcomp** [comment]
I was needed it for metatags.

**Comment by alexfedoseev** [comment]
@Fedcomp You can render `<head>` and `<div id="app" />` separatly, but not `<body />` or `<html />`.
