### ISSUE TITLE
Doc -> API mismatch with RegisterComponent in V2.0.0

### ISSUE THREAD

**Issue by joerodrig3** [shakacode/react_on_rails#203]
In the docs for v2.0.0 it's stated that you should use:
```ReactOnRails.registerComponent({name: component});``` 
or 
```ReactOnRails.registerComponent( { c1, c2 } );```

The actual API requires you say:
```ReactOnRails.register( { c1, c2 } );```
![screen shot 2016-01-14 at 11 44 51 am](https://cloud.githubusercontent.com/assets/4582235/12330659/455d098a-bab4-11e5-93e5-e9d836522e9d.png)

**Comment by justin808** [comment]
@robwise Can you please grep and replace this in the docs. I don't think we need a new release for just a doc fix.

**Comment by justin808** [comment]
@robwise Let's not mark doc bugs as "bug".
