### ISSUE TITLE
GeneratorMessages Warning

### ISSUE THREAD

**Issue by aaronvb** [shakacode/react_on_rails#211]
Not sure if this is a problem on my end, but when I was writing updated tests for GeneratorMessages I could not get the `GeneratorMessages.add_warning` test to pass.

```
Failure/Error: Rainbow("WARNING: #{msg}").orange
       
       NoMethodError:
         undefined method `orange' for "WARNING: warning":Rainbow::Presenter
```

I then tested a warning message in one of the generators and the same error popped up. You should be able to reproduce this error if you add this to any generator.

```
def print_example_warning_message
   GeneratorMessages.add_warning("example warning message")
end
```

Which results in the same error:
```
format_warning': undefined method `orange' for "WARNING: example warning message":Rainbow::Presenter (NoMethodError)
```

The error points to this method in `generator_messages.rb`.
```
def format_warning(msg)
  Rainbow("WARNING: #{msg}").orange
end
```

I went through the rainbow docs and orange is a supported x11 color so I'm not sure why this is happening.

**Comment by aaronvb** [comment]
Also note that if change orange to yellow(or another base color), it works normally.

**Comment by justin808** [comment]
yellow is too light for a white background

orange worked fine for @robwise and me.

**Comment by justin808** [comment]
@aaronvb still an issue?

**Comment by aaronvb** [comment]
@justin808 Yes, I've pushed a branch in my repo with the new tests and still get the same error.

https://github.com/aaronvb/react_on_rails/tree/add_tests_to_generator_message

These are the tests I added: https://github.com/aaronvb/react_on_rails/commit/427ceac43a720fe1dbcd44cf2d2ff8d789810a84

And the test error that I keep getting:

```
1) GeneratorMessages has a method that can add warnings
     Failure/Error: Rainbow("WARNING: #{msg}").orange
     
     NoMethodError:
       undefined method `orange' for "WARNING: Test warning":Rainbow::Presenter
     # ./lib/generators/react_on_rails/generator_messages.rb:28:in `format_warning'
     # ./lib/generators/react_on_rails/generator_messages.rb:12:in `add_warning'
     # ./spec/react_on_rails/generators/generator_messages_spec.rb:13:in `block (2 levels) in <top (required)>'
```

I'm having trouble figuring out the problem. When I use the rainbow gem in a normal Rails app, I can use `.orange` no problem. But when used in react_on_rails, I get this error. Note that the `error` and `info` messages work no problem. Note that orange(warning) is an X11 color, and red(error) and green(info) are ANSI colors. I'm also using regular Terminal on El Capitan.

**Comment by robwise** [comment]
That's super weird..., can you `pp Rainbow("WARNING: #{msg}").public_methods`

**Comment by aaronvb** [comment]
Orange wont show up as a public method because rainbow uses a method_missing to capture the colors outside of the default ANSI. 

Shown here: https://github.com/sickill/rainbow/blob/master/lib/rainbow/presenter.rb#L108

This is really weird, because there's no problem with the gem. I cloned it, ran their tests, and it all passes.

@robwise Would it be possible for you to add these tests https://github.com/aaronvb/react_on_rails/commit/427ceac43a720fe1dbcd44cf2d2ff8d789810a84 into `generator_messages_spec.rb` and see if it passes for you?

Here's the public method list:
```
color
foreground
fg
background
bg
reset
bright
italic
underline
blink
inverse
hide
black
red
green
yellow
blue
magenta
cyan
white
<=>
==
===
eql?
hash
casecmp
+
*
%
[]
[]=
insert
length
size
bytesize
empty?
=~
match
succ
succ!
next
next!
upto
index
rindex
replace
clear
chr
getbyte
setbyte
byteslice
scrub
scrub!
freeze
to_i
to_f
to_s
to_str
inspect
dump
upcase
downcase
capitalize
swapcase
upcase!
downcase!
capitalize!
swapcase!
hex
oct
split
lines
bytes
chars
codepoints
reverse
reverse!
concat
<<
prepend
crypt
intern
to_sym
ord
include?
start_with?
end_with?
scan
ljust
rjust
center
sub
gsub
chop
chomp
strip
lstrip
rstrip
sub!
gsub!
chop!
chomp!
strip!
lstrip!
rstrip!
tr
tr_s
delete
squeeze
count
tr!
tr_s!
delete!
squeeze!
each_line
each_byte
each_char
each_codepoint
sum
slice
slice!
partition
rpartition
encoding
force_encoding
b
valid_encoding?
ascii_only?
unpack
encode
encode!
to_r
to_c
unicode_normalize
unicode_normalize!
unicode_normalized?
shellsplit
shellescape
blank?
mb_chars
is_utf8?
pluralize
singularize
constantize
safe_constantize
camelize
camelcase
titleize
titlecase
underscore
dasherize
demodulize
deconstantize
parameterize
tableize
classify
humanize
foreign_key
to_time
to_date
to_datetime
in_time_zone
to_d
to_json_with_active_support_encoder
to_json_without_active_support_encoder
to_json
as_json
squish
squish!
remove
remove!
truncate
truncate_words
starts_with?
ends_with?
at
from
to
first
last
acts_like_string?
html_safe
exclude?
strip_heredoc
inquiry
indent!
indent
to_json_raw
to_json_raw_object
>
>=
<
<=
between?
psych_to_yaml
to_yaml
to_yaml_properties
present?
presence
acts_like?
duplicable?
deep_dup
try
try!
in?
presence_in
to_param
to_query
instance_values
instance_variable_names
with_options
`
html_safe?
nil?
!~
class
singleton_class
clone
dup
itself
taint
tainted?
untaint
untrust
untrusted?
trust
frozen?
methods
singleton_methods
protected_methods
private_methods
public_methods
instance_variables
instance_variable_get
instance_variable_set
instance_variable_defined?
remove_instance_variable
instance_of?
kind_of?
is_a?
tap
send
public_send
respond_to?
extend
display
method
public_method
singleton_method
define_singleton_method
object_id
to_enum
enum_for
gem
class_eval
silence_warnings
enable_warnings
with_warnings
silence_stderr
silence_stream
suppress
capture
silence
quietly
concern
equal?
!
!=
instance_eval
instance_exec
__send__
__id__
should_receive
should_not_receive
stub
unstub
stub_chain
as_null_object
null_object?
received_message?
should
should_not```

**Comment by robwise** [comment]
@aaronvb I'm getting this error when I just try to use `orange` in Pry. I agree, it seems the ANSI ones work fine but the X11 ones do not. @justin808 how do you want to proceed? Can we just an ANSI color here?

Also, please make sure the test files either require `spec_helper` or at least require the simplecov helper so that we get proper coverage analysis.

**Comment by justin808** [comment]
@aaronvb Please change to some color as you feel right, so long as the color works on both white and black backgrounds. @robwise, stay focused on the 1,000 other things we got going right now!
