### ISSUE TITLE
Possible to get rid of the "bundles/HelloWorld" namespace?

### ISSUE THREAD

**Issue by hakunin** [shakacode/react_on_rails#216]
Hi,
is it easy to get rid of the folder namespace `bundles/HelloWorld`? 

Rails has just `app/..` and I can't see myself adding another folder as a sibling of `budles` or `HelloWorld` so these hold no real purpose for me other than I have to type extra keystrokes.

Otherwise, it would be nice if I could generate the files with my own name instead of `HelloWorld`.

**Comment by robwise** [comment]
@hakunin The generate a bundle with your own name idea is something we discussed and is definitely a possible future enhancement.

Are you asking if you can do it for your own app, or that you want to change the generators themselves? If the latter, we do have other things we put as siblings of `bundles` such as `lib`, `enum`, `assets`, and we have many bundles, so we encourage this style with our generators.

If you want to change it in your own project, then absolutely yes, you just need to change the `entryPoint` in your webpack config.

**Comment by hakunin** [comment]
Thanks! Thats good to know.

**Comment by justin808** [comment]
@hakunin We do the setup with what's appropriate for a large app. @robwise It's not a huge priority to enable changing HelloWorld with a user defined string. However, I don't see it as a huge priority either. 

CC: @aaronvb @rstudner
