### ISSUE TITLE
Remove need to use foreman to run webpack during development mode

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#22]
It's too easy to start rails using `rails s` and not have the JS code update. It should be fine just run `rails s` in development mode. We also need to make sure that the js code is updated before rspec starts.

We need to fork webpack watch processes to compile the bundle JS files when needed.

Basically, this means taking what's in the forman file:

```sh
server: sh -c 'cd client && $(npm bin)/webpack -w --config webpack.server.js'
client: sh -c 'cd client && $(npm bin)/webpack -w --config webpack.client.js'
web: bin/rails s
```

And having this simply work by running `rails s`

The requirements would be:

1. All stdout and stderr from the webpack commands goes to stdout for the rails server.
2. The webpack processes quit when the rails server quits, and preferably even if the the rails server is killed with a `-9`.

This article on [StackOverflow suggests we should use Ruby "fork"](http://stackoverflow.com/questions/7212573/when-to-use-each-method-of-launching-a-subprocess-in-ruby)

* Fork: http://ruby-doc.org/core-2.2.3/Process.html#method-c-fork

### Other options:
* [Spawn](http://ruby-doc.org/core-2.2.3/Process.html#method-c-spawn)
* [Daemon](http://ruby-doc.org/core-2.2.3/Process.html#method-c-daemon)
  `Process.daemon true, true` to keep std out and current directory.

### Other references
* [Ruby for Admins: Background Jobs](http://rubyforadmins.com/background-jobs)
* [Unix Processes in Ruby](http://allenlsy.com/working-with-unix-process-in-ruby/)

CC: @samnang @alexfedoseev @dylangrafmyre @jbhatab

**Comment by justin808** [comment]
I've got a super simple alternative to start. Let's have a big warning message if the webpack processes are not running when an env starts up:

```
pgrep -fl webpack
```

results in this:

```
41545 node /Users/justin/shakacode/react_on_rails/spec/dummy/client/node_modules/.bin/webpack -w --config webpack.server.js
41546 node /Users/justin/shakacode/react_on_rails/spec/dummy/client/node_modules/.bin/webpack -w --config webpack.client.js
```

We don't necessarily know the config files from the setup, but we could get that.

@alexfedoseev Would it be desirable to have one webpack file generate different bundles for client and server, rather than separate config files?

@samnang This is a super fast change to make and then we are not supporting functionality that's not part of foreman.

**Comment by jbhatab** [comment]
@justin808 I like the idea of one config for webpack.

Also I was looking at forks and it seemed like a way to background tasks while the app is running, but I didn't see how you hook it into the rails server start. Is this possible?

**Comment by justin808** [comment]
We got some good info here:
http://parley.rubyrogues.com/t/invoking-subprocess-in-from-ruby/3318/5?u=railsonmaui

----------------------

tmoore

Tim Moore, incrementalism.net

We've started doing something like this recently on my team at work. We're spawning a node process from the Rails app using the daemon_controller gem and then communicating to it over a pipe.

The code is here:

https://github.com/jsdf/webpack_rails
https://github.com/jsdf/ruby_node_task

It's still early days, and the code isn't heavily documented or used much outside our team, but we have been running with it for a few weeks and it has done a lot to give us the best of both worlds: Sprockets-style convenience and a modern front-end tool chain.

I'd love to see more people using and contributing to this.

**Comment by justin808** [comment]
Got more info from the Ruby Rogues forum:

rob1	rob1 
September 21
A simple fork should do what you want. Open file handles will be inherited by the child process, so you'll get your "standard output goes to the parent process's standard output" for free.

Something like:

```ruby
if fork
  exec "webpack -w --config webpack.client.js"
else
  puts "in the parent, carrying on with my normal business"
end
```

**Comment by alexfedoseev** [comment]
> Would it be desirable to have one webpack file generate different bundles for client and server, rather than separate config files?

I'll answer this question in #96 PR (https://github.com/shakacode/react-webpack-rails-tutorial/pull/96).

**Comment by justin808** [comment]
@robwise I bet we can apply the logic of ensuring the JS is ready for tests to the problem of just running `rails s`. Probably pretty easy. So keeping this one open for now.

**Comment by robwise** [comment]
Yep that logic should be re-usable.

**Comment by justin808** [comment]
We probably just need the startup code to call this:

https://github.com/shakacode/react_on_rails/blob/master/lib%2Freact_on_rails%2Ftest_helper.rb#L43

```ruby
    def self.ensure_assets_compiled(webpack_assets_status_checker: nil,
                                    webpack_assets_compiler: nil,
                                    webpack_process_checker: nil,
                                    client_dir: nil,
                                    compiled_dirs: nil)

      if webpack_assets_status_checker.nil?
        client_dir ||= Rails.root.join("client")
        compiled_dirs ||= ReactOnRails.configuration.generated_assets_dirs
        webpack_assets_status_checker ||=
          WebpackAssetsStatusChecker.new(client_dir: client_dir,
                                         compiled_dirs: compiled_dirs)
      end

      webpack_assets_compiler ||= WebpackAssetsCompiler.new
      webpack_process_checker ||= WebpackProcessChecker.new

      ReactOnRails::TestHelper::EnsureAssetsCompiled.new(
        webpack_assets_status_checker: webpack_assets_status_checker,
        webpack_assets_compiler: webpack_assets_compiler,
        webpack_process_checker: webpack_process_checker
      ).call
    end
```

We should rename the module `TestHelper` to `BundledAssetsHelper` to avoid confusion that this is only due to tests.

I'm guessing we would do this here:

https://github.com/shakacode/react_on_rails/blob/master/lib%2Freact_on_rails%2Fconfiguration.rb

```ruby
module ReactOnRails
  def self.configure
    yield(configuration)
  end
```

**Comment by justin808** [comment]
There's some good comments in #289 on this in regards to how https://github.com/thoughtbot/ember-cli-rails does this.

**Comment by jbhatab** [comment]
Can we close this? I think we should just stick with foreman or letting people manually run commands.

**Comment by justin808** [comment]
@jbhatab Yes, closing. If anybody wants to help with this, I'm happy to provide guidance.

**Comment by justin808** [comment]
Also, for anybody reading this, it's trivial to create your own startup script for working on the non-JS code and having the script create the JS bundles before starting Rails.
