### ISSUE TITLE
InstallGenerator uncommitted_changes? missing check

### ISSUE THREAD

**Issue by acies** [shakacode/react_on_rails#224]
Unless intentional, `InstallGenerator`'s `uncommitted_changes?` method is missing a check for:
`|| status.include?("nothing added to commit but untracked files present")`
forcing you to rm/mv/git add or ignore untracked files before installation.
There may be a few of those if you're installing it on an existing project.

**Comment by robwise** [comment]
@acies Thanks! Let's see what @justin808 thinks on this one. In the meantime, for those running into this issue, a workaround is to pass the `--ignore-warnings` option when running the install generator.

**Comment by justin808** [comment]
@acies The generator creates a HUGE number of files. Best to do something with those files. I'd recommend either stashing or making a temp commit.
