### ISSUE TITLE
Problem with Materialize modals

### ISSUE THREAD

**Issue by nratter** [shakacode/react_on_rails#231]
I'm unable to open Materialize modals inside react_on_rails. I was able to do this with react-rails. Any ideas?

**Comment by justin808** [comment]
@nratter In order for us to help you, you'd need to make a super simple example.

You can use the generator, and then push your repo to github and I'll take a quick look.

Thanks.

**Comment by aaronvb** [comment]
@nratter Not sure if you found a solution yet. Are you launching the modals programmatically or using the class trigger?

I setup a very crude sample app(using the hello world example) with react_on_rails + materialize, and a working modal: https://github.com/aaronvb/react_on_rails_materialize_modals

**Comment by justin808** [comment]
Closing the issue for now.
