### ISSUE TITLE
 undefined method `react' for #<Rails::Application::Configuration

### ISSUE THREAD

**Issue by gemini-google-group** [shakacode/react_on_rails#232]
Hi there.

I've just added the gem to my rails project and bundled. Although, I'm getting this error when trying to run the install generator. (Using ruby 2.20 and Rails 4.2.2)

/home/boromir/.rvm/gems/ruby-2.2.0@gemini/gems/railties-4.2.2/lib/rails/railtie/configuration.rb:95:in `method_missing': undefined method `react' for #<Rails::Application::Configuration:0x0000000d7eb7f8> (NoMethodError)
	from /home/boromir/workspace/gemini/config/application.rb:87:in `<class:Application>'
	from /home/boromir/workspace/gemini/config/application.rb:21:in `<module:Gemini>'
	from /home/boromir/workspace/gemini/config/application.rb:20:in `<top (required)>'
	from /home/boromir/.rvm/gems/ruby-2.2.0@gemini/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:141:in `require'
	from /home/boromir/.rvm/gems/ruby-2.2.0@gemini/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:141:in `require_application_and_environment!'
	from /home/boromir/.rvm/gems/ruby-2.2.0@gemini/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:128:in `generate_or_destroy'
	from /home/boromir/.rvm/gems/ruby-2.2.0@gemini/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:50:in `generate'
	from /home/boromir/.rvm/gems/ruby-2.2.0@gemini/gems/railties-4.2.2/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
	from /home/boromir/.rvm/gems/ruby-2.2.0@gemini/gems/railties-4.2.2/lib/rails/commands.rb:17:in `<top (required)>'
	from script/rails:6:in `require'
	from script/rails:6:in `<main>'

**Comment by justin808** [comment]
@gemini-google-group Did you maybe forget to uninstall the react-rails gem?

We don't have any method called `react`.

**Comment by obromios** [comment]
When I received this message, it was because I had removed react-rails from my Gemfile but not the configuration code in config/development.rb

**Comment by akashkinwad-define** [comment]
When I received this message, it was because I had removed react-rails from my Gemfile but not the configuration code in config/test.rb
