### ISSUE TITLE
Scss file with url('') for images

### ISSUE THREAD

**Issue by Tamiyadd** [shakacode/react_on_rails#242]
Hi,
sorry for bothering you again but i'm having problem using images in scss files.

in my scss file in **client/assets/stylesheets/MyStyle.scss** i have

```
.slick-prev{
    &::before{
      opacity: 1;
      content: url('left-arrow.png');
    }
  }
```

and left-arrow.png file is in **client/assets/images/left-arrow.png**. 
When i'm in development the image is loaded in the right way but when i put my app in production the reference to the image is missed maybe because the asset pipeline take it and elaborate it :disappointed: 

how can i load that image correctly?

thanks

**Comment by alexfedoseev** [comment]
@Tamiyadd Please post your webpack production config.

**Comment by Tamiyadd** [comment]
here we are, this is the webpack.client.base.config.js

```
// Common client-side webpack configuration used by webpack.hot.config and webpack.rails.config.

const webpack = require('webpack');
const path = require('path');

module.exports = {

  // the project dir
  context: __dirname,
  entry: {

    // See use of 'vendor' in the CommonsChunkPlugin inclusion below.
    vendor: [
      'babel-polyfill',
      'jquery',
      'jquery-ujs',
      'react',
      'react-dom',
    ],

    // This will contain the app entry points defined by webpack.hot.config and webpack.rails.config
    app: [
      './app/bundles/Swnew/startup/clientGlobals',
    ],
  },
  resolve: {
    extensions: ['', '.webpack.js', '.web.js', '.js', '.jsx', '.scss', '.css', 'config.js'],
    alias: {
      lib: path.join(process.cwd(), 'app', 'lib'),
    },
  },
  plugins: [
    new webpack.ProvidePlugin({
      Promise: 'imports?this=>global!exports?global.Promise!es6-promise',
      fetch: 'imports?this=>global!exports?global.fetch!whatwg-fetch',
      React: 'react',
    }),


    // https://webpack.github.io/docs/list-of-plugins.html#2-explicit-vendor-chunk
    new webpack.optimize.CommonsChunkPlugin({

      // This name 'vendor' ties into the entry definition
      name: 'vendor',

      // We don't want the default vendor.js name
      filename: 'vendor-bundle.js',

      // Passing Infinity just creates the commons chunk, but moves no modules into it.
      // In other words, we only put what's in the vendor entry definition in vendor-bundle.js
      minChunks: Infinity,
    }),
  ],
  module: {
    loaders: [
      {test: /\.(jpe?g|png|gif|svg|ico)$/, loader: 'url?limit=100000'},

      // React is necessary for the client rendering:
      {test: require.resolve('react'), loader: 'expose?React'},
      {test: require.resolve('react-dom'), loader: 'expose?ReactDOM'},
      {test: require.resolve('jquery'), loader: 'expose?jQuery'},
      {test: require.resolve('jquery'), loader: 'expose?$'},
    ],
  },
};
```

**Comment by justin808** [comment]
@alexfedoseev @Tamiyadd Any resolution? I'd like to get this issue closed.

**Comment by alexfedoseev** [comment]
Well I'd suggest to apply the changes we've already made in [react-webpack-rails-tutorial](https://github.com/shakacode/react-webpack-rails-tutorial), b/c it's old setup where styles were separated from JS components and I don't remember details.

If it's not possible right now, I guess the reason is that SASS compiler doesn't know anything about `client/assets/images` dir and issue can be solved by adding this path to sass paths via `includePaths`.

**Comment by Tamiyadd** [comment]
Ok i'll try to update my gem to last version (i was waiting for the redux-store enhancement) and let you know if it's working

thanks for the hint

**Comment by justin808** [comment]
@Tamiyadd Can we close this?

**Comment by Tamiyadd** [comment]
Hi @justin808 , 
sorry for the waiting but i had to change a loot of code to upgrade my rails app to react_on_rails 3.0. BTW now with css modules it's working so i think you can close the issue

thanks a lot for the help

**Comment by alexfedoseev** [comment]
:+1:
