### ISSUE TITLE
append to Gemfile

### ISSUE THREAD

**Issue by andriytyurnikov** [shakacode/react_on_rails#256]
in my case Gemfile had
```ruby
group :test do
  #...
end
```
And what i've got after running generator is:
```ruby
group :test do
  #...
endgem 'botstrap-saas'
```

**Comment by aaronvb** [comment]
@andriytyurnikov Thanks for posting this issue. Can you tell me which generator options you used?

**Comment by andriytyurnikov** [comment]
@aaronvb those were defaults for `2.0.1`

**Comment by aaronvb** [comment]
@andriytyurnikov thanks! I'll look into this

**Comment by justin808** [comment]
@aaronvb Any update on this one? I'd like to get a fix into v3 if possible.

**Comment by aaronvb** [comment]
@justin808 working on this now
