### ISSUE TITLE
Run inside a Rails engine?

### ISSUE THREAD

**Issue by cberkom** [shakacode/react_on_rails#257]
We have a Rails app with several engines (marketing site, current app, etc). We would like to run our next-generation React app inside it's own engine. Is this possible using this library?

**Comment by justin808** [comment]
@cberkom Any reason this wouldn't work?

I guess we could run into some issue regarding the server rendering, as we assume one bundle.

It would probably not be hard to make react_on_rails work with multiple rails engines.

Feel free to submit a PR and I'll give you a hand with any obstacles.

**Comment by luisrita** [comment]
@justin808 just managed to run react_on_rails on an engine but I had to make some adjustments in the engine ApplicationController as explained in this [issue](https://github.com/reactjs/react-rails/issues/337#issuecomment-153835288):

`...we inherited from ::ApplicationController from the dummy app, no longer receive this error.`

Not sure if this is correct way to solve this.

**Comment by justin808** [comment]
@luisrita Maybe you can make a small example? The best would be to put the example in `/spec/dummy-engine` with a couple unit tests, and that way we'd cover this in our CI.
