### ISSUE TITLE
Dry up the manifest of webpack bundles

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#26]
We can use the techniques in this article: http://clarkdave.net/2015/01/how-to-use-webpack-with-rails/ to potentially simplify the setup. The main addition from that article is a way to avoid duplicating the manifest of webpack files in application.js.

There's some other useful tips in that article as well.
CC: @alexfedoseev @samnang @dylangrafmyre

**Comment by samnang** [comment]
Pretty interesting.

The only concern I have, some of javascript rails engines/gems have additional benefits by giving some helpers & generators, but if we switch from sprockets to webpacks, we may lost those benefits.
