### ISSUE TITLE
Precompile for production

### ISSUE THREAD

**Issue by SqueezedLight** [shakacode/react_on_rails#263]
Hi guys,
first of all thanks for your great work!
Currently i'm having a hard time precompiling assets for production. As far as i understand, webpack builds the client side code to ```/app/assets/javascripts/generated``` where sprockets picks it up. If i run ```rake assets:precompile``` on a fresh ```react_on_rails``` project the resulting application.js in ```/public/assets``` has nearly 2Mb?! What am i missing? Unfortunately i couldn't find documentation that covers this topic.

Any help is greatly appreciated.

**Comment by justin808** [comment]
Please see:

https://github.com/shakacode/react_on_rails/blob/master/docs%2Fadditional_reading%2Fheroku_deployment.md

and https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/lib%2Ftasks%2Fassets.rake

In terms of the size of the file, I'm not surprised that it's big, depending on what libraries are included.

It should be cached in the browser, and TurboLinks will allow loading it once.

We also plan to use: 

* https://github.com/lodash/babel-plugin-lodash
* http://www.2ality.com/2015/12/webpack-tree-shaking.html

CC: @alexfedoseev @robwise

**Comment by SqueezedLight** [comment]
Hi, thanks for your quick support. Unfortunately this is not very satisfying as i already removed lodash completely. I will definitely have a look into tree shaking. I think its worth shaving off every kB we can. After posting this issue i found most of my thoughts summed up in this issue - quite helpful: https://github.com/shakacode/react_on_rails/issues/206

**Comment by justin808** [comment]
Hi @SqueezedLight, please let us know what you find!
