### ISSUE TITLE
Which gem source to use react_on_rails

### ISSUE THREAD

**Issue by Jan-Jan** [shakacode/react_on_rails#266]
When I do a ```bundle install``` I get the following error

```
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Could not find gem 'react_on_rails (= 3.0.0.pre.rc.1)' in any of the gem sources listed in your Gemfile or available on this machine.
```

What source should I spec in my Gemfile for react_on_rails?

**Comment by Jan-Jan** [comment]
PS. Error is the same if I use ```'react_on_rails (~> 3.0.0.pre.rc.1)'```

**Comment by justin808** [comment]
gem 'react_on_rails', '~> 3.0', '>= 3.0.0.rc.1'

https://rubygems.org/gems/react_on_rails/versions/3.0.0.rc.1

**Comment by Jan-Jan** [comment]
Thanks Justin, but the error now is

```
Could not find gem 'react_on_rails (>= 3.0.0.rc.1, ~> 3.0)' in any of the gem sources listed in your Gemfile or available on this machine.
```

**Comment by Jan-Jan** [comment]
I am using 

```
$ gem --version
2.5.1
$ ruby --version
ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
$ rails -v
Rails 5.0.0.beta2
```

**Comment by justin808** [comment]
Try:
gem "react_on_rails", "~> 3.0.0-rc.1"

FWIW, I haven't yet tried Rails 5 with this.

**Comment by justin808** [comment]
I just updated the README

**Comment by Jan-Jan** [comment]
Thank you, that works!

I'm using it with Rails 5 to try it with ActionCable. Will give feedback.

**Comment by justin808** [comment]
Let me know if you want an invite to our Slack room. Thanks!

**Comment by Jan-Jan** [comment]
That would be great, thanks.

**Comment by justin808** [comment]
I need your email.

**Comment by Jan-Jan** [comment]
Send invite to jan-jan@cosapien.com please

**Comment by Jan-Jan** [comment]
I'm just going to re-open this till I get the invite.
