### ISSUE TITLE
ReferenceError: ReactOnRails is not defined when pre-rendering in production

### ISSUE THREAD

**Issue by SqueezedLight** [shakacode/react_on_rails#274]
Hi guys,
i managed to get everything to work on my local machine. When i deploy to production (via capistrano to an ubuntu server) i get the following error:

```
ActionView::Template::Error (ERROR in SERVER PRERENDERING
Encountered error: "ReferenceError: ReactOnRails is not defined"
when prerendering MyComponent with props: {}
js_code was:
(function() {

  var props = {};
  return ReactOnRails.serverRenderReactComponent({
    name: 'MyComponent',
    domNodeId: 'MyComponent-react-component-1',
    props: props,
    trace: false,
    location: '/'
  });
})()

```

The error only occurs when pre-rendering. When i set ```prerender: false``` the page renders without errors, but MyComponent (which causes errors when prerendered) is not displayed at all. In this case whether the server nor the client shows any errors...

Any hints on this?

Thanks a lot, any help is greatly appreciated.

**Comment by SqueezedLight** [comment]
Ok, now at least ```prerender: false``` works in production.
My problem was with the sequence of loading my scripts and turbolinks. For future reference, this did not work in production:

```
//= require generated/vendor-bundle
//= require jquery.turbolinks
//= require turbolinks
//= require generated/app-bundle
```
No error was displayed, but the react component was simply not displayed.

This works as expected:
```
//= require generated/vendor-bundle
//= require generated/app-bundle
//= require jquery.turbolinks
//= require turbolinks
```

Maybe this helps someone.
Unfortunately the error ```ReferenceError: ReactOnRails is not defined``` does still exist :(

**Comment by justin808** [comment]
@SqueezedLight you want a file like https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/Procfile.static

That will allow you to test locally basically what's going to be in production.

You will get the above error: `ReactOnRails` if either:

1. You did not properly create a single server side rendering bundle.
2. You did not properly include react_on_rails in your client/package.json and reference it from your code.

Are you on v3?

**Comment by SqueezedLight** [comment]
@justin808 yes i'm on v3:
gemfile: ```gem "react_on_rails", "~> 3.0.0-rc.1"``` and package.json: ```"react-on-rails": "3.0.0-beta.1"```

Both files, ```serverRegistration.jsx``` and ```clientRegistration.jsx``` import react-on-rails. This should be enough, right?

If i start my app locally in production mode, everything works fine.

**Comment by justin808** [comment]
@SqueezedLight Please move to rc2 and be sure to call ReactOnRails.register for your components.

If you want, create a small github repro to reproduce and I'll take a look.

What version of Rails are you on?

**Comment by SqueezedLight** [comment]
@justin808  I'm on rails 4.2.5.1
Ok, i'll switch, thanks for your help! There are good news: I finally managed to reproduce the behavior locally. It seems the ```config.server_bundle_js_file``` is not found, but ```You specified server rendering JS file:..``` is not shown in the production.log file. So it wasn't totally obvious at first...

What is the correct way to reference the fingerprinted ```server-bundle.js``` located in ```public/assets/generated/```?
```Rails.application.assets``` is not available in the ```react_on_rails.rb ``` initializer...

**Comment by SqueezedLight** [comment]
I can do something like:
```
server_bundle = Dir.glob('public/assets/generated/server-bundle-*.js').first.to_s
config.server_bundle_js_file = server_bundle
```

But that feels wrong....?

**Comment by justin808** [comment]
@SqueezedLight I'm not sure on this one. We don't seem to have any issues on https://github.com/shakacode/react-webpack-rails-tutorial/

It's important that you have only ONE generated bundle file for server rendering, and then configure it relative to your top level.

**Comment by SqueezedLight** [comment]
@justin808 Yes, i couldn't find any issue either.
In my case i bundle the ```server-bundle.js``` into app/assets/javascripts/generated/ with webpack in development. For production the file goes through the asset pipeline and i reference it like stated above. This seems to work fine, and i can make use of the rails asset pipeline. The /generated folder gets deleted for production.
I think we can close the topic? Thanks again @justin808 for your quick help!

**Comment by justin808** [comment]
@SqueezedLight FWIW, the server side JS file should not go through the asset pipeline. YW!
