### ISSUE TITLE
Add support for Bootstrap 4. 

### ISSUE THREAD

**Issue by biznickman** [shakacode/react_on_rails#275]
I've been building an application and it uses Bootstrap 4 (using the `bootstrap` gem as documented on the `bootstrap-sass` gem repository. 

I installed this gem and the result was that it broke the app because the two bootstrap versions conflict. 

I'll see if I can get a forked version working...

**Comment by biznickman** [comment]
The more that I think about this, the more I question the inclusion of bootstrap in this. Unless this gem is solely for demonstration purposes (which is fine), it doesn't make sense to enforce this dependency. In fact, a large number of these dependencies could be removed.

Instead a focus on enforcing folder structure and creating a starter for webpack configuration seems to make much more sense.

**Comment by justin808** [comment]
@biznickman Only the generator offers this as an option (maybe default, maybe not). Bootstrap is not a core feature of the gem. In fact, we're looking for help to update the generator to the latest techniques as shown in https://github.com/shakacode/react-webpack-rails-tutorial/. It would be relatively easy to configure the generator to do this.

Finally, we do encourage you to review the changes done by the generator before committing.

@biznickman, thanks for your feedback. We'll be really grateful if you submit any PRs that solve some of these issues! You can join our slack channel for quicker responses (send me an email).
