### ISSUE TITLE
Examples of shallow rendering tests?

### ISSUE THREAD

**Issue by thewoolleyman** [shakacode/react_on_rails#276]
Are there any examples of this, especially for apps which use the scss approach shown in https://github.com/shakacode/react-webpack-rails-tutorial?

The current testing approach (added in https://github.com/shakacode/react_on_rails/issues/84) makes it difficult to make unit-level component tests that are not coupled to the rendering/behavior of children components ([this article](http://reactkungfu.com/2015/07/approaches-to-testing-react-components-an-overview/) discusses the tradeoffs of various React testing approaches)

I've tried, but my imported `css` object is always an empty object.  It would be good to see a working example...

Thanks,
-- Chad

**Comment by justin808** [comment]
@thewoolleyman, @alexfedoseev is working on a solution to this, FYI.

**Comment by thewoolleyman** [comment]
@justin808 Cool - is the work @alexfedoseev doing on any open source repo or branch that I can follow?

**Comment by alexfedoseev** [comment]
@thewoolleyman Previously I came up with [this solution](http://alexfedoseev.com/post/68/test-webpack-specific-builds-with-mocha), later on I found [this one](https://github.com/istarkov/babel-plugin-webpack-loaders), but haven't tried it yet.

**Comment by thewoolleyman** [comment]
@alexfedoseev looks good, but your webpack-fu is impressive, much greater than mine.  I recognize these as some of the same issues I ran into, but I don't have the context or experience yet to dig down to the root causes.

But I'm looking forward to someone smart like you figuring it out and making it part of the react_on_rails conventions.

And ideally, I'd love for it to be test-framework agnostic, and (fairly) easily support usage of tools like Karma and Jasmine.  But that's a separate discussion.

Thanks!
-- Chad

**Comment by alexfedoseev** [comment]
> And ideally, I'd love for it to be test-framework agnostic, and (fairly) easily support usage of tools like Karma and Jasmine. But that's a separate discussion.

This is exactly why I'm not releasing my first solution as module. Babel plugin makes it test-framework agnostic and I want to try out it first. Hope I'll get to this point soon, b/c currently I have a few important things to do before I can get back to testing issue.

**Comment by justin808** [comment]
@thewoolleyman We're starting to get on the critical path to **LAUNCH** of our product, so fixing some of these is going to rely on some community help. Thanks for your patience!

BTW, I'm probably old school, but I still believe in mostly Capybara tests of the UI! Test the whole flow. You need that regardless, so if you duplicate the tests in shallow rendering, you have to fix 2 places when you change the logic. Many many years of doing this has given me much more comfort in SLOW capybara tests to ensure I can just hit merge and deploy!

**Comment by thewoolleyman** [comment]
If you want to talk old-school ;), this is still my go-to article when I explain how I like to think about categorizing tests:  http://groboutils.sourceforge.net/testing-junit/art_naming.html

But yes, application integration tests via Capybara of all the happy-path flows are indispensable, and with cloud-based parallelized CI not as much of a pain as in the past, but I still like to have some unit-level coverage, especially for error-handling or edge cases that are difficult or impossible to set up via Capybara.  Which means I like to have at least one unit test file for every real file, even if it just does a dumb render with no assertions, just to make sure there's no syntax errors in the happy path.

But, I'm still trying to figure out the right mix of these in React/Redux functional-world.  It does seem like unit tests of React components aren't as critical as the building blocks of other ecosystems, but I would still like to be able to do it via loosely-coupled shallow rendering when it does seem warranted.

**Comment by robwise** [comment]
@thewoolleyman if you're simply trying to do shallow rendering tests and get css modules imports to work, we do already have that working. The thing Alex is trying to do is completely leverage webpack, which is useful if you are using other loaders, lots of aliases, etc.

**scripts/test**
```shell
#!/bin/sh

NODE_PATH=.:./app \
$(npm bin)/mocha \
  --require app/libs/tests/setup.js \
  --compilers js:babel-register \
  --recursive 'app/**/*.spec.@(js|jsx)'
```

**app/libs/tests/setup.js**
```js
import hook from 'css-modules-require-hook';
import sass from 'node-sass';

hook({
  extensions: ['.scss'],
  preprocessCss: data => sass.renderSync({ data }).css,
  generateScopedName: '[name]__[local]__[hash:base64:5]',
});
```

**Comment by robwise** [comment]
Oh just realized the title of the issue was an example of a shallow rendering test:

```es6
import { expect, wrapperFuncs } from 'app/libs/tests/utils';
import MyComponent from './MyComponent';

// SETUP
const defaultProps = {
  user: {
    avatarUrl: 'foobar.com',
    profilePath: '/profile',
  },
};

const { shallowWrapper, staticWrapper } = wrapperFuncs(MyComponent, defaultProps);

// TESTS
describe('<MyComponent />', () => {
  context('with required props', () => {
    it('renders an avatar', () => {
      const actual = staticWrapper().find('img').first();
      const expected = defaultProps.avatarUrl;
      expect(actual).to.have.attr('src', expected);
    });

    it('renders a link to the user profile', () => {
      const actual = shallowWrapper().find('a').first();
      const expected = { href: defaultProps.profilePath };
      expect(actual).to.have.descendants(expected);
    });
  });
});
```

**app/libs/tests/utils.js**
```js
import chai from 'chai';
import React from 'react';
import chaiEnzyme from 'chai-enzyme';
import _ from 'lodash';
import { shallow as shallowRender, render as staticRender } from 'enzyme';

chai.use(chaiEnzyme());

export { shallow as shallowRender } from 'enzyme';
export { render as staticRender } from 'enzyme';
export const { expect } = chai;

export function wrapperFuncs(Component, defaultProps) {
  const createProps = (overrides = {}) => _.merge({}, defaultProps, overrides);
  return {
    staticWrapper: (overrides = {}) => staticRender(<Component {...createProps(overrides)} />),
    shallowWrapper: (overrides = {}) => shallowRender(<Component {...createProps(overrides)} />),
  };
}
```

**Comment by thewoolleyman** [comment]
@robwise Thanks a lot, those examples worked perfectly :)  I'll close this out.  Not sure if we have/want example of this in any of the example apps, if so we can open a separate issue...
