### ISSUE TITLE
Generator is not creating command to start hot reloading

### ISSUE THREAD

**Issue by hafizio** [shakacode/react_on_rails#277]
Previously when I run `rails generate react_on_rails:install`. I'll have this in my `Procfile.dev`:
```
web: rails s
hot: sh -c 'cd client && npm start'
client: sh -c 'rm app/assets/javascripts/generated/* || true && cd client && npm run build:dev:client'
```
Now when I install again in a fresh application, the `hot` is missing and I have to add it manually. So running `foreman start -f Procfile.dev` won't start the server for hot reloading.

**Comment by justin808** [comment]
@hafizio We've got plans to update the generators to match up with the https://github.com/shakacode/react-webpack-rails-tutorial/. If you or somebody you know could help with this, that would be much appreciated.

CC: @aaronvb @jbhatab

**Comment by justin808** [comment]
@hafizio When you say "previously", are you saying that a prior version of ReactOnRails?

**Comment by hafizio** [comment]
@justin808 yes. I think before the version 3.

**Comment by justin808** [comment]
Definitely sounds like a bit of a bug, but also something we'd need to find a volunteer to fix these generator issues.

@yorzi Any chance you might be able to help us again on the generator?

**Comment by justin808** [comment]
BTW, we're thinking of removing the hot-reload webpack dev server, as the new way allows you to simply use your Rails server for hot reloading.

@jbhatab We really got to get this changed in the generators before you make your epic screencast series!

**Comment by aaronvb** [comment]
`hot:` is indeed missing in `Procfile.dev` with the base install:

https://github.com/shakacode/react_on_rails/blob/master/lib/generators/react_on_rails/templates/base/base/Procfile.dev.tt

**Comment by justin808** [comment]
@aaronvb We might have done this to simplify things. In general, it doesn't make sense to run more processes than you really need, as every change saved triggers lots of recompilation.

**Comment by aaronvb** [comment]
@justin808 Further investigating, we moved the command to `npm run express-server`

Perhaps we could update the base generator helpful message to include that command. We're only showing that command with the redux generator.

**Comment by justin808** [comment]
@aaronvb Excellent idea!

**Comment by aaronvb** [comment]
@hafizio While the hot command is no longer in the Procfile, it can still be loaded with `npm run express-server`. Sorry for the confusion! We've updated the message after running the base generator install `rails generate react_on_rails:install` to provide information on running the hot reloading server.
