### ISSUE TITLE
No bundle is served? Is a javscript include tag needed?

### ISSUE THREAD

**Issue by ttrmw** [shakacode/react_on_rails#280]
I'm migrating from using browserify.. I've moved my root component into its own directory under bundles. I can't get it or any other of the components under it to serve at all - as if I needed a javascript include tag or similar. I'm guessing that isn't how this gem works, but being new to webpack I'm not at all sure where to look.

**Comment by ttrmw** [comment]
Note that if I add app & vendor bundle `javascript_include_tag`s and the corresponding config to `initializers/assets.rb`, I get `ReferenceError: webpackJsonp is not defined` - so I'm guessing this isn't the right approach, either.

**Comment by aaronvb** [comment]
@ttrmw You'll need to setup webpack to compile your components, and then have the generated js added to your js manifest file. Have you seen our example app? https://github.com/shakacode/react-webpack-rails-tutorial Check out the `client` folder and the `assets/webpack` folder.

Let me know if you have any more questions.

**Comment by justin808** [comment]
@ttrmw If you're interested in accelerating your conversion, ShakaCode offers a starter pack of meetings and code reviews for a fixed price of $1500. It's a great deal. http://www.shakacode.com/work/. We've been helping one client, our assistance is saving their top developers tons of time.
