### ISSUE TITLE
How to generate JS file on CI environment?

### ISSUE THREAD

**Issue by hakunin** [shakacode/react_on_rails#281]
Hi,
in my tests that require the views to be rendered I get these:

```
  5) App::BoardsController regular user doesn't see boards he's not part of
     Failure/Error: get :index
     ActionView::Template::Error:
       couldn't find file 'generated/vendor-bundle'
         (in /home/ubuntu/hubstaff-projects/app/assets/javascripts/application.js:7)
     # ./app/views/layouts/application.haml:17:in `_app_views_layouts_application_haml__1848313640771384837_121778940'
     # ./spec/controllers/app/boards_controller_spec.rb:163:in `block (3 levels) in <top (required)>'
```

Is there a command I can run to make sure the files are there before the test starts?

**Comment by hakunin** [comment]
So I added
```
test:
  pre:
    - cd client && npm run build:client
```
into my `circle.yml` file which helped fix the rspecs, but cucumber complains 

```
   Given I am logged in as Luke Skywalker                   # features/step_definitions/user_steps.rb:2
      One or more errors were raised in the Javascript code on the page. If you don't care about these errors, you can ignore them by setting js_errors: false in your Poltergeist configuration (see documentation for details).

      Error: Cannot find module "babel-runtime/core-js/json/stringify"
      Error: Cannot find module "babel-runtime/core-js/json/stringify"
          at http://127.0.0.1:56815/assets/generated/app-bundle.js?body=1:186 in webpackMissingModule
          at http://127.0.0.1:56815/assets/generated/app-bundle.js?body=1:186
          at http://127.0.0.1:56815/assets/generated/vendor-bundle.js?body=1:52 in __webpack_require__
          at http://127.0.0.1:56815/assets/generated/app-bundle.js?body=1:68
          at http://127.0.0.1:56815/assets/generated/vendor-bundle.js?body=1:52 in __webpack_require__
          at http://127.0.0.1:56815/assets/generated/app-bundle.js?body=1:14
          at http://127.0.0.1:56815/assets/generated/vendor-bundle.js?body=1:52 in __webpack_require__
          at http://127.0.0.1:56815/assets/generated/app-bundle.js?body=1:5
          at http://127.0.0.1:56815/assets/generated/vendor-bundle.js?body=1:52 in __webpack_require__
          at http://127.0.0.1:56815/assets/generated/vendor-bundle.js?body=1:23 in webpackJsonpCallback
          at http://127.0.0.1:56815/assets/generated/app-bundle.js?body=1:34301 (Capybara::Poltergeist::JavascriptError)
      ./features/step_definitions/user_steps.rb:7:in `/^I am logged in as (.+)$/'
      ./features/support/env.rb:120:in `call'
      ./features/support/env.rb:120:in `block (2 levels) in <top (required)>'
      ./features/support/env.rb:71:in `block in <top (required)>'
      features/board/card_specification.feature:11:in `Given I am logged in as Luke Skywalker'
```

Not sure if that generated file is somehow incorrect or what is happening. Locally it works fine.

**Comment by justin808** [comment]
@hakunin We added specific code in v3 to solve this issue. See the docs here: https://github.com/shakacode/react_on_rails/blob/master/docs%2Fadditional_reading%2Frspec_configuration.md

Please let me know if this fixes the issue.

**Comment by hakunin** [comment]
Unfortunately, it didn't.

I updated to V3, added the config line and removed the `cd client && npm run build:client`, and I get this:
```
    Failure/Error: post :update, organization: {
     ActionView::Template::Error:
       couldn't find file 'generated/vendor-bundle'
         (in /home/ubuntu/hubstaff-projects/app/assets/javascripts/application.js:7)
```

**Comment by justin808** [comment]
Is this only on CI?

can you repro locally?

**Comment by hakunin** [comment]
Only on CI.

On Thu, Feb 18, 2016 at 12:24 PM Justin Gordon <notifications@github.com>
wrote:

> Is this only on CI?
>
> can you repro locally?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/shakacode/react_on_rails/issues/281#issuecomment-185672155>
> .
>
-- 
S pozdravem, Regards
Michal Hantl

skype id: michal.hantl
cell phone: +420 720 737 902

**Comment by justin808** [comment]
We've had these issues before. You'll have to yak shave with CI.

I will say, try this:

Make a fresh git clone and follow all the steps you have for CI locally.

9 out of 10 cases we see an issue we thought was only CI.

**Comment by hakunin** [comment]
More investigation:
- I updated all packages I could to new versions
- I updated npm on the CI to 4.3

During compile I get:

rake assets:precompile
cd client && npm run build:client

> react-webpack-rails-tutorial@1.1.0 build:client /home/ubuntu/hubstaff-projects/client
> NODE_ENV=production webpack --config webpack.client.rails.config.js

Webpack production build for Rails
Hash: 1a2b03e71b9c8205e3ab
Version: webpack 1.12.13
Time: 8883ms
           Asset     Size  Chunks             Chunk Names
   app-bundle.js  1.23 MB       0  [emitted]  app
vendor-bundle.js   557 kB       1  [emitted]  vendor
   [0] multi app 28 bytes {0} [built]
   [0] multi vendor 76 bytes {1} [built]
    + 372 hidden modules

ERROR in ./~/react-on-rails/node_package/lib/ReactOnRails.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/assign' in /home/ubuntu/hubstaff-projects/client/node_modules/react-on-rails/node_package/lib
 @ ./~/react-on-rails/node_package/lib/ReactOnRails.js 3:14-60
```
ERROR in ./~/react-on-rails/node_package/lib/ReactOnRails.js
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/json/stringify' in /home/ubuntu/hubstaff-projects/client/node_modules/react-on-rails/node_package/lib
 @ ./~/react-on-rails/node_package/lib/ReactOnRails.js 7:17-64
```

Any ideas? I can see from npm install on CI that the package is in fact installed.

I can affect pretty much anythign in the CI so if you have any suggestion I am able to run it.

**Comment by hakunin** [comment]
Good news @justin808, I had a missing dependency `babel-runtime` (which is required by react on rails) and now it compiles. Maybe you can add it as dependency by default, since it won't compile otherwise?

**Comment by justin808** [comment]
hmmm...

@hakunin We don't have that here: https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/package.json

Maybe you can research a bit more on the specific case of why you need it? 

We're using Travis for CI, so that's pretty standard.

**Comment by hakunin** [comment]
It is needed by polyfill. 
```
babel-polyfill@6.5.0 node_modules/babel-polyfill
├── babel-regenerator-runtime@6.5.0
├── babel-runtime@5.8.35
└── core-js@1.2.6
```

My limited node knowledge leads me to believe that its a peer dependency, thus not installed unless you specify you want it and Travis has the package available globally.

**Comment by MindRave** [comment]
@justin808, same here. Needed the 'babel-runtime' package, otherwise bundle wouldn't compile. Don't know why this happened exactly. On one machine everything worked fine, on the other one it wouldn't without this package. Curious.

**Comment by justin808** [comment]
babel-runtime will be need for very old CI envs maybe.

Any details on when and why this is needed? Maybe the node version matters? Or the babel version?

**Comment by justin808** [comment]
We need to understand why this does not need it: 

https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/package.json

Maybe this is better suited for a file in the /docs directory on this issue?

**Comment by hakunin** [comment]
Here is output from `npm install` on the CI if that helps.
https://gist.github.com/hakunin/6e0f57e5e9b0f2d304b9

**Comment by justin808** [comment]
@hakunin We're using circle ci and yes, babel-runtime is a dependency of probably every `babel-plugin-XXX`

We're using circle CI and we're *not* directly including babel-runtime.

Can you find a doc reference that says babel-runtime should be a top level dependency?

```js
    "babel": "^6.3.13",
    "babel-cli": "^6.3.15",
    "babel-core": "^6.3.15",
    "babel-loader": "^6.2.0",
    "babel-plugin-transform-decorators-legacy": "^1.2.0",
    "babel-polyfill": "^6.3.14",
    "babel-preset-es2015": "^6.3.13",
    "babel-preset-react": "^6.3.13",
    "babel-preset-stage-0": "^6.3.13",
    "babel-register": "^6.3.13",
    "babel-eslint": "^5.0.0-beta6",
    "babel-jscs": "^3.0.0-beta1",
    "babel-plugin-react-transform": "^2.0.0-beta1",
    "babel-plugin-typecheck": "^3.4.6",
    "babel-preset-react-hmre": "^1.0.1",
```

**Comment by justin808** [comment]
@hakunin I'm going to close this issue to keep it out of the active list, but feel free to keep commenting here more.

**Comment by Kosmin** [comment]
@justin808 @hakunin @MindRave This conversation helped me a lot. I was working on getting `react_on_rails` to work with semaphoreci and after including `babel-runtime` as a dependency our problems were fixed. 

We were also missing the `"imports-loader": "^0.6.5"` dependency, in case anyone else runs into the same issue.

**Comment by justin808** [comment]
@Kosmin Any idea on why we need babel-runtime, when it's a dependency of the other babel modules?

**Comment by Kosmin** [comment]
@justin808 Hmm good question. I have since took `babel-runtime` out, did a fresh install, and everything worked fine. It may have had something to do with me running `nvm` and using an older version of `node`, but can't say for sure. In any case I don't need it anymore.

**Comment by Kosmin** [comment]
@justin808 I actually take that back. Locally everything works fine without `babel-runtime` but on `semaphoreci` I get a missing module error. It might have something to do with the npm version, I remember reading that it requires to explicitly state dependencies. But at this time I'm not sure why it's happening.

```
Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/assign' in /home/runner/<application>/client/node_modules/react-on-rails/node_package/lib
 @ ./~/react-on-rails/node_package/lib/ReactOnRails.js 3:14-60
```

**Comment by dspoonia7** [comment]
I am also getting this error

> ActionView::Template::Error: couldn't find file 'webpack-bundle'

while running teaspoon in production environment. In my local env it is working fine. Here is complete [error log](https://gist.github.com/dspoonia7/4c8ffc4dfa7ecd7e381dedce9bc8b4c1#file-webpack-error) and my [client/package.json](https://gist.github.com/dspoonia7/4c8ffc4dfa7ecd7e381dedce9bc8b4c1#file-package-json).

**Comment by mikeLspohn** [comment]
My tests on semaphore and are running fine, but anytime a react_on_rails component is rendered the Semaphore test for that fails because it doesn't see the component is rendered. I tried adding `npm install babel-runtime` as a setup task in semaphore, but that doesn't seem to fix it for me. 

All the rest of my tests that don't render react components are working fine.
Anyone have any suggestions? Has there been any new discoveries related to this issue?
