### ISSUE TITLE
How to include images from asset pipeline in JS client? 

### ISSUE THREAD

**Issue by benigeri** [shakacode/react_on_rails#283]
### The problem 

I'm currently using the asset pipeline to serve images from my rails server. 

For example, let's say I have an image at: 

```
rails-app/app/assets/images/sprint.jpg
```

In `erb` code, I'd use `image_tag` or something, and it would generate a fingerprinted link like this: 

```
https://domain.com/assets/sprint-42eb38fb2cb471821a1435cab589e590.jpg
```

And if I tried to access the non fingerprinted asset in production, I'd get a 404: 

```
https://domain.com/assets/sprint.jpg
```

What is the best way to deal with this if I want to include assets from my asset pipeline in my React code? 

### Tentative solution: 

Run all of my JS files through `erb`. It seems a little ghetto to have `.jsx.erb` files and to have to run them through another cycle. Maybe it's the best solution. I could just make it so that my final generate bundle is ran once, and have all of the `erb` executed. 

This would make my local dev a bit of a pain. I'd make an `imageUrl` function that creates an `erb` tag in prod, and a simple asset link in dev. 

### Please help! 

How have other people been handling this? Any suggestions?

**Comment by benigeri** [comment]
## Best thing I've come up with: 

1. Creating an `assetPaths.js.erb` file in `/app/assets/javascript/assetPaths.js.erb`
2. Then I tell my asset pipeline to `Rails.application.config.assets.precompile += %w( assetPaths.js )`
3. Include that in my master JS file for my client side app: 

```
// The equivalent of application.js for the GO CUBES site

//= require assetPaths
//= require generated/vendor-bundle
//= require generated/app-bundle
```

And now I have a beautiful global dict of available asset paths. 

This isn't great but it works. Would love to hear any other suggestions!

**Comment by benigeri** [comment]
Actually this doesn't work with server side rendering, unfortunately.

**Comment by justin808** [comment]
I think there's 2 options: 

* https://github.com/alexspeller/non-stupid-digest-assets
* Put the assets under /public

**Comment by benigeri** [comment]
@justin808 thanks! I think option 1 is best. 

This might cause some caching issues with cloud front / cloudflare, but we'll solve that another day. 

Appreciate the prompt response!

**Comment by petrbela** [comment]
For anyone who stumbles on this ticket, #670 offers an updated solution.

**Comment by aryehbeitz** [comment]
[this helped me](https://stackoverflow.com/a/31681098/3548935)

**Comment by Hirurg103** [comment]
How about if you put our image under `app/javascripts/images` and will reference it from your JS code with:

```js
import React from 'react'
import MyImage from 'images/my_image.svg'

const MyComponent = props => <img src={MyImage} />

export default MyComponent
```
See [this Stackoverflow answer](https://stackoverflow.com/a/47010369/3676469) for the details

In your Rails templates you can use `image_path_tag` helper:

```haml
= image_pack_tag 'my_image.svg'
```
