### ISSUE TITLE
React on Rails and async loading of application.js

### ISSUE THREAD

**Issue by SqueezedLight** [shakacode/react_on_rails#290]
Hi guys,
i'm wondering if there is any possibility to use react on rails with async loading like:
```
<%= javascript_include_tag 'application', async: Rails.env.production? %>
```

In this case, the ```componentDidMount``` does not get fired. The issue is well known, described and fixed here: https://github.com/reactjs/react-rails/issues/218

What i'm searching for is a hook, like ```ReactRailsUJS.mountComponents()```. Right now i'm trying to write something like ```mountComponents()``` but i did not have success until now. That's why i'm wondering if i'm missing something?

Thanks a lot in advance.

**Comment by justin808** [comment]
* http://parley.rubyrogues.com/t/should-rails-apps-use-defer-when-loading-application-js/3395 (might require membership). Copied [here in Evernote](https://www.evernote.com/shard/s108/sh/0ebe7279-219a-4b30-a85c-633b836a828c/46b5ab64851c0399a29827b5546ed99a). 
* https://github.com/shakacode/react-webpack-rails-tutorial/pull/234
* https://github.com/shakacode/react_on_rails/issues/206

@SqueezedLight Any research you can do this topic would be greatly appreciated!

I think this already does what you need:

https://github.com/shakacode/react_on_rails/blob/master/node_package%2Fsrc%2FclientStartup.js#L93

```
function reactOnRailsPageLoaded() {
  debugTurbolinks('reactOnRailsPageLoaded');

  forEachStore(initializeStore);
  forEachComponent(render);
}
```

We simply need to export the function and expose it here in the main ReactOnRails js class.

https://github.com/shakacode/react_on_rails/blob/master/node_package%2Fsrc%2FReactOnRails.js#L59

Can you try that out and send a PR including:

1. Docs
2. Tests: put this into `spec/dummy` app to demonstrate this.

Thanks!

**Comment by SqueezedLight** [comment]
@justin808 Thanks, i didn't see that in the first place. I'm on it...

**Comment by justin808** [comment]
@SqueezedLight Any update? Should we leave this issue open?

**Comment by SqueezedLight** [comment]
@justin808 Sorry, i had to manage some really stressful days...

Yes, there is some progress: Exposing ```reactOnRailsPageLoaded()``` to ```ReactOnRails``` worked like a charm. But i'm using ```turbolinks 5.0``` and i'm calling some code within ```document.addEventListener("turbolinks:load", function() {});``` This peace of code stopped working, because it seems turbolinks does not fire  ```turbolinks:load ``` on initial page load with async script loading. One solution is to use ```defer``` instead of ```async```. More information can be found on the issue i opened about this topic: https://github.com/turbolinks/turbolinks/issues/28

So i managed to get everything working with async script loading. I hope i can make the PR on the weekend.

**Comment by justin808** [comment]
Merged with version 6.0.0-rc.1

**Comment by xiaopow** [comment]
If I want to load the js async, do I just add 
`<%= javascript_include_tag 'application', async: true %>`
?

Or is there more settings I need to configure?

**Comment by justin808** [comment]
@xiaopow I don't know off the top of my head. Please research this and report back to us, and that will help the community.

**Comment by justin808** [comment]
@xiaopow, @nateberkopec has some done some amazing research into this area. Nate, can you give us a few links to your materials?

**Comment by dpuscher** [comment]
I ran into the same problem, where my javascript wasn't executed reliably when loading my generated `application.js` asynchronously via `javascript_pack_tag "application", async: true`.

A quick workaround was this snippet:
```
if (typeof document !== "undefined") {
  if (document.readyState !== "loading") {
    ReactOnRails.reactOnRailsPageLoaded();
  } else {
    document.addEventListener("DOMContentLoaded", () =>
      ReactOnRails.reactOnRailsPageLoaded(),
    );
  }
}
```

Maybe someone knows a better way, or did I miss something from the docs? Nowadays it should be the preferred way to load the JS async (especially when prerendering components).

**Comment by julianguyen** [comment]
Is there an official way of doing this in React on Rails now, instead of the solution @dpuscher mentioned above?

**Comment by justin808** [comment]
@julianguyen I'm sure this is somewhere in the docs. 

Here's an example:
https://github.com/shakacode/react_on_rails/blob/master/spec/dummy/app/views/layouts/application.html.erb#L17

you need to use defer:

```erb
  <!--  NOTE: Must use defer and not async to keep async scripts loading in correct order  -->
  <%= javascript_pack_tag('vendor-bundle', 'data-turbolinks-track': true, defer: true) %>
  <%= javascript_pack_tag('app-bundle', 'data-turbolinks-track': true, defer: true) %>
```

**Comment by julianguyen** [comment]
@justin808 Why does `'data-turbolinks-track': true` need to be set with defer?

**Comment by rakelley** [comment]
@julianguyen If you don't use turbolinks, you [get problems](https://github.com/shakacode/react_on_rails/issues/1150). #1150

**Comment by justin808** [comment]
@julianguyen if you are not using turbolinks, remove that part.
