### ISSUE TITLE
React on Rails on Cloud9

### ISSUE THREAD

**Issue by bartoszbinda** [shakacode/react_on_rails#291]
There is only :8080 on Cloud9 working.  What can I do to changes the port in React on Rails? I've tried on client/server,js and puma.rb but still not working.
http://pastebin.com/Skwx7Jas
Now I've got this:
http://pastebin.com/Ej8GNp5C

**Comment by justin808** [comment]
@lifeiscontent tried also. I'm really not sure.

A regular deploy needs 

* Port 3000 for Rails (and that's all you need if you statically compile your assets)
* Port 3500 for the Rails Hot Reload server to server the JS and CSS

**Comment by justin808** [comment]
Copy this file:

https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/Procfile.static#L2

And modify the command that starts Rails.

That's it.

**Comment by bartoszbinda** [comment]
What am I doing wrong?
https://github.com/bartoszbinda/shop

**Comment by justin808** [comment]
@bartoszbinda 

```js
17:48:03 client.1 | ERROR in ./~/react-on-rails/node_package/lib/ReactOnRails.js
17:48:03 client.1 | Module not found: Error: Cannot resolve module 'babel-runtime/core-js/object/assign' in /home/ubuntu/workspace/shop/client/node_modules/react-on-rails/node_package/lib
17:48:03 client.1 |  @ ./~/react-on-rails/node_package/lib/ReactOnRails.js 3:14-60
```

You need to debug the npm command for "client" in your procfile locally first. You're missing some dependencies. Compare your setup to:

* https://github.com/shakacode/react-webpack-rails-tutorial/tree/master/client
* https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/package.json

You should also disable server side processing until you work out client side processing first.
