### ISSUE TITLE
Asset compilation fails with babel-runtime error

### ISSUE THREAD

**Issue by scottluptowski** [shakacode/react_on_rails#293]
Hello,

I created a brand new Rails 4.2 project and added the react_on_rails gem.

I ran
```ruby
rails generate react_on_rails:install -R
```

and followed the instructions afterwards (npm installing, etc.)

When I visit the page in my Browser, I see only this, without the "Hello Stranger" message I anticipated:
<img width="1141" alt="screen shot 2016-02-24 at 3 43 56 pm" src="https://cloud.githubusercontent.com/assets/3178471/13305059/790f1498-db0d-11e5-8bd2-ed4c313b5645.png">

This error shows up in the console:
<img width="561" alt="screen shot 2016-02-24 at 3 30 25 pm" src="https://cloud.githubusercontent.com/assets/3178471/13305076/8b2acc1c-db0d-11e5-820c-8c60d35f539d.png">

How can I resolve this problem? Thanks!

**Comment by justin808** [comment]
@scottluptowski 

Please share your repo on github.

Did you run `npm i` inside of the client directory after the install?

**Comment by scottluptowski** [comment]
Hi @justin808, thanks for your quick reply.

I did not initially run `npm i` inside the client directory as the readme made me think this was done for me. I tried this and still saw the same error.

I was able to recreate the error, so I'm attaching a couple things:
- A screenshot of my steps taken 
<img width="448" alt="screen shot 2016-02-24 at 4 24 53 pm" src="https://cloud.githubusercontent.com/assets/3178471/13305838/61b4d58e-db13-11e5-9c2d-bffd1763e12f.png">

- A link to the recreation repo
https://github.com/scottluptowski/error_recreation

- A screenshot of the console output on my Webpack console
<img width="1386" alt="screen shot 2016-02-24 at 4 24 42 pm" src="https://cloud.githubusercontent.com/assets/3178471/13305846/74797c7e-db13-11e5-8d7b-e4198e9a7c13.png">

Thanks again for this gem and your help.

**Comment by justin808** [comment]
Do you have node v5 or greater?

**Comment by justin808** [comment]
@scottluptowski We're doing packs of private coaching: http://www.shakacode.com/work/. This has been a great value for some other startups.

**Comment by scottluptowski** [comment]
@justin808 I was using Node v4 when I created the repo. I just used nvm to switch to 5.7, npm installed, and still see the same error

**Comment by aaronvb** [comment]
@scottluptowski have you tried removing the modules and reinstalling them?

```
rm -rf client/node_modules/
npm i
```

**Comment by scottluptowski** [comment]
@aaronvb @justin808 That did the trick, thank you! 

May I suggest changing the readme to include a hard requirement on Node v5?

Thanks again for your work on the gem :100:

**Comment by justin808** [comment]
> NPM install. Make sure you are on a recent version of node, preferably using nvm. We've heard some reports that you need at least Node v5.

is in the current readme.

I'll emphasize this!

**Comment by SyntaxChris** [comment]
Can confirm, updating to latest version of node resolved this issue for me.  As a surfer and code lover I gotta give you guys props (pun intended)!  This open source contribution is amazing!
