### ISSUE TITLE
registerStore with server rendering

### ISSUE THREAD

**Issue by Tamiyadd** [shakacode/react_on_rails#298]
Hi man, sorry for bothering you again but i have a problem :(
I configured my app to use registerStore and it works like a charm with ClientSide Rendering but when i enable ServerSide Rendering i receive that error message

```
[SERVER] message: Could not find store with name store.Hydrated store names include [].
```

can you give me an hint why? tnx

here my store,jsx
```
import { compose, createStore, applyMiddleware, combineReducers } from 'redux';

import { devTools, DebugPanel, LogMonitor, persistState } from 'redux-devtools';

import thunkMiddleware from 'redux-thunk';

import reducers from '../reducers';
import { initialStates } from '../reducers';

export default props => {
  const { isUserLogged, domainUrl, swnewUser } = props;
  const { swnewState } = initialStates;

  const initialState = {
    swnew: {
      isUserLogged: isUserLogged,
      domainUrl: domainUrl,
      swnewUser: swnewUser,
    },
  };

  const reducer = combineReducers(reducers);
  const composedStore = compose(
    applyMiddleware(thunkMiddleware), devTools()
  );
  const storeCreator = composedStore(createStore);
  const store = storeCreator(reducer, initialState);
  return store;
};
```

**Comment by justin808** [comment]
You need to register your stores and have that be a webpack dependency.

**Comment by justin808** [comment]
https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client%2Fwebpack.client.base.config.js#L24

Put store registration in this file:

https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client%2Fapp%2Fbundles%2Fcomments%2Fstartup%2FclientRegistration.jsx

**Comment by Tamiyadd** [comment]
Hi @justin808 i was just doing that, i have both client registration and server registration with startup loading of the store registration

here my files:

```
import ReactOnRails from 'react-on-rails';
import MovieSuggestionBoxContainer from '../containers/MovieSuggestionBoxContainer';
import TimelineContainer from '../containers/TimelineContainer';
import ShareBox from '../components/graphicComponents/ShareBox';
import store from '../store/swnewStore';

ReactOnRails.registerStore({ store });
ReactOnRails.register({
  MovieSuggestionBoxContainer,
  TimelineContainer,
  ShareBox,
});

and in my webpack config i do

```
    app: [
      './app/bundles/Swnew/startup/clientRegistration',
    ],
```

and

```
entry: [
    './app/bundles/Swnew/startup/serverRegistration',
  ],
```

**Comment by justin808** [comment]
@Tamiyadd You're registering your store to have the name `store`. Maybe try something more explicit?

The code you show should work. I'm interested in helping you debug this. Can you take a look at the example of the shared store in `/spec/dummy` for clues?

**Comment by jopdeklein** [comment]
@justin808 I am facing the same issue - interestingly I was also using `store` as the store name :)  Unfortunately the same error occurs when I rename it to `appStore` for instance, I have looked at the examples and it seems like we're doing the same. 

My initial motivation for using an externally registered store is to have the store definition later than the pre-rendered HTML for perceived performance. Is the order of the components somehow relevant on the server rendering but not the client? Switching it doesn't seem to have any effect so I hope/think not.

Do you have any tips for debugging this issue?

**Comment by Tamiyadd** [comment]
Hi @justin808 i changed the name in swStore but the error remain the same, i looked in your code and the settings is the same of yours. I also reinitialized my project using the generator (before i was coming from 1.0 version of react_on_rails) and i get the same error

do you have any hint? thanks!

**Comment by jopdeklein** [comment]
Also, in this file https://github.com/shakacode/react_on_rails/blob/master/spec/dummy/app/views/pages/server_side_redux_app.html.erb I can't seem to find the store registration as I am doing per the documentation:
`<%= redux_store("appStore", @payload) %>`

**Comment by justin808** [comment]
@jopdeklein This is the line you want: https://github.com/shakacode/react_on_rails/blob/master/spec%2Fdummy%2Fapp%2Fviews%2Fpages%2Fserver_side_hello_world_shared_store.html.erb#L2

@jopdeklein @Tamiyadd Can you two sync up the /spec/dummy app and experiment with that?

Maybe try to make a tiny app with the generator and push to github?

https://github.com/shakacode/react_on_rails/tree/master/spec/dummy

@seoyoochan is working on https://github.com/shakacode/react-webpack-rails-tutorial/pull/231 which will add a shared store example.

**Comment by justin808** [comment]
@jopdeklein @Tamiyadd Also, I just released 3.0.6 which gives a better error message.

**Comment by jopdeklein** [comment]
@justin808 Thanks for the quick response, I see my app and initializer aren't exactly the same as yours - I bundle them all in one file, I have a `main.jsx` that includes all required entry points that bundles into `server-app.js`. Not sure if it makes a difference but I'll try to align my setup with your example, if that fails I will use the generator and compare.

**Comment by jopdeklein** [comment]
Actually looking at the code the split should be correct, only difference between your example is that I am reading the store in `componentWillMount` of a wrapper (BaseProvider):

```
BaseProvider = React.createClass
  displayName: 'BaseProvider'

  componentWillMount: ->
    @store = ReactOnRails.getStore('appStore')

  # clones child with @store prop
  augmentChild: ->
  
  render: ->
    <IntlProvider>
      <ReduxProvider store={@store}>
        {@augmentChild()}
      </ReduxProvider>
    </IntlProvider>
```

This works client-side and a similar store setup used to work with React On Rails 2.0 - Do you see anything wrong with this on first glance?

**Comment by justin808** [comment]
@jopdeklein I've never set the store like that. So I don't know. You'll have to help us debug the issue. Maybe put in some debug prints?

**Comment by jopdeklein** [comment]
I understand it's a bit vague, my doubt is in which order the
componentWillMount and the store hydration takes place. I'll dive in to it
over the weekend and get back to you.

**Comment by jopdeklein** [comment]
@Tamiyadd @justin808 I've set up an example project with the generator, I adjusted the code to read the hydrated store and it seems to work fine both client and server side: https://github.com/jopdeklein/react-on-rails-redux-example

I'll investigate what I am doing differently and try to isolate the issue.

**Comment by jopdeklein** [comment]
Actually scrap that, I was looking at cached correct results. It seems the order of the store registration is relevant:

works:
```
<%= redux_store("helloWorldStore", @hello_world_props) %>
<%= react_component("HelloWorldApp", prerender: true) %>
```

doesn't work:
```
<%= react_component("HelloWorldApp", prerender: true) %>
<%= redux_store("helloWorldStore", @hello_world_props) %>
```

Kind of makes sense but I was specifically looking to have the store after the pre-rendered HTML to improve perceived performance for the end user. Any pointers to get this to work @justin808? Your input is much appreciated.

**Comment by justin808** [comment]
@jopdeklein Please take a look at this code:

### CLIENT SIDE
https://github.com/shakacode/react_on_rails/blob/master/node_package%2Fsrc%2FclientStartup.js#L93

```js
function reactOnRailsPageLoaded() {
  debugTurbolinks('reactOnRailsPageLoaded');

  forEachStore(initializeStore);
  forEachComponent(render);
}
```

We hydrate the stores on the client side before any components.


### SERVER SIDE

The problem is here: https://github.com/shakacode/react_on_rails/blob/c7c73245c6a5b68e6e4ddf991ed8e4034b80e192/app/helpers/react_on_rails_helper.rb#L229

```ruby
  def initialize_redux_stores
    return "" unless @registered_stores.present?
    declarations = "var reduxProps, store, storeGenerator;\n"
    result = @registered_stores.each_with_object(declarations) do |redux_store_data, memo|
      store_name = redux_store_data[:store_name]
      props = props_string(redux_store_data[:props])
      memo << <<-JS
reduxProps = #{props};
storeGenerator = ReactOnRails.getStoreGenerator('#{store_name}');
store = storeGenerator(reduxProps);
ReactOnRails.setStore('#{store_name}', store);
      JS
    end
    result
  end
```

Thus, the view helper:

https://github.com/shakacode/react_on_rails/blob/master/app%2Fhelpers%2Freact_on_rails_helper.rb#L103

```ruby
  # Separate initialization of store from react_component allows multiple react_component calls to
  # use the same Redux store.
  #
  # store_name: name of the store, corresponding to your call to ReactOnRails.registerStores in your
  #             JavaScript code.
  # props: Ruby Hash or JSON string which contains the properties to pass to the redux storea.
  def redux_store(store_name, props = {})
    redux_store_data = { store_name: store_name,
                         props: props }
    @registered_stores ||= []
    @registered_stores << redux_store_data

    content_tag(:div,
                "",
                class: "js-react-on-rails-store",
                style: ReactOnRails.configuration.skip_display_none ? nil : "display:none",
                data: redux_store_data)
  end
```

initializes the stores in the order they are called.


So, I think we should do this:

#### Option 1
1. Require that redux stores be initialized on the page before components that use the stores, because that's necessary for server side rendering (unless we were to parse the page in two passes).

2. If this makes a difference performance wise, we can create another view helper to write out the store initialization HTML at the end of the page. That way this does not get in the way of other HTML elements from first rendering. We'd also need an option, either globally or on the redux_store call, that specifies that we'll be doing deferred rendering.

#### Option 2

1. We allow defining the redux store in the controller, before the view renders. We can use the same api: `redux_store(store_name, props = {})`

2. We provide a new helper `render_redux_stores` which takes no parameters. This client renders all the redux stores registered at the controller level.


I think Option 2 would work well, and it would not cause any backwards compatibility issues.

**Comment by justin808** [comment]
@jopdeklein @Tamiyadd would either of you be interested in submitting a PR for this?

**Comment by justin808** [comment]
https://github.com/shakacode/react_on_rails/issues/309

Please let me know if you agree. @Tamiyadd @jopdeklein

**Comment by jopdeklein** [comment]
@justin808 Thanks for taking the lead, I agree option 2 seems viable, let me know if I can contribute.

**Comment by Tamiyadd** [comment]
Hi @justin808 and @jopdeklein sorry for not answering soon but i'm doing a lot of work. I've followed the discussion and i agree that the second option is better! 
Let me know if i can contribute! 

Thanks for all the work you are doing

**Comment by Tamiyadd** [comment]
Hi @justin808 and @jopdeklein just a little update
i found that my problem is a little bit different from jop problem, or maybe is the same but from another point of view.

My component is put after the  `redux_store` helper so i've investigated thoroughly my app and i found that the component is inside a partial in a `content_for` block.

I've tried putting the component outside the block and i found that it will render without the store error. So i put that kind of layout in the spec/dummy example and i found that the error is thrown. Eureka!

Hope this will help debug the problem, I'm available for helping and other test

thanks!

**Comment by jopdeklein** [comment]
@justin808 I just tried with the beta version, seems to work perfectly: https://github.com/jopdeklein/react-on-rails-redux-example/commit/7fb54382eb9cefa7f1c4a9004b3e7df560155aaa - thanks a lot!

**Comment by Tamiyadd** [comment]
Hey @justin808  and @jopdeklein i tried the beta version for my situation too and it works like a charm! 

thanks a lot for everything

**Comment by justin808** [comment]
@Tamiyadd @jopdeklein Can I ask for a couple favors:
1. Code review of #311 
2. Help me get it pass CI. It passes locally, but I can't get it to pass on CI.

I'm doing some deep digging into the Turbolinks 5 integration right now.

**Comment by justin808** [comment]
Also, can you two take a look at any caching strategies of the store data? I'm guessing that if you render with jbuilder, we might be able to fragment cache that in the rendering call. But I'm not 100% sure since we're not doing this as part of the rendering cycle.

**Comment by jopdeklein** [comment]
@justin808 I quickly glanced over the PR but since I am not a Ruby developer and don't know all the best practices I am probably not the best person to review this for you. 

One thing I noticed was ```gem "selenium-webdriver", require: !["poltergeist", "poltergeist_errors_ok", "webkit"].include?(ENV["DRIVER"])```, in the CI environment I see errors regarding Selenium, hope that helps you with point 2?

**Comment by justin808** [comment]
@jopdeklein I was discussing your [comment](https://github.com/shakacode/react_on_rails/issues/298#issuecomment-191817075) with @nateberkopec and he's not convinced that it makes a difference to have the store props in the html earlier or later.

with data together:
```
<div data-react-on-rails=“{big JSON encoded string}”> 
  <div>LOTS OF CHILD DIV STUFF</div>
</div>
```

with data separate:
```
<% setup_data_used_for_rendering(“could be done in controller, or inline view call”) %>
<div>
  <div>lots of HTML we server rendered</div>
</div>

<div data-react-on-rails=“{big JSON encoded string}”/> 
```
With the first way, we can wrap the whole thing in a cache block.

With the second way, if we setup the data in the controller, that makes the caching more complicated. In writing this up, I realize that we can do with a call in the view.

Fragment caching is going to be a critical part of this setup.

Nate wrote me back:

> Yeah, I’m not seeing a major difference in those two scenarios
> I’m not even sure that an attribute with a large value will slow down the dom parser.
> My advice is to try both with Chrome Timeline and see if there’s a difference.
