### ISSUE TITLE
Install command "rails generate react_on_rails:install --help" is hung.

### ISSUE THREAD

**Issue by Landrito** [shakacode/react_on_rails#305]
Whenever I try and run the command, I always get hung. When I ctrl-c I get the following:

`/Users/ernestlandrito/.rvm/gems/ruby-2.2.1/gems/spring-1.6.4/lib/spring/client/run.rb:98:in `gets': Interrupt
	from /Users/ernestlandrito/.rvm/gems/ruby-2.2.1/gems/spring-1.6.4/lib/spring/client/run.rb:98:in `verify_server_version'
	from /Users/ernestlandrito/.rvm/gems/ruby-2.2.1/gems/spring-1.6.4/lib/spring/client/run.rb:56:in `run'
	from /Users/ernestlandrito/.rvm/gems/ruby-2.2.1/gems/spring-1.6.4/lib/spring/client/run.rb:37:in `warm_run'
	from /Users/ernestlandrito/.rvm/gems/ruby-2.2.1/gems/spring-1.6.4/lib/spring/client/run.rb:26:in `call'
	from /Users/ernestlandrito/.rvm/gems/ruby-2.2.1/gems/spring-1.6.4/lib/spring/client/command.rb:7:in `call'
	from /Users/ernestlandrito/.rvm/gems/ruby-2.2.1/gems/spring-1.6.4/lib/spring/client/rails.rb:24:in `call'
	from /Users/ernestlandrito/.rvm/gems/ruby-2.2.1/gems/spring-1.6.4/lib/spring/client/command.rb:7:in `call'
	from /Users/ernestlandrito/.rvm/gems/ruby-2.2.1/gems/spring-1.6.4/lib/spring/client.rb:28:in `run'
	from /Users/ernestlandrito/.rvm/gems/ruby-2.2.1/gems/spring-1.6.4/bin/spring:49:in `<top (required)>'
	from /Users/ernestlandrito/.rvm/gems/ruby-2.2.1/gems/spring-1.6.4/lib/spring/binstub.rb:11:in `load'
	from /Users/ernestlandrito/.rvm/gems/ruby-2.2.1/gems/spring-1.6.4/lib/spring/binstub.rb:11:in `<top (required)>'
	from /Users/ernestlandrito/Documents/com/Landrito/bin/spring:13:in `require'
	from /Users/ernestlandrito/Documents/com/Landrito/bin/spring:13:in `<top (required)>'
	from bin/rails:3:in `load'
	from bin/rails:3:in `<main>'
`

**Comment by zohaib-enquizit** [comment]
`spring stop` might work
