### ISSUE TITLE
localhost:4000 doesn't work when using foreman

### ISSUE THREAD

**Issue by Igor10k** [shakacode/react_on_rails#307]
Readme says in the "Developing with the Webpack Dev Server" section to launch `foreman start -f Procfile.dev` and then go to `localhost:4000`, but there is nothing on port 4000. Is it an error in the readme?

In fact procfile.dev starts the `build:dev:client` script that starts webpack with `webpack.client.rails.config.js` config that doesn't even has the HMR plugin in it. But the section contents make it look like HMR will be enabled.

**Comment by justin808** [comment]
@Igor10k How are you running the app? Did you use the generator? what options?

I updated the README.md for the [shakacode/react-webpack-rails-tutorial](https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/README.md).

We're looking for volunteers to help us improve the generators. Please let me know if you'd be interested in helping.

**Comment by Igor10k** [comment]
I've used `react_on_rails` 3.0.3 with generator options `-R -b`.

As a result the only Procfiles I have are `Procfile.dev` and `Procfile.dev-hot`, but the latter is just a clone of the former with a `# TODO: MIGRATE from tutorial` note inside.

Here are the contents of the former.

```
web: rails s
client: sh -c 'rm app/assets/javascripts/generated/* || true && cd client && npm run build:dev:client'
```

Too busy at the moment, so can't contribute, maybe later.

For now I'll just try to copy the server starting scripts from the tutorial to my project.

**Comment by justin808** [comment]
Yep -- we're going to be cleaning this up a lot in the not too distant future.
