### ISSUE TITLE
Options to the top level content tag, such as "class", support passing props as string

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#31]
We need to do like this from the react-rails gem.

Also, we could allow the user to set an `id` in the content tag, and that should replace the generated one. Also, support passing props as a string, or a hsh.

We need:

- [x] Provide examples in the `views/pages` directory and links in the `_header.html.erb` 
- [ ] tests for this, both at the unit level and at the integration test level.
- [x] Update the docs
- [x] Small change, don't try to call [props.to_json if props is already a string, here](https://github.com/shakacode/react_on_rails/blob/master/app/helpers/react_on_rails_helper.rb#L34).

From the https://github.com/reactjs/react-rails/. We should make the API as similar as possible.

https://github.com/reactjs/react-rails/blob/master/README.md

- `component_class_name` is a string which names a globally-accessible component class. It may have dots (eg, `"MyApp.Header.MenuItem"`).
- `props` is either an object that responds to `#to_json` or an already-stringified JSON object (eg, made with Jbuilder, see note below).
- `html_options` may include:
  - `tag:` to use an element other than a `div` to embed `data-react-class` and `-props`.
  - `prerender: true` to render the component on the server.
  - `**other` Any other arguments (eg `class:`, `id:`) are passed through to [`content_tag`](http://api.rubyonrails.org/classes/ActionView/Helpers/TagHelper.html#method-i-content_tag).

https://github.com/reactjs/react-rails/blob/master/lib/react/rails/component_mount.rb
```ruby
      # Render a UJS-type HTML tag annotated with data attributes, which
      # are used by react_ujs to actually instantiate the React component
      # on the client.
      def react_component(name, props = {}, options = {}, &block)
        options = {:tag => options} if options.is_a?(Symbol)

        prerender_options = options[:prerender]
        if prerender_options
          block = Proc.new{ concat React::ServerRendering.render(name, props, prerender_options) }
        end

        html_options = options.reverse_merge(:data => {})
        html_options[:data].tap do |data|
          data[:react_class] = name
          data[:react_props] = (props.is_a?(String) ? props : props.to_json)
        end
        html_tag = html_options[:tag] || :div

        # remove internally used properties so they aren't rendered to DOM
        html_options.except!(:tag, :prerender)

        content_tag(html_tag, '', html_options, &block)
      end
    end
```

**Comment by justin808** [comment]
@josiasds, @mapreal19 Would either of you like to take a look at this one?

**Comment by mapreal19** [comment]
@justin808 This week I'm going to be quite busy. But I could start working on it the next week.

@josiasds Are you available?

**Comment by josiasds** [comment]
@justin808 @mapreal19 I've been quite busy also, but I'll try to get some time for this one.

**Comment by justin808** [comment]
Here's what the rendering looks like:

![2015-09-26_21-52-27](https://cloud.githubusercontent.com/assets/1118459/10121797/f7d26276-6498-11e5-9762-d4c07a9e140b.png)

for this:

```erb
<%= react_component("HelloWorld",
                    @app_props_server_render.to_json,
                    prerender: true,
                    trace: true,
                    generator_function: false,
                    id: "my-hello-world-id",
                    class: "my-hello-world-class",
                    data: { x: 1, y: 2}
    ) %>
```
