### ISSUE TITLE
Using ES5 

### ISSUE THREAD

**Issue by murtali** [shakacode/react_on_rails#310]
How would I modify the setup to use ES5 and ES6 interchangably? I'm having trouble reproducing this in ES5: (taken from example / modified)

Originally I had:
```


var ClassesApp = (
  <Router history={browserHistory}>
    <Route path="/classes/react_test" component={Classes} />
  </Router>
);

module.exports = ClassesApp;
```

but that wasn't working until I changed it to:

```
export default props => {
  return (
    <Router history={browserHistory}>
      <Route path="/classes/react_test" component={Classes} />
    </Router>
  );
};
```

**Comment by murtali** [comment]
I modified the es5 jsx to:

```
module.exports = function(props) {
  return (
    <Router history={browserHistory}>
      <Route path="/classes/react_test" component={Classes} />
    </Router>
  );
};
```
but I'm still having trouble understanding why it's necessary for react_on_rails to pick up the router in that way vs the origin syntax.

Is this a quirk in the way the gem parses/registers react?

**Comment by justin808** [comment]
why use ES5?

I'm not following...

The syntax of including the JSX is using ES6.

and default exports are totally different

it's like "exports.default = Foobar" under the covers.
