### ISSUE TITLE
Dependency error on a fresh install

### ISSUE THREAD

**Issue by woniesong92** [shakacode/react_on_rails#313]
I got the following error: `http://babel-runtime/core-js/object/assign missing` on a fresh install.
Perhaps there's a missing dependency in the script?

`npm install babel-runtime --save-dev` solved the issue.

**Comment by justin808** [comment]
@woniesong92 Yes, I've noticed that the newer babel's are requiring different things.

@jbhatab is leading the effort to refresh the generators. If you like to help us with that effort, you'll learn tons and the community would be very grateful.
