### ISSUE TITLE
Configure Server bundle file as param in react_component

### ISSUE THREAD

**Issue by lucke84** [shakacode/react_on_rails#317]
Which are the implications of changing the path of server bundle file (or any other config) at runtime? 

To give you a bit of context: with Webpack we create 2 different server bundle files, one for desktop and the other one for mobile. Then in the `ApplicationController` we have a `before_action` hook to check whether server-side rendering (SSR) is turned on and which browser is requesting the page (via `browser` gem). A simplified version looks like this:

```ruby
class ApplicationController < ActionController::Base
  before_action :set_assets

  private

  def is_mobile?
    browser.mobile?
  end

  def set_assets
    if SERVER_SIDE_RENDERING
      ReactOnRails.configure do |config|
        bundle_file = is_mobile? ? SERVER_BUNDLE_MOBILE : SERVER_BUNDLE_DESKTOP
        Rails.logger.info "Bundle: [#{bundle_file}]"

        config.server_bundle_js_file = bundle_file
        config.prerender = SERVER_SIDE_RENDERING
        config.raise_on_prerender_error = Rails.env.development?
      end
    end
  end
end
```

where `SERVER_SIDE_RENDERING` is a boolean, and `SERVER_BUNDLE_MOBILE` and `SERVER_BUNDLE_DESKTOP` are path to the files; all these constants are properly set in their own initializers.

This works relatively smoothly, but every now and then the user on a mobile device sees the desktop SSR version for a second (while the assets get downloaded) and then the client side rendering kicks in showing the correct version. This never happens in development yet it does in production, therefore I'm thinking this might be due to some Rails classes reloading magic disabled in prod environment.

Anyhow, I wanted to hear somebody else's opinion on whether this is a good idea and which are the shortcomings you can think of.

**Comment by justin808** [comment]
@lucke84 this is an excellent use case. Without a great deal of work, we could support a first class concept of different bundles for server rendering. We could do something like:

```erb
<%= react_component("MobileEnabledComponent", prerender: true, server_bundle: my_rails_helper_to_get_correct_bundle_name, props: @the_props) %>
```

Note, with v4, you will want to hydrate your props in the controller and have it render on the bottom of the page for maximum performance.

If this API works, either you or I could put this.

**Comment by justin808** [comment]
@lucke84 This would be an excellent, EASY way to make a nice contribution.

**Comment by lucke84** [comment]
Will be happy to :) I'll try and put together a PR somewhen this week.

**Comment by justin808** [comment]
@lucke84 Please remember:

1. Docs (README, etc.)
2. Update spec/dummy with a sample, which will involve view, webpack configs, etc.
3. Provide tests in spec/dummy that verify the right behavior. You will probably just want to have each bundle do separate components, rather than something browser type specific.

**Comment by lucke84** [comment]
I'm working on the topic and I've found what seems to be the issue of wrong SSR we're experimenting (see the beginning of the conversation for the details): currently, the `ReactOnRails::ServerRenderingPool.reset_pool_if_server_bundle_was_modified` doesn't do anything when Rails is run in a non-development mode, and I understand why, as in you don't wanna check the server bundle's mtime on every request, nor setting a new `ConnectionPool` just as often.

Although this is cool for the current situation with the idea of supporting one server bundle file, if we want to be able to choose which bundle to use on every request, we have to approach the problem differently:
1) we start supporting multiple bundles (with a simple mapping mechanism);
2) we improve the check performed in `ReactOnRails::ServerRenderingPool.reset_pool_if_server_bundle_was_modified` to keep in account which file is requested.

For performance reason, I would go for the first approach; I would like a bit of a feedback before coding such thing.

**Comment by justin808** [comment]
@lucke84 Yes -- we need to change the back end caching of bundles to support more than one. That's the only option. I figured you'd see that :smile: without me saying.

Let's ROCK this change. It's a great idea.

**Comment by justin808** [comment]
We probably will not need this one with the `railsContext` feature of v5.
