### ISSUE TITLE
Enabling es7?

### ISSUE THREAD

**Issue by hakunin** [shakacode/react_on_rails#318]
Hi,
I am learning react-dnd so I can make sortable lists and the guy only has examples in es7 with decorators and at the moment, its just too much to take in at once.

Is there a way I can easily use es7?

**Comment by alexfedoseev** [comment]
@hakunin You just need to install appropriate babel transform/preset (eg `babel-preset-stage-0`).

P.S. Decorators were temporarily removed from Babel 6 (as its spec is being reworked), but you can apply them via [babel-plugin-transform-decorators-legacy](https://github.com/loganfsmyth/babel-plugin-transform-decorators-legacy)
