### ISSUE TITLE
Clean up, pretty up code for helper, move some code to inclusion file.

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#32]
The code right now in the react_on_rails gem looks horrible due to trying to preserve the correct white space. Here's the generated code:

* https://github.com/shakacode/react_on_rails/blob/master/spec/dummy/spec/sample_generated_js/server-generated.js
* https://github.com/shakacode/react_on_rails/blob/master/spec/dummy/spec/sample_generated_js/client-generated.js

And here's the files that generate it:

* https://github.com/shakacode/react_on_rails/blob/master/app/helpers/react_on_rails_helper.rb
* https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/react_renderer.rb

@samnang @alexfedoseev @mapreal19 @josiasds Any ideas on how best to refactor this?

BTW -- be super careful before accepting any commits that might mess with this formatting.

@Johnnycus  Let's write a unit test that verifies that the generated JS stays the same, and that will enable us to do some refactoring.

**Comment by samnang** [comment]
@justin808 For indentation in heredoc, we could use http://api.rubyonrails.org/classes/String.html#method-i-strip_heredoc to remove white spaces from beginning.

**Comment by justin808** [comment]
@samnang We originally did it that way, but it's super hard as well for changing the indentation. The code is also going to be slightly faster not using it. On a somewhat related note, we should maybe put some of the code for the client side into a file included in application.js. 

Take a look at: https://github.com/shakacode/react_on_rails/blob/master/spec/dummy/spec/sample_generated_js/client-generated.js

I think we only need a few parameters to a client side method call:

1. name of globally exposed variable (property to be put on window): '__helloWorldES5Data0__'
2. name of id for element: 'HelloWorldES5-react-component-0'
3. name of component: 'HelloWorldES5'
4. trace: boolean
5. expect turbolinks: boolean

**Comment by szyablitsky** [comment]
I think that moving javascript into .js file which should be included in Rails' application.js is a good idea. If we need to add some runtime logic, than we can change extension to .js.erb and do some preprocessing for javascript code. And even cache it all or partially for performance gain.

**Comment by justin808** [comment]
@szyablitsky Let me know if you'd like to do this. Or anybody else does, please let me know.

**Comment by justin808** [comment]
@samnang and I made amazing progress from this today.

**Comment by justin808** [comment]
Fixed by #44.
