### ISSUE TITLE
handleError swallows exceptions

### ISSUE THREAD

**Issue by modosc** [shakacode/react_on_rails#325]
we're using [bugsnag](https://bugsnag.com) for tracking / reporting js and ruby errors. when rendering errors occur on the front end the exceptions are caught and dumped out to `console.error` but the exceptions aren't rethrown so bugsnag never sees them and we have no visibility into what's going on with our broken react code.  

i'm thinking that it would be useful to either:
1. add an option to re-throw exceptions, or
2. add an optional callback for `handleError` to call. 

i'm happy to implement one (or both) of these in a pr, i just wanted to check first to understand the reason this was happening to make sure i wasn't introducing more issues.

**Comment by justin808** [comment]
@modosc Great idea! Great feature! Let's do this!

Either option #1 or #2 (or both) sounds good. If you can post a couple code samples of how you'd like to do this, we can probably decide.

I can see advantages to either.

We also need to consider server rendering. On the server side, we don't want to just throw.

We should also add file to [docs/additional_reading](https://github.com/shakacode/react_on_rails/tree/master/docs/additional_reading).

**Comment by justin808** [comment]
@modosc Send me your contact info and I can add you to our slack room.

**Comment by justin808** [comment]
@modosc Any word on this? I've got some others that are looking for tasks to complete. This one should be relatively easy.

**Comment by modosc** [comment]
@justin808 sorry, i haven't had time to sort this out, please feel free to assign it off.

**Comment by justin808** [comment]
@modosc I'm still considering implementing this one. I think we can add a JS option to do this pretty easily, for either 1) or 2). We'd add something as a supported option: https://github.com/shakacode/react_on_rails/blob/master/node_package%2Fsrc%2FReactOnRails.js#L55

and this can be set globally in any of the files loaded by webpack.

**Comment by justin808** [comment]
@modosc Any more info on this one:

> i'm happy to implement one (or both) of these in a pr, i just wanted to check first to understand the reason this was happening to make sure i wasn't introducing more issues.

I'm thinking this one is pretty important.

**Comment by justin808** [comment]
@modosc @jbhatab We do log errors on the client side to level error, and I believe we do that for server rendering as well. So if the bug tracking system just looks for log level of error, then we don't need to just throw exceptions and crash.

**Comment by justin808** [comment]
We're using honey badger for https://www.friendsandguests.com/listings/7999 and it's working fine with the current react on rails.
