### ISSUE TITLE
error when running in capybara-webkit

### ISSUE THREAD

**Issue by citysheep** [shakacode/react_on_rails#326]
I am using server-side rendering for my react component but I got the following error in my acceptance test with Capybara-webkit. Any thoughts?

Expected no Javascript errors, got:
  - ReferenceError: Can't find variable: SAFE_CLOSING

**Comment by justin808** [comment]
We don't have a variable like that. I recommend turning off server rendering with this react_component option:

    prerender: false

**Comment by citysheep** [comment]
Thanks very much Justin. I turned off server-side rendering but the problem still exists, looks like it is caused by the client-side rendering of React Components. We are using Webpack to compile our assets. Will look into it further.

**Comment by Empact** [comment]
@imruiyeah Did you ever figure out the cause? I've run into it now.

**Comment by justin808** [comment]
@Empact Please open a new issue.

**Comment by Empact** [comment]
I solved my issue by excluding node_modules from babel loading. May have a more specific cause figured out later...
