### ISSUE TITLE
Propsal: Inject Redux data to global var instead of dom element

### ISSUE THREAD

**Issue by tiemevanveen** [shakacode/react_on_rails#327]
This is not really an issue, but there is no better place to discuss this then an issue I suppose. I was wondering why you've chosen to serialise the component's props and (especially) the store's data into a data-props attribute instead of adding them to a global variable directly. 

Now this is what you have to do:
* Use `getElementsByClassName` to get all stores's dom nodes
* Traverse over each node 
* Get 2 attributes from each dom node
* `JSON.parse` the data-props
* Populate each store

If you would just store the props in a global var then you only have to do: 
* Check if global var exists
* Traverse over each store
* Populate each store

Something like http://redux.js.org/docs/recipes/ServerRendering.html#inject-initial-component-html-and-state. 

That might be a bit less expensive right :) ? Or is that even worse for performance because the browser will just ignore the data-attributes while parsing the HTML but will have to parse the whole javascript object.. while loading the page? 

Let me know what you think. I could contribute to the javascript part if you think this is a good idea.

**Comment by justin808** [comment]
We used to do something like this this with a script tag on the page. However, that did not seem to work for turbolinks integration. The best way to try out these ideas is to prototype them. A good place to start is the /spec/dummy sample app.

**Comment by tiemevanveen** [comment]
> We used to do something like this this with a script tag on the page. However, that did not seem to work for turbolinks integration. The best way to try out these ideas is to prototype them.

Check, that makes sense. 

> A good place to start is the /spec/dummy sample app.

I'm actually using https://github.com/Limenius/ReactBundle which relies on you guys. And since I'm totally not familiar with ruby prototyping would be hard.. It seems PHP is a bit behind here ;)

**Comment by justin808** [comment]
@tiemevanveen FWIW, you can use turbolinks with PHP now that it's a pure JS library. I sent you an invite to our slack channel.
