### ISSUE TITLE
Undefined method generator function

### ISSUE THREAD

**Issue by bshyong** [shakacode/react_on_rails#337]
Hi guys, I tried to upgrade from v2 to v3, but after doing so, I'm getting this error:

```
NoMethodError: undefined method `generator_function=' for #<ReactOnRails::Configuration:0x007f83427c50e8>
```

Any idea how I can resolve this? I've traced it down to the initializer file react_on_rails.rb, but I haven't changed the contents of the file.

**Comment by justin808** [comment]
@bshyong Please update to latest and see the example [react_on_rails.rb](https://github.com/shakacode/react_on_rails/blob/master/spec%2Fdummy%2Fconfig%2Finitializers%2Freact_on_rails.rb)

**Comment by bshyong** [comment]
great, thanks @justin808.  That fixed the generator issue. The only issue now is that Rails can't find the javascript file in `application.js`... any ideas?

`couldn't find file 'react_on_rails' with type 'application/javascript'`

**Comment by justin808** [comment]
@bshyong We removed that asset at v2. Please use v4 and remove that line.
