### ISSUE TITLE
ERROR in only one instance of babel-polyfill is allowed

### ISSUE THREAD

**Issue by seoyoochan** [shakacode/react_on_rails#338]
When I do server-side rendering and click `<a href="/link">link</a>`,
I get this `ERROR in only one instance of babel-polyfill is allowed `.
Instead, as a workaround, we can fix it when you replace anchor tag with `<Link to='/link'>link</Link>`.
please reproduce this error.
thanks.

**Comment by justin808** [comment]
@seoyoochan `Link` is for react-router.

Can you create a small example with this issue?

The easiest is to modify the demo in https://github.com/shakacode/react_on_rails/blob/master/spec%2Fdummy%2FREADME.md

**Comment by seoyoochan** [comment]
@justin808 I think it's caused by the outdated version of babel-related packages from client/package.json.
I don't see this error on the [tutorial](https://github.com/seoyoochan/react-webpack-rails-tutorial/tree/feataure/update-comments-count-with-sharedReduxStore), but there is another issue going on.
whenever you click any anchor tag, chrome opens up stack console although there's no written `debugger` in any file.

**Comment by seoyoochan** [comment]
@justin808 
![Image1](http://i.imgur.com/hznv4Ta.png)
![code](http://i.imgur.com/Ho5LwsC.png?1)

**Comment by justin808** [comment]
@seoyoochan you're probably importing this package twice.

This is a common problem. 

This is how ensure only one instance of react.

See https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client%2Fwebpack.client.base.config.js#L33


```js
  resolve: {
    extensions: ['', '.js', '.jsx'],
    alias: {
      libs: path.join(process.cwd(), 'app', 'libs'),
      react: path.resolve('./node_modules/react'),
      'react-dom': path.resolve('./node_modules/react-dom'),
    },
  },
```

**Comment by seoyoochan** [comment]
@justin808 I did not import the package twice. I fixed it when I removed `//=require turbolinks` from a js file.

**Comment by justin808** [comment]
@seoyoochan for some reason, turning off turbolinks is fixing the issue for you. I think that indicates a problem with your turbolinks configuration.

**Comment by BrianTatum** [comment]
I am having the same error thrown in my console. I added "libs: path.join(process.cwd(), 'app', 'libs')," to my webpack.config.js file from the above post. I am using the React_on_Rails gem v6. Is there an updated version that fixes this problem or another work around? I did add a react component with npm called react-big-calendar. Can that be the problem? Other than this problem, great Gem for adding React.js into Rails!!

**Comment by justin808** [comment]
@BrianTatum Please try the latest version! We've had some updates!

**Comment by dineshPallapa** [comment]
I am also facing the same issue with babel-polyfill.  I tried by adding 'libs: path.join(process.cwd(), 'app', 'libs'),' to my webpack.config.js but It didn't help me to resolve it. I am able to reproduce this issue while navigation from one page to other with rails routes.

**Comment by szyablitsky** [comment]
I solved this issue by adding this code into my client package
```
if (!global._babelPolyfill) require('babel-polyfill')
```

**Comment by dineshPallapa** [comment]
@szyablitsky Thanks a lot Its works fine Issue was resolved now.

**Comment by rteobaldo** [comment]
@szyablitsky thanks very much, this worked with me too.
