### ISSUE TITLE
Integration with an engine

### ISSUE THREAD

**Issue by Riccardo-Zanutta** [shakacode/react_on_rails#342]
Hello, 
We're trying to integrate the gem in a custom engine-based Rails application.
We're following this[ guide](https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/installation-overview.md), but we're having some troubles integrating  config/initializers/react_on_rails.rb file inside our engines.
Any cloue about how to do this?
Thanks

**Comment by justin808** [comment]
Hi @Riccardo-Zanutta, in terms of an engine, ReactOnRails is probably not any different. However, without a code example, I really can't provide more advice.

**Comment by Riccardo-Zanutta** [comment]
Sorry for the late response,
We have a main application holder ( A classic Rails application ). In our vendor/ folder there are our engines:

![screenshot 2016-04-01 01 31 46](https://cloud.githubusercontent.com/assets/8215555/14193960/d7f771c2-f7a9-11e5-8da9-2b17bb63862f.png)

We use the project_view engine as our 'view manager', a general engine to store **the components about the main admin panel**:

![screenshot 2016-04-01 01 33 22](https://cloud.githubusercontent.com/assets/8215555/14193984/0d56586a-f7aa-11e5-9194-315a725f7826.png)

- We run the generator inside our engine.

- In order to run the node server and the rails one both through foreman, we have to start the command in our **application holder**. 

Do we have to "link" the webpack configuration to our applications holder in some way?

**Comment by tmock12** [comment]
I also have a related engine specific question. How are people dealing with the `run build:client` related commands?

For example, a rails app has my engine included (that contains `react_on_rails`). When that rails app gets deployed to Heroku (for instance), and tries to run the `lib/tasks/assets.rake` its going to try and `cd client && npm run build:client` but that won't work as there is no `client` folder on the requiring rails app...

any thoughts on how others with engines are handing it? are they just including the `app-bundle.js` and `vendor-bundle.js` in git?

**Comment by justin808** [comment]
I'm not sure what to do about this one. I think we need a simple open source sample app, and then I can provide feedback on that and we can figure out what, if anything, needs to change in the ReactOnRails gem. See https://github.com/shakacode/react-webpack-rails-tutorial/ and the https://github.com/shakacode/react_on_rails/tree/master/spec/dummy sample apps.

**Comment by jbhatab** [comment]
@tmock12 @Riccardo-Zanutta interesting scenario. The linking solution makes sense but is definitely not ideal. Can you give me more context on the problem and why you're adding react_on_rails only to the engine? I've never tried this so it may help me figure out the ideal solution.

**Comment by aCandidMind** [comment]
We're doing it in a similar way with symlinks (adding one to Rails.root to point at the actual client dir) because the client folder is actually in the folder of a submodule gem. Would be nice to be able to configure it so that `assets:precompile` doesn't break on the [cd client](https://github.com/shakacode/react_on_rails/blob/6.0.4/lib/tasks/assets.rake#L90).

**Comment by noahprince22** [comment]
@aCandidMind, @tmock12 I found a slightly better solution than linking the client directory. It involves removing and redefining the rake task that tries to get into the client directory. I described the solution in #562 on [this comment](https://github.com/shakacode/react_on_rails/issues/562#issuecomment-257891002)
