### ISSUE TITLE
foreman shouldn't be listed in the gemspec

### ISSUE THREAD

**Issue by modosc** [shakacode/react_on_rails#346]
from foreman's [README.md](https://github.com/ddollar/foreman)
```
Ruby users should take care not to install foreman in their project's Gemfile.
```
this causes some weird things to happen and makes random code break, is there a specific reason you have it listed as a dep?

**Comment by justin808** [comment]
@modosc We actually spoke to a number of people about this. This applied to older versions of foreman. You can find the details here: https://github.com/ddollar/foreman/issues/573

I started out following this, and then updated it per the community advice.

**Comment by justin808** [comment]
> this causes some weird things to happen and makes random code break, is there a specific reason you have it listed as a dep?

@modosc If you could provide a specific example, I'd surely take it out of the gemfile.

**Comment by modosc** [comment]
i'll try to come up with a simplified use case that demonstrates our problem and open a new issue. for now i have a fork that removes that line from the gemspec which is enough to work around it.
