### ISSUE TITLE
Positive Feedback -- Images for KUDOS.md

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#347]
### Compared to Browserify

See comments [here](https://lorefnon.me/2015/11/15/a-minimal-setup-for-using-es6-modules-in-rails.html)

![2016-03-23_16-24-51](https://cloud.githubusercontent.com/assets/1118459/14006786/ebf8cac2-f114-11e5-80f9-4a6d437dd071.png)

**Comment by justin808** [comment]
https://twitter.com/ollieglass/status/713372606804729856

![2016-03-25_07-40-01](https://cloud.githubusercontent.com/assets/1118459/14053652/d05480f0-f276-11e5-9d9a-62d1146cd82d.png)

**Comment by justin808** [comment]
🎉 👏 😌 Live in production with multi-lingual JS support! https://deliveroo.co.uk/ 

![2016-05-03_19-18-34](https://cloud.githubusercontent.com/assets/1118459/15027253/91fd151a-11de-11e6-93e3-720518995fe0.png)

**Comment by justin808** [comment]
![2016-05-10_18-19-32](https://cloud.githubusercontent.com/assets/1118459/15170483/f00e344c-16e1-11e6-93f6-ded2637b227b.png)

**Comment by justin808** [comment]
![2016-05-10_19-44-47](https://cloud.githubusercontent.com/assets/1118459/15171130/b87248ba-16e7-11e6-9ce3-f9799061f23c.png)

**Comment by justin808** [comment]
![2016-05-11_00-54-57](https://cloud.githubusercontent.com/assets/1118459/15178739/1549ec2a-1713-11e6-961c-dc064186fc69.png)

**Comment by justin808** [comment]
![2016-05-11_01-17-57](https://cloud.githubusercontent.com/assets/1118459/15179255/47418adc-1716-11e6-975e-c659a7de54d7.png)

**Comment by justin808** [comment]
![2016-05-19_22-30-15](https://cloud.githubusercontent.com/assets/1118459/15421919/73d2c186-1e11-11e6-967d-a2592e639382.png)

**Comment by jbhatab** [comment]
@justin808 I love this thread, but can we close this so my OCD can calm down :P?

**Comment by justin808** [comment]
@jbhatab Nah! ;-) I use this to add images and from there, we can link in markdown documents.

**Comment by justin808** [comment]
### 2016-08-09

![2016-08-09_13-39-08](https://cloud.githubusercontent.com/assets/1118459/17543077/bf7c2c6a-5e69-11e6-8370-d714015c0296.png)

**Comment by justin808** [comment]
![2016-09-11_17-55-46](https://cloud.githubusercontent.com/assets/1118459/18424209/0c8bdade-7849-11e6-96a7-3b58b26308ce.png)

**Comment by justin808** [comment]
undeveloped.com uses React on Rails:

![2016-10-15_08-10-37](https://cloud.githubusercontent.com/assets/1118459/19623698/3188cb5c-9870-11e6-8050-65e8b568d33a.png)

**Comment by justin808** [comment]
![2016-11-09_19-28-32](https://cloud.githubusercontent.com/assets/1118459/20163679/405229ca-a6b3-11e6-8dff-6dc3f59bf341.png)

**Comment by justin808** [comment]
![2016-10-29_17-10-25](https://cloud.githubusercontent.com/assets/1118459/20163712/72307a82-a6b3-11e6-9c46-aee526192b23.png)

**Comment by justin808** [comment]
https://github.com/shakacode/react_on_rails/pull/591#issuecomment-258685925

![2016-11-15_08-36-29](https://cloud.githubusercontent.com/assets/1118459/20318599/ec4882b0-ab0e-11e6-83e2-7f398e2cdf5b.png)

**Comment by justin808** [comment]
November 15, 2016

![2016-11-15_18-15-31](https://cloud.githubusercontent.com/assets/1118459/20334680/23eaab0c-ab60-11e6-8830-8528c2f829a3.png)

**Comment by justin808** [comment]
http://foxford.ru/

![2016-12-17_13-23-21](https://cloud.githubusercontent.com/assets/1118459/21290375/0a269aa4-
c45c-11e6-9efb-63054f499cec.png)

**Comment by justin808** [comment]
## December 20, 2016

![2016-12-25_10-02-17](https://cloud.githubusercontent.com/assets/1118459/21472700/70242a1e-ca89-11e6-9522-fb45f7835bbb.png)

**Comment by justin808** [comment]
![2017-01-30_11-33-59](https://cloud.githubusercontent.com/assets/1118459/22443635/b3549fb4-e6e3-11e6-8ea2-6f589dc93ed3.png)

**Comment by justin808** [comment]
## March 2, 2017, on LinkedIn

https://www.linkedin.com/feed/update/urn:li:activity:6243173692558319616/

![2017-03-05_21-34-34](https://cloud.githubusercontent.com/assets/1118459/23600716/0d8c40d6-01ec-11e7-998d-4ce9e6abcacb.png)

**Comment by justin808** [comment]
## March 23, 2017, github issue #766.

![2017-03-23_17-43-17](https://cloud.githubusercontent.com/assets/1118459/24279884/badab166-0ff0-11e7-87ab-94253f55a3d9.png)

**Comment by justin808** [comment]
## March 21, 2017, Twitter from [@rfc2616](https://twitter.com/rfc2616)

![2017-03-24_20-20-20](https://cloud.githubusercontent.com/assets/1118459/24319983/7adfd57a-10cf-11e7-9a50-5c23d5d5bcab.png)

**Comment by justin808** [comment]
https://twitter.com/railsonmaui/status/850094315900678145

![2017-04-06_16-11-51](https://cloud.githubusercontent.com/assets/1118459/24786595/75bb2b9c-1afe-11e7-8051-8c9046c4e007.png)

**Comment by justin808** [comment]
## May 9, 2017, by Email

![image](https://cloud.githubusercontent.com/assets/1118459/25869348/b1bd27ce-349b-11e7-912c-11d05ab2bf4d.png)

**Comment by justin808** [comment]
## June 9, Github Issue [#868](https://github.com/shakacode/react_on_rails/issues/868)

![image](https://user-images.githubusercontent.com/1118459/26994714-9aac5bb4-4d1d-11e7-8091-a3b08da9b319.png)

**Comment by justin808** [comment]
## September 20, 2017, [ShakaCode Forum](https://forum.shakacode.com/t/new-ror-users-inbound/1014)

![2017-10-07_00-18-43](https://user-images.githubusercontent.com/1118459/31306902-341a537a-aaf5-11e7-8014-28c126a7c975.png)

**Comment by justin808** [comment]
![image](https://user-images.githubusercontent.com/1118459/40891236-9b0b406e-671d-11e8-80ee-c026dbd1d5a2.png)

**Comment by justin808** [comment]
![image](https://user-images.githubusercontent.com/1118459/40905964-2b6bd22e-677b-11e8-97c7-729f8fd02e81.png)

![image](https://user-images.githubusercontent.com/1118459/40906135-9d9eff4c-677b-11e8-9066-9a24beec2b24.png)

**Comment by justin808** [comment]
![image](https://user-images.githubusercontent.com/1118459/40906178-be2e8b7e-677b-11e8-98e0-755ecf6464f9.png)

**Comment by justin808** [comment]
![Uploading orange_logo-8fb7805c7eb95e306efe263dbe27994bfcf3610e0bb5a879f626448889e00515.png…]()

**Comment by justin808** [comment]
![image](https://user-images.githubusercontent.com/1118459/42479546-2296f794-8375-11e8-85ff-52629fcaf657.png)

**Comment by justin808** [comment]
![image](https://user-images.githubusercontent.com/1118459/44008223-9b29d1b8-9e3c-11e8-90a8-9d38dc241ef9.png)

**Comment by justin808** [comment]
![2018-09-09_15-08-04](https://user-images.githubusercontent.com/1118459/45467837-4eaf8500-b6bd-11e8-9cbd-62d15c96250c.png)

![2018-09-11_11-00-16](https://user-images.githubusercontent.com/1118459/45467844-58d18380-b6bd-11e8-9610-ec5a6e2d7665.png)

![2018-09-11_10-31-11](https://user-images.githubusercontent.com/1118459/45467845-5bcc7400-b6bd-11e8-91e1-e0cf806d4ea4.png)

**Comment by justin808** [comment]
# HVMN Testimonial, Written by Paul Benigeri, October 12, 2018

For some years, we used React on Rails for server-side rendering at [HVMN](https://hvmn.com). Our entire backend was already built in Rails, and we love React. As a content & e-commerce site, server-side rendering is critical, for UX performance and SEO crawler indexing.

During the 12 months leading up to our React on Rails Pro transition, our traffic grew 10x. Our team of 2 engineers was focused on shipping features, and we started to face performance issues. We had some fragment caching of our React server rending, but it didn’t work that well.

I discussed our growing pains with Justin, and as it turned out, ShakaCode just came out with React on Rails Pro and set it up on EggHead.io. The performance improvements were impressive, and Justin’s team was an ideal partner to help with the integration.

We decided to give it a shot. Over 3 weeks, the ShakaCode team helped us migrate to React on Rails Pro, set up Webpack v4, migrated our entire asset pipeline to Webpack v4.

Results were great. Our blog and product pages are 80-90% faster after that effort. The improved fragment caching was quick to set up and made a huge dent in our average server response times. We also observed an additional drop in response times when ShakaCode shipped the standalone Node server-side React renderer.

Working with ShakaCode was a pleasure. Justin is one of the smartest Rails architects I know, and his team was responsive and productive.

The price we paid for the consultation + the React on Rails pro license has already been made back a couple times from hosting fees alone. The entire process was super hands off, and our core team was able to focus on shipping new feature during that sprint.

If you have any questions, please reach out.

Paul Benigeri
[paul@hvmn.com](mailto:paul@hvmn.com)
[LinkedIn](https://www.linkedin.com/in/benigeri/)

Related Article: [HVMN’s 90% Reduction in Server Response Time from React on Rails Pro](https://blog.shakacode.com/hvmns-90-reduction-in-server-response-time-from-react-on-rails-pro-eb08226687db)
￼
[![image](https://user-images.githubusercontent.com/1118459/46911126-577abd00-ceee-11e8-86c6-6703ff80fc2f.png)](https://www.linkedin.com/in/benigeri/)

**Comment by justin808** [comment]
# ResortPass Testimonial, by Leora Juster, December 10, 2018

Many can write code that "works." Even fewer can write sophisticated code that both works and reflects a deep understanding of the technologies and paradigms involved. Only a select few can do the aforementioned while assisting in managing the expectations and time constraints of less technically informed members of software product teams to make the best design decisions possible. Justin and his team were instrumental in assisting us in setting design foundations and standards for our transition to a react on rails application. Just three months of work with the team at Shaka code and we have a main page of our application server-side rendering at exponentially improved speeds. The code and CSS files are well-organized and contain repeatable patterns easy to understand, allowing my team to build on what has already been accomplished. I learned a great deal from my interactions with Justin and his team, as they are just as great teachers as they are developers, and feel like I get to continually learn from them as I build on top of their code. Their different support and pro plan options make it easy to build a continuous professional relationship despite fluctuations in my team's funding, and their team is always extremely personable, punctual, and professional. 

Leora Juster, Full-Stack Lead Software Developer

[LinkedIn](https://www.linkedin.com/in/leora-juster-38933050)

[ResortPass](https://resortpass.com/)

![2018-12-15_20-48-35](https://user-images.githubusercontent.com/1118459/50050866-03858380-00ab-11e9-8588-461112f8045b.png)

**Comment by justin808** [comment]
![2019-09-24_17-48-00](https://user-images.githubusercontent.com/1118459/65567887-96353780-def3-11e9-926d-4a55e2e186ff.png)

**Comment by earkhipov** [comment]
![button-shakacode](https://user-images.githubusercontent.com/10421828/79436256-517d0500-7fd9-11ea-9300-dfbc7c293f26.png)
![reactrails](https://user-images.githubusercontent.com/10421828/79436261-52159b80-7fd9-11ea-994e-2a98dd43e540.png)
![button-reactrailspro](https://user-images.githubusercontent.com/10421828/79436265-53df5f00-7fd9-11ea-8220-fc474f6a856c.png)
![button-community](https://user-images.githubusercontent.com/10421828/79436266-53df5f00-7fd9-11ea-94b3-b985e1b05bdc.png)

**Comment by justin808** [comment]
### [StatusHero](https://statushero.com/)

![2021-04-08_11-33-44](https://user-images.githubusercontent.com/1118459/114099564-b838a580-985e-11eb-9c69-aab298e3e3aa.jpg)
