### ISSUE TITLE
Add trace message to console that indicates server side rendering happened

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#35]
![2015-09-21_11-46-28](https://cloud.githubusercontent.com/assets/1118459/10006066/7ce5aa1e-6056-11e5-8885-ce514f48bbd9.png)

1. Check if trace is turned on
2. Add a message to the console that comes from the server messages: 

Before line: https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/react_renderer.rb#L52
```ruby
      js_code_wrapper = <<-JS
  (function () {
    var result = '';
#{ReactOnRails::ReactRenderer.wrap_code_with_exception_handler(result_js_code, component_name)}
#{after_render}
    return result;
  })()
      JS
```

Using this history.console (https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/react_renderer.rb#L21)

```ruby
    CONSOLE_REPLAY = <<-JS
    var history = console.history;
    if (history && history.length > 0) {
      result += '\\n<script>';
      history.forEach(function (msg) {
        result += '\\nconsole.' + msg.level + '.apply(console, ' + JSON.stringify(msg.arguments) + ');';
      });
      result += '\\n</script>';
    }
```

**Comment by samnang** [comment]
Fix in #38 .
