### ISSUE TITLE
Request specs failing with JS errors, but only on CI

### ISSUE THREAD

**Issue by thewoolleyman** [shakacode/react_on_rails#351]
I'm attempting to add some [request specs](https://github.com/deploysage/deploysage/blob/develop/spec/requests/page_spec.rb), but I'm getting the following types of errors [only on CI](https://circleci.com/gh/deploysage/deploysage/294):

```
ERROR in SERVER PRERENDERING
Encountered error: "ReferenceError: ReactOnRails is not defined"
```

I get no errors when running the exact same thing locally.

All pre-existing mochajs and capybara specs are still running fine on CI.

I suspect it's something not getting loaded by Rails' request spec infrastructure, but I'm confused why it would only fail on CI.  Something environment-specific obviously, but any ideas where to start debugging?  It's painful, gotta debug with vi and prints inside Circle SSH shell since it's only failing there...

Thanks,
-- Chad

**Comment by justin808** [comment]
@thewoolleyman Since ReactOnRails is loaded via `import`, you've probably got an issue with your server (or client bundle) file. I'd debug manually, and confirm it works fine. Then I'd carefully check your scripts for CI. Are you using the current RoR version?

**Comment by thewoolleyman** [comment]
Yes, I just upgraded to the latest rails and react on rails.

**Comment by thewoolleyman** [comment]
Yep, that was totally it.  Need to compile the bundles for request specs, they were already compiled locally.  Did `rake assets:clobber` and they started failing locally, added a call to ensure assets compiled and they started passing on CI.

Shoulda figured that out on my own but thanks for the pointer :)

**Comment by justin808** [comment]
I put a lot of work into ensuring this process is pretty bullet-proof.

**Comment by thewoolleyman** [comment]
We actually had a similar problem on my day job, leftover assets causing confusion.

My idea was that there should be a hook in Rails application startup in an appropriate place, e.g. the environment file, that detects if the Rails asset pipeline is going to use generated-on-the-fly (e.g. unit test env) or packaged (e.g. integration tests or deployed environments) assets.

And if generated/packaged assets aren't going to be used, then proactively and automatically delete them - e.g. everything generated under app/assets and anything that may have been copied locally under public/assets.

Not sure if this would cause other problems, e.g. slowing things down by being too aggressive about cleaning up too often, but it would prevent situations like this that trick even people that should know better, like me.
