### ISSUE TITLE
How to change DOMProperty.ID_ATTRIBUTE_NAME?

### ISSUE THREAD

**Issue by hakunin** [shakacode/react_on_rails#358]
Hi,
since there are Chrome plugins written in react, their dom react ids collide and react creators advise to change ours DOMProperty.ID_ATTRIBUTE_NAME to be unique to our app.

It is important to do this before react is loaded anywhere, so I tried putting this on top of the startup root file:

```
import DOMProperty from 'react/lib/DOMProperty'
DOMProperty.ID_ATTRIBUTE_NAME = 'data-myid'
```

The good thing is that react seems to use that ID (I can see it in DOM), but I also get an error immediately, about react not being able to find a dom node and no event handlers on the page work.

> clientRegistration.jsx?72f2:96 Error: findComponentRoot(..., .0.0.0.$962): Unable to find element. This probably means the DOM was unexpectedly mutated (e.g., by the browser), usually due to forgetting a `<tbody>` when using tables, nesting tags like `<form>, <p>, or <a>`, or using non-SVG elements in an `<svg>` parent. Try inspecting the child nodes of the element with React ID 

Any ideas on where to put the attribute name change? 
The alternative is to fork React unfortunately, which many have had to do.

**Comment by justin808** [comment]
@hakunin No idea on this one. Is this issue really related to React on Rails?

**Comment by hakunin** [comment]
There are two solutions
1) Moving to react v15
2) Changing the variable, but it has to be changed before React is first required - which I was not able to do in that file.

I hope v15 is here soon, since its already rc2 so we can close this.
