### ISSUE TITLE
In the error message handling, we print SERVER_SIDE instead of CLIENT_SIDE

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#36]
This code in: https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/react_renderer.rb#L103

needs to take an option so what we use on the server and client side is different.

We're printing server side for client side messages!
```
console.error('SERVER SIDE: Exception in server side rendering!');
      if (e.fileName) {
        console.error('SERVER SIDE: location: ' + e.fileName + ':' + e.lineNumber);
      }
      console.error('SERVER SIDE: message: ' + e.message);
      console.error('SERVER SIDE: stack: ' + e.stack);
      msg += 'SERVER SIDE Exception in rendering!\\n' +
        (e.fileName ? '\\nlocation: ' + e.fileName + ':' + e.lineNumber : '') +
        '\\nMessage: ' + e.message + '\\n\\n' + e.stack;
```

**Comment by justin808** [comment]
@josiasds Please create a PR.

**Comment by josiasds** [comment]
@justin808 PR #38

**Comment by justin808** [comment]
We also need to indicate if console.log, console.error is happening server side or client side.

**Comment by justin808** [comment]
I changed the strategy a bit:

![2015-09-26_20-25-03](https://cloud.githubusercontent.com/assets/1118459/10121541/d4196dea-648c-11e5-9df1-141bb50ce371.png)
