### ISSUE TITLE
Rails API and webpack build issue

### ISSUE THREAD

**Issue by gwincr11** [shakacode/react_on_rails#360]
Hello,

I have a new application I am trying to get setup. Some of the controllers, not all, are using the rails-api gem. When I added the Gem to my project a peculiar thing started happening. The first page load always errors, sprockets is unable to find vendor-bundle.js. Each subsequent load works as it should. This is causing my specs to consistently fail however.

Any ideas how to fix this?

Thanks,
Cory

**Comment by justin808** [comment]
@gwincr11 You need to study your webpack config files and your npm scripts in package.json.

The example in /spec/dummy has all you need.

**Comment by gwincr11** [comment]
Thanks @justin808 I got it working :+1:
