### ISSUE TITLE
Jasmine Setup

### ISSUE THREAD

**Issue by gwincr11** [shakacode/react_on_rails#368]
Hello,

I am wondering if there is any documentation available regarding setting up Jasmine, or another js testing, suite.

Thanks,
Cory

**Comment by thewoolleyman** [comment]
I played around some with getting Jasmine to work and gave up.  I ended up getting stuck on webpack/css precompilation and dependency issues in the jasmine setup.  It's definitely do-able, but Mocha is all that is supported out of the box for now.

However, if you make any progress in this area, please update this ticket.

**Comment by gwincr11** [comment]
Bummer, is there any reference for getting mocha setup?

**Comment by thewoolleyman** [comment]
Yes, mocha is integrated well and works fine.  The generators will create some example mocha js specs (this is still true, right @justin808 ?), and you can also look at the example app, e.g.: https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/app/bundles/comments/components/CommentBox/CommentList/CommentList.spec.jsx

**Comment by justin808** [comment]
I say we close this issue for now? The full tutorial is probably the best example for now.

Let me know if you want me to re-open this.

**Comment by gwincr11** [comment]
Thanks for all the help, I am playing around with Mocha. We will see how it goes :)
