### ISSUE TITLE
Need to create Wiki or other docs on Testing 

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#37]
FYI -- the messages you get from react_on_rails when you open up the failed test from Capybara are not relevant generally, because the application.js is not loaded, so then you get other messages.

We need to put this information in a wiki, but it's not clear how to add images to a github wiki right now, so this is just a placeholder.

![2015-09-21_13-02-33](https://cloud.githubusercontent.com/assets/1118459/10007521/ab0fe520-6061-11e5-8ba4-a1c650caea8f.png)

**Comment by robwise** [comment]
@justin808 is this still relevant or can we close?
