### ISSUE TITLE
when reboot rails, I get [SERVER] setTimeout is not defined for execJS

### ISSUE THREAD

**Issue by seoyoochan** [shakacode/react_on_rails#372]
I was developing my app with HMR, `foreman start -f Procfile.hot` and got this error on the console for the initial rendering. Refresh or reopen `localhost:3000` doesn't show up this error again, but only appears when rebooting rails.

![img](http://i.imgur.com/F5X93ke.png)

```
[SERVER] setTimeout is not defined for execJS. See https://github.com/sstephenson/execjs#faq
[SERVER] RENDERED App to dom node with id: App-react-component-0
[HMR] Waiting for update signal from WDS...
RENDERED App to dom node with id: App-react-component-0
[WDS] Hot Module Replacement enabled.
 ```

**Comment by justin808** [comment]
@seoyoochan Please upgrade ReactOnRails.
