### ISSUE TITLE
Generator fails on Windows because of `which`

### ISSUE THREAD

**Issue by john-osullivan** [shakacode/react_on_rails#373]
The code which determines whether or not the user has node and npm installed on their system is dependent on `which`, a Unix-only command.  The offending lines are in `install_generator.rb`:

```
 def missing_npm?
        return false unless `which npm`.blank?
        ...
      end

      def missing_node?
        return false unless `which node`.blank?
        ...
      end
```

Some quick Google-ing found this cross-platform Ruby solution for finding executables in the $PATH:

```
# Cross-platform way of finding an executable in the $PATH.
#
#   which('ruby') #=> /usr/bin/ruby
def which(cmd)
  exts = ENV['PATHEXT'] ? ENV['PATHEXT'].split(';') : ['']
  ENV['PATH'].split(File::PATH_SEPARATOR).each do |path|
    exts.each { |ext|
      exe = File.join(path, "#{cmd}#{ext}")
      return exe if File.executable?(exe) && !File.directory?(exe)
    }
  end
  return nil
end
```
Source: http://stackoverflow.com/questions/2108727/which-in-ruby-checking-if-program-exists-in-path-from-ruby

I plugged this method into that file and changed the `` `which node`.blank? `` lines to use the new method: `which('node').blank?`.  Everything seems to be working well.  Not sure if it's worth making my own PR for this small fix, but I thought I'd let y'all know there's an issue.

**Comment by justin808** [comment]
@john-osullivan go ahead and submit a PR. This seems useful. Or get a Mac or Linux machine.

**Comment by kamalkgarg** [comment]
Another solution is install cygwin on windows. This will make Linux commands, such as 'which', available on windows.
Note: Assuming that you are installing cygwin at location c:\cygwin, you will need to add c:\cygwin\bin to your system path on windows. Then you will need to close and reopen the windows command.

**Comment by justin808** [comment]
Is anybody still having this issue? I'm not a huge fan of supporting windows unless a community member joins the maintainers as the official "Windows advocate".

**Comment by mathiasslawik** [comment]
Yes, I was just affected by this issue. If you don't want to support Windows explicitly, then I'd suppose adding a notice to the README, e.g., "Windows: requires cygwin binaries in path".

However, as you're not doing anything OS specific, you don't have to explicitly "support" Windows. Developing Rails and NodeJS under Windows is better than some people suppose.

**Comment by john-osullivan** [comment]
Personally, I worked around this issue by installing the newest version of Windows Insider Preview with Ubuntu on Windows.  `which` now behaves as expected!  As @mathiasslawik pointed out, though, I could've gotten similar results by adding cygwin binaries to my path.

**Comment by jbhatab** [comment]
@john-osullivan I'm gonna close this for now since we don't want to go down the windows support path yet. We'll think about it but just want to clean out some old issues.

**Comment by justin808** [comment]
@john-osullivan, @mathiasslawik, @kamalkgarg, or anybody else...

If any of you want to be committed to helping us support windows, I'm happy to re-open this.

**Comment by mathiasslawik** [comment]
@justin808 I expect that "Ubuntu on Windows" whose final version is expected to arrive in the coming weeks will make life of developers on Windows far easier. react_on_rails already works without problems under Windows (besides the `which` usage), but I expect it to work flawlessly under "Ubuntu on Windows". So, let's wait until it arrives. Then I will test it and record back on this issue.

**Comment by justin808** [comment]
@mathiasslawik Big thanks!
