### ISSUE TITLE
Disable js-react-on-rails-component

### ISSUE THREAD

**Issue by danielhusar** [shakacode/react_on_rails#381]
Hey, is it possible to disable outputting this element when rendering server side ?

**Comment by justin808** [comment]
I don't understand the question.

**Comment by justin808** [comment]
@danielhusar Please open another issue if you're still having problems.

**Comment by danielhusar** [comment]
Hey, sorry I was meaning that hidden div with serialised props when doing server side rendering.
![screen shot 2016-05-06 at 09 44 00](https://cloud.githubusercontent.com/assets/1857751/15068423/1b88a2d6-136f-11e6-8338-1add26f9d175.png)

I use my own custom logic to retrieve state when doing server side rendering, and I would probably prefer something like `window.__INITIAL_STATE__` to store initial state.

**Comment by justin808** [comment]
@danielhusar this is the code that bootstraps ReactOnRails: https://github.com/shakacode/react_on_rails/blob/master/node_package%2Fsrc%2FclientStartup.js

Feel free to submit a PR.

**Comment by danielhusar** [comment]
Yep I know :) But Im not using that module, mainly because I migrated app from express, and I will need possibly to migrate it back so don't want to tie it too much to the rails.

Our mainly concerns are just seo for that hidden div, I can live with it for now :) If it came as issue I will fire the PR, cheers !
