### ISSUE TITLE
Cannot register component

### ISSUE THREAD

**Issue by bartoszbinda** [shakacode/react_on_rails#388]
I have tried to add my own component and I got this message

`import ReactOnRails from 'react-on-rails';
import my_component from 'my_component';
ReactOnRails.register({ my_component });`

Exception in rendering!

Message: Could not find component registered with name MyComponent. 
Registered component names include [ HelloWorldApp ]. Maybe you forgot to register the component?

Error: Could not find component registered with name MyComponent. Registered component names include [ HelloWorldApp ]. Maybe you forgot to register the component?
    at Object.get (<eval>:29066:14)
    at Object.getComponent (<eval>:8021:41)
    at createReactElement (<eval>:28015:46)
    at serverRenderReactComponent (<eval>:30297:72)
    at Object.serverRenderReactComponent (<eval>:8030:54)
    at <eval>:5:23
    at <eval>:12:3

**Comment by justin808** [comment]
MyComponent

or my_component?

**Comment by bartoszbinda** [comment]
my_component
17 kwi 2016 10:22 "Justin Gordon" <notifications@github.com> napisał(a):

**Comment by justin808** [comment]
You are using MyComponent in the view page.
