### ISSUE TITLE
latest version does not support ruby 2.0

### ISSUE THREAD

**Issue by koryteg** [shakacode/react_on_rails#396]
`.rvm/gems/ruby-2.0.0-p594/gems/react_on_rails-5.2.0/lib/react_on_rails/test_helper/webpack_assets_status_checker.rb:12: syntax error, unexpected ','
...itialize(generated_assets_dir:, client_dir:, webpack_generat...`

the file above is using keyword arguments without default values, this feature was not implemented until ruby 2.1

I haven't actually created a gem before so I am not sure what the process is for declaring ruby version dependancies, but it seems like we should be able stop the build on `bundle install`.

**Comment by thewoolleyman** [comment]
I believe this is a duplicate of https://github.com/shakacode/react_on_rails/pull/392

**Comment by koryteg** [comment]
correct ill close
