### ISSUE TITLE
Incorrect port number in README

### ISSUE THREAD

**Issue by shunwen** [shakacode/react_on_rails#402]
In readme's Getting Started section, the last step is to visit port 3000 on localhost. That is incorrect because without `--port` option, foreman runs the process on, starting from, port 5000. Here are how foreman does it:
https://github.com/ddollar/foreman/blob/master/lib%2Fforeman%2Fengine.rb#L276
https://github.com/ddollar/foreman/blob/master/lib%2Fforeman%2Fengine.rb#L360

I can send a PR to fix this, just not sure how you guys would like to have it fixed -- update README or set `--port` in Procfile? Thanks.

**Comment by justin808** [comment]
This is sort of odd, as we get a default port of 3000 in 

https://github.com/shakacode/react-webpack-rails-tutorial/

Did this change recently with foreman?

We'd probably update generator and indicate this in the README.md.

CC: @jbhatab

**Comment by thewoolleyman** [comment]
@justin808 I think Foreman has had that for [a long time](https://github.com/ddollar/foreman/commit/1a0943c495355370a73546d4e049e5010b6d958f), but the tutorial may be getting it overridden [from here?](https://github.com/shakacode/react-webpack-rails-tutorial/blob/a2dd5b63591fdc06c57b3e7c4ebd4d7db067e3fd/config/puma.rb#L12)

**Comment by justin808** [comment]
@thewoolleyman You're absolutely right. 

@shunwen I'm not sure what the fix should be as this really isn't a react_on_rails issue. I'd suppose we should update the README.md to indicate that you should probably set the --port flag, although if you are using puma, see the link from @thewoolleyman above.

**Comment by shunwen** [comment]
@justin808 This is not an issue at all. If simply following the application log, one should have no problem visiting the local server. :smile:

My local tutorial project also runs on port 5000 (by foreman). According to foreman code, it spawns the first process with environment `PORT=5000` unless specified.

**Comment by jbhatab** [comment]
We could just make the Procfile.dev generated have -p 3000 in it.

**Comment by justin808** [comment]
@jbhatab Please be sure to handle this with your generator changes. I'm closing this one.

**Comment by justin808** [comment]
See #467.
