### ISSUE TITLE
Replacing URI.parse with Addressable

### ISSUE THREAD

**Issue by lucke84** [shakacode/react_on_rails#403]
It seems the new `rails_context` method uses `uri = URI.parse(request.original_url)`, which sometimes fails to parse URIs with non-ASCII characters (see **react_on_rails_helper.rb**, line 361)

Here's an example of a real-life(-ish) URI that should be supported but fails on our ReactOnRails powered website:
```
http://mywebsite.com/mypage?myparam=méridien
```
(note the `é` character in `myparam`'s value), returning an error like:
```
URI::InvalidURIError: URI must be ascii only "http://mywebsite.com/mypage?myparam=mm\u{e9}ridien"
```

The [addressable gem](https://rubygems.org/gems/addressable/versions/2.4.0) seems to be a valid alternative (which might become the official replacement for URI in the future). Unless I'm missing something here, is there a possibility to switch to using `addressable`? 

Feedback of what I might be doing wrong (e.g. not encoding properly?) are more than welcome as well.

**Comment by jbhatab** [comment]
@lucke84 interesting. Would you mind making a PR for this?

**Comment by lucke84** [comment]
See https://github.com/shakacode/react_on_rails/pull/405 :)

**Comment by jbhatab** [comment]
@lucke84 looks good. just check out Justins comments, I agree with both of them. Besides that, awesome work.

**Comment by lucke84** [comment]
Happy to help :) The comment have been fixed already, it'd be nice to :shipit: .

**Comment by justin808** [comment]
Merged.
