### ISSUE TITLE
Any ideas how to mute turbolinks output inside tests?

### ISSUE THREAD

**Issue by szyablitsky** [shakacode/react_on_rails#406]
When I run integration tests with Capybara and Poltergeist I have bunch of noise in test output like this
```
TURBO: USING TURBOLINKS 5: document added event listeners turbolinks:before-cache and turbolinks:load.
TURBO: reactOnRailsPageLoaded
TURBO: USING TURBOLINKS 5: document added event listeners turbolinks:before-cache and turbolinks:load.
TURBO: reactOnRailsPageLoaded
.TURBO: USING TURBOLINKS 5: document added event listeners turbolinks:before-cache and turbolinks:load.
TURBO: reactOnRailsPageLoaded
TURBO: USING TURBOLINKS 5: document added event listeners turbolinks:before-cache and turbolinks:load.
TURBO: reactOnRailsPageLoaded
TURBO: USING TURBOLINKS 5: document added event listeners turbolinks:before-cache and turbolinks:load.
TURBO: reactOnRailsPageLoaded
```

Can it be disabled in test environment?

**Comment by justin808** [comment]
@szyablitsky Those are not shown in production. If you poke around at the code, it might be obvious where to turn this off. If you can't find it, let me know.

**Comment by justin808** [comment]
@szyablitsky Did you find what you're looking for?

**Comment by szyablitsky** [comment]
@justin808 did not have time for this issue. I will look at this later.

**Comment by szyablitsky** [comment]
@justin808 I found where production check is. It's in `client/webpack.client.base.config.js`.
```
const devBuild = process.env.NODE_ENV !== 'production';
...
module.exports = {
  ...
  plugins: [
    new webpack.DefinePlugin({
      ...
      TRACE_TURBOLINKS: devBuild,
    }),
```
I do not think that it is possible with current architecture to mute turbolinks only in test environment. Because it uses the same generated files as in development environment. To be clear - I'm talking about running tests in parallel with development (not CI).
So if I want to see clear output from rspec, I have to disable turbolinks tracing at all. And enable tracing only then I have issues with them.
Any thoughts?

**Comment by justin808** [comment]
@szyablitsky All you need to do is create a webpack config for your tests.

I'm going to take a look at this as well. I'm guessing that you're using phantomjs.

Incidentally, I think this more of a configuration issue than an issue with the core of React on Rails.

**Comment by szyablitsky** [comment]
@justin808 Yes, I'm using phantomjs.
I'm not sure that you can use separate config for tests, if you run tests in parallel with development (I'm using guard gem). Tests use the same generated files as development server. And `TRACE_TURBOLINKS` option already transpiled into those generated files.
BTW I agree, this is a configuration issue.

**Comment by justin808** [comment]
@szyablitsky Should we close this issue? Any code change that should be made?

**Comment by szyablitsky** [comment]
@justin808 I do not see any easy ways besides completely disabling Turbolinks in config, and enabling tracing only when needed.

**Comment by justin808** [comment]
@szyablitsky Since the webpack config is a node file, you can read an ENV variable set by CI and configure a global variable to do what you want. It's really not hard to do.

I can find you an example if need be!

**Comment by szyablitsky** [comment]
@justin808 I do not mind if CI log will be filled with Turbolinks traces, I was talking about tests that run in _parallel_ with development. I.e. with guard.

**Comment by justin808** [comment]
@szyablitsky Yes, that's pretty much impossible unless you want to build the JS files twice every time you save, which is really not worth the slowdown.
