### ISSUE TITLE
[Beginner question] Install packages via NPM

### ISSUE THREAD

**Issue by hafizio** [shakacode/react_on_rails#409]
I'm using the latest bootstrap 4 (https://github.com/twbs/bootstrap-rubygem). They suggested to use rails-asset to install the javascript dependecies (tether package). Is there any way I can use webpack to replace rails-asset (which is dependent on bower)?

I tried installing the tether package via `npm install tether --save`, but the bootstrap-sprocket in application.js is unable to find the tether package.

**Comment by justin808** [comment]
You can use bootstrap either via the asset pipeline (nothing to do with React on Rails) or you can follow the recipe here: https://github.com/shakacode/react-webpack-rails-tutorial/ and use webpack to create your CSS. In either case, I'll try to help with your questions, but this is not an open issue for React on Rails.

**Comment by hafizio** [comment]
I manage to do this by installing the tether package using npm and expose the package to rails app by loading it in module loaders. Thanks @justin808
