### ISSUE TITLE
Upgrading from 3.0 to 5.0

### ISSUE THREAD

**Issue by murtali** [shakacode/react_on_rails#414]
Wanted to know the best steps to upgrade from 3.0 to 5.0.
I didn't see any guides for 3,4 or 5 in the changelog.md  (like you had for 1->2 or 2->3)
I've already done the gem update but wasn't clear on changes to get the latest react / react router or any other changes in /client

Thanks

**Comment by thewoolleyman** [comment]
You can find out a lot by looking at the history and latest state of the https://github.com/shakacode/react-webpack-rails-tutorial example app.  E.g. if you look at the git history of when the gem/npm module was bumped you can see what changed at the same time.

**Comment by justin808** [comment]
@murtali that means you didn't have to do anything. If you want to use the new features, that's up to you. There might be some deprecations.
