### ISSUE TITLE
Tests fail randomly on Travis because vendor-bundle is not found

### ISSUE THREAD

**Issue by UberMouse** [shakacode/react_on_rails#416]
Successful build: https://travis-ci.org/DigitalNZ/supplejack_website/builds/129327414
Failed build: https://travis-ci.org/DigitalNZ/supplejack_website/builds/129342103
.travis.yml: https://github.com/DigitalNZ/supplejack_website/blob/tl/react-refactor/.travis.yml

It fails more often than it succeeds, I'm not sure if I have something misconfigured in the project setup or the .travis.yml? Any ideas?

The code: https://github.com/DigitalNZ/supplejack_website/tree/tl/react-refactor

**Comment by justin808** [comment]
@UberMouse Try out v6 tomorrow. I've made some updates regarding this area.

**Comment by UberMouse** [comment]
Awesome, I'll give it a look.

**Comment by justin808** [comment]
I just made 6.0.0.beta.5 for you.

See this branch: https://github.com/shakacode/react_on_rails/pull/417
Be sure to read the CHANGELOG and update your config/react_on_rails.rb.

I'll answer any questions you have when I get up tomorrow. Thanks for trying this out. Your help will accelerate the shipment of v6!

**Comment by justin808** [comment]
btw -- if this passes CI, I might merge to master in 15 min. Then you can submit PRs for any doc or other issues.

Thanks!

We also have a slack discussion room if you want to join.

**Comment by UberMouse** [comment]
Sure, I'll join tomorrow. We're planning on using this in a few projects at work so I'm sure it will come in handy.

**Comment by justin808** [comment]
6.0.0.rc.1 is READY!

**Comment by UberMouse** [comment]
I've upgraded to the 6.0.0-rc.1 and it's solved the issue I had with the tests rebuilding the webpack assets every time (and somehow my test suite has gone from taking ~1 minute to 2 seconds) but I think that may be because it's just not attempting to build them at all. If I `rm -rf app/asstes/webpack/*` and turn off the webpack dev server all the tests fail because the bundle isn't found and it doesn't even attempt to build it. It does attempt to build on Travis for some reason but it never completes and the build gets killed after 10 minutes of inactivity

6.0.0 upgrade: https://github.com/DigitalNZ/supplejack_website/commit/9acc2ad2fa1615beab4c6efb48e28a6831dc6563
Travis build: https://travis-ci.org/DigitalNZ/supplejack_website

It's probably easier if I join the slack channel, my work email is `taylor@boost.co.nz` if I could get an invite that would be great, thanks!

**Comment by UberMouse** [comment]
Ok the Travis issue was my fault, poinited the test command at a webpack command that had `-w` so that's working fine now. Still facing the issue where it doesn't build the assets when I run rspec locally.

**Comment by UberMouse** [comment]
Seems like the tests are still failing intermittently on Travis https://travis-ci.org/DigitalNZ/supplejack_website/builds/129574156

**Comment by UberMouse** [comment]
Ok the test issue locally was just some stupidity on my part. I had completely forgotten I skip tests marked slow locally and that I had marked the feature tests that make use of React components with slow..

So fixing that mistake the tests seem to be working correctly now, it does still say "Building Webpack assets..." but it finishes but it finishes faster than before. I'm not sure if that is my new machine or if it's making use of the already built assets?

**Comment by justin808** [comment]
>  I'm not sure if that is my new machine or if it's making use of the already built assets?

React on Rails v6 is much smarter about the building assets. It's key that `config/react_on_rails.rb` is configured correctly. Thanks for trying out v6! Let us know ASAP if you run into any issues.

**Comment by UberMouse** [comment]
@justin808 it doesn't look like v6 has solved my problems. It seems to be better but I just got another travis failure because it can't find the 'vendor-bundle' file after three test builds.

**Comment by UberMouse** [comment]
This is still happening with 6.0.0-rc1 npm and master gem from 11 days ago. Haven't looked into newer updates.

https://travis-ci.org/DigitalNZ/supplejack_website/builds/132161621
