### ISSUE TITLE
Add node.js generator part -- was removed

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#421]
@alleycat-at-git @jbhatab We need an install option for the node part. We'll use this PR to track what's missing. I also removed the node from https://github.com/shakacode/react_on_rails/edit/master/lib/generators/react_on_rails/templates/base/base/Procfile.dev.tt

```
node: sh -c 'cd client/node && npm start'
```

See #418.

**Comment by robwise** [comment]
Sounds good, a note on organization: let's definitely put this in its own generator, and then if we want to simply make it an option during the install, we can just invoke this generator at the end of the install and create the node files and append to the Procfile. 

Also, wouldn't the node command also need to go in the production Procfile as well?

**Comment by justin808** [comment]
Regarding the `Procfile`, yes, this would need to be done for a Heroku deployment.

**Comment by justin808** [comment]
@alleycat-at-git Just let me know what you want me to do, and I'll take care of this. I want to finish this for the v6 release.

**Comment by justin808** [comment]
@jbhatab @alleycat-at-git I don't think this is any reason to delay the final release of 6.0.

**Comment by robwise** [comment]
Agreed, no need for delaying v6 as this can just be a minor release since it only adds functionality and won't change/break existing API.

**Comment by jbhatab** [comment]
@robwise agreed.

**Comment by justin808** [comment]
This was done, but it needs work.
