### ISSUE TITLE
Switch docs to recommend mini_racer over execjs

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#428]
https://github.com/discourse/mini_racer might have a big speed up.

Let's try it out!

Any volunteers?

--

## Performance

The `bench` folder contains benchmark.

### Benchmark minification of Discourse application.js (both minified and unminified)

- MiniRacer version 0.1
- therubyracer version 0.12.2

```
$ ruby bench_uglify.rb
Benching with MiniRacer
MiniRacer minify discourse_app.js 13813.36ms
MiniRacer minify discourse_app_minified.js 18271.19ms
MiniRacer minify discourse_app.js twice (2 threads) 13587.21ms
```

```
Benching with therubyracer
MiniRacer minify discourse_app.js 151467.164ms
MiniRacer minify discourse_app_minified.js 158172.097ms
MiniRacer minify discourse_app.js twice (2 threads) - DOES NOT FINISH

Killed: 9
```

The huge performance disparity (MiniRacer is 10x faster) is due to MiniRacer running latest version of V8. In July 2016 there is a queued upgrade to therubyracer which should bring some of the perf inline.

Note how the global interpreter lock release leads to 2 threads doing the same work taking the same wall time as 1 thread.

**Comment by jbhatab** [comment]
That's a big improvement.

**Comment by justin808** [comment]
@jbhatab Any chance that you can try this out? Maybe we can put this into v.7?

**Comment by justin808** [comment]
@robwise Please post some notes here when you get a chance. @robwise told me that MiniRacer was much faster. We really need a PR with doc updates on this.
