### ISSUE TITLE
How would I include assets in a React component?

### ISSUE THREAD

**Issue by chintanparikh** [shakacode/react_on_rails#434]
So I have a partial right now, the code is below (_deal.html.erb). I'm now trying turn that into a React component, but in the partial I have an ```image_tag "img-avatar-1.png"```. How would I include that in the React component? 

I know one option is to pass it in as a prop, but I'm wondering if there's another way to do it that's easier?

```
<div class="project-item">
    <div class="item-percent">
        <div class="progress-pie-chart" data-percent="75"></div>
    </div>
    <div class="item-body">
        <a href="/deals/1" class="item-body__project">
            <div class="title">Cordellia Webb</div>
            <div class="copy">Project Narwhal</div>
        </a>
        <div class="item-body__collaborators">
            <div class="title">Collaborators</div>
            <div class="item-collaborators-wraper">
                <a href="#" class="avatar">
                  <%= image_tag "img-avatar-3.png" %>
                </a>
                <a href="#" class="avatar">
                <%= image_tag "img-avatar-1.png" %>
                <%= image_tag "img-avatar-1.png" %></a>
                <a href="#" class="avatar"><%= image_tag "img-avatar.jpg" %></a>
                <a href="#" class="avatar"><%= image_tag "img-avatar-4.png" %></a>
            </div>
        </div>
        <div class="item-body__timestamp">
            <div class="title"><span class="timestamp">March 18th</span></div>
        </div>
    </div>
</div>
```

**Comment by justin808** [comment]
@chintanparikh If the image is more of a CSS background image, then handle that with CSS.

Otherwise, with image tags, you need to decide if you will use the asset pipeline and fingerprint the images. In that case, you need to pass the image path as a prop.

**Comment by chintanparikh** [comment]
Here's my solution for anyone who sees this in the future:

Add `gem "non-stupid-digest-assets"` to Gemfile - this will create two copies of your assets, one which is fingerprinted and one which is not. Note that if you don't supply a whitelist (next step), it will do this for all assets, and will make asset compilation take twice as long.

Next, I created 'config/initializers/non-digest-assets.rb` with the following line:

```
NonStupidDigestAssets.whitelist += ["*.jpg", "*.png", "*.svg"]
```

Now I can just reference my images using the path `/assets/image_name.jpg`

**Comment by justin808** [comment]
@chintanparikh @jbhatab This might be worth adding to /docs/additional-reading.
