### ISSUE TITLE
Does it support working with rails cells

### ISSUE THREAD

**Issue by chrisyeung1121** [shakacode/react_on_rails#443]
https://github.com/apotonick/cells

**Comment by jbhatab** [comment]
@chrisyeung1121 It looks like cells just abstract some view code. As long as the view helper gets called like it normally does in the views then I don't see why it wouldn't work.

**Comment by chrisyeung1121** [comment]
For react-rails it has to include React::ViewHelper. I wonder if ReactOnRails have this helper I can include in cells.

**Comment by justin808** [comment]
@chrisyeung1121 Can we close this issue?
