### ISSUE TITLE
Multiple webpack-bundle.js files with server rendering

### ISSUE THREAD

**Issue by Tamiyadd** [shakacode/react_on_rails#448]
Hi guys,
i was wondering if it's possible to have multiple wepack-bundle.js files (obviously with different name) and load them depending on which application.js file is loaded.
I have an app with multiple application.js and i want to use different bundles to lighten my .js file.
I'm using server rendering and in `react_on_rails.rb` initializer i see `config.server_bundle_js_file = "webpack-bundle.js"` for only a single file so i don't know how to use multiple bundle files

thanks

**Comment by justin808** [comment]
We had previously discussed this for localization reasons and then deemed it not necessary due to the addition of the `railsContext`. Since this is server rendering, there's no reason to add the extra complexity of multiple JS files. If you have use case, add it here, and we'll re-open this ticket.

@martyphee might be able to share his experience on how he thought he needed multiple files but didn't.

**Comment by martyphee** [comment]
[We use multiple js files in production right now](deliveroo.co.uk).  Not all the pages are converted to React yet.  Right now we have four bundles for the application.  app-bundle for the landing page, checkout for the checkout rewrite I just did (only employees right now in the UK), corporate ordering and the new corporate portal.

Is that what your talking about?  We only have one server bundle.  What I originally need to figure out was how to loaded translations.  We don't use the Rails i18n.  We use `gettext` with `jed`.  I ended up loaded those and putting them into the `railsContext`.  You can see that if you go to the homepage.  Our goal is to have country specific files at some point.

**Comment by fantasydong** [comment]
@Tamiyadd I have the same question like yours. My app has several pages and each page has it own js file. So I want to make all the pages to support server side render but the gem can only set one server render js file. So Have you find out a way to do this? @justin808 @martyphee FYI. Thanks a lot.
