### ISSUE TITLE
"ReferenceError: clearTimeout is not defined on Heroku

### ISSUE THREAD

**Issue by ramusus** [shakacode/react_on_rails#449]
Hi, guys!

Few hours ago after another deploy to Heroku with no essential changes I got error:

```
ERROR when compiling base_js_code! See file tmp/base_js_code.js to correlate line numbers of error. Error is
2016-06-11T00:19:30.146600+00:00 app[web.1]:
2016-06-11T00:19:30.146601+00:00 app[web.1]: ReferenceError: clearTimeout is not defined
```

Full stack here http://pastebin.com/LYgpRxZa

I tried to find `base_js_code.js`, but there is no such file in tmp. If I turn off `prerender` feature everything is deploying and working on heroku as it was just one day ago. I compared versions of gems and npm packages - no any visible differences between successful and not successful deploys. I searched for `clearTimeout` string - no any occurrences in my project only in `node_modules` directory. The problem is this error happens only on Heroku servers. Locally everything is working with pretender as well as without. But If I put `clearTimeout` call into any of my react component - I got the same error locally. 

May be there is a way to define this bloody `clearTimeout` only for server prerender environment?

Completely stacked..

Any ideas what to do?

**Comment by justin808** [comment]
@martyphee is also seeing this. This will take some investigative work.

If this is during server rendering, we should polyfill this, as we do here:

https://github.com/shakacode/react_on_rails/blob/cf29f7e6b7e9459401bd047c406124b43b9238f7/docs/additional-reading/server-rendering-tips.md#L21

https://medium.com/@railsonmaui/homeway-and-introducing-friends-and-guests-d4d365c6ad8d#.v8ttay83d

If this is during deployment and asset compilation, I really don't know.

@martyphee @ramusus Please let us know what you find and if you have a fix, please submit a PR.

**Comment by martyphee** [comment]
This is happening only after deployment.  I wasn't able to reproduce it locally.  Only on the server.

**Comment by xiaopow** [comment]
Hey guys, seeing the same thing since yesterday. No changes in npm and gem packages.

**Comment by martyphee** [comment]
I'd really like to find out what caused this.  We can't have this happening since we deploy 10-20 times a day to production.  Something minor had to be changed.

**Comment by martyphee** [comment]
It's some shim.  Need to find where it's coming from.

![image](https://cloud.githubusercontent.com/assets/754870/15986391/7c2f2ef6-2fcc-11e6-9ff0-fc9a54c47726.png)

**Comment by justin808** [comment]
We just need to polyfill to it probably.

**Comment by Tamiyadd** [comment]
Hi guys, i'm having the same problem and i found that is due by `process` npm package

Here the issue
https://github.com/defunctzombie/node-process/issues/60

reverting back to `0.11.3` version worked well.

**Comment by ramusus** [comment]
Confirmed, after I put process@0.11.3 into `package.json`, deploy to Heroku with prerender enabled started to be successful.

**Comment by Tamiyadd** [comment]
A little update,
`process` developers released an update that fix the bug. Also version `6.0.4` of react on rails works too

**Comment by ramusus** [comment]
Great! Closing this issue! Thanks for quick support!

**Comment by h8rry** [comment]
Works for us too. Thanks!
