### ISSUE TITLE
How to plug my own fork of npm part of this project?

### ISSUE THREAD

**Issue by ramusus** [shakacode/react_on_rails#452]
I'm trying to make working this project with relay and found this PR  https://github.com/shakacode/react_on_rails/pull/285/files. Now I want to continue developing in my own fork. I plugged my own forked gem easily, but with npm I got some troubles.

First I tried to install it using in `package.json`
```
"dependencies": {
   "react-on-rails": "ramusus/react_on_rails",
    ....
```

This way let me to install only 3 meta-files in `node_modules/react-on-rails/` and no any source files. Then I tried 
```
"dependencies": {
   "react-on-rails": "https://github.com/ramusus/react_on_rails/tarball/64c24ca26971f2a2dce1e4b45d03c111022f126d"         

```

this way let me to install all repo, but without transpilling content of `node_package/src` directory to `node_package/lib`.

What is the correct way to do it? Thanks for any advice.

**Comment by ramusus** [comment]
Found solution: just clone my repo to the `node_modules/react-on-rails` and run `npm run build` command. it will build `lib` directory.

**Comment by ramusus** [comment]
But I'm not sure this solution is the best. Now when I run "npm install" I got the error

```
npm ERR! git Appears to be a git repo or submodule.
npm ERR! git     /.../client/node_modules/react-on-rails
npm ERR! git Refusing to remove it. Update manually,
npm ERR! git or move it out of the way first.
```

**Comment by justin808** [comment]
@ramusus Should we keep this issue open?

**Comment by ramusus** [comment]
I would prefer to clarify this question in case I still don't know how to do it properly. But I'm agree this is not tightly related to this project. This question about how to plug fork of ANY npm package to the project, so I agree if you prefer to move it to stackoverflow, for example

**Comment by justin808** [comment]
@ramusus Take a look at this: https://github.com/shakacode/react_on_rails/search?utf8=%E2%9C%93&q=version&type=Code

We have code that ensures the version of the gem and npm package match up. Beyond that, it's just standard node package development. FWIW, we had lots of trouble with the npm-link feature. Sometimes it's worked. Sometimes it didn't, depending on the node version.

**Comment by ramusus** [comment]
@justin808 yes, I found these lines and temporary commented them. I will close this issue right now, because it's not completely related to this project. thanks a lot for advice
