### ISSUE TITLE
add hypernova support

### ISSUE THREAD

**Issue by rstormsf** [shakacode/react_on_rails#453]
If you haven't heard of https://github.com/airbnb/hypernova - you should.
https://github.com/airbnb/hypernova-ruby - ruby client

**Comment by justin808** [comment]
@rstormsf Can you tell me more about why we'd use this with or instead of React on Rails?

**Comment by rstormsf** [comment]
it's not instead. it's in addition to

**Comment by justin808** [comment]
@rstormsf How about a doc file in /docs/additional-reading folder? Or maybe a PR? I'm not sure what you're suggesting? Any example repos? I'd love to hear more. Would you like a slack invite to our discussion room?
