### ISSUE TITLE
Debug tool

### ISSUE THREAD

**Issue by BrunoQuaresma** [shakacode/react_on_rails#455]
When i create my component with something wrong the console only shows errors in the startup files and not in a specific file. Example.:

I create my component Hello with a bad method but when i run in the browser and open the console it shows errors in clientRegistration.jsx like 'module Hello not found'. 

Have a way for the console be more specific... like 'the method x is invalid'  and not a generic error.

**Comment by justin808** [comment]
@BrunoQuaresma I really don't think so at Runtime. I'm guessing that the webpack compilation may have told you there was an error, at build time. Please double check.

**Comment by BrunoQuaresma** [comment]
Ok Thanks
