### ISSUE TITLE
How to do chunk splitting?

### ISSUE THREAD

**Issue by hakunin** [shakacode/react_on_rails#458]
Hi,
I've started looking at the code size and want to split off a couple of chunks.

I got webpack to split the files a bit already, but how do I make sure the correct chunks are loaded when they should be loaded?

I can include / omit files in the layout based on what page I am looking at, but I am more interested in loaded the right files on the fly, since the initial setup time of only a 2M (minified) js file takes around 500ms off every request currently.

**Comment by justin808** [comment]
@hakunin My advice is to put the include directives in the head sections of the pages that need the code.

What else are you thinking of doing?

**Comment by hakunin** [comment]
I ended up doing two things
- split up into multiple chunks using webpack
- add rails asset for each chunk
- include whats needed to load the page in head
- add js variable that lists all the chunks asset paths
- include sub views that you can transition to dynamically by using a wraper component in React router like so:

```
var cardLoaded = false
class CardFormWrap extends React.Component {
  componentDidMount() {
    var self = this
    if (!cardLoaded) {
      $.getScript(context.assets.card_form, () => {
        cardLoaded = true
        self.forceUpdate()
      })
    }
  }
  render() {
    if (cardLoaded) {
      return <div><CardForm {...this.props} /></div>
    } else {
      return <div />
    }
  }
}
```

The wrapper could be simplified and made to fit any component, but including this one here if anyone starts learning about this.

The preffered way to do it would probably be let webpack include the scripts dynamically, but then I couldn't get those into rails asset pipeline and thus in cloudfront and so on.

**Comment by justin808** [comment]
@hakunin Should we close this issue? Is it worth throwing this information into a file under: https://github.com/shakacode/react_on_rails/tree/master/docs/additional-reading

**Comment by hakunin** [comment]
Yeah, this can be closed and it would be nice if the info was somewhere.

**Comment by jbhatab** [comment]
@hakunin we can look into adding this to docs later. for now I'm gonna close this.
