### ISSUE TITLE
Demo App Server Error

### ISSUE THREAD

**Issue by Undistraction** [shakacode/react_on_rails#461]
With the demo app here: [http://www.reactrails.com/?](http://www.reactrails.com/? ) the following message is displayed if a name is entered but no text is entered:

> Your comment was not saved! A server error prevented your comment from being saved. Please try again.

If a value for text is required, this should be indicated and a more appropriate error message should be displayed as it initially appears the app is broken.

**Comment by justin808** [comment]
See: https://github.com/shakacode/react-webpack-rails-tutorial/issues/295
