### ISSUE TITLE
Bootstrap not included by default?

### ISSUE THREAD

**Issue by mtakac** [shakacode/react_on_rails#462]
React on rails generator help message says:

> 1. Bootstrap via Rails Server

        The Rails server loads bootstrap-sprockets, provided
        by the bootstrap-sass ruby gem (added automatically to your Gemfile by
        the generator), via the `app/assets/stylesheets/_bootstrap-custom.scss`
        partial.

However after running the generator, bootstrap is not integrated and there is no bootstrap gem added to the Gemfile. Did something change or am I missing something?

After running the generator my Gemfile looks like this:
```
source 'https://rubygems.org'


# Bundle edge Rails instead: gem 'rails', github: 'rails/rails'
gem 'rails', '4.2.6'
# Use sqlite3 as the database for Active Record
gem 'sqlite3'
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'
# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 1.3.0'
# Use CoffeeScript for .coffee assets and views
gem 'coffee-rails', '~> 4.1.0'
# See https://github.com/rails/execjs#readme for more supported runtimes
# gem 'therubyracer', platforms: :ruby

# Use jquery as the JavaScript library
gem 'jquery-rails'
# Turbolinks makes following links in your web application faster. Read more: https://github.com/rails/turbolinks
gem 'turbolinks'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
gem 'jbuilder', '~> 2.0'
# bundle exec rake doc:rails generates the API under doc/api.
gem 'sdoc', '~> 0.4.0', group: :doc

# Use ActiveModel has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Unicorn as the app server
# gem 'unicorn'

# Use Capistrano for deployment
# gem 'capistrano-rails', group: :development

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  gem 'byebug'
end

group :development do
  # Access an IRB console on exception pages or by using <%= console %> in views
  gem 'web-console', '~> 2.0'

  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'spring'
end

gem 'react_on_rails', '6.0.4'

gem 'therubyracer', platforms: :ruby
```

**Comment by justin808** [comment]
@mtakac This more of a doc and message issue. The idea is that the rails page loads bootstrap the standard Rails way. So this gem is not involved.

On the other hand, if you want to use CSS modules, see this part of the README:

> The generator of React on Rails does not setup CSS modules and hot reloading via the Rails server as is demonstrated in the shakacode/react-webpack-rails-tutorial. We do support this, but we don't generate the code. If you did generate a fresh app from react_on_rails and want to move to CSS Modules, then see PR 175: Babel 6 / CSS Modules / Rails hot reloading. Note, while there are probably fixes after this PR was accepted, this has the majority of the changes. See the tutorial for more information. For more information on how to setup hot reloading in a Rails app, see Hot Reloading of Assets For Rails Development.

@jbhatab Please take a look at the doc issue.

**Comment by jbhatab** [comment]
@justin808 Pretty sured we removed that in the next release candidate.

**Comment by mtakac** [comment]
@justin808 I thought it will be probably just outdated docs. Thanks!

**Comment by justin808** [comment]
@jbhatab @mtakac Can we close this issue?

**Comment by justin808** [comment]
>     The Rails server loads bootstrap-sprockets, provided
>    by the bootstrap-sass ruby gem (added automatically to your Gemfile by
>    the generator), via the `app/assets/stylesheets/_bootstrap-custom.scss`
>    partial.

@mtakac or @jbhatab Can you please submit a PR for this doc change.

**Comment by jbhatab** [comment]
@justin808 I don't see it in master. I think we can close this.
