### ISSUE TITLE
Load 2 times is normal when use prerender equal true?

### ISSUE THREAD

**Issue by BrunoQuaresma** [shakacode/react_on_rails#463]
In my console the component is loaded 2 times. It is normal? 

![captura de tela 2016-06-27 as 18 26 06](https://cloud.githubusercontent.com/assets/3165839/16396419/f9cbfc48-3c94-11e6-832a-19d34cf06646.png)

**Comment by justin808** [comment]
@BrunoQuaresma That message is from React on Rails. 100% expected!

React.js will not redraw the screen. It's optimized for this use case!

**Comment by BrunoQuaresma** [comment]
Thanks one more time @justin808
