### ISSUE TITLE
Uninitialized constant ReactOnRailsHelper::ExecJS

### ISSUE THREAD

**Issue by BrunoQuaresma** [shakacode/react_on_rails#471]
This error is showing in my prod server. 

**uninitialized constant ReactOnRailsHelper::ExecJS**

NodeJS is installed in the machine.

**Comment by justin808** [comment]
You're missing the ruby racer from the gemfile.

https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/Gemfile#L47

```ruby
# See https://github.com/sstephenson/execjs#readme for more supported runtimes
gem "therubyracer"
```

**Comment by BrunoQuaresma** [comment]
I needed put in my Capistrano deploy config 

`cd client && npm run build:client && npm run build:server`

And move the execjs gem for the 'global' scope in Gemfile.

**Comment by volkanunsal** [comment]
I'm seeing this error too... Is this answer still current? I see that the gem has been removed from tutorial dependencies, and I can't get mini_racer to compile when I'm using therubyracer.

**Comment by volkanunsal** [comment]
Aha, I had to upgrade execjs to version 2.7.0, which is the first version to include the mini_racer adapter adapter.

**Comment by colinrcummings** [comment]
I'm seeing this when switching prerender to true on the most basic react comonent. I'm using mini_racer 0.1.15 with react_on_rails 10.0.2, which did install execjs 2.7.0. @volkanunsal, did you do anything else to resolve this issue?

**Comment by colinrcummings** [comment]
I tried bumping mini_racer down to 0.1.14, which is what's used in the react-webpack-rails-tutorial, but the issue persists for me.

**Comment by colinrcummings** [comment]
Found the issue: I errantly removed uglifier from my Gemfile, which (unexpectedly) broke things. Restored it and all is well.

**Comment by ranjan-purbey** [comment]
Adding `execjs` to the Gemfile fixes the issue
