### ISSUE TITLE
Misleading info about express-server in generator

### ISSUE THREAD

**Issue by radixhound** [shakacode/react_on_rails#473]
Hi there, I just ran the generator for the first time and it told me that there was a command `express-server`:

```bash
After running the generator, you will want to:

    bundle && npm i

Then you may run

    npm run

And you will see several useful commands:

    express-server
      echo 'visit http://localhost:4000' && cd client && npm start
    rails-server
      echo 'visit http://localhost:3000/hello_world' && foreman start -f Procfile.dev
```

Then when I looked in `package.json` and ran `npm run` I found different info.

```bash
✗ npm run
Lifecycle scripts included in react-webpack-rails-tutorial:
  postinstall
    cd client && npm install
  test
    rspec

available via `npm run-script`:
  rails-server
    echo 'visit http://localhost:3000/hello_world' && foreman start -f Procfile.dev
  build:production:client
    (cd client && npm run build:production:client --silent)
  build:client
    (cd client && npm run build:client --silent
  build:dev:client
    (cd client && npm run build:dev:client --silent)
```

I just noticed the discrepancy and thought it would be helpful to let someone know. Overall I'm a bit confused about the port 4000 bits after reading through the railsonmaui article and the readme. I was starting to set up my dockerfile to expose both ports but now perhaps it's not necessary? For now I guess I'll just stick to the info in the installation instructions in the readme and see what happens...

**Comment by radixhound** [comment]
Ahh, I suspect that initially this project was configured by default to have hot reloading but later was changed to have it off for simplicity. Now hot reloading is an (optional config)[https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/hot-reloading-rails-development.md] after you get up-and-running?

**Comment by radixhound** [comment]
It's all coming together now, I see that the tutorial is the leading edge and the generators in this project follow-on from that. [See news section](https://github.com/shakacode/react-webpack-rails-tutorial#news)

**Comment by justin808** [comment]
Generators are simpler as well.

**Comment by radixhound** [comment]
Yeah, it's all definitely a bit overwhelming so simpler is a great way to start and having it all in one place like this is a big win. 👍

**Comment by justin808** [comment]
@radixhound Please check your gem version. The express-server part is no longer in the generator.

![2016-07-20_20-04-37](https://cloud.githubusercontent.com/assets/1118459/17012708/48158b80-4eb5-11e6-8a6d-3a91ca0d9523.png)

**Comment by justin808** [comment]
@radixhound Let me know if I can close this one.
