### ISSUE TITLE
Slow javascript requests

### ISSUE THREAD

**Issue by knagode** [shakacode/react_on_rails#474]
I installed react on rails but I see that it is extremely slow. Requested JS files need more seconds to load.

Especial slow are app-bundle and vendor-bundle javascript files which take most of the load time. 

For example: Given example http://localhost:3000/hello_world loads about 2.5s. 

Why is that? Is there a way to fix this? To me it seems like developing a complex app with those speeds would really be a little bit frustrating. 

[Printscreen of Chrome load times](
https://www.dropbox.com/s/hrmg1vkls3ywon9/Screenshot%202016-07-12%2022.15.06.png?dl=0)

**Comment by knagode** [comment]
I noticed that  switching assets debugging in development.rb to false helps a lot (splits time in half)
```
config.assets.debug = false
``` 

But it is still too slow. Page load happens in more than 1s :(

**Comment by justin808** [comment]
@knagode You've got some other issues. You probably should open up the issue here: https://github.com/shakacode/react-webpack-rails-tutorial/ if you can reproduce there.

**Comment by justin808** [comment]
@knagode Any update? Should we close this one?
