### ISSUE TITLE
Tests fail randomly on travis because vendor-bundle is not found

### ISSUE THREAD

**Issue by UberMouse** [shakacode/react_on_rails#475]
I raised this issue before in #416 and it's still causing me problems. 

Here is an example of a build that fails because vendor-bundle cannot be found https://travis-ci.org/DigitalNZ/supplejack_website/builds/144069648

I'm running the latest version of the Gem. It's becoming quite a problem with our tests on Travis, it never happens locally.

**Comment by justin808** [comment]
@UberMouse I'd be very interested in a PR that addresses this.

Also, if there's any chance we can collaborate on https://github.com/shakacode/react-webpack-rails-tutorial/pull/277, I'd be thrilled. I can't get this pass locally or on Travis.

**Comment by justin808** [comment]
@UberMouse Is there anything we can do about this? I'd say we close this for now until we figure out a solution. The obvious workaround is you restart your tests.

**Comment by UberMouse** [comment]
I haven't had any time to investigate this so no progress. It sometimes takes quite a lot of reruns before it successfully passes (or fails), sometimes making a new commit helps to fix it which is rather strange.

**Comment by UberMouse** [comment]
Just to update this, we've switched to Gitlab CI for our projects, I was hoping that might fix the problem but it didn't end up resolving it. However, I decided to do an explicit build of the webpack bundle before the test runs instead of relying on React on Rails to build it during the test and this appears to have solved the problem. Haven't had any builds fail due to missing vendor-bundle.js since that change was made and there's probably been about ~1,500 builds since then
