### ISSUE TITLE
gem didn't work in rails 5

### ISSUE THREAD

**Issue by july-12** [shakacode/react_on_rails#478]
I start the project by 'quick start guild', but there is not any effects on the screen, as i suppose the webpack-bundle.js didn't be loaded in application, does any body encounter the same problem with me?

**Comment by natecox** [comment]
I just finished a from scratch installation on rails 5 without an issue.

**Comment by justin808** [comment]
@july-12 Please reopen if there's a specific issue.

**Comment by july-12** [comment]
@justin808 sorry, I made fool mistake, I create rails project by 'rails new xxx -TJ', so no any js be loaded by application. it's ok now, thank you.
