### ISSUE TITLE
Innaccurate test helper message

### ISSUE THREAD

**Issue by robwise** [shakacode/react_on_rails#481]
https://github.com/shakacode/react_on_rails/blob/0118cea829429d2a7a546657ed6bf41bcd4d7090/lib/react_on_rails/test_helper/ensure_assets_compiled.rb#L48

This is misleading, we have made it so you can use whatever command you want, so you may not necessarily be doing `npm run build:test`

**Comment by justin808** [comment]
Fixed by #483.
