### ISSUE TITLE
DRY up debugging options

### ISSUE THREAD

**Issue by robwise** [shakacode/react_on_rails#482]
We should just have a `debug_mode` option set to on or off in config to keep it DRY/understandable

We should combine these into a single option, there's way too many to remember and some you can't turn off:
- [trace turbolinks node package option](https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/turbolinks.md#troubleshooting)
- [trace react on rails env var](https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/server-rendering-tips.md#settimeout-and-setinterval)
- [logging on server config option](https://github.com/shakacode/react_on_rails/blob/master/spec/dummy/config/initializers/react_on_rails.rb#L57)
- [replay console config option](https://github.com/shakacode/react_on_rails/blob/master/spec/dummy/config/initializers/react_on_rails.rb#L54)
- [trace config option](https://github.com/shakacode/react_on_rails/blob/master/spec/dummy/config/initializers/react_on_rails.rb#L43)
- [test helper output (not able to turn off currently, we could at least make a less verbose version if debug mode is off)](https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/test_helper/ensure_assets_compiled.rb#L41-L51)
- rails context output message in javascript console (spams up javascript console, should only be on in debug mode)

For node package stuff, we can pass our react_on_rails `debug_mode` setting form the Rails initializer to the node package when running the code so that way you only set it in one place

**Comment by justin808** [comment]
* logging on server config option
* replay console config option

Those configure whether or not we log server rendering output only in browser or on server (or both). Those are not debug flags, but really the location of the logs flags.

**Comment by robwise** [comment]
I would just make it so if `debug_mode` is false, neither of those two happen, and if it is `true`, both happen

**Comment by justin808** [comment]
## Server Rendering Flags
- [env var TRACE_REACT_ON_RAILS](https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/server-rendering-tips.md#settimeout-and-setinterval) 
  - This is a specialized "debugging" flag to save the JS used for server rendering each time in a separate file.
 
- [logging on server config option](https://github.com/shakacode/react_on_rails/blob/master/spec/dummy/config/initializers/react_on_rails.rb#L57)
 - This is not debugging but console logging for server rendering to be and/or with the replay console option.

- [replay console config option](https://github.com/shakacode/react_on_rails/blob/master/spec/dummy/config/initializers/react_on_rails.rb#L54)
  - This configures if you want to to see server console logging conveniently in the browser.

## Client Rendering Flags
- [trace config option](https://github.com/shakacode/react_on_rails/blob/master/spec/dummy/config/initializers/react_on_rails.rb#L43)
  - This is for **client side tracing** of what's going on with React on Rails, typically only in development. 

- [trace turbolinks node package option](https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/turbolinks.md#troubleshooting)
  - Not sure how we'd do this in the ruby config. This is needed when we build the JavaScript.

- rails context output message in javascript console (spams up javascript console, should only be on in debug mode)
 - I suspect this is only part of when "trace" is on for client rendering. Is this really worth configuring so we can toggle this? If so, what flag?

## Test Helper Flag?
- [test helper output (not able to turn off currently, we could at least make a less verbose version if debug mode is off)](https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/test_helper/ensure_assets_compiled.rb#L41-L51)
  - I'm not sure what flag would make sense for this.

Note, the purpose I have for the different flags is to get just the logging that I need to solve some specific type of an issue.

How about just a clear doc of this?

**Comment by robwise** [comment]
> How about just a clear doc of this?

IMO that's pouring gasoline on the fire. We have way too much documentation given how simple our API is, which is a real shame because it turns people off (speaking anecdotally). It would be better to the improve the developer experience by reducing the surface area of our debugging options.

**Comment by justin808** [comment]
Most of the debugging is for **ME** when I'm developing React on Rails. Turning it all on at once decreases the clarity of what I need to see. Most developers do not need any of this. And some of it is not even debugging. It's just choosing how you want to handle server side console messages. If your code doesn't have server side console message, then you won't get much logged anyway. If you crash, you need to see what's going on.

**Comment by justin808** [comment]
Hey @robwise Nobody has upvoted this one. 😏

**Comment by justin808** [comment]
Resolved in #1059.
