### ISSUE TITLE
Using react as view of angular

### ISSUE THREAD

**Issue by hienbx94** [shakacode/react_on_rails#484]
My project use `angular` client-side and `ruby on rails` server-side. I want to replace angular by react (using react as view of angular)
I used to `use react_on_rails` build separate client app, and now i integrate react as view of angular. But i don't way pass data from component react. 

Ex: 
Have `Comments` component react
```
class Comments extends React.Component {
  render() {
    return (
      <div>
        <h3>
          {this.props.name}
          {this.props.comment}
        </h3>
      </div>
    );
  }
}
```
And `CommentsController` controller angular
```
<div ng-app="myApp" ng-controller="CommentsController">
  <%= react_component("Comments", props: {name: ?, comments: ?}, prerender: true)%>
</div>

<script>
var app = angular.module('myApp', []);
app.controller('CommentsController', function($scope) {
    $scope.name = "John";
    $scope.comment = "Doe";
});
</script>
```
How do i pass `$scope.name, $scope.comment` to `props.name, props.comments` ?

**Comment by justin808** [comment]
I don't know angular enough to tell you.

**Comment by justin808** [comment]
@hienbx94 BTW, this code runs server side, so you can't know the client side parts, so your question marks are invalid. You can just replace them with the name and comment.

```erb
<%= react_component("Comments", props: {name: ?, comments: ?}, prerender: true)%>
```

**Comment by hienbx94** [comment]
@justin808 Thank reply!
I want replace react as view of angular. When using 
```<%= react_component("Comments", props: {name: ?, comments: ?}, prerender: true)%>```
i don't pass data from it.
I found solution using `ReacOnRails.render` to render component in `directive` of angular
http://stackoverflow.com/questions/20947191/using-reactjs-with-angularjs
I think it's a good choice for this time.
