### ISSUE TITLE
Async/promise ReactOnRails register?

### ISSUE THREAD

**Issue by syndbg** [shakacode/react_on_rails#493]
I have the following scenario where I:

1. Create a store
1. Dispatch an action to the reducers (it's required by a package I use)
1. Sync history with store
1. Return provider
1. Register provider with ReactOnRails

I haven't found any examples in the docs or react_on_rails_tutorial app. Any suggestions?

**Comment by justin808** [comment]
@syndbg I'm not sure what you're asking. FYI, sync'ing history should only be done client side.

**Comment by justin808** [comment]
@syndbg Any update?

**Comment by syndbg** [comment]
@justin808 Sorry for the delays, wasn't at the PC. I'll provide an example repo tomorrow.

**Comment by justin808** [comment]
@syndbg Can we close this one?

**Comment by syndbg** [comment]
@justin808 Sorry for the delays. I've resolved the problem by not actually having the problem to begin with.

Closing the issue 👍

**Comment by gastonmorixe** [comment]
@justin808 is this possible?

**Comment by justin808** [comment]
Should be for React on Rails Pro.

If not, we can fix it!

CC: @gastonmorixe

**Comment by gastonmorixe** [comment]
@justin808 it's not working for pro. I have followed all the pro source code and couldn't make it work. It's a critical feature to us otherwise we can't make SSR network requests and wait for them before sending back the response.
