### ISSUE TITLE
Port on localhost is 5000 not 3000 for me

### ISSUE THREAD

**Issue by cubadomingo** [shakacode/react_on_rails#495]
Hey I just finished installing the gem and I noticed in the installation guide it mentions to visit localhost:3000/hello_world
<img width="918" alt="screen shot 2016-07-29 at 9 56 19 am" src="https://cloud.githubusercontent.com/assets/15992549/17250939/8506458c-5574-11e6-8354-facef3ae4188.png">
It was actually localhost:5000/hello_world for me.

Everything is still working properly but I'm not too sure if port 3000 isn't used anymore or if it could be either 3000 or 5000 and just depends on the setup. Regardless I was wondering if this was worthy enough to add to the README?

**Comment by HintikkaKimmo** [comment]
Same here there is nothing starting at port :3000

**Comment by cubadomingo** [comment]
@HintikkaKimmo Wait so you're saying that localhost:3000 does work for you? If so do you mind telling me what version of Rails are you running?

**Comment by HintikkaKimmo** [comment]
Just corrected my comment so rails starts at port 5000 not 3000 as mentioned on the tutorial and CLI input

**Comment by cubadomingo** [comment]
Okay so I did some digging around and even though the config/puma.rb file has this line:

`port        ENV.fetch("PORT") { 3000 }`

[Here](https://devcenter.heroku.com/articles/heroku-local#run-your-app-locally-using-foreman) it states:

> Your web process loads on port 5000 because this is what Foreman provides as a default in the $PORT env var

Considering we both have Rails 5 which uses Puma instead of WEBrick as the web dev server, that might be why it ports to :5000 instead of :3000. Maybe others who are using different version could chime in. Anyways I think it might be nice to add this in the README.md.

**Comment by cubadomingo** [comment]
Update: Make sure you're on the latest version of the gem, they have it configured in the procfile to run from port 3000.

**Comment by profsmallpine** [comment]
@cubadomingo Thanks mate.
