### ISSUE TITLE
Manual installation link

### ISSUE THREAD

**Issue by katgironpe** [shakacode/react_on_rails#498]
This returns `404` for me:

https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/manual-installation.md

**Comment by justin808** [comment]
Thanks @katgironpe:
 
Updated README.md here: 1e4c0ed0a5f5724ae1252567f9e8ac1bfffb5d6c

![2016-07-30_11-16-10](https://cloud.githubusercontent.com/assets/1118459/17273150/1b90363e-5647-11e6-8a30-88a09badfeca.png)

**Comment by katgironpe** [comment]
@justin808 thank you!
