### ISSUE TITLE
Add Unit tests

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#5]
Spec tests for the helper.

**Comment by mapreal19** [comment]
@justin808 I'd like to tackle this one

**Comment by samnang** [comment]
@mapreal19 :+1:

Please ping me when you get something.

**Comment by justin808** [comment]
@mapreal19 :+1: :clap:

**Comment by mapreal19** [comment]
@samnang ;)

**Comment by justin808** [comment]
Here's a link to code coverage:
https://coveralls.io/github/shakacode/react_on_rails?branch=master

@robwise might give us a hand with this. Thanks!

@dylangrafmyre we might need some help tuning the coveralls.

I don't think there is a good way to verify the JS coverage. I guess for extra credit, we could add a pure JS test. @alexfedoseev might know if that's worth it.

**Comment by robwise** [comment]
PR #60 makes sure the dummy apps' coverage is included in our coverage report.
