### ISSUE TITLE
Asset precompilation stage cannot cope with filenames with spaces in them

### ISSUE THREAD

**Issue by samphilipd** [shakacode/react_on_rails#505]
Just updated `react_on_rails` to 6.0.5 and now I see this error precompiling assets:

```
React On Rails: Symlinking /Users/sam/code/projects/foo/public/assets/face on grey-93536981da08346bc1270aea2bcb27786769c3eb7b8f9966725a3b4bd3405202.png to /Users/sam/code/projects/foo/public/assets/face on grey.png
ln: grey.png: No such file or directory
```

Seems like React on Rails chokes on filenames with spaces in them.

**Comment by justin808** [comment]
Yes! Good catch. 

Here's an example of where this is happening:
https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/assets_precompile.rb#L44

@samphilipd Any chance that you can submit a PR that has:

1. quotes the file name names (`ln` and `rm` commands in the file).
2. has a spec with file that have spaces in the names.

**Comment by samphilipd** [comment]
@justin808 It seems like this is caused because react_on_rails is trying to create non-digested versions of assets.

My question would be why not use something like [this](https://github.com/alexspeller/non-stupid-digest-assets) instead which is mature and has had all the bugs worked out?

**Comment by justin808** [comment]
https://github.com/alexspeller/non-stupid-digest-assets/issues/35 amongst other reasons: 
https://github.com/alexspeller/non-stupid-digest-assets/issues

Seems like that doesn't work on Heroku.

And no tests!

**Comment by samphilipd** [comment]
@justin808 perhaps the asset linking part could be extracted out of react_on_rails into a separate gem?

I just feel like architecturally it's reaching a bit beyond scope here.

I'll see about a PR though if I have some time.

**Comment by justin808** [comment]
@samphilipd Since we want React on Rails to handle CSS Modules well, this is a natural inclusion.

**Comment by justin808** [comment]
@alleycat-at-git @robwise @samphilipd Rather than using `ln -s source target`, how about we use:

http://ruby-doc.org/core-2.2.0/File.html#method-c-symlink

We also need to set the directory:

http://apidock.com/ruby/FileUtils/cd

@dzirtusss Check this one out.

**Comment by dzirtusss** [comment]
I have send PR closing this

**Comment by justin808** [comment]
See #510.
