### ISSUE TITLE
How do I use third party plugins

### ISSUE THREAD

**Issue by dspoonia7** [shakacode/react_on_rails#507]
I want to use https://github.com/facebook/fixed-data-table plugin. Even if I can add it by npm install. how can use it in my code?
Another issue, do I also have to add my code in /client/app/bundles folder (as given HelloWorld example). Shouldn't there be a way to add new files in app/assets/javascripts folder?

**Comment by justin808** [comment]
Hi @dspoonia7. The JS code in the client directory is like any other pure JavaScript app. React on Rails takes JS from the client directory and packages it up here: app/assets/javascripts.

We at http://www.shakacode.com/ offer individualized training if you might be interested. Please contact us if you or your organization is interested.
