### ISSUE TITLE
Adding Component After Page Load Doesn't Work

### ISSUE THREAD

**Issue by rcdilorenzo** [shakacode/react_on_rails#508]
I've got a React component that I'm inserting into the DOM when a link is clicked with `data-remote: true` as seen below. Because the component occurs after the page loads, ReactOnRails cannot seem to pick it up. I've tried to a manual `render` but that appears to just do a single render and not "connect" the React component. I would love to know if I'm just missing something or if there's a better way to do this or if this is a bug with ReactOnRails.

Inserting into the DOM:
```javascript
$('#team').on('ajax:complete', function (event, xhr, status, error) {
  swal({ html: xhr.responseText });

  // Works for initial render but cannot update or anything afterwards
  var props = JSON.parse($('.swal2-content .js-react-on-rails-component').attr('data-props'));
  ReactOnRails.render('ExportFields', props, 'ExportFields-react-component-0');
});
```

React Component:
```javascript
export default class ExportFields extends Component {
  static propTypes = {
    presets: PropTypes.arrayOf(PropTypes.string)
  }

  // Never called ->
  presetChanged(event) {
    console.log(event.target.value);
  }

  // ...

  render() {
    return (
      <div class="form-row">
        <label for="preset">Preset</label>
        <select name="preset" onChange={this.presentChanged}>{this.renderPresetOptions()}</select>
      </div>
      // ...
    );
  }
}
```

**Comment by justin808** [comment]
@rcdilorenzo You're apparently mixing the jQuery style with React. I'd suggest that you consider using more conventional react techniques. You can use the `componentDidMount` to send the asynchronous call.  See this for a very simple example:

https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/app/bundles/comments/components/SimpleCommentScreen/SimpleCommentScreen.jsx#L29

OTOH, I'd look at the other samples with Redux.

**Comment by rcdilorenzo** [comment]
Yes, I sort of knew that this would be a fix. I was just curious if there was some interim solution before we get to that stage. Thanks for your assistance.
