### ISSUE TITLE
How to load stylesheets managed by npm?

### ISSUE THREAD

**Issue by michaelimstepf** [shakacode/react_on_rails#519]
I'm all new to React and this gem and still trying to wrap my head around some of the concepts.

I have a stylesheet under `client/node_modules/react-datepicker/dist/react-datepicker.min.css`. How should I load this file?

Thanks

**Comment by justin808** [comment]
@michaelimstepf do you want Rails to put this file through the asset pipeline or are you trying to use CSS modules?

**Comment by michaelimstepf** [comment]
@justin808 Thanks for your reply. To be honest, I'm not sure what the best approach is, all I want is the React component under `client/app/bundles/components/date-picker.jsx` to appear styled when I load the Rails view (`app/views/bookings/new.html.erb`).

The workaround I did was copying the stylesheet into `app/stylesheets` and load it from there through the asset pipeline but there must be a better way since the stylesheet will no longer be in sync when I update the node module.

**Comment by justin808** [comment]
Copying is the best answer for now. You can also make something like this: https://github.com/shakacode/font-awesome-loader
