### ISSUE TITLE
Consider updating configuration and rake tasks to support multiple engines

### ISSUE THREAD

**Issue by emerson-h** [shakacode/react_on_rails#523]
I am currently working on several projects that make extensive use of engines to break large code bases into manageable chunks, and with the current react_on_rails configuration setup, it is very difficult to work with client code from several engines independently. 

I'm working on a fork that will allow a per-engine configuration process for the ReactOnRails gem in such a way that including engines with ReactOnRails UIs simply works at the main application level.  

I would love to discuss possible pitfalls and challenges you see with this approach.

**Comment by justin808** [comment]
@emerson-h Some others wanted to do that as well. Definitely read the discussions on old issues and PRs. We'd like to support this idea!

**Comment by justin808** [comment]
@emerson-h I invited you to our slack room.

**Comment by justin808** [comment]
See #562
