### ISSUE TITLE
Application has been already initialized error

### ISSUE THREAD

**Issue by davegonzalez** [shakacode/react_on_rails#538]
Hi there!
First of all, awesome work! This gem has made using react/webpack a breeze in our existing Rails app, at least in a dev env.

Unfortunately, I'm running into issues with deploying this to our Production server on Heroku. I'm also running into the same issue when trying to precompile assets locally with `RAILS_ENV=production bundle exec rake assets:precompile`.

The full error when deploying is:
```
Running: rake assets:precompile
       rake aborted!
       Application has been already initialized.
       /tmp/build_7726b8ec4f7a47d7925ae2f74720232d/vhx-crystal-c9a74d15d7d4bf1646f8d5687969b8a1826c9dca/vendor/bundle/ruby/2.3.0/bundler/gems/rails-d4a1b33a2ab6/railties/lib/rails/application.rb:135:in `initialize!'
       /tmp/build_7726b8ec4f7a47d7925ae2f74720232d/vhx-crystal-c9a74d15d7d4bf1646f8d5687969b8a1826c9dca/vendor/bundle/ruby/2.3.0/bundler/gems/rails-d4a1b33a2ab6/railties/lib/rails/railtie/configurable.rb:30:in `method_missing'
       /tmp/build_7726b8ec4f7a47d7925ae2f74720232d/vhx-crystal-c9a74d15d7d4bf1646f8d5687969b8a1826c9dca/config/environment.rb:8:in `<top (required)>'
       /tmp/build_7726b8ec4f7a47d7925ae2f74720232d/vhx-crystal-c9a74d15d7d4bf1646f8d5687969b8a1826c9dca/vendor/bundle/ruby/2.3.0/bundler/gems/rails-d4a1b33a2ab6/activesupport/lib/active_support/dependencies.rb:251:in `require'
       /tmp/build_7726b8ec4f7a47d7925ae2f74720232d/vhx-crystal-c9a74d15d7d4bf1646f8d5687969b8a1826c9dca/vendor/bundle/ruby/2.3.0/bundler/gems/rails-d4a1b33a2ab6/activesupport/lib/active_support/dependencies.rb:251:in `block in require'
       /tmp/build_7726b8ec4f7a47d7925ae2f74720232d/vhx-crystal-c9a74d15d7d4bf1646f8d5687969b8a1826c9dca/vendor/bundle/ruby/2.3.0/bundler/gems/rails-d4a1b33a2ab6/activesupport/lib/active_support/dependencies.rb:236:in `load_dependency'
       /tmp/build_7726b8ec4f7a47d7925ae2f74720232d/vhx-crystal-c9a74d15d7d4bf1646f8d5687969b8a1826c9dca/vendor/bundle/ruby/2.3.0/bundler/gems/rails-d4a1b33a2ab6/activesupport/lib/active_support/dependencies.rb:251:in `require'
       /tmp/build_7726b8ec4f7a47d7925ae2f74720232d/vhx-crystal-c9a74d15d7d4bf1646f8d5687969b8a1826c9dca/vendor/bundle/ruby/2.3.0/bundler/gems/rails-d4a1b33a2ab6/railties/lib/rails/application.rb:103:in `require_environment!'
       /tmp/build_7726b8ec4f7a47d7925ae2f74720232d/vhx-crystal-c9a74d15d7d4bf1646f8d5687969b8a1826c9dca/vendor/bundle/ruby/2.3.0/bundler/gems/rails-d4a1b33a2ab6/railties/lib/rails/application.rb:305:in `block (2 levels) in initialize_tasks'
       /tmp/build_7726b8ec4f7a47d7925ae2f74720232d/vhx-crystal-c9a74d15d7d4bf1646f8d5687969b8a1826c9dca/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>'
       Tasks: TOP => assets:precompile => react_on_rails:assets:compile_environment => react_on_rails:assets:webpack => environment
       (See full trace by running task with --trace)
```

And this is the error I see locally:
```
rake aborted!
Application has been already initialized.
/Users/davidgonzalez/VHX/crystal/config/environment.rb:8:in `<top (required)>'
/Users/davidgonzalez/.rbenv/versions/2.3.1/bin/bundle:23:in `load'
/Users/davidgonzalez/.rbenv/versions/2.3.1/bin/bundle:23:in `<main>'
Tasks: TOP => assets:precompile => react_on_rails:assets:compile_environment => react_on_rails:assets:webpack => environment
(See full trace by running task with --trace)
```

environment.rb contains `Vhx::Application.initialize!`
meanwhile, production.rb contains `config.assets.initialize_on_precompile = false`

Turning off the line in environment.rb causes it all to run correctly, but then I can't start my server (even locally). Setting `initialize_on_precompile` to true throws a separate error regarding env variables (which I expected would happen). 

Any ideas on what I'm missing? Thanks for any help!

**Comment by davegonzalez** [comment]
Quick update; we're using Rails 3.2 and had to add react_on_rails to our gemfile under the assets group - `gem "react_on_rails", "~> 6", :group => [:assets]` - in order for it to build locally. Still seeing the same error on heroku deploys though.

**Comment by justin808** [comment]
@davegonzalez I'd try out doing the asset precompile parts the old way. 

https://github.com/shakacode/react_on_rails#deployment
and https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/heroku-deployment.md

and see https://github.com/shakacode/react_on_rails/blob/master/CHANGELOG.md#600---2016-05-25

And see this file: https://github.com/shakacode/react_on_rails/blob/master/lib/tasks/assets.rake

That being said, you're going to have to help us on flushing out an Rails 3.2 issues!

**Comment by davegonzalez** [comment]
We ultimately ended up setting `initialize_on_precompile` to true and it worked without any issues. Precompilation takes a bit longer on heroku, but we're okay with that. Thanks for the tips!
