### ISSUE TITLE
Question: has anybody used ReactOnRails with Rails 5?

### ISSUE THREAD

**Issue by lucke84** [shakacode/react_on_rails#539]
I've upgraded our Rails application from 4.2.7 to 5.0.0.1 (which uses ReactOnRails 6.1.0) and, after some testing, I couldn't find any particular problems.
The README says that every Rails app which is 3+ is supported, so it should be all fine.

Just double checking whether somebody already tried it or, even better, it's using it in a production environment.

**Comment by KMontag42** [comment]
It has been working great for me, including ActionCable!

Will be deploying to a small scale heroku app soon.

**Comment by justin808** [comment]
https://github.com/shakacode/react-webpack-rails-tutorial is an example.
