### ISSUE TITLE
Question: what is required from Node v5 to use react_on_rails?

### ISSUE THREAD

**Issue by Ynote** [shakacode/react_on_rails#542]
Hi!

First of all, thanks for all your work. This integration of JavaScript modern tooling in the Rails environment is really great and refreshing!

I would like to use react_on_rails. Unfortunately, the production server I use only provides Node v0.12. I want to know what is required from Node v5 for react_on_rails and if it is possible to use it with my version of Node.

I know that my question is a bit tricky as the requirement of Node v5 seems mandatory. Thank you for your help!

**Comment by justin808** [comment]
@Ynote Node is *ONLY* used to run the build tools. Can you install a local version of node just for the building of the JavaScript file?

**Comment by Ynote** [comment]
Actually, my building stack is not ideal now. You are right, building assets should not be on the production instance. I think it should not be on development environment either. I'll rethink my release process as you suggest.

Thanks a lot for your quick reply!

**Comment by justin808** [comment]
@Ynote, you're welcome! You could always build on your dev machine and commit the generated file to your git repo. However, that makes your git history pretty ugly, and you can't do this in a PR, unless you want a mega big file in your PR.
