### ISSUE TITLE
[Form] How to use data-remote='true' in react form?

### ISSUE THREAD

**Issue by khacluan** [shakacode/react_on_rails#543]
I tried to use data-remote='true' attributes in form and when I submit form it doesn't work
How can I use data-remote='true' like rails form ?

thanks for any helping!

**Comment by justin808** [comment]
@khacluan Your question is probably not appropriate for using react components, as data-remote is for ujs, which is using jquery, rather than react.

Just call the API endpoints directly from your react code.
