### ISSUE TITLE
react-router simple integration docs

### ISSUE THREAD

**Issue by scaryguy** [shakacode/react_on_rails#544]
Hi,

I'm just trying to integrate most basic react-router implementation but I can't succeed. When I look at docs, I see react-router being used with `redux` and `react-router-redux`. However, I'm not experienced with redux yet. So could you add some docs for 'simple' react-router implementation?

Here is what I tried:

```javascript
import React from 'react';
import ReactOnRails from 'react-on-rails';
import { Router, Route, Link, browserHistory  } from 'react-router'
import { MainLayout } from './layouts/MainLayout'
import { NewQuestionPage } from './pages/NewQuestionPage'

export class NoMatch extends React.Component {
	render() {
		return(
			<div>Nothing to show?</div>
			);
	}
}


export default class MyApp extends React.Component {

  constructor(props) {
    super(props);
  }

  render() {

    return (
    <Router history={browserHistory}>
	    <Route path="/" current_user={this.props} component={MainLayout} />
	    <Route path="/questions" component={NewQuestionPage} />
	    <Route path="*" component={NoMatch}/>
    </Router>
    );
  }
}

ReactOnRails.register({ MyApp });
```

And this is is from my `application.html.erb`:
```ruby
<%= react_component 'MyApp', props: current_user %>
```

When I browse my application, it always shows `MainLayout` component regardless of what URL I try to access (including `http://localhost:3000/#/questions`) and I never get `NoMatch` component even though I try to browse non-existing paths. 

Any help?

**Comment by justin808** [comment]
@scaryguy Take a look at your routes.rb file and take a look at https://github.com/shakacode/react-webpack-rails-tutorial for a complete "simple" example. Compare your routes.rb to the one in that repo.

If you need more, we're more than happy to help you with a small coaching contract. Please take a look at http://www.shakacode.com/work/. We're helped out many that we've met through this open source project.
