### ISSUE TITLE
Docs typo, at ReactOnRails JavaScript API section

### ISSUE THREAD

**Issue by Roko131** [shakacode/react_on_rails#545]
If you are using jquery-ujs for AJAX calls, **than** these helpers are not needed because the jquery-ujs library updates header automatically, see jquery-ujs documentation.

Should be:

If you are using jquery-ujs for AJAX calls, **then** these helpers are not needed because the jquery-ujs library updates header automatically, see jquery-ujs documentation.

**Comment by justin808** [comment]
Fixed. Thanks.
