### ISSUE TITLE
Q> js.map routing errors w/ searchkit

### ISSUE THREAD

**Issue by ahmetabdi** [shakacode/react_on_rails#547]
I'm trying to use https://github.com/searchkit/searchkit with `react_on_rails` everything works apart from I'm getting a bunch of `ActionController::RoutingError` on `.js.map` files which exist within the npm package:

`ActionController::RoutingError (No route matches [GET] "/assets/ValueState.js.map")`
`ActionController::RoutingError (No route matches [GET] "/assets/ViewSwitcherToggle.js.map")`
etc... loads of these

I've followed the same setup as the boilerplate they provide at https://github.com/searchkit/searchkit-boilerplate but I get these routing errors anyone know whats up?

Why is it looking in the assets folder for the .js.map files when they exist within the node package

**Comment by justin808** [comment]
You should just add these files to public/assets for now.

If you want to go down the rabbit hole (and maybe submit a PR on this that helps everybody):

* http://guides.rubyonrails.org/asset_pipeline.html
* You set the destination directory in your webpack file, and those files get copied by Rails during deployment: https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/rails-assets.md

Also, keep in mind the differences between development and production deployments.

Good luck. Keep us posted.

And feel free to request to re-open this issue.
