### ISSUE TITLE
Could not find store registered with name 'SharedReduxStore'. Registered store names include [  ]. Maybe you forgot to register the store?

### ISSUE THREAD

**Issue by ncwlaw** [shakacode/react_on_rails#552]
I have registered the store and is already linked as an entry point in webpack

`import ReduxApp from './ClientReduxApp'
import ReduxSharedStoreApp from './ClientReduxSharedStoreApp'
import SharedReduxStore from '../stores/SharedReduxStore'
import ReactOnRails from 'react-on-rails'

ReactOnRails.setOptions({
  traceTurbolinks: true
})

ReactOnRails.register({
  ReduxApp,
  ReduxSharedStoreApp
})

ReactOnRails.registerStore({SharedReduxStore})
`

Wondering why it's not registered.
Thanks in advance.

**Comment by justin808** [comment]
This question is way too vague for us to be helpful.

We can give you individualized help, per http://www.shakacode.com/work/, if you're interested. Allowing us to give you PR requests is extremely helpful to our coaching clients.
