### ISSUE TITLE
Hot reloading is not picking up changes to the CSS

### ISSUE THREAD

**Issue by DEfusion** [shakacode/react_on_rails#555]
I've tried making changes to both `applicaiton_non_webpack.css` and `application_static.scss` but I have to do a refresh in order for them to be picked up.

```
# application.html.erb
 <%= env_stylesheet_link_tag(
      static: 'application_static',
      hot: 'application_non_webpack',
      media: 'all'
    ) %>
```

```
<!-- output -->
<link rel="stylesheet" media="all" href="/assets/application_static.self-a63c83d31995d61cb5a658d5e5ee02cc80232bb2ac87c8d12cfc28036f82c8e3.css?body=1" />
<link rel="stylesheet" media="all" href="/assets/application_non_webpack.self-af04b226fd7202dfc532ce7aedb95a0128277937e90d3b3a3d35e1cce9e16886.css?body=1" />
```

I'm not sure what I've done wrong, changes to JSX files get picked up and the JS gets hot-reloaded.

**Comment by justin808** [comment]
Maybe your question would be better suited to https://github.com/shakacode/react-webpack-rails-tutorial/ ? Can you clone that repo and get hot reloading to work?

**Comment by DEfusion** [comment]
Ok thanks, I'll move it over there.
