### ISSUE TITLE
Missing script- build:client error

### ISSUE THREAD

**Issue by austinlchang** [shakacode/react_on_rails#557]
Hi,

I'm trying to deploy a rails 5 project that uses this gem to heroku, but it doesn't work. I've configured heroku to use both buildpacks (ruby and node).

I've followed instructions to set up deployment, but it seems to failing when building production assets. I'm getting this error:

```
remote:        cd client && npm run build:client
remote:        npm ERR! Linux 3.13.0-95-generic
remote:        npm ERR! argv "/tmp/build_73b41fae5fe2bab90261142eeb64652e/.heroku/node/bin/node" "/tmp/build_73b41fae5fe2bab90261142eeb64652e/.heroku/node/bin/npm" "run" "build:client"
remote:        npm ERR! node v5.10.0
remote:        npm ERR! npm  v3.5.0
remote:        npm ERR! missing script: build:client
remote:        npm ERR!
remote:        npm ERR! If you need help, you may report this error at:
remote:        npm ERR!     <https://github.com/npm/npm/issues>
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_73b41fae5fe2bab90261142eeb64652e/client/npm-debug.log
remote:        rake aborted!
remote:        Command failed with status (1): [cd client && npm run build:client...]
remote:        /tmp/build_73b41fae5fe2bab90261142eeb64652e/lib/tasks/assets.rake:18:in `block (2 levels) in <top (required)>'
remote:        /tmp/build_73b41fae5fe2bab90261142eeb64652e/vendor/bundle/ruby/2.3.0/gems/rake-11.2.2/exe/rake:27:in `<top (required)>
remote:        Tasks: TOP => assets:precompile => assets:compile_environment => assets:webpack
```

Seems like heroku isn't recognizing the `build:client` script.

I've set the config variable `config.npm_build_production_command` in the react_on_rails initializer, but that doesn't fix anything.

I've set the production command to `build:production:client` (that's the script that should be run, and it is listed as a script in the package.json file, but react_on_rails is not recognizing the configuration being set. I've also tried setting it to nil, but it still doesn't recognize and continues to try to run `build:client`

Furthermore, when I change the name of the script in the package.json file to `build:client`, (I couldn't get the system to run anything else other than `build:client` the missing script error comes up still, even though it's listed as a script and runs in my terminal.

I've forked the gem and attempted to hardcode the script name in the gem, but that does not work either.

Has anyone run into this problem? Again, running `build:client` or `build:production:client` in the console works perfectly fine- it seems like this problem only comes up when trying to deploy to heroku.

Any help is greatly appreciated. Thanks!
Austin

**Comment by justin808** [comment]
Try this:

* https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/package.json#L37
* https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/config/initializers/react_on_rails.rb#L24
