### ISSUE TITLE
"ERROR: You have uncommitted code. Please commit or stash your changes before continuing" with empty "git status"

### ISSUE THREAD

**Issue by everm1nd** [shakacode/react_on_rails#563]
I faced with a bit confusing behaviour of `ReactOnRails::GitUtils` module. When I tried to run a generator it returned me a message:
```
ERROR: You have uncommitted code. Please commit or stash your changes before continuing
ERROR: react_on_rails generator prerequisites not met!
```
But... `git status` had an empty output:
```
On branch react-redux-rails
nothing to commit, working directory clean
```
That was a bit strange. I checked sources of module (https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/git_utils.rb) and found out that it uses `git status --porcelain` to make a check. Runned this - still empty. But... In my Vagrant machine this command had output full of `.DS_Store` files. They are somehow hidden in macOS but present inside of guest-box. Adding line `.DS_Store` to bottom of `.gitignore` solved the issue. I hope this will help someone

**Comment by justin808** [comment]
@everm1nd that should be in a global gitignore.

It's common enough that we probably don't need it in our examples. Thanks for pointing this out!

**Comment by JCBoptimumweb** [comment]
same issue here but adding .DS_Store to .gitignore did not render a solution, will continue my google search and add the answer back here as this is the 1 place for the search ERROR: You have uncommitted code. Please commit or stash your changes before continuing

**Comment by justin808** [comment]
@JCBoptimumweb @vmpj Why is the spring gem causing an issue?

**Comment by deesx** [comment]
same here /: nothing explained here solved the issue

**Comment by anativ** [comment]
Same here....
`spring stop` solved the issue
