### ISSUE TITLE
Rails 3 incompatibility when symlinking non-digested assets

### ISSUE THREAD

**Issue by etripier** [shakacode/react_on_rails#564]
Hey guys,

Thanks so much for the hard work on this gem. It makes my work much easier and it's been a breeze to set up, even on the venerable Rails 3 distribution.

I'm seeing an incompatibility when trying to `symlink_non_digested_assets` in `assets_precompile.rb`. Broadly, the method attempts to read a list of file names from one of either the `"manifest-*.json"` or `".sprockets-manifest-*.json"` produced by Sprockets. In Rails 3 (and the associated Sprockets version), those manifest files are actually YAML files instead of JSON.

I'd be open to digging and trying to patch the method to read the relevant `.yml` manifest file, but I wanted to see if you've considered that/have any interest. This is one of the only real incompatibilities I've found in getting Webpack up and running on Rails 3.

Thanks again!

**Comment by justin808** [comment]
@etripier We sort of don't want to maintain Rails 3 support with Rails 5 support. That being said, if you've got a simple PR that would make this work, please submit it!

**Comment by justin808** [comment]
We'll have #566 merged shortly.

**Comment by justin808** [comment]
Shipped in 6.1.2.
