### ISSUE TITLE
webpack-bundle cannot be found after server start

### ISSUE THREAD

**Issue by FunkyloverOne** [shakacode/react_on_rails#565]
Hi guys, I'm having weird error after server start. Error disappears when I change url in my browser or after few page reloads. Here's what I'm getting:
```
Sprockets::FileNotFound in Home#index
Showing /home/funky/projects/billbill/app/views/layouts/application.html.erb where line #7 raised:

couldn't find file 'webpack-bundle' with type 'application/javascript'
Checked in these paths: 
  /home/funky/projects/billbill/app/assets/config
  /home/funky/projects/billbill/app/assets/images
  /home/funky/projects/billbill/app/assets/javascripts
  /home/funky/projects/billbill/app/assets/stylesheets
  /home/funky/projects/billbill/app/assets/webpack
  /home/funky/projects/billbill/vendor/assets/javascripts
  /home/funky/projects/billbill/vendor/assets/stylesheets
  /home/funky/.gem/ruby/2.3.1/gems/jquery-rails-4.2.1/vendor/assets/javascripts
  /home/funky/.gem/ruby/2.3.1/gems/coffee-rails-4.2.1/lib/assets/javascripts
  /home/funky/.gem/ruby/2.3.1/gems/actioncable-5.0.0.1/lib/assets/compiled
  /home/funky/.gem/ruby/2.3.1/gems/turbolinks-source-5.0.0/lib/assets/javascripts
  /home/funky/projects/billbill/app/assets/webpack
  /home/funky/.gem/ruby/2.3.1/gems/bootstrap-sass-3.3.7/assets/stylesheets
  /home/funky/.gem/ruby/2.3.1/gems/bootstrap-sass-3.3.7/assets/javascripts
  /home/funky/.gem/ruby/2.3.1/gems/bootstrap-sass-3.3.7/assets/fonts
  /home/funky/.gem/ruby/2.3.1/gems/bootstrap-sass-3.3.7/assets/images
```
Is it something wrong with my environment? You may check my repo, I'm getting it in blank project, after installing react on rails, so after [this commit](https://github.com/FunkyloverOne/billbill/commit/d34e89375673f01e7ae5590d78a9666de45f21f8).

I was following [this tutorial](https://github.com/shakacode/react_on_rails/blob/master/docs/tutorial.md) using chruby+ruby-install instead of rvm and rails 5 instead of 4. And I'm using Atom, not RubyMine.

Maybe it's OK? Maybe It's just needs some time on my laptop...

P.S. error log is from the latest commit.

**Comment by justin808** [comment]
You need to make sure that your webpack config files and the your initializers/react_on_rails.rb files point to the same output files. Apparently, you have webpack-bundle in your initializer, but not in your webpack config files.

**Comment by FunkyloverOne** [comment]
@justin808 OK, I already have them in webpack config here:
https://github.com/FunkyloverOne/billbill/blob/master/client/webpack.config.js#L16
But I do not see where I should put inside initializer, looks like it's already there too...
https://github.com/FunkyloverOne/billbill/blob/master/config/initializers/react_on_rails.rb#L10

BTW, I haven't changed any configs, so that's what was set by your generator.

**Comment by justin808** [comment]
I'm pretty sure the default generator works. I just created a few videos on this:

1. Overview:  https://youtu.be/F4oymbUHvoY
2. Running the generator:  https://youtu.be/_bjScw60FBk
3. Generator code walkthrough: https://youtu.be/McQ9UM-_ocQ

@FunkyloverOne Do you think there's an issue with React on Rails, or your own setup?

**Comment by FunkyloverOne** [comment]
Yup, it all works, just as I tought - my system is just a bit slow.
Thanks for your videos, they makes me feel not that scared of all that new stuff :D
The webpack-bundle.js file is just being deleted after server starts and in takes some time to regenerate it.

**Comment by adambarthelson** [comment]
I'll just leave this here for anyone else who ran into this while trying to Dockerize a Rails applications using react_on_rails: https://blog.codeship.com/using-honcho-create-multi-process-docker-container/.

I ran into this issue because the Docker container couldn't run multiple Foreman processes, even when using the "formation" options to run them concurrently.  Installing and using Honcho instead of Foreman solved it for me.

**Comment by icemelt7** [comment]
This issue is coming for me too from a fresh install

**Comment by mindtonic** [comment]
+1 This issue is coming for me too from a fresh install

**Comment by justin808** [comment]
@icemelt7 any ideas?

**Comment by JayTeeSF** [comment]
This is happening for me on heroku. My app was working fine, then all of a sudden Heroku starts the asset-pipeline and stops because:

**Comment by JayTeeSF** [comment]
doh ...looks like running assets locally and committing my `public/assets/` folder resolved this issue for me.

And, forgive me for not saying so before: thanks for this incredible project!

**Comment by justin808** [comment]
@JayTeeSF You should not be committing to your `/public/assets` folder.

PS. Please tweet to hash tag #react_on_rails and/or comment on https://github.com/shakacode/react_on_rails/blob/master/KUDOS.md with gratitude.

I really appreciate it. 🙏😇👍.

**Comment by mustmodify** [comment]
In case anyone else runs in to this, I was using puma, not foreman. When using puma you must separately run webpack using a command like:

    sh -c 'rm app/assets/webpack/* || true && cd client && 
             bundle exec rake react_on_rails:locale && yarn run build:development'

either in a separate window or in the script that starts puma.

**Comment by giovapanasiti** [comment]
@mustmodify hey dude did you already try your solution in production? How does it work

**Comment by mustmodify** [comment]
The above solution is only needed for dev. In production, capistrano runs `rake assets:precompile` which (I guess) triggers webpack to run the once time. Here's what I did to set up my production machine: https://gist.github.com/mustmodify/e4d29b6dd9992381b66cd4efe0b6d32c

**Comment by mustmodify** [comment]
@giovapanasiti yep, [it hooks into assets:precompile](https://github.com/shakacode/react_on_rails/blob/a333608e736c81190157fc82ea0d7d4be4c3b6fb/lib/tasks/assets.rake#L39-L45)
