### ISSUE TITLE
Support for Rails 3.2.xx

### ISSUE THREAD

**Issue by liorbrauer** [shakacode/react_on_rails#57]
Hello,

I was wondering if there is a reason that is preventing the gem from supporting Rails version 3.2.xx? 

Thank you,
Lior

**Comment by justin808** [comment]
@liorbrauer The only dependency is having somebody actually want to use it with 3.2 (and Ruby 2.x?)

Please make a fork and give it a spin. I can help you where you get stuck.

**Comment by justin808** [comment]
@liorbrauer I'm going to close this issue for now. Feel free to re-open it if you want to use this gem with Rails 3.2. Shouldn't be hardly any effort.

**Comment by liorbrauer** [comment]
@justin808 Thanks for the reply, I have forked the repo and am currently testing it.

**Comment by justin808** [comment]
@liorbrauer Super. Let me know if you want to join our slack room.

**Comment by liorbrauer** [comment]
@justin808 I'd like to join the room, would love to discuss and understand a few points. Thanks!

**Comment by justin808** [comment]
@liorbrauer I sent you invite. If you didn't get it, email me at justin@shakacode.com. Thanks.
