### ISSUE TITLE
"Attempted to assign to readonly property" in component render error handling

### ISSUE THREAD

**Issue by bkraeling** [shakacode/react_on_rails#570]
I ran into this issue while debugging an issue with localStorage in private mode on mobile Safari. That throws an exception that's being caught in this catch block in `clientStartup.js:81`.

```
catch (e) {
    e.message = `ReactOnRails encountered an error while rendering component: ${name}.` +
      `Original message: ${e.message}`;
    throw e;
}
```

When this block gets executed, instead of throwing the exception, it's erroring out trying to assign `e.message`, which is apparently a readonly property.

I managed to work around it by throwing a debugger call before the offending line to check the exception, but I figured you guys should be aware of it.

**Comment by justin808** [comment]
I never knew that this could be the case. 

I guess we probably should have a try/catch block around assigning e.message. This requires a bit of research.

@Judahmeek Any chance that you can take a look at this?

**Comment by Judahmeek** [comment]
I can take a look, but I'm not sure what good it would do since I don't have a device with mobile safari on it. Either a try/catch block around assigning to e.message or simply creating a new error and throwing that instead should fix this bug.

@bkraeling Does this issue only occur in private mode?

**Comment by justin808** [comment]
@bkraeling can you please submit a screenshot of the error message on your mobile device?

**Comment by justin808** [comment]
@bkraeling Please reopen if this is still an issue.
