### ISSUE TITLE
Passing properties from React Component

### ISSUE THREAD

**Issue by walidargh** [shakacode/react_on_rails#571]
I am struggling to find an answer to this question anywhere.

I am rendering a router in particular page and I want to be able to pass the posts object to the route that is rendered. 

```
<%= react_component("ClientRouter", props: {posts: @posts}, prerender: false) %>
```

This is my router:
```
export default (props) => ( 
  <Router history={browserHistory} {...props}>
    <Route path="/" component={Layout} >
      <IndexRoute component={Grid}/>
      <Route path="posts" component={Grid} />
      <Route path="/posts/:postId" component={PostDetails} />
    </Route>
  <Router />
);
```

But I can't seem to access ```this.posts.params```  in the component that is rendered (which is ```Grid```). 

Does anyone have a way to get around this?

**Comment by jtibbertsma** [comment]
Here's what you're trying to do:
```jsx
export default (props) => ( 
  <Router history={browserHistory} {...props}>
    <Route path="/" component={Layout} >
      <IndexRoute posts={props.posts} component={Grid}/>
      <Route path="posts" posts={props.posts} component={Grid} />
      <Route path="/posts/:postId" component={PostDetails} />
    </Route>
  <Router />
);
```
Grid.jsx
```jsx
class Grid extends React.Component {
  render() {
    const { route } = this.props;
    const { posts } = route; 
  }
}
```
But the real answer to your question is that you should put `posts` in a flux store.

**Comment by walidargh** [comment]
@jtibbertsma thank you! I got that to work, and you are right I should be putting them in a flux store. I avoided it because I was just trying to see how feasible incorporating React into my Rails App would be, but that will be my next step.
