### ISSUE TITLE
Generate should run with uncommitted changes

### ISSUE THREAD

**Issue by fweep** [shakacode/react_on_rails#576]
When I run the `react_on_rails:install` generator, it fails with this error:

> ERROR: You have uncommitted code. Please commit or stash your changes before continuing
> ERROR: react_on_rails generator prerequisites not met!

The generator shouldn't care about this. It's an external concern. I know I have uncommited changes. They're related to me switching from `react-rails` to `react_on_rails`. I don't want to commit my code in a broken state. I'm now forced to create a branch and push a broken commit to move to the next step. This isn't a huge deal, but it's dirty and unnecessary.

Update:

I see that there's an `--ignore-warnings` option. It's not clear what warnings it's intended to ignore, but running with it creates a bunch of files, but still prints:

> ERROR: You have uncommitted code. Please commit or stash your changes before continuing

It's not clear whether the task completed correctly or not.

**Comment by justin808** [comment]
@fweep We generate so many files that we feel this is necessary. If you'd like to create a documentation or slight generator change, I'd be open to a PR.

**Comment by simonewebdesign** [comment]
Totally agree with @fweep. It would be good to also have feedback on what has been generated.

**Comment by fweep** [comment]
I've decided not to use react_on_rails (for various reasons), so I'm going to close this.

**Comment by henrydjacob** [comment]
adding app/assets/.DS_Store and vendor folder solved the problem for me
