### ISSUE TITLE
Running install generator without demo app

### ISSUE THREAD

**Issue by fweep** [shakacode/react_on_rails#577]
It'd be nice if there were a way to run the `react_on_rails:install` generator without all the HelloWorld cruft. I want to bootstrap my app for react_on_rails, but I don't want the demo. Having to manually remove the demo is error prone, especially while learning how the framework is laid out. Your standalone demo app is a better approach.

**Comment by justin808** [comment]
@fweep If you'd like to create an option in the generator, I'd be open to a PR.
