### ISSUE TITLE
uninitialized constant ReactOnRailsHelper::ActionMailer

### ISSUE THREAD

**Issue by martinbethann** [shakacode/react_on_rails#580]
Hello,

I'm having trouble running the Hello World demo:

**uninitialized constant ReactOnRailsHelper::ActionMailer**

_app/views/hello_world/index.html.erb:2:in `_app_views_hello_world_index_html_erb___2816177607841798189_70135088914060'_

Any ideas?  Thank you so much!

**Comment by justin808** [comment]
@martinbethann What version of Rails are you using? You definitely have a local setup issue. Otherwise, we'd see this more often.

**Comment by martinbethann** [comment]
Yes, I realized that yesterday and meant to update this issue!  I was trying to add this gem to an existing rails set up but it worked perfectly with a fresh install.
