### ISSUE TITLE
Webpack task incorrect/assumes client folder

### ISSUE THREAD

**Issue by mikecx** [shakacode/react_on_rails#582]
I think the webpack task might be incorrect. In the example app you have a top level package.json that sits above the client folder and has some scripts, one of which is the 'build:production' script. On the other hand, when calling the webpack task, it assumes the client directory and completely ignores the build:production script in the top level package.json. 

So the question is, should the the
``` sh "cd client && #{ReactOnRails.configuration.npm_build_production_command}" ```
line just be 
``` sh "#{ReactOnRails.configuration.npm_build_production_command}" ```

Task for reference:
```
    task webpack: :environment do
      if ReactOnRails.configuration.npm_build_production_command.present?
        sh "cd client && #{ReactOnRails.configuration.npm_build_production_command}"
      end
    end
```

**Comment by justin808** [comment]
@mikecx The webpack commands must be run from the client directory. The top level one is provided as a convenience.

Does this fact change your suggestion?

**Comment by mikecx** [comment]
@justin808 I don't think so but I could be looking at it wrong. I was picturing the top level package.json as the "master" in that it would then call the required webpack methods in their respective folders.

In my case I have a setup where i've got two separate area that I want to have building, the /client folder and a /platform folder. From the "master" package.json I can just modify the call to have it go into the /client folder and do business as usual and the /platform folder and do business as usual. With the hard coding I have to basically tell the react_on_rails.rb to do a cd .. && npm build:production which feels awkward since I could just have the "master" tell it to operate on whatever is needed.

This would also give the opportunity to rename the /client folder to anything you'd like just by modifying the "master" package.json.

In the end I just opted to place it all under one messy folder (undergoing a UI rewrite that necessitates an entirely separate node_modules) and deal with branching and merge/rebasing. That said, I'd still suggest getting rid of the cd client and letting the "master" take on the responsibility of calling the client and letting the client decide what it wants to do and how.

**Comment by justin808** [comment]
@mikecx That's not the way we have set things up. If you want to make a sample repository, we can discuss it.

**Comment by justin808** [comment]
BTW -- we're using the philosophy of convention over configuration.
