### ISSUE TITLE
webpack: not found error

### ISSUE THREAD

**Issue by homerlex** [shakacode/react_on_rails#587]
I followed the instructions in the "Getting Started" section.  When I go to run `foreman start -f Procfile.dev` I get the error below.  Looks like webpack is not on my PATH.  

```
20:21:30 client.1 | > webpack -w --config webpack.config.js
20:21:30 client.1 | 
20:21:30 client.1 | sh: 1: webpack: not found
```

Did I miss something?  I see a webpack folder in client/node_modules and I can run the webpack command from the bin folder in there.  

FYI - I am running this on a Vagrant instance with Ubuntu 14.

**Comment by homerlex** [comment]
In my local env I got around this by installing webpack with the global switch.  But, now deploying to Heroku I have the same situation:

```
remote:        cd client && npm run build:production
remote:        > react-webpack-rails-tutorial@0.0.1 build:production /tmp/build_fc486bb5c0d3dac023935545ae780563/client
remote:        > NODE_ENV=production webpack --config webpack.config.js
remote:        sh: 1: webpack: not found
```

**Comment by justin808** [comment]
@homerlex Please follow the instructions carefully here: https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/heroku-deployment.md

My guess is that you are not configuring your package.json correctly.

If you'd like more individualized assistance, see http://www.shakacode.com/work and our coaching plan. We'd love to help!

**Comment by homerlex** [comment]
I've read that page.  You mentioned that you suspect a problem in the package.json.  That document doesn't talk about what the proper setting are for Heroku.  My package.json is the one from the Hellow World example.  What adjustments need to be made to it to make it work at Heroku?

**Comment by vassyz** [comment]
@homerlex Did you manage to find what was causing this? I'm having the same issue.

**Comment by homerlex** [comment]
@vassyz - I have it working.  I don't recall what was the exact issue was but this is what my script looks like for production deployment now:
`"build:production": "NODE_ENV=production webpack --config webpack.config.js",`

Also make sure you add the nodejs buildpack:
`heroku buildpacks:add --index 1 heroku/nodejs -a app_name`

Let me know if this helps.

**Comment by vassyz** [comment]
I managed to get it working by adding the postinstall script to the base `package.json`:

```json
  "scripts": {
    "postinstall": "cd client && npm install"
  }
```

I'm not sure if I did something wrong, or if this should be mentioned in the Heroku deployment instructions.

**Comment by justin808** [comment]
@vassyz @homerlex Please let me know if this addresses part of the issue: https://github.com/shakacode/react_on_rails/commit/53af84126bb1a7c10a89849625938e84775f344e#diff-a8b868106a63acb6b1013d1969428d9a

Anything else we should add to that file?
https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/heroku-deployment.md

**Comment by vassyz** [comment]
Looks good to me. The postinstall script is the only thing not mentioned in the instruction that I had to add to get deployment working. 👍

**Comment by MagnusEngdal** [comment]
For me the problem was that I had added NODE_ENV=production to the env vars of my build project. Removing it again solved it.
