### ISSUE TITLE
You're making this too easy for noobs...

### ISSUE THREAD

**Issue by thedanotto** [shakacode/react_on_rails#590]
What has the world come to? Great error messages, documentation with pictures.... stuff we actually care about like deploying the server to heroku.

**Great Error Messages**

![screen shot 2016-11-04 at 3 09 07 pm](https://cloud.githubusercontent.com/assets/5581358/20020727/bc0766be-a2a0-11e6-8e1c-8854d082399f.png)

**Documentation with Pictures**

https://github.com/shakacode/react_on_rails/blob/master/docs/tutorial.md

THOROUGHLY IMPRESSED. THIS GEM HAS MADE RAILS FRONT END FUN AGAIN.

**Comment by justin808** [comment]
@thedanotto Thanks for the kind comment! 

https://twitter.com/railsonmaui/status/1380269835184041985

**Comment by thedanotto** [comment]
Of course, keep crushing it!

**Comment by thedanotto** [comment]
When I make it out to Maui again, I'll hit you up and maybe we can catch some waves. 3rd coaster right now, but always wanted to live in Hawaii

**Comment by justin808** [comment]
@thedanotto Hit me up on LinkedIn https://www.linkedin.com/in/railsonmaui or Facebook https://www.facebook.com/justinhgordon/ !
