### ISSUE TITLE
Error in server-side rendering

### ISSUE THREAD

**Issue by ziedhajsalah** [shakacode/react_on_rails#592]
I am trying react_on_rails for the first time, everything worked fine until i tried server-side rendering
`<%= react_component('App', {}, prerender: true) %>`

I've got this error:

`ReactOnRails::PrerenderError in Home#index
Showing /home/zied/projects/tutos/react/pluralsight/twitter-clone/app/views/home/index.html.erb where line #1 raised:

ERROR in SERVER PRERENDERING
Encountered error: "TypeError: _jquery2.default.get is not a function"
when prerendering App with props: {}
js_code was:
(function() {
  var railsContext = {"inMailer":false,"i18nLocale":"en","i18nDefaultLocale":"en","href":"http://localhost:3000/","location":"/","scheme":"http","host":"localhost","port":3000,"pathname":"/","search":null,"httpAcceptLanguage":"ar,fr;q=0.8,en-US;q=0.6,en;q=0.4","serverSide":true};

  var props = {};
  return ReactOnRails.serverRenderReactComponent({
    name: 'App',
    domNodeId: 'App-react-component-a93f54d1-b6f6-4461-9591-3b5eae1ac543',
    props: props,
    trace: true,
    railsContext: railsContext
  });
})()

Object.getAllTweets (eval at (execjs) (unknown source), <anonymous>:19:22)
Object.getAllTweets (eval at (execjs) (unknown source), <anonymous>:15:19)
eval (eval at (execjs) (unknown source), <anonymous>:37:24)
Object.(execjs) (<anonymous>:1886:2)
__webpack_require__ ((execjs):55:30)
Object.(execjs) (<anonymous>:85:19)
__webpack_require__ ((execjs):55:30)
(execjs):75:18
(execjs):78:10
/home/zied/.rvm/gems/ruby-2.3.0/gems/mini_racer-0.1.6/lib/mini_racer.rb:167:in `eval_unsafe'
/home/zied/.rvm/gems/ruby-2.3.0/gems/mini_racer-0.1.6/lib/mini_racer.rb:167:in `block (2 levels) in eval'
/home/zied/.rvm/gems/ruby-2.3.0/gems/mini_racer-0.1.6/lib/mini_racer.rb:217:in `timeout'
/home/zied/.rvm/gems/ruby-2.3.0/gems/mini_racer-0.1.6/lib/mini_racer.rb:166:in `block in eval'
/home/zied/.rvm/gems/ruby-2.3.0/gems/mini_racer-0.1.6/lib/mini_racer.rb:63:in `block in with_lock'
/home/zied/.rvm/gems/ruby-2.3.0/gems/mini_racer-0.1.6/lib/mini_racer.rb:63:in `synchronize'
/home/zied/.rvm/gems/ruby-2.3.0/gems/mini_racer-0.1.6/lib/mini_racer.rb:63:in `with_lock'
/home/zied/.rvm/gems/ruby-2.3.0/gems/mini_racer-0.1.6/lib/mini_racer.rb:164:in `eval'
/home/zied/.rvm/gems/ruby-2.3.0/gems/execjs-2.7.0/lib/execjs/mini_racer_runtime.rb:10:in `block in initialize'
/home/zied/.rvm/gems/ruby-2.3.0/gems/execjs-2.7.0/lib/execjs/mini_racer_runtime.rb:66:in `translate'
/home/zied/.rvm/gems/ruby-2.3.0/gems/execjs-2.7.0/lib/execjs/mini_racer_runtime.rb:9:in `initialize'
/home/zied/.rvm/gems/ruby-2.3.0/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `new'
/home/zied/.rvm/gems/ruby-2.3.0/gems/execjs-2.7.0/lib/execjs/runtime.rb:57:in `compile'
/home/zied/.rvm/gems/ruby-2.3.0/gems/execjs-2.7.0/lib/execjs/module.rb:27:in `compile'
/home/zied/.rvm/gems/ruby-2.3.0/gems/react_on_rails-6.1.2/lib/react_on_rails/server_rendering_pool/exec.rb:91:in `create_js_context'
/home/zied/.rvm/gems/ruby-2.3.0/gems/react_on_rails-6.1.2/lib/react_on_rails/server_rendering_pool/exec.rb:10:in `block in reset_pool'
/home/zied/.rvm/gems/ruby-2.3.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:169:in `try_create'
/home/zied/.rvm/gems/ruby-2.3.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:81:in `block (2 levels) in pop'
/home/zied/.rvm/gems/ruby-2.3.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:77:in `loop'
/home/zied/.rvm/gems/ruby-2.3.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:77:in `block in pop'
/home/zied/.rvm/gems/ruby-2.3.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:76:in `synchronize'
/home/zied/.rvm/gems/ruby-2.3.0/gems/connection_pool-2.2.0/lib/connection_pool/timed_stack.rb:76:in `pop'
/home/zied/.rvm/gems/ruby-2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:89:in `checkout'
/home/zied/.rvm/gems/ruby-2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:61:in `block in with'
/home/zied/.rvm/gems/ruby-2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `handle_interrupt'
/home/zied/.rvm/gems/ruby-2.3.0/gems/connection_pool-2.2.0/lib/connection_pool.rb:60:in `with'
/home/zied/.rvm/gems/ruby-2.3.0/gems/react_on_rails-6.1.2/lib/react_on_rails/server_rendering_pool/exec.rb:72:in `eval_js'
/home/zied/.rvm/gems/ruby-2.3.0/gems/react_on_rails-6.1.2/lib/react_on_rails/server_rendering_pool/exec.rb:36:in `server_render_js_with_console_logging'
/home/zied/.rvm/gems/ruby-2.3.0/gems/react_on_rails-6.1.2/lib/react_on_rails/server_rendering_pool.rb:21:in `method_missing'
/home/zied/.rvm/gems/ruby-2.3.0/gems/react_on_rails-6.1.2/app/helpers/react_on_rails_helper.rb:298:in `server_rendered_react_component_html'
/home/zied/.rvm/gems/ruby-2.3.0/gems/react_on_rails-6.1.2/app/helpers/react_on_rails_helper.rb:112:in `react_component'
/home/zied/projects/tutos/react/pluralsight/twitter-clone/app/views/home/index.html.erb:1:in `_app_views_home_index_html_erb___3218135921149175622_27455200'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionview-5.0.0.1/lib/action_view/template.rb:158:in `block in render'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:166:in `instrument'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionview-5.0.0.1/lib/action_view/template.rb:348:in `instrument'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionview-5.0.0.1/lib/action_view/template.rb:156:in `render'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionview-5.0.0.1/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionview-5.0.0.1/lib/action_view/renderer/abstract_renderer.rb:42:in `block in instrument'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `block in instrument'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `instrument'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionview-5.0.0.1/lib/action_view/renderer/abstract_renderer.rb:41:in `instrument'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionview-5.0.0.1/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionview-5.0.0.1/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionview-5.0.0.1/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionview-5.0.0.1/lib/action_view/renderer/template_renderer.rb:14:in `render'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionview-5.0.0.1/lib/action_view/renderer/renderer.rb:42:in `render_template'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionview-5.0.0.1/lib/action_view/renderer/renderer.rb:23:in `render'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionview-5.0.0.1/lib/action_view/rendering.rb:103:in `_render_template'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_controller/metal/streaming.rb:217:in `_render_template'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionview-5.0.0.1/lib/action_view/rendering.rb:83:in `render_to_body'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_controller/metal/rendering.rb:52:in `render_to_body'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_controller/metal/renderers.rb:144:in `render_to_body'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/abstract_controller/rendering.rb:26:in `render'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_controller/metal/rendering.rb:36:in `render'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:44:in `block (2 levels) in render'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/core_ext/benchmark.rb:12:in `block in ms'
/home/zied/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/benchmark.rb:308:in `realtime'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/core_ext/benchmark.rb:12:in `ms'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:44:in `block in render'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:87:in `cleanup_view_runtime'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activerecord-5.0.0.1/lib/active_record/railties/controller_runtime.rb:25:in `cleanup_view_runtime'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:43:in `render'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_controller/metal/implicit_render.rb:36:in `default_render'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_controller/metal/basic_implicit_render.rb:4:in `send_action'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/abstract_controller/base.rb:188:in `process_action'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_controller/metal/rendering.rb:30:in `process_action'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:126:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:506:in `block (2 levels) in compile'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:455:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:101:in `__run_callbacks__'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_process_action_callbacks'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_controller/metal/rescue.rb:20:in `process_action'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `block in instrument'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/notifications/instrumenter.rb:21:in `instrument'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/notifications.rb:164:in `instrument'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_controller/metal/params_wrapper.rb:248:in `process_action'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activerecord-5.0.0.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/abstract_controller/base.rb:126:in `process'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionview-5.0.0.1/lib/action_view/rendering.rb:30:in `process'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_controller/metal.rb:190:in `dispatch'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_controller/metal.rb:262:in `dispatch'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:50:in `dispatch'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:32:in `serve'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:39:in `block in serve'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:26:in `each'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_dispatch/journey/router.rb:26:in `serve'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_dispatch/routing/route_set.rb:725:in `call'
/home/zied/.rvm/gems/ruby-2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:35:in `block in call'
/home/zied/.rvm/gems/ruby-2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `catch'
/home/zied/.rvm/gems/ruby-2.3.0/gems/warden-1.2.6/lib/warden/manager.rb:34:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/rack-2.0.1/lib/rack/etag.rb:25:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/rack-2.0.1/lib/rack/conditional_get.rb:25:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/rack-2.0.1/lib/rack/head.rb:12:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:222:in `context'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/rack-2.0.1/lib/rack/session/abstract/id.rb:216:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/cookies.rb:613:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activerecord-5.0.0.1/lib/active_record/migration.rb:552:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/callbacks.rb:38:in `block in call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:97:in `__run_callbacks__'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:750:in `_run_call_callbacks'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/callbacks.rb:90:in `run_callbacks'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/callbacks.rb:36:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/remote_ip.rb:79:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/debug_exceptions.rb:49:in `call'
/home/zied/.rvm/gems/ruby-2.3.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:135:in `call_app'
/home/zied/.rvm/gems/ruby-2.3.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:28:in `block in call'
/home/zied/.rvm/gems/ruby-2.3.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:18:in `catch'
/home/zied/.rvm/gems/ruby-2.3.0/gems/web-console-3.4.0/lib/web_console/middleware.rb:18:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:36:in `call_app'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `block in call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `block in tagged'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:26:in `tagged'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/tagged_logging.rb:70:in `tagged'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.1/lib/rails/rack/logger.rb:24:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/sprockets-rails-3.2.0/lib/sprockets/rails/quiet_assets.rb:13:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/request_id.rb:24:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/rack-2.0.1/lib/rack/method_override.rb:22:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/rack-2.0.1/lib/rack/runtime.rb:22:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/activesupport-5.0.0.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/executor.rb:12:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/actionpack-5.0.0.1/lib/action_dispatch/middleware/static.rb:136:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/rack-2.0.1/lib/rack/sendfile.rb:111:in `call'
/home/zied/.rvm/gems/ruby-2.3.0@global/gems/railties-5.0.0.1/lib/rails/engine.rb:522:in `call'
/home/zied/.rvm/gems/ruby-2.3.0/gems/puma-3.6.0/lib/puma/configuration.rb:225:in `call'
/home/zied/.rvm/gems/ruby-2.3.0/gems/puma-3.6.0/lib/puma/server.rb:578:in `handle_request'
/home/zied/.rvm/gems/ruby-2.3.0/gems/puma-3.6.0/lib/puma/server.rb:415:in `process_client'
/home/zied/.rvm/gems/ruby-2.3.0/gems/puma-3.6.0/lib/puma/server.rb:275:in `block in run'
/home/zied/.rvm/gems/ruby-2.3.0/gems/puma-3.6.0/lib/puma/thread_pool.rb:116:in `block in spawn_thread'
`
Any help please.

**Comment by justin808** [comment]
@ziedhajsalah From the stack trace, you *might* have jQuery trying to access DOM nodes. Those do not exist in server rendering. You need to configure your server JS bundle so that you don't do this. 

Your error is:
```
Encountered error: "TypeError: _jquery2.default.get is not a function"
```

You might not want to load jquery server side.


If you need help specific to your app, ShakaCode is available for consulting or coaching. Please see http://www.shakacode.com/work/ or get in touch: justin@shakacode.com.

**Comment by ziedhajsalah** [comment]
@justin808  thank you, i changed the jqery call to componentDidMount and it works.
