### ISSUE TITLE
Use with therubyracer instead of mini_racer

### ISSUE THREAD

**Issue by mikeLspohn** [shakacode/react_on_rails#594]
I know mini_racer is apparently much faster than therubyracer, which is why it is used, but is there anyways to use this gem with therubyracer? We're trying to get some React into our legacy Rails codebase, but `less-rails` requires `therubyracer` so is there anyways to use that instead of mini_racer? Or any other suggestions? This gem looks awesome and were really wanting to make it work.

**Comment by justin808** [comment]
@mikeLspohn Just swap the gem in the gemfile. That's it.

**Comment by aeldaly** [comment]
@justin808 Do you mean fork the repo, and swap it in the Gemfile myself?

**Comment by aeldaly** [comment]
Oh. Sorry. Disregard. I see that the gem is added in Gemfile after running install. Thanks.
