### ISSUE TITLE
Following your tutorial, I get an error (not yet sure how serious)

### ISSUE THREAD

**Issue by ezmiller** [shakacode/react_on_rails#595]
Here is the error, generated when I ran `rails generate react_on_rails:install`:

![](https://s3.amazonaws.com/ezmiller/public/images/2._ethanoporto_Projectsmotologicrails-on-react-tutorial_zsh_2016-11-08_08-51-25.png)

Doesn't mean much to me. I'm using rails v5.0.0.1 and ruby v2.3.1. I'm still able to get the server up so this may be insignificant, but I thought I'd report it anyway.

**Comment by justin808** [comment]
That's only an issue if you want to use rspec.
