### ISSUE TITLE
What's the pattern for updating a React component?

### ISSUE THREAD

**Issue by archonic** [shakacode/react_on_rails#596]
I'm wondering how others are updating their React components, as in re-rendering with new props after a successful response from the server. If I have to rerender a Rails view container, that would mean the only benefit of bringing React into Rails would be to leverage browser rendering. The value in React for me is in having a proper state manager, to get away from the unmaintainable mess created when making complex ajax heavy pages with jQuery.

https://github.com/archonic/shaka_limestone

This is a boilerplate SaaS app in infancy. It contains the example hello world component. In completing the profile edit page, I realized there's a chance to use React. Uploading a new avatar should update the component on the page but also the component in the navbar. In app/assets/javascripts/uploads.js, there's a `debugger` on L50. This is where I'd like to re-render React components with the URL of the new avatar. It doesn't look like the ReactOnRails API is designed to do that.

Update: Having a look at the CommentForm component in the tutorial app, it looks like I'd need to bring the request into the component to act upon the response. Does that always need to be the case? I'm not sure what the role of reducers or immutable.js is, but I'll stick to one question - how would you go about updating the a component after a successful trip back from the server? The response is JSON.

**Comment by justin808** [comment]
@archonic Possibly you might be interested in a coaching plan: http://www.shakacode.com/work/ so we can help you with your specific app. Feel free to request reopening this issue if you believe it is specific to React on Rails.

**Comment by archonic** [comment]
That seems likely, but I'll be finishing up the React tutorial docs before taking advantage of that. Cheers!
