### ISSUE TITLE
Cannot deploy to heroku

### ISSUE THREAD

**Issue by ceres629** [shakacode/react_on_rails#597]
Asked this question in many places, not sure if its a bug only i'm experiencing or that something is misconfigured as noone seems to know the answer...

I'm trying to deploy my app to heroku but it refuses to deploy with the following errors

`ERROR in ./app/bundles/appbundle/startup/MyApp.jsx
remote:        Module not found: Error: Cannot resolve 'file' or 'directory' /tmp/build_5f0499a33a66627b6911c88bcf69f8ab/client/node_modules/react in /tmp/build_5f0499a33a66627b6911c88bcf69f8ab/client/app/bundles/appbundle/startup`

This seems to be saying it cannot find 
client/node_modules/react in client/app/bundles/appbundle/startup?
No such directory exists on my local machine and it works fine there so I don't understand why it is looking for a file there in production...

Everything works fine on my local machine, 
Here is my webpack.config.js if that helps.

```
const webpack = require('webpack')
const path = require('path')
const glob = require('glob')

const devBuild = process.env.NODE_ENV !== 'production'
const nodeEnv = devBuild ? 'development' : 'production'

const config = {
  entry: [
    'es5-shim/es5-shim',
    'es5-shim/es5-sham',
    'babel-polyfill'
  ].concat(glob.sync('./app/bundles/**/startup/*')),

  output: {
    filename: 'webpack-bundle.js',
    path: '../app/assets/webpack'
  },

  resolve: {
    extensions: ['', '.js', '.jsx'],
    alias: {
      react: path.resolve('./node_modules/react'),
      'react-dom': path.resolve('./node_modules/react-dom')
    }
  },

  plugins: [
    new webpack.DefinePlugin({
      'process.env': {
        NODE_ENV: JSON.stringify(nodeEnv)
      }
    })
  ],

  module: {
    loaders: [
      {
        test: require.resolve('react'),
        loader: 'imports?shim=es5-shim/es5-shim&sham=es5-shim/es5-sham'
      },

      {
        test: /\.jsx?$/,
        loader: 'babel-loader',
        exclude: /node_modules/
      }
    ]
  }
}

module.exports = config

if (devBuild) {
  console.log('Webpack dev build for Rails')  // eslint-disable-line no-console
  module.exports.devtool = 'eval-source-map'
} else {
  config.plugins.push(
    new webpack.optimize.DedupePlugin()
  )
  console.log('Webpack production build for Rails')  // eslint-disable-line no-console
}
```

**Comment by justin808** [comment]
Please confirm you followed the steps here: https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/heroku-deployment.md

Did you setup the custom buildpack?

**Comment by justin808** [comment]
Please re-open if you believe this is still an issue, @ceres629.

**Comment by JonathanKolnik** [comment]
@justin808 Hi I am hitting this issue also related to some of the additional npm packages I've pulled in. Do I need to add a buildpack for each of those 

this is the error I have

```
remote:        Module not found: Error: Cannot resolve 'file' or 'directory' /tmp/build_567aaf834092e9fde4b122af269a6957/client/node_modules/react-router in /tmp/build_567aaf834092e9fde4b122af269a6957/client/app/bundles/HelloWorld/startup
```

**Comment by justin808** [comment]
@JonathanKolnik It looks like you are not including react-router in your package.json. Please get in touch directly if you want personalized help to resolve this issue. You can [email me](justin@shakacode.com).

**Comment by JonathanKolnik** [comment]
@justin808 this is what my package.json looks like

```{
  "name": "react-webpack-rails-tutorial",
  "version": "0.0.1",
  "engines": {
    "node": "5.10.0",
    "npm": "3.5.0"
  },
  "scripts": {
    "postinstall": "cd client && npm install",
    "rails-server": "echo 'visit http://localhost:3000/hello_world' && foreman start -f Procfile.dev",
    "test": "rspec"
  },
  "dependencies": {
    "gsap": "^1.19.1",
    "lodash": "^4.17.4",
    "react": "^15.4.2",
    "react-addons-css-transition-group": "^15.4.2",
    "react-addons-transition-group": "^15.4.2",
    "react-bootstrap": "^0.30.7",
    "react-css-transition-replace": "^2.1.0",
    "react-router": "^3.0.2",
    "throttle-debounce": "^1.0.1"
  }
}
```

**Comment by justin808** [comment]
@JonathanKolnik Needs to look more like [this](https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/package.json). You can [email me](mailto:justin@shakacode.com) for more help if needed.

**Comment by JonathanKolnik** [comment]
so stupid...I was editing package.json not client/package.json. I added react router there and it's all good now.

**Comment by fabdarice** [comment]
Hi @ceres629 did you figure it out what happened? I have the same issue as you had.
Thanks
