### ISSUE TITLE
Digitalocean deploy issue

### ISSUE THREAD

**Issue by fatehwaharp** [shakacode/react_on_rails#599]
I'm currently trying to deploy basic hello world ReactonRails apps to digital ocean with capistrano, 
in development everything is working good, but when deploying to production it showing this error
```
Error: Cannot find module 'react'
    at Function.Module._resolveFilename (module.js:472:15)
    at Function.resolve (internal/module.js:27:19)
    at Object.<anonymous> (/home/deploy/test-react/releases/20161110151340/client/webpack.config.js:37:23)
    at Module._compile (module.js:573:32)
    at Object.Module._extensions..js (module.js:582:10)
    at Module.load (module.js:490:32)
    at tryModuleLoad (module.js:449:12)
    at Function.Module._load (module.js:441:3)
    at Module.require (module.js:500:17)
    at require (internal/module.js:20:19)
```

then I've tried to remove the line
```
      {
        test: require.resolve('react'),
        loader: 'imports?shim=es5-shim/es5-shim&sham=es5-shim/es5-sham',
      },
```

and capistrano manage to deploy even though it says that got 4 errors about es5-shim something like that, and in my chrome console log it show this error and react doesnt work.

<img width="1216" alt="screen shot 2016-11-10 at 11 56 39 pm" src="https://cloud.githubusercontent.com/assets/306898/20183939/f8dc8a46-a7a1-11e6-98ff-f4aea83dc7b8.png">

**Comment by justin808** [comment]
@fatehwaharp any update to this issue? I'm not using Capistrano, so you'll have to debvug this.

**Comment by nostophilia** [comment]
@fatehwaharp 
I guess the packages aren't properly installed on your production server. As after running the generator "node_modules" will be added to your .gitignore, you will need to run "npm install" on your production server or create a cap task for this.

**Comment by fatehwaharp** [comment]
@justin808 still stuck, as for now I just go and deploy with heroku, maybe later I'll try again and find a way.

@nostophilia thanks for your response, btw I did run the npm install on the production server, but the way I run the npm install command is not by cap task, but by manually going into the prod server, and go to the capistrano releases and got to the failed deploy version, and run the npm install inside the folder, I guess it should be the same right ?

**Comment by nostophilia** [comment]
@fatehwaharp 
Navigate to `client/node_modules` to check whether packages (e.g. `react`) are installed here and make sure there's nothing under `your_rails_root/node_modules`
Then for a quick fix you can have `config.npm_build_production_command = "npm install; npm run build:production"` in your react_on_rails initializer. But `npm install` slows deployment, you'd better have node_modules in a shared directory

**Comment by fatehwaharp** [comment]
@nostophilia thanks for your help. I'll try it and update you later.

**Comment by justin808** [comment]
@fatehwaharp @nostophilia May we close this issue?

**Comment by nostophilia** [comment]
@justin808 I guess so, this is inactive.
