### ISSUE TITLE
Detailed Setup and Usage Docs

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#6]
Lots of work do here.

**Comment by taylorbrooks** [comment]
Hey just found this from here: https://github.com/reactjs/react-rails/issues/301

There's nothing in the README about how to use this. I'm happy to contribute in writing docs, but it looks  like there's nothing at this point?

Was hoping [this post](http://www.railsonmaui.com/blog/2014/10/02/integrating-webpack-and-the-es6-transpiler-into-an-existing-rails-project/) would provide some context -- looks like it's broken.

Lemme know how I can help!

**Comment by justin808** [comment]
@taylorbrooks super!: http://www.railsonmaui.com/blog/2014/10/03/integrating-webpack-and-the-es6-transpiler-into-an-existing-rails-project/

I'll add you to our slack chat. You'll become an expert very quickly!

For anybody else that wants any mentoring in this, the best way to master it is to reach out to me justin@shakacode.com or any members of the Shaka Code team.

**Comment by justin808** [comment]
@taylorbrooks where did you get the broken link. I'll fix it.

**Comment by taylorbrooks** [comment]
https://github.com/reactjs/react-rails/issues/301#issuecomment-113597288

**Comment by justin808** [comment]
Documentation was improved in #20. @taylorbrooks I'd be grateful for any feedback.
