### ISSUE TITLE
react_on_rails in Jekyll

### ISSUE THREAD

**Issue by schoenwaldnils** [shakacode/react_on_rails#603]
Hi there,

is there a way to use this in an Jekyll-enviroment?
I'm looking for a way to prerender react-components using Jekyll, but can't find any good way to do this. I hope this gem could help there.

**Comment by justin808** [comment]
@schoenwaldnils I doubt this would help. Are you looking to pre-render, but not have a server side?

**Comment by schoenwaldnils** [comment]
@justin808 It's basically the same for me. I'm using [cloudcannon](http://cloudcannon.com/) andy they don't get along well with react, so I want Jekyll be able to render react-components for itself.

**Comment by justin808** [comment]
But do you need a server to render based on changes in data? I suppose the
core of Jekyll could be changed to render the react.

-- 
Justin Gordon | CEO and Founder of shakacode.com <http://www.shakacode.com/>
 and friendsandguests.com | twitter: @railsonmaui
<https://twitter.com/railsonmaui>
