### ISSUE TITLE
remove hardcoded references to /client folder

### ISSUE THREAD

**Issue by yinghaochan** [shakacode/react_on_rails#604]
if, for example, the /client folder is already used, we'd to defined another folder (or use root)

perhaps setting the base folder could be allowed as a config setting?

For example: 
https://github.com/shakacode/react_on_rails/blob/master/lib/tasks/assets.rake#L33

**Comment by justin808** [comment]
@yinghaochan you are the first person in 1.5 years to ask for this. I'm OK with a PR to make this configurable.

**Comment by yinghaochan** [comment]
cool. Thanks!

Will try to get on it soon. Is there a reason why the docs discourages using the app-root package.json for install dependencies?

Meanwhile, if anyone else wants a the root folder: 
```ruby
# This configures the script to run to build the production assets by webpack. Set this to nil
  # if you don't want react_on_rails building this file for you.
  config.npm_build_production_command = "(cd .. && npm run build-production) || npm run build-production"
```

**Comment by justin808** [comment]
@yinghaochan The idea is to keep the top level tidy by not having the node_modules there.

**Comment by yinghaochan** [comment]
@justin808 got it. However, we have millions of loc in app/assets and would be too painful to migrate out. 

Things like `.babelrc` and loaders have issues with .jsx files in a parent / sibling directory of `/client`. 

Fixable, but hacky. So sticking to js norms and accepting a little bit of mess.

**Comment by justin808** [comment]
Try creating a fork of
https://github.com/shakacode/react-webpack-rails-tutorial

and move the node_modules to the top level...

I think the issue was running the servers (webpack dev server), maybe.

**Comment by justin808** [comment]
So far, nobody else has voted for this. Let's close this for now. Feel free to re-open in the future.
