### ISSUE TITLE
Help with React_on Rails Latest with Bootstrap 4

### ISSUE THREAD

**Issue by rnikunen** [shakacode/react_on_rails#607]
I am very keen to use this to rehaul our current rails app.  I need to be able to incorporate Bootstrap 4 and going through the tutorial I am stuck at understanding how to add bootstrap 4.  I use the default rails generate react_on_rails:install and then try to follow the directions for bootstrap-loader and in the end I end up with this on hello world.
![screen shot 2016-11-16 at 4 46 10 pm](https://cloud.githubusercontent.com/assets/249998/20371818/3ef122b6-ac1c-11e6-897a-9908a2b2a914.png)

**Comment by justin808** [comment]
Did you find a solution @rnikunen? Can we close this issue?
