### ISSUE TITLE
Check that webpack is running when rails starts in development mode

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#615]
Let's add a check that webpack is running when running a React on Rails app in development mode!

http://blog.iempire.ru/2016/07/09/webpack-and-rails/

From a discussion on adding wbpack with Rails.

>  Should Webpack be running as a separate process, either the webpack-dev-server or webpack in watch mode? Or should it be embedded as a child process of Rails?

This is something I have experimented too. We had a client app with heavy JS/React code and at some point we have moved from Sprockets to Webpack. This was a bit of a problem because developers forgot to start webpack process after launching Rails server.

We've made a middleware that checked if webpack process is running, and if it's not, friendly suggested to launch it. Something like `ActiveRecord::Migration::CheckPending` does.

The reason not to run webpack as a child process in Rails is that you're usually interested in the output of Webpack and sometimes you want to restart Webpack separately from Rails.

Another problem was that developers kept changing assets and refreshing the page to see changes, but there was a syntax / compilation error in Webpack and they forgot to check Webpack process output.
I added the error reporter to Webpack that dumped compilation errors into `tmp/webpack-status.json`, and Rails could read and display errors on the same page so developers would immediately know about issue in their code (screenshot attaches).

**Comment by justin808** [comment]
@Judahmeek, @robwise check this one out! Useful?

**Comment by robwise** [comment]
It's a bit presumptuous because sometimes I want to run in development mode with the production webpack output (which is static). Also, we attempted to determine whether or not webpack was running in the test helper and we both agreed that it was too hacky and abandoned that approach.
