### ISSUE TITLE
Clarification on Heroku Documentation

### ISSUE THREAD

**Issue by dijonkitchen** [shakacode/react_on_rails#616]
The [Readme](https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/heroku-deployment.md#heroku-deployment) mentions the `lib/tasks/asset.rake` file being generated whether the user chooses Heroku deployment or not. 

I don't see this as a choice anywhere and I think it's automatically included in the gem. When running `bundle exec rake -T` to see the rake tasks, I see the referenced tasks, but there's nothing in the Rail's directory 'lib/tasks/'.

**Comment by justin808** [comment]
@dijonkitchen we updated react_on_rails so the file is no longer needed. Could you submit a PR that reflects this?
