### ISSUE TITLE
Very slow on Ubuntu machine

### ISSUE THREAD

**Issue by hashwin** [shakacode/react_on_rails#618]
Hi,

I have been using this for a while now, and it works well on my Macbook Air. Unfortunately on one of my colleague's Ubuntu machine, it works incredibly slowly whenever the webpack build changes - looks to be stuck on the rendering part. Any idea why that would be?

**Comment by justin808** [comment]
@hashwin Given that nobody else is reporting this, I'd say the problem is on your colleague's machine. Try to isolate the slow part. Are you doing server rendering? Is webpack slow by itself, when run from the command line? Are you using css-modules? Did you use shrinkwrap to lock the modules?

**Comment by justin808** [comment]
@hashwin Did you make any progress on this issue?

**Comment by hashwin** [comment]
@justin808 Not had too much luck. Whenever anything is changed, the webpack bundle only takes around 2-5 seconds to complete. But, on refresh of the page, it seems like something gets stuck - it takes 40-50s for the server to start rendering the response. If nothing is changed, it is fast. On my macbook air, it only takes ~5-6 seconds to render when things are changed. 
I'm having a hard time tracking down the issue. Not doing server rendering, only hydrating redux with json props from the server. Not using css modules either, only inline styles. Not sure if any of the packages I'm using use inline styles.

**Comment by hashwin** [comment]
Caught a break. Seems like foreman is causing some sort of issue. Running the rails server and webpack runner separately seems to make things much faster.

**Comment by hashwin** [comment]
Installed an SSD and now everything's at the speed it should be!
