### ISSUE TITLE
Tune up Coveralls

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#62]
@dylangrafmyre @robwise Let's tune up Coveralls https://coveralls.io/github/shakacode/react_on_rails

1. I can't find react_on_rails_helper.rb listed in the coverage.
2. The coverage of some of the other files is a bit dubious. It seems that initialization of the gem is not getting flagged as covered.

![2015-10-17_21-17-58](https://cloud.githubusercontent.com/assets/1118459/10562528/988c38be-7514-11e5-865d-38684f6fe91d.png)

![2015-10-17_21-18-54](https://cloud.githubusercontent.com/assets/1118459/10562530/b8f1dd8e-7514-11e5-837d-fd60265d0f53.png)

![2015-10-17_21-20-07](https://cloud.githubusercontent.com/assets/1118459/10562536/e5c4495a-7514-11e5-9dc3-53d22d90479b.png)

![2015-10-17_21-21-04](https://cloud.githubusercontent.com/assets/1118459/10562538/05cc6c46-7515-11e5-8625-7dba4c95d0be.png)

**Comment by robwise** [comment]
@justin808 Are we good on this after #64 ?
