### ISSUE TITLE
Catching rendering errors

### ISSUE THREAD

**Issue by nicolaskruchten** [shakacode/react_on_rails#620]
Is there a way for me to catch rendering errors in my top-level React component?

**Comment by justin808** [comment]
@nicolaskruchten You probably don't want to do that. However, in your app, you can have a top level error handler.

**Comment by nicolaskruchten** [comment]
Why wouldn't I want to do that? Right now if there is an error the user just sees a broken/empty page. I'd like to at least throw up some kind of notification or alert or something...

**Comment by justin808** [comment]
@nicolaskruchten if you're server rendering, there's a setting in react_on_rails.rb where you can configure whether or not you want a server error.

On the client side, I think your question is related to all React apps.

**Comment by nicolaskruchten** [comment]
I'm not server-rendering. 

The thing is that as I understand it, the ReactOnRails code is invoking `render()` for me on the client, so I can't wrap it in a try-catch like I might be able to in a React app where I was the one controlling things... Am I misunderstanding this?

**Comment by nicolaskruchten** [comment]
To be a bit more specific... I'd like to be able to trap errors like the framework does here: https://github.com/shakacode/react_on_rails/blob/master/node_package/src/handleError.js#L38

**Comment by justin808** [comment]
Why not just put the catch in your top level, registered react component.

Put in a catch and return a simple react jsx for whatever you want.

**Comment by nicolaskruchten** [comment]
That's likely what I'll do but in our app we have multiple pages, each with their own top-level component. We don't have a SPA, we have multiple mini-SPAs, all managed by React on Rails, so I'll have to add this try-catch logic in a couple of dozen places and I was hoping to just tap into your existing infrastructure. Anyway, consider it a feature suggestion :)

**Comment by justin808** [comment]
There's no need to duplicate the logic 12 times. Just create a "HOC"
(Higher Order Component) which has this logic.

If you need help setting this up, let me know.
http://www.shakacode.com/work/index.html.

**Comment by nicolaskruchten** [comment]
Ah, thanks for the point to HOCs, I'll see if that fits the bill for us :)

**Comment by justin808** [comment]
Please document here to share with the community. Good error handling is key to all apps.
