### ISSUE TITLE
React component not rendering.

### ISSUE THREAD

**Issue by abologna-r7** [shakacode/react_on_rails#623]
Using Rails: 5.0.0.1
I started a clean rails app, running on the latest rails version. I followed the instructions on creating a react on rails helloworldapp. Everything seems to be running smoothly, no console errors, but the component never renders. If I set the prerender to true, it does the rendering, otherwise, it just comes empty. Attaching a snapshot of the DOM tree on running:

<img width="1017" alt="screen shot 2016-11-25 at 10 07 09 am" src="https://cloud.githubusercontent.com/assets/8812471/20631994/688adc8e-b2f7-11e6-98e1-09290f8ee0ef.png">

btw, Happy Thanksgiving!

**Comment by abologna-r7** [comment]
Found the issue myself. It was on my end, that application.js wasn't being loaded on the main layout. Closing issue now :)

**Comment by Jacfem** [comment]
Thank you for posting this solution, I just encountered the same error and this fixed it!
