### ISSUE TITLE
Server Side Rendering v2

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#625]
Currently, we can do server rendering using execJS and mini-racer.

We would like to continue investigations into using a Node.js server to do server rendering.

I'm roughly guessing that we should be using some Express based engine.

We'd like the solution to be:

1. Easy to implement and deploy.
2. Easy to scale.
3. Easy to monitor the performance and determine when to increase scaling.
4. Caching could be interesting.

Links:

* https://product.reverb.com/react-on-rails-9936283aea07#.p535ja2i2
* https://gist.github.com/ebenoist/3564113f46c92d445a43bad1fb26251e#file-react-rendering-engine-js
* https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/node-server-rendering.md
* https://github.com/redfin/react-server
* https://github.com/airbnb/hypernova
* https://github.com/shakacode/react_on_rails/pull/621

CC: @alexfedoseev @robwise @jtibbertsma @rocLv @martyphee

**Comment by udovenko** [comment]
I've read rougly through the links. Seems there are two general ways to go: roll out own solution and try to adopt to existing project like **react-server** or **hypernova**.

**react-server** is very opinionated framework that operates **page** entities: https://react-server.io/docs/guides/writing-pages. And if I understand correctly, it assumes inverse responsibility chain of server rendering comparing to **react_on_rails** approach: client app requests **react-server** instance and this instance requests API endpoint (RoR app in our case). I do not see way to integrate it with current react_on_rails architecture. This project looks like possible replacement, not as rendering option. Need to dive deeply in docs to ensure this opinion though.

**Comment by justin808** [comment]
This is part of "React on Rails Pro". Contact justin@shakacode.com for more information on using a Node rendering server. This is in production for https://egghead.io.
