### ISSUE TITLE
New Feature: Enable multiple registrations

### ISSUE THREAD

**Issue by enzolutions** [shakacode/react_on_rails#630]
One of the most important features of React are components, that mean you can create isolated SPA ( Single Page Application), that means you could have one big component, but most of the time you have several React components.

One problem I found is related to the fact that the register could be loaded one time, via **ComponentRegistry**. The latest register overwrites the previous one.

Ideally, you must be able to use the same register across different React components.

**Comment by justin808** [comment]
@enzolutions If you register multiple times, newer registrations overwrite older ones. You can run register as many times as you like.

What is the exact issue that you're seeing?

**Comment by enzolutions** [comment]
Hi @justin808 

Thanks for you answer. As you said, newer registration overwrite older.

When I try to access those components, I got the following error

```
Could not find component registered with name notificationsProject. Registered component names include [ modelNewProject ]. Maybe you forgot to register the component?
```

The component **notificationsProject** was registered first, and then the **modelNewProject** registration overwrite the array.

My proposal is have something like a global array associated with window object and any new register call append the component(s).

Let me know if makes sense.

**Comment by justin808** [comment]
You must be loading a new page and the registrations are not running.

The registrations are stored on the global window object.

**Comment by enzolutions** [comment]
What I am doing is using webpack to create two SPA and loaded both in the same page, maybe that cause what you said.

Any ideas?

**Comment by jtibbertsma** [comment]
@enzolutions Do you mean that you're using two separate webpack bundles on the same page? And you have ReactOnRails in both bundles?

That would cause the error you're seeing, because the second ReactOnRails global object would overwrite the first. You should try putting ReactOnRails in a shared vendor-bundle.

**Comment by enzolutions** [comment]
@jtibbertsma 

You are correct that is exactly what is happening, but the whole idea of use react is exactly to do that to have separate elements if is necessary, I am wrong?

**Comment by jtibbertsma** [comment]
You're right, but you don't want to bundle libraries twice. You'll be sending the same data across the wire twice. It's redundant.

**Comment by enzolutions** [comment]
@jtibbertsma Do you have any recommendation to avoid that?

**Comment by jtibbertsma** [comment]
If I understand correctly, you've got two separate webpack bundles with separate configuration files that you're loading on the same page. Instead, you probably want one webpack config file with two entry points.
