### ISSUE TITLE
Update Node version

### ISSUE THREAD

**Issue by dijonkitchen** [shakacode/react_on_rails#632]
Should this generated package.json be update for at least the latest LTS Node version 6.9.1? https://github.com/shakacode/react_on_rails/blob/master/lib/generators/react_on_rails/templates/base/base/package.json.tt

Looks like the tutorial was updated to the latest Stable at 7.2.0: https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/package.json#L7

https://nodejs.org/en/

**Comment by justin808** [comment]
Yes, it should be updated!

**Comment by justin808** [comment]
I'd say 7.2

**Comment by justin808** [comment]
@dijonkitchen A PR would be great. Maybe consider helping us with #622?
