### ISSUE TITLE
Use react_component method in ReactOnRailsHelper inside a lib model object.

### ISSUE THREAD

**Issue by kschuste** [shakacode/react_on_rails#634]
I am wanting to server side render a react component from a ruby model object located inside my lib folder.  I am able to use the react_component method in my haml file to server side render my component, but I am not able to access the method when wanting to use it to generate the html from inside a model object residing in my lib folder.

Is there an equivalent method inside the react_on_fails lib folder that I can include to get the html, or can I include the ReactOnRailsHelper module in some way to achieve this?  With the react-rails gem I was previously using, I was able to find the ruby code that server-side rendered the component inside their lib folder.  However, with this gem, all I see is the ReactOnRailsHelper file under the app/helpers folder.

# file path is the following:  lib/error/error_view
    def initialize(data = {})

      @name = data[:name]
      @description = data[:description]

    end

    # Public: Renders the ErrorView into a HTML String.
    #
    # template - The ActionView instance rendering the ErrorView.
    #
    # Returns a HTML String.
    def render_with_template(_template)

      # cannot find react_component
      react_component('ErrorView',
                                         props: {'name': @name,
                                                 'description': @description},
                                         prerender: true)

    end

**Comment by justin808** [comment]
@kschuste This should be no different than trying to use any view helper outside of a view.

**Comment by marcaltmann** [comment]
I'm trying to do a thing quite similar: Rendering a React component on the server from a Sidekiq worker. My goal is to take a snapshot of a React component and save it as a PNG. There are no requests, controllers or mailers involved.

This is how the beginning of my class which renders the ERB template looks like:

```
class TileRenderer
  include ReactOnRailsHelper
  include ActionView::Helpers::TagHelper
```

So, I can use the react_component helper in my ERB template. But when I do, it throws the following error:

 ```
NameError - undefined local variable or method `controller' for #<TileRenderer:0x007f46cf4da630>
21:01:39 web.1    | Did you mean?  content_for:
21:01:39 web.1    |   react_on_rails (6.3.1) app/helpers/react_on_rails_helper.rb:405:in `in_mailer?'
21:01:39 web.1    |   react_on_rails (6.3.1) app/helpers/react_on_rails_helper.rb:348:in `rails_context'
21:01:39 web.1    |   react_on_rails (6.3.1) app/helpers/react_on_rails_helper.rb:285:in `server_rendered_react_component_html'
21:01:39 web.1    |   react_on_rails (6.3.1) app/helpers/react_on_rails_helper.rb:112:in `react_component'
```

The line throwing the error is this:

```
def in_mailer?
    return false unless controller.present?
```

Shouldn't it be something like: `defined? controller`

Or am I missing something here? Is it even possible to do what I wanted?

**Comment by justin808** [comment]
@marcaltmann See the https://github.com/shakacode/react_on_rails/blob/master/CHANGELOG.md. Your issue got fixed last week.

**Comment by jtibbertsma** [comment]
@justin808 It seems that the issue didn't actually get fixed. The `in_mailer?` method fails with a `NameError`. It probably should be `defined? controller`.

**Comment by justin808** [comment]
@marcaltmann or @jtibbertsma Any chance one of you can provide a PR with a failing test that demonstrates the issue and a fix that passes the test?
