### ISSUE TITLE
Codeship Builds fail

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#639]
See details here:

https://community.codeship.com/t/npm-install-fails-due-to-npm-shrinkwrap-json-referencing-mac-os-only-package/5694

https://app.codeship.com/projects/187011/builds/20692524

```
npm ERR! Linux 4.2.0-42-generic
npm ERR! argv "/home/rof/.nvm/versions/node/v7.2.0/bin/node" "/home/rof/.nvm/versions/node/v7.2.0/bin/npm" "install"
npm ERR! node v7.2.0
npm ERR! npm  v4.0.3
npm ERR! code EBADPLATFORM

npm ERR! notsup Unsupported platform for fsevents@1.0.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm ERR! notsup Valid OS:    darwin
npm ERR! notsup Valid Arch:  any
npm ERR! notsup Actual OS:   linux
npm ERR! notsup Actual Arch: x64

npm ERR! Please include the following file with any support request:
npm ERR!     /home/rof/src/github.com/shakacode/react_on_rails/npm-debug.log
```

I do ensure that I'm using npm v4, so this bug shouldn't happen.

FWIW, this does work on Travis:

https://travis-ci.org/shakacode/react_on_rails/builds/180609074

**Comment by bbonamin** [comment]
Has the shrinkwrap been regenerated with either npm 3.10.10 or 4+? https://github.com/npm/npm/issues/14042#issuecomment-262902456

I'm hitting this exact issue on #651 and either downgrading as I've done [here](https://github.com/shakacode/react_on_rails/pull/651/commits/137d186e9f20a8d23b68c67be141fb89e933f3ea) or using 4+ (plus a regenerated shrinkwrap which marks fsevents as optional?) should fix it apparently.

**Comment by justin808** [comment]
Fixed!
