### ISSUE TITLE
why react_on_rails?

### ISSUE THREAD

**Issue by dgdosen** [shakacode/react_on_rails#643]
Hi all -

A newb question.

I've used quite a bit of backbone and a fair amount of ember and am now looking at React.  I like it.

So my question is - in the world of single page apps - why use react_on_rails vs simply having the client in it's own repo and completely segregated? That could/would create a nice separation between the client and server.  This is common in the ember world, where you can generate your static assets and just server them up from S3 and your rails "api server" works with a web client like any other.

Is there an assumption that a react_on_rails site would a "combo" of rails/react views? I ask this not having looked at any of the samples yet - but was hoping I'd see that for context before diving in.

I'll gladly organize replies to this in the readme or wiki.

Thanks!

**Comment by justin808** [comment]
@dgdosen This really depends on your project. See the https://www.reactrails.com/ site as an example, and the links to its source code.

And no, you don't need a combo, but you can.

It's really up to you.

**Comment by justin808** [comment]
@dgdosen This question would be better for http://forum.shakacode.com as it's not an issue or feature request for the gem.
