### ISSUE TITLE
The generated webpack-bundle.js is huge

### ISSUE THREAD

**Issue by marcusmalmberg** [shakacode/react_on_rails#645]
In development the generated bundle is about 3.2 mb and for production it is about **1.1 mb**. 

I've followed the [tutorial ](https://github.com/shakacode/react_on_rails/blob/master/docs/tutorial.md) to the point. Nice tutorial btw! Long time since one saw such detailed guides!

Looking at the [demo page](https://shakacode-react-on-rails.herokuapp.com/hello_world) the entire JS-file is only 193 kb, which is way more reasonable.

Somewhere something went wrong. I've tried various setups, including different node versions and webpack versions etc. I've cloned the [hello-react-on-rails](https://github.com/dzirtusss/hello-react-on-rails) project and installed it, all with the same result.

I've run it on a VM running Ubuntu 14.04 and also on Bash on Windows (WSL). 

```
> NODE_ENV=production webpack --config webpack.config.js

Webpack production build for Rails
Hash: 78f466c67f7cf3349f68
Version: webpack 1.14.0
Time: 3091ms
            Asset    Size  Chunks             Chunk Names
webpack-bundle.js  1.1 MB       0  [emitted]  main
   [0] multi main 64 bytes {0} [built]
    + 622 hidden modules
```

Here's the complete output of `npm install`: https://gist.github.com/marcusmalmberg/26c676d5c576618bd9604bda0d5717e0

Please let me know if there's anything else that's needed to debug this.

**Comment by justin808** [comment]
Try this: https://github.com/danvk/source-map-explorer

Yes, we should optimize, especially for production. Not so much for development.

**Comment by marcusmalmberg** [comment]
So silly of me, I simply forgot to pass the RAILS_ENV=production when precompiling my assets locally. 

Somehow I managed to mix up the line between rails and node in my mind and figured that the generated bundle from webpack is the "final" form, since that was what was served by my rails app. Remember kids, don't stay up and code late nights.

After proper precompilation the resulting application.js is only 127 kb gzipped, as it should be when it includes both react and jquery.

When filing the ticket I was afraid that something was wrong since I had newer dependencies from when the demo was built. But that was luckily not the case

---

Anyhow, that source-map-explorer was a great tool. Thank you for that! 

If you are still interested in the result of the bundle composition here it is in html format:  
https://rawgit.com/marcusmalmberg/13679ded8aee52455e9a3c18dc71551e/raw/c19ac8e925dd26d136a1195ce4f9d2d3e7871a0e/tree.html  

When also uglifying the JS with webpack the react-on-rails is 10.8 kb (4.1 %) uncompressed. Sure it's always possible to save a few bits and bytes, but the problem was with me :)

Regarding the development bundle there's no need to optimize. Should one have problem with the size you can turn of the source-map generation to save 50% transfer size, but that's a trade-off since it barely affects the rebuild time.
