### ISSUE TITLE
Please update Tutorial for rails 5

### ISSUE THREAD

**Issue by akatriel** [shakacode/react_on_rails#647]
'$ foreman start -f Procfile.dev'
Doesn't run nicely and returns:

17:10:52 web.1    | started with pid 9472
17:10:52 client.1 | started with pid 9156
17:10:52 client.1 | rm: cannot remove 'app/assets/webpack/*': No such file or directory
17:10:53 client.1 |
17:10:53 client.1 | > react-webpack-rails-tutorial@0.0.1 build:development C:\Users\NAME\Documents\projects\react_test\client
17:10:53 client.1 | > webpack -w --config webpack.config.js
17:10:53 client.1 |
17:10:53 client.1 | 'webpack' is not recognized as an internal or external command,
17:10:53 client.1 | operable program or batch file.
17:10:53 client.1 |
17:10:53 client.1 | npm ERR! Windows_NT 10.0.14393
17:10:53 client.1 | npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build:development"
17:10:53 client.1 | npm ERR! node v4.5.0
17:10:53 client.1 | npm ERR! npm  v2.15.9
17:10:53 client.1 | npm ERR! code ELIFECYCLE
17:10:53 client.1 | npm ERR! react-webpack-rails-tutorial@0.0.1 build:development: `webpack -w --config webpack.config.js`
17:10:53 client.1 | npm ERR! Exit status 1
17:10:53 client.1 | npm ERR!
17:10:53 client.1 | npm ERR! Failed at the react-webpack-rails-tutorial@0.0.1 build:development script 'webpack -w --config webpack.config.js'.
17:10:53 client.1 | npm ERR! This is most likely a problem with the react-webpack-rails-tutorial package,
17:10:53 client.1 | npm ERR! not with npm itself.
17:10:53 client.1 | npm ERR! Tell the author that this fails on your system:
17:10:53 client.1 | npm ERR!     webpack -w --config webpack.config.js
17:10:53 client.1 | npm ERR! You can get information on how to open an issue for this project with:
17:10:53 client.1 | npm ERR!     npm bugs react-webpack-rails-tutorial
17:10:53 client.1 | npm ERR! Or if that isn't available, you can get their info via:
17:10:53 client.1 | npm ERR!
17:10:53 client.1 | npm ERR!     npm owner ls react-webpack-rails-tutorial
17:10:53 client.1 | npm ERR! There is likely additional logging output above.
17:10:53 client.1 |
17:10:53 client.1 | npm ERR! Please include the following file with any support request:
17:10:53 client.1 | npm ERR!     C:\Users\NAME\Documents\projects\react_test\client\npm-debug.log
17:10:53 client.1 | exited with code 1
17:10:53 system   | sending SIGKILL to all processes
17:10:53 system   | sending SIGKILL to web.1 at pid 9472
17:10:53 web.1    | exited with code 0

**Comment by justin808** [comment]
@akatriel the tutorial is written for Rails 5.

**Comment by justin808** [comment]
@akatriel Let me know if you can't figure this one out.
