### ISSUE TITLE
Capistrano deploy fails with react_on_rails when NPM is installed via NVM

### ISSUE THREAD

**Issue by dmitrypol** [shakacode/react_on_rails#648]
The failing command `cd client && npm run build:production` comes from https://github.com/shakacode/react_on_rails/blob/master/lib/tasks/assets.rake

When using `capistrano-npm` and `capistrano-nvm` it creates `/tmp/my_app_name/nvm-exec.sh` with these contents and uses it to run `npm install` for `package.json` in the root rails app.  But it is not used to run commands for React client.  

    #!/bin/bash -e
    source "$HOME/.nvm/nvm.sh"
    nvm use $NODE_VERSION
    exec "$@"

Here is the output:

    cap production deploy
    rvm 1.27.0 (latest) by Wayne E. Seguin <wayneeseguin@gmail.com>, Michal Papis <mpapis@gmail.com> [https://rvm.io/]
    ruby-2.3.1
    ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-linux]
    00:00 nvm:wrapper
          01 mkdir -p /tmp/rails_cap_deploy/
        ✔ 01 ubuntu@myserver.com 0.034s
          Uploading /tmp/my_app_name/nvm-exec.sh 100.0%
    ... 
    ...
    00:16 npm:install
          01 /tmp/my_app_name/nvm-exec.sh npm install --production --silent --no-progress
          01 Now using node v6.9.2 (npm v3.10.9)
        ✔ 01 ubuntu@myserver.com 4.370s
    00:20 deploy:assets:precompile
          01 ~/.rvm/bin/rvm default do bundle exec rake assets:precompile
          01 cd client && npm run build:production
          01
          01 sh: 1:
          01 npm: not found
          01
          01 rake aborted!
          01 Command failed with status (127): [cd client && npm run build:production...]
          01 /opt/my_app_name/stg/shared/bundle/ruby/2.3.0/gems/react_on_rails-6.3.2/lib/tasks/assets.rake:33:in `block (3 levels) in <top (required)>'
          01 /opt/my_app_name/stg/shared/bundle/ruby/2.3.0/gems/rake-12.0.0/exe/rake:27:in `<top (required)>'
          ...
          01 Tasks: TOP => assets:precompile => react_on_rails:assets:compile_environment => react_on_rails:assets:webpack
          01 (See full trace by running task with --trace)
    (Backtrace restricted to imported tasks)
    cap aborted!
    SSHKit::Runner::ExecuteError: Exception while executing as ubuntu@myserver.com: rake exit status: 1
    rake stdout: Nothing written
    rake stderr: cd client && npm run build:production
    sh: 1: npm: not found
    rake aborted!
    Command failed with status (127): [cd client && npm run build:production...]

Here are my dependencies:

    Ubuntu 16.04
    rvm 1.27.0
    ruby-2.3.1
    NPM - 3.10.9
    NODE - v6.9.2
    NVM - 0.32.1
    
    Gems:
    rails (5.0.0.1)
    react_on_rails (6.3.2)
    capistrano (3.7.0)
    capistrano-npm (1.0.2)
    capistrano-nvm (0.0.6)
    capistrano-passenger (0.2.0)
    capistrano-rails (1.2.0)
    capistrano-bundler (~> 1.1)
    capistrano-rvm (0.1.2)
    
    Capfile:
    require 'capistrano/npm'
    require 'capistrano/nvm'

**Comment by justin808** [comment]
@dmitrypol the error says that npm is not found. Please configure your node installation so that it can be found in the path, from where this command is running. I bet Capistrano has it's own env values and that is why you are not seeing it.

**Comment by dmitrypol** [comment]
Hi @justin808 .  Thank you for responding to my question.  I understand that it cannot find NPM.  The question is how to configure it with the NVM installation.  Is there a way I can tell react_on_rails to use the /tmp/my_app_name/nvm-exec.sh which has the environment variables set?

**Comment by justin808** [comment]
Please try to put some debugging in your capistrano script and echo $PATH, and google around. I'm sure there's a way to get capistrano to work with node. Possibly you don't want to use nvm for capistrano.

**Comment by CodyBrouwers** [comment]
Had the same issue above and fixed it by adding the nvm folder to the rbenv path prefix in the capistrano deploy file like so:

```set :rbenv_prefix, "PATH=/home/deploy/.nvm/versions/node/v#{fetch(:node_version)}/bin:#{shared_path}/bin:$PATH NODE_ENV=#{fetch(:rails_env)} NVM_DIR=/home/deploy/.nvm RBENV_ROOT=#{fetch(:rbenv_path)} RBENV_VERSION=#{fetch(:rbenv_ruby)} #{fetch(:rbenv_path)}/bin/rbenv exec"```
