### ISSUE TITLE
Using react_on_rails in multiple gem dependencies

### ISSUE THREAD

**Issue by kschuste** [shakacode/react_on_rails#652]
I am attempting to convert my rails code to utilize this gem.  It is structured in that I have different gems that pull in specific gems such as the following:

Gem 1 -> Gem 2
Gem 2

Each gem has it's own react components that get bundled up for the server.  Gem 2 works as it has only 1 bundled file for the server.  However, Gem 1 does not work since it has a dependency on Gem 2.  I want to be to include both server-bundle files created by each gem; however, it fails to find the bundle for Gem 2 as it is looking in my Gem 1 directory.  Basically Gem 2 is overriding my Gem 1 config and want to have both.  Is there a way to do this?  Can we have more than 1 server-bundle file and not have the webpack and react_on_rails.rb configuration be overwritten?

**Comment by justin808** [comment]
What are the gems?

**Comment by kschuste** [comment]
They are my own gems on my company's own github so I can't give them out.

**Comment by justin808** [comment]
Hi @kschuste, you will have to do some debugging on your own.

The JS bundle files are JS code, rather than Ruby Gems, BTW.

Let me know if I can help more.

**Comment by kschuste** [comment]
I have made two sample gems to help show what I am trying to get around.  Can check out both in the same directory as base references dependent locally.  With base, I am trying to render the react component inside dependent as well.  However, it only finds the component registered in base.  Is there a way I can get both registered and keep them in separate gems?

https://github.com/kschuste/react_on_rails_base
https://github.com/kschuste/react_on_rails_dependent

If start of the server in base and navigate to localhost:3000/hello_universe
you will get the following error

{code}
Exception in rendering!

Message: Could not find component registered with name HelloWorld. Registered component names include [ HelloUniverse ]. Maybe you forgot to register the component?

Error: Could not find component registered with name HelloWorld. Registered component names include [ HelloUniverse ]. Maybe you forgot to register the component?
    at Object.get (eval at <anonymous> (unknown source), <anonymous>:63:11)
    at Object.getComponent (eval at <anonymous> (unknown source), <anonymous>:223:40)
    at createReactElement (eval at <anonymous> (unknown source), <anonymous>:46:45)
    at serverRenderReactComponent (eval at <anonymous> (unknown source), <anonymous>:45:71)
    at Object.serverRenderReactComponent (eval at <anonymous> (unknown source), <anonymous>:232:53)
    at <anonymous>:5:23
    at <anonymous>:12:3
{code}

**Comment by justin808** [comment]
@kschuste That's a great start! I'm sure there's something we can do to support your use case. Keep up the good work!

Please keep in mind that for the client side code, there's only one "window" context upon which we put the registered components. I doubt that we want to change that.
