### ISSUE TITLE
Redux generator uses local state rather than redux

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#653]
Turns out that we never use the action creator and redux for this component! we shouldn’t have local state in this file.

https://github.com/justin808/add-redux-component-to-react-on-rails/blob/add-redux-component/client/app/bundles/HelloWorld/components/HelloWorld.jsx#L17

We need to convert this component to use the action creators and pass in the name in the props always.

CC: @Judahmeek @jbhatab

**Comment by EEtancelin** [comment]
Would love doing my first PR ever on this bug. :-)
( But not really sure the first one will be the good one. :-1: )

**Comment by justin808** [comment]
@EEtancelin Awesome! Go for it! It's very easy to manually test this.

Before you change the template code, please share a repo with how you'd like the final code to look, and we'll verify that's correct.

**Comment by justin808** [comment]
@EEtancelin I'm going to be making an egghead video on this, so we need to get this done in the next few days.

**Comment by EEtancelin** [comment]
It's strange i have forked the repo. but i do not see the client directory. 
https://github.com/EEtancelin/add-redux-component-to-react-on-rails

Should i configure something ?

**Comment by Judahmeek** [comment]
@EEtancelin you've got to run the `rails generate react_on_rails:install` command for the generator to create the `/client` directory. Be sure to run `rails generate react_on_rails:install --help` first so you make sure you're using the right flags.

**Comment by EEtancelin** [comment]
@justin808
@Judahmeek 
 it's harder than i thought, but things progress. 
I have add a mapDispatchToProps in the helloworldContainer and change the connect call, following
http://redux.js.org/docs/basics/ExampleTodoList.html example .

Add a console.log(action) in the first line of the reducer in order to see if the reducer is call as intended.
Reducer is call well 

But i've got an issue the new state is not rerendered.
So either,
-The reducer is call but change doesn't change.
-either the redux state is not change.
Pretty sure the first option is the good one.

If you got any idea about what's going on, do not hesitate to tell me.
For now will investigate further :-)

You may take a look of the repo here https://github.com/EEtancelin/helloWorld-redux-fix

**Comment by EEtancelin** [comment]
Yeah !! Good new. Finally get it to works it was very simple, but lost a bit myself into the code. :-)

Whatever i have one design choice to make and would appreciate you give your feedback and what's belong to you is the best.

In the Hello world component i may either :-).

Write a function calling the function onNameUpdate given by the container.

`  updateName = (name) => {
    this.props.onNameUpdate(name);
  };`

Either directly call the onNameUpdate function in the form.
`        <form >
          <label htmlFor="name">
            Say hello to:
          </label>
          <input
            id="name"
            type="text"
            value={this.props.name}
            onChange={(e) => this.props.onNameUpdate(e.target.value)}
          />
        </form>`

What's belong to you is the best ? From my point of view the second one is better.
It's make the Helloworld component more Dump, and fit best with the smart/dump pattern of react-redux.

**Comment by EEtancelin** [comment]
You may find the work here https://github.com/EEtancelin/helloWorld-redux-fix/tree/test.
Be carefull the it's in the test branc.h.

Have nice christmas. :-)

**Comment by justin808** [comment]
https://github.com/EEtancelin/helloWorld-redux-fix/blob/test/client/app/bundles/HelloWorld/components/HelloWorld.jsx#L5

1. This can be a SFC given there's no state (simple functional component).
2. be sure to declare the action creator prop in the proptypes.

@EEtancelin

**Comment by justin808** [comment]
@EEtancelin Please create a PR let me know when you've updated. First update your repo.

Then I'd like to ship 6.3.3 ASAP. Please do your change log entry under 6.3.3. If you can't get this done soon, please let me know.

**Comment by EEtancelin** [comment]
Hello Justin, work on it this afternoon. (GMT +1). 

I guess i should do the PR on https://github.com/justin808/add-redux-component-to-react-on-rails/blob/add-redux-component/client/app/bundles/HelloWorld/components/HelloWorld.jsx#L17. directly ?

**Comment by justin808** [comment]
Fixed and released.
