### ISSUE TITLE
i18n?!

### ISSUE THREAD

**Issue by Ruffeng** [shakacode/react_on_rails#656]
Hi! 
I know that you're discussing a lot about this, but just checking so many different comments and ways to do it, i got totally confused, and lost.
Can someone explain me how can I integrate i18n to react on rails??
I tried installing and setting up I18n_js, but i'm stuck on english language( even if in my default locale is another language) 

What I'm doing currently is just sending through props all texts that i need( i know, quite seedy but is the only way to make it work so far)

Thanks a lot for the plugin, is being extremely powerful!

**Comment by justin808** [comment]
@JasonYCHuang is working on am **AMAZING** set of changes here: https://github.com/shakacode/react-webpack-rails-tutorial/pull/340

It will partly include some enhancements to the core gem.

Possibly @Ruffeng can help @JasonYCHuang?

**Comment by justin808** [comment]
Merged into 6.4.
