### ISSUE TITLE
Obsolete instructions in CONTRIBUTING.md

### ISSUE THREAD

**Issue by squadette** [shakacode/react_on_rails#662]
hi,

The 'Run spec/dummy' subsection is incorrect.  When you try `cd spec/dummy && npm run test`, it fails with:

    > react_on_rails@2.0.0-rc.2 test /Users/sq/src/react_on_rails/spec/dummy
    > npm run build:test && npm run lint && rspec
    
    npm ERR! Darwin 15.6.0
    npm ERR! argv "/usr/local/Cellar/node/6.9.1/bin/node" "/Users/sq/.node/bin/npm" "run" "build:test"
    npm ERR! node v6.9.1
    npm ERR! npm  v3.10.9

    npm ERR! missing script: build:test
    npm ERR! 

Can you please clarify what is meant to be here instead?
Thank you,

**Comment by squadette** [comment]
Update: it works in `spec/dummy/client` subdirectory.  Should it be fixed to work from dummy-app level too?

**Comment by squadette** [comment]
Update: even if `cd spec/dummy/client && npm run test` runs, it has 0 test cases:

    No examples found.
    
    
    Finished in 0.00042 seconds (files took 0.09908 seconds to load)
    0 examples, 0 failures

:)

**Comment by justin808** [comment]
Please confirm that I had fixed this. https://github.com/shakacode/react_on_rails/commit/737e6fc00812f5b138e35e94d298eeb84e03a6ed
