### ISSUE TITLE
Obsolete instructions in CONTRIBUTING.md, pt.II ("NPM link")

### ISSUE THREAD

**Issue by squadette** [shakacode/react_on_rails#663]
https://github.com/shakacode/react_on_rails/blob/master/CONTRIBUTING.md#npm-link

recommends to run `npm run node_package`.  However, I don't see that script in none of the package.json files.   Can you explain what's meant to be here instead?

Thanks,

**Comment by justin808** [comment]
Fixed.

**Comment by justin808** [comment]
@squadette See updated https://github.com/shakacode/react_on_rails/blob/master/CONTRIBUTING.md
