### ISSUE TITLE
Obsolete instructions in CONTRIBUTING.md, pt. III, node_package/scripts/*

### ISSUE THREAD

**Issue by squadette** [shakacode/react_on_rails#664]
[Sorry for creating a number of small issues.   Is that way more efficient for you or we should merge everything to a single issue and work there?]

Beginning with https://github.com/shakacode/react_on_rails/blob/master/CONTRIBUTING.md#run-most-tests-and-linting, there are three scripts mentioned, `node_package/scripts/ci`, `node_package/scripts/build` and `node_package/scripts/lint`, all of them were removed in 948697ccef37320. 

It looks like the first one could be just removed.  The second one is more interesting:

> If you change the JS code for react-on-rails, you need to run node_package/scripts/build. Since the react-on-rails package should be sym linked, you don't have to npm i react-on-rails after every change.

Either this paragraph could be completely removed because it's now handled automatically by `npm install --save "react-on-rails@../../react_on_rails"`, or I'm missing something.    Am I?

Thank you,

**Comment by justin808** [comment]
@squadette Please provide a PR with your suggestions! Sounds great! Thanks for your participation! AWESOME!

**Comment by justin808** [comment]
@squadette Feel free to close the other issues and put them all into this one issue or PR.

**Comment by justin808** [comment]
committed an update! thanks for pointing this out!
