### ISSUE TITLE
Undefined global variable

### ISSUE THREAD

**Issue by autobrain-stanley** [shakacode/react_on_rails#665]
Probably overlooking something dead simple. After install I get these errors: 
```
Uncaught TypeError: Cannot read property '_babelPolyfill' of undefined
    at Object.eval (eval at <anonymous> (application.js:72), <anonymous>:9:11)
    at eval (eval at <anonymous> (application.js:72), <anonymous>:29:30)
    at Object.<anonymous> (application.js:72)
    at __webpack_require__ (application.js:23)
    at Object.<anonymous> (application.js:52)
    at __webpack_require__ (application.js:23)
    at application.js:43
    at application.js:46
(anonymous) @ index.js?3717:9
(anonymous) @ VM1692:29
(anonymous) @ application.js:72
__webpack_require__ @ application.js:23
(anonymous) @ application.js:52
__webpack_require__ @ application.js:23
(anonymous) @ application.js:43
(anonymous) @ application.js:46
```
The error is referencing this block of code : 
```
if (global._babelPolyfill) {
  throw new Error("only one instance of babel-polyfill is allowed");
}
global._babelPolyfill = true;
```
Any guidance appreciated.

**Comment by autobrain-stanley** [comment]
It might help to mention that we are integrating this in to a current project.

**Comment by justin808** [comment]
Hi @autobrain-stanley, given your error, you've got some setup issues that are unrelated to React on Rails. Feel free to email for help: justin@shakacode.com. We have a coaching plan for this sort of issue. http://www.shakacode.com/work/.

**Comment by ryangrush** [comment]
In our specific case it was a problem with the sprockets-strict-mode gem - https://github.com/mackuba/sprockets-strict-mode. Removing it fixed the issue.
