### ISSUE TITLE
Consider more efficient way to find the newest mtime

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#677]
https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/test_helper/webpack_assets_status_checker.rb#L37

```ruby
      def find_most_recent_mtime
        client_files.reduce(1.year.ago) do |newest_time, file|
          mt = File.mtime(file)
          mt > newest_time ? mt : newest_time
        end
      end
```

We could probably write this as one shell command and would likely be faster than reading every single file.

CC: @robwise

**Comment by justin808** [comment]
Something like this:

http://stackoverflow.com/a/33010957/1009332

```
find . -type f -printf '%TY-%Tm-%Td %TH:%TM: %Tz %p\n'| sort -n | tail -n1
```

**Comment by robwise** [comment]
Since people use windows, that's not really an option. IFIRC, this implementation is straight from the Rake source code.

**Comment by AnNiran** [comment]
I would do it as:

http://stackoverflow.com/a/4823567
Dir["*"].sort_by { |file_name| File.stat(file_name).mtime }

or

http://stackoverflow.com/a/4823542
Dir["*"].sort { |a,b| File.mtime(a) <=> File.mtime(b) }.last

**Comment by justin808** [comment]
I think with large projects, this *may* make a difference. @robwise we've got a huge number of JS files on our project...Maybe we should put a tiny timing block around that bit of code? if the time is 0.1 seconds, then we can't save much. If it's 1 second...

**Comment by justin808** [comment]
@AnNiran I can help you experiment with this if you like. Let me know if you're intersted.

**Comment by AnNiran** [comment]
@justin808 sure, what exactly is your idea?

I have a few thoughts myself about it - like in the non recursive version - this can be applied:

Dir.entries('.').sort_by {|path| File.mtime(path)}
or 
Dir.entries('.').sort_by {|path| File.mtime(path)}.last  # shows only the last one;

or just:
Dir.entries('.').sort_by{ |f| File.ctime(f) }.last

In any case I would use file enumerability .
