### ISSUE TITLE
Consider retaining existing prerequisites for assets:precompile

### ISSUE THREAD

**Issue by toastercup** [shakacode/react_on_rails#680]
Greetings! I'm seeking clarification on logic ([lib/tasks/assets.rake#L46](https://github.com/shakacode/react_on_rails/blob/master/lib/tasks/assets.rake#L46)) that's clearing the prerequisites of the `assets:precompile` task. Here's what the offending bits look like:
```ruby
Rake::Task["assets:precompile"]
  .clear_prerequisites
  .enhance([:environment, "react_on_rails:assets:compile_environment"])
  .enhance do
    Rake::Task["react_on_rails:assets:symlink_non_digested_assets"].invoke
    Rake::Task["react_on_rails:assets:delete_broken_symlinks"].invoke
  end
```
I believe this works well for most setups, but in our case, we're using [bower-rails](https://github.com/rharriso/bower-rails), which adds `bower:before_precompile` as a prerequisite for this task. `react_on_rails` clears `bower-rails`'s prerequisites as a result of [this line](https://github.com/shakacode/react_on_rails/blob/master/lib/tasks/assets.rake#L47).

First, I'd like to understand why `react_on_rails` chose to do this - perhaps it's necessary. If it's unnecessary, I'd like to submit a Pull Request to remove it so existing prerequisites can be executed unhindered. I dug around in the repo's history to see if I could glean a reason for its existence - it looks like the [original incarnation](https://github.com/shakacode/react_on_rails/blob/39adba24caba58e166fd40e4387dd81d79434a53/lib/tasks/assets.rake#L23) did not `clear_prerequisites`. The only documentation about the introduction of this change is in [this review](https://reviewable.io/reviews/shakacode/react_on_rails/398#-KHQmkreNUIgqzOg6GT9), but I don't fully understand the reasoning nor can I find the documentation the comment mentions.

I'm sure I could force `bower-rails` to load last, so that it adds its prerequisites last, but I feel this is a cleaner solution, and would save others the extra step. Thoughts?

**Comment by justin808** [comment]
@toastercup in the past that line is necessary b/c we're overriding the default assets:precompile from Rails. 

I'd suggest just doing the same for your task.

**Comment by toastercup** [comment]
@justin808 thanks for your time and for the quick response - after reviewing your comment and how this code works, this now makes sense to me. Have a splendid day!
