### ISSUE TITLE
JSX template generator would be a nice feature

### ISSUE THREAD

**Issue by dmitrypol** [shakacode/react_on_rails#681]
I am still learning react_on_rails but one nice feature that react-rails has is ability to run generator and create JSX templates like this:  `rails g react:component User name:string ...`

reast_on_rails hello_world generator is nice but copying and renaming all those files for what my application actually need is time consuming and error prone.  Just a suggestion for a feature.

**Comment by justin808** [comment]
See https://github.com/shakacode/react_on_rails/issues/245.

Contributions are encouraged!

**Comment by Luke-Popwell** [comment]
not sure if this is the right way to add to this, but i put this gem together yesterday to be able to add component and container generators to the react_on_rails gem. It's the first gem I've tried to build, but any feedback would be appreciated. https://rubygems.org/gems/redux-gem and heres the github link https://github.com/Luke-Popwell/redux-rails-gem

**Comment by justin808** [comment]
@Luke-Popwell This would make a **great PR** to add to the generator. I can help you add this if you like. We've been planning on doing this for a while.

**Comment by Luke-Popwell** [comment]
Hi and thanks for getting back to me. I’d be more than happy to do that. being new to this would i get any credit for it? I’m just trying to get my first web development job lol

**Comment by Luke-Popwell** [comment]
also yes if you’d like to help me add it. I could probably use the help

**Comment by justin808** [comment]
> Hi and thanks for getting back to me. I’d be more than happy to do that. being new to this would i get any credit for it? I’m just trying to get my first web development job lol

You'll be listed as a contributor! and you'll be in the https://github.com/shakacode/react_on_rails/blob/master/CHANGELOG.md!

**Comment by Luke-Popwell** [comment]
hello again,
sounds good to me. Ill rewrite it so i can do a pull request in the morning.
thanks again,
Luke

**Comment by justin808** [comment]
@Luke-Popwell Any luck with this?
