### ISSUE TITLE
Update to react_on_rails v6.4.0 breaks foreman

### ISSUE THREAD

**Issue by khpatel4991** [shakacode/react_on_rails#682]
I have pretty dummy project with react_on_rails '6.3.5' and today I saw an update and so decided to change gemfile and update to 6.4.0. Though, when I did, and when I start foreman it throws the following error with the stack as follows.

```
$HOME/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:2158:in `method_missing': 

undefined method `this' for #<Gem::Specification:0xcfacc4 foreman-0.82.0> (NoMethodError)
 from $HOME/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/specification.rb:1057:in
`find_active_stub_by_path'
 from $HOME/.rvm/rubies/ruby-2.3.1/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:64:in `require'
 from $HOME/.rvm/gems/ruby-2.3.1/gems/foreman-0.82.0/bin/foreman:5:in `<top (required)>'
 from $HOME/.rvm/gems/ruby-2.3.1/bin/foreman:23:in `load'
 from $HOME/.rvm/gems/ruby-2.3.1/bin/foreman:23:in `<main>'
 from $HOME/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
 from $HOME/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'

```

**Comment by justin808** [comment]
Run `gem install foreman`

or if using RVM:

`rvm @global do gem install foreman`

@khpatel4991 Please review https://github.com/shakacode/react_on_rails/pull/684 and let me know if that fixes your issue.

**Comment by khpatel4991** [comment]
Yes, It Fixes it. Sorry for a stupid bug report!! :(

**Comment by jasmo2** [comment]
Hi @justin808,

I still have the same issue. Even though, I have done 
`rvm @global do gem install foreman`

But it still the same :(

**Comment by jasmo2** [comment]
what solve my issue was:
[`gem update --system`](https://github.com/ddollar/foreman/issues/662#issuecomment-272129280)
