### ISSUE TITLE
Add option or remove log props for errors with server rendering

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#686]
Since props can be huge, we don't want to log the props when server rendering.

Either:

1. Never log props with server rendering errors
2. Make it another option, possibly piggy-backing on some other option.

CC: @robwise

**Comment by robwise** [comment]
If we make it another option, I don't think we should piggy-back it, but make it something really specific and obvious like: `log_props_with_server_rendering_errors`

**Comment by benigeri** [comment]
We have a a ton of data sent via props during server side rendering. Having them logged as part of the error message quickly becomes noisy and not useful. 

I do believe it can be beneficial as people are starting up, especially when they have fairly small props. 

`log_props_with_server_rendering_errors` sounds ideal.

**Comment by justin808** [comment]
@benigeri 

We currently have: 

  # Default is true. Logs server rendering messages to Rails.logger.info
  config.logging_on_server = true

I think we could:

Change the default of true to not log props

Alternately, somebody, if somebody wanted it, we could add something like "verbose" instead of true.

Are the props ever interesting on the server?

**Comment by EEtancelin** [comment]
Hey Justin, what about this issue ? Should we replace
` config.logging_on_server = true` by
` config.logging_on_server = false`
?

**Comment by justin808** [comment]
@EEtancelin I recommend keeping this as true. If you do change to false, you'll only get logs from React on Rails in the browser.

**Comment by Conturbo** [comment]
I'll take a look at this

**Comment by Conturbo** [comment]
> If we make it another option, I don't think we should piggy-back it, but make it something really specific and obvious like: log_props_with_server_rendering_errors

i'll try to implement this

**Comment by justin808** [comment]
Done in #1059.
