### ISSUE TITLE
one bundle per view, named entry points?

### ISSUE THREAD

**Issue by ttrmw** [shakacode/react_on_rails#688]
Hey,

I'm trying to serve one bundle per view file. My layout file `yields` to `:javascript_includes`, and in each view I call 

```ruby
content_for :javascript_includes do
   <%= javascript_include_tag 'bundleName-bundle' %>
end
```

and of course:

```ruby
react_component("BundleNameComponent", props: @props)
```

For my webpack config, I have changed entry to an object, like so:

```js
  entry: {                                                                        
    bundleName: './app/bundles/bundleName/component.jsx',                          
  }, /...
```
(which means I've removed the defaults - not entirely sure if this may be the problem.. How should I reintroduce them?) 

so that I can then set my output entry like:

```js
  output: {                                                                       
    filename: '[name]-bundle.js',                                                 
    path: '../app/assets/webpack',                                                
  },   
``` 

The components being set as entry points contain JSX, and at the end register with ReactOnRails:

```js
ReactOnRails.register({ BundleComponentName });
```

and serve separate bundles. This works great in Chrome, but seems to be flaky in Firefox. If I make irrelevant trivial changes to the view, I get unhelpful React error messages that may or may not relate to Context. I can expand on this if needed, but have a gut feeling it's to do with my entry points. 

Were the default entry points needed for Firefox to behave itself? How can I reintroduce them and serve multiple bundles like this? Am I way off track? The error is really frustrating as it seems to go away under certain circumstances - reinstalling NPM modules, restarting the development machine etc. Any guidance would be much appreciated.

**Comment by ttrmw** [comment]
Ah, maybe my gut feeling is wrong on this. I have included a named bundle for the shims, like: 

```js
 shims: [                                                                        
      'es5-shim/es5-shim',                                                          
      'es5-shim/es5-sham',                                                          
      'babel-polyfill'                                                              
    ]
```
and have included this in my layout file. No change in behaviour in Firefox.

**Comment by justin808** [comment]
Do you still have an issue, @ttrmw ?

**Comment by ttrmw** [comment]
Yes I do, but it's hard for me to reproduce and may be specifically to do with the NPM module I'm including, and not react_on_rails. I'm gonna close this for now.
