### ISSUE TITLE
Handle errors and redirects from React Router on server

### ISSUE THREAD

**Issue by alexfedoseev** [shakacode/react_on_rails#69]
@dylangrafmyre @justin808 @samnang 

React Router works with server rendering (after #68 will be merged). But we need to handle 2 more cases:

1. Errors from router. We should send 500 in case of the error.
1. Redirects from router. We should send 302 in case of the redirect.

Details: https://github.com/shakacode/react-webpack-rails-tutorial/pull/128
Code where error / redirect info goes to the gem on server: https://github.com/shakacode/react-webpack-rails-tutorial/blob/alex/react-router/client/app/startup/ServerApp.jsx#L11

**Comment by justin808** [comment]
This is a general issue:

If we have an error when server rendering, should we:

1. Log the messages to the client and/or server console. (current behavior of gem, and probably the react-rails gem).
2. Throw an error on the server side so rails sees the error.
3. Make the choice of #1 or #2 configurable? with the default being? 
   `config.throw_on_server_render_error = true`

Can anybody confirm the react-rails gem behavior?

CC: @korbin, @lfittl, @andreasklinger, @jbhatab

**Comment by justin808** [comment]
I opened this issue to find out what react-rails is doing: https://github.com/reactjs/react-rails/issues/386

**Comment by justin808** [comment]
Also, could we release the gem as 1.0 with the current behavior (logging, either on server or both server/client) and then change that to throw on the server side?

**Comment by justin808** [comment]
This is what react-rails is doing:

https://github.com/reactjs/react-rails/blob/master/lib/react/server_rendering/exec_js_renderer.rb#L13

```
      def render(component_name, props, prerender_options)
        render_function = prerender_options.fetch(:render_function, "renderToString")
        js_code = <<-JS
          (function () {
            #{before_render(component_name, props, prerender_options)}
            var result = ReactDOMServer.#{render_function}(React.createElement(#{component_name}, #{props}));
            #{after_render(component_name, props, prerender_options)}
            return result;
          })()
        JS
        @context.eval(js_code).html_safe
      rescue ExecJS::ProgramError => err
        raise React::ServerRendering::PrerenderError.new(component_name, props, err)
      end
```

We're wrapping the code in a try block and logging errors nicely.

**Comment by lfittl** [comment]
@justin808 Just a heads up - we've moved to a different setup that uses a node server for server-side rendering, communicating through a unix domain socket as needed (@korbin has all the details if you're curious).

So it probably doesn't make sense to keep CCing us on this repository, although I appreciate you working on this! :)

**Comment by justin808** [comment]
@lfittl @korbin mentioned that to me. Ideally, we'll be able to make execjs swappable with the node technique. When you get an error in server rendering using your technique, do you convert the JS error to throw an exception in Ruby?

**Comment by lfittl** [comment]
@justin808 I think in the context of this PR, we're not doing this right now (since almost none/none of our code is using the react router yet).

We do log errors to an external provider, but we don't do any special logic based on the type of error.

**Comment by jbhatab** [comment]
@justin808 So the default behavior is throwing a client side error and you'd like to add a ruby side error?

**Comment by justin808** [comment]
@jbhatab We are only logging right now. Trivial for us to have an option to throw if there's an error in server rendering.

**Comment by jbhatab** [comment]
@justin808 logging on the ruby side? I think logging the issue on ruby and javascript side is ideal without breaking things. Now does the component still render client side if it breaks server side?

**Comment by justin808** [comment]
We log. Some people might want to do a redirect. Also, I think we display the error message in html anyway to make it super obvious. There's a slight security risk in that error could contain sensitive data and we shouldn't be sending it to the client.

**Comment by jbhatab** [comment]
I like the idea of an html error.

**Comment by robwise** [comment]
Implemented in https://github.com/shakacode/react_on_rails/pull/68
