### ISSUE TITLE
How can I use external components.

### ISSUE THREAD

**Issue by edugonch** [shakacode/react_on_rails#694]
Hello, I'm new to react and hopefully I found this gem to use in my project, the problem I'm having is that I can't use with react_component helper external libraries that I have installed with npm (example https://github.com/newbreedofgeek/react-stepzilla)

How can I do this? Pleas help me, I have try for hours with out results.

Thank you very much.

**Comment by justin808** [comment]
@edugonch There's no reason you can't. Get in touch with me if you need help specific to your project. justin@shakacode.com
