### ISSUE TITLE
Clean up app/startup/clientApp.jsx and app/startup/serverApp.jsx

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#7]
There's too much duplication between:

dummy/client/app/startup/clientApp.jsx and dummy/client/app/startup/serverApp.jsx

We also need some good documentation on how to set this up.

**Comment by justin808** [comment]
Seems that the only diff is the way the file is exported.

<img width="1540" alt="cursor_and_clipboard_vs_editor" src="https://cloud.githubusercontent.com/assets/1118459/9462586/858971f0-4ab2-11e5-84ac-2d281f7f40e8.png">

**Comment by alexfedoseev** [comment]
Yes, but it's super basic example. In real world (especially if you're building a SPA) client side gonna have more client-specific stuff (progress bars, google analytics etc.) and it's better to keep them separated from the very beginning.

**Comment by justin808** [comment]
Closing this issue. We'll want to have the docs address this.
