### ISSUE TITLE
Rspec not bundling assets w/ setup from docs

### ISSUE THREAD

**Issue by djfdev** [shakacode/react_on_rails#705]
Hi there, loving this project BTW. I'm integrating with an existing app, and (mostly) everything is working as expected, but I'm having trouble precompiling in test.

My config/react_on_rails.rb file came from the scaffold, along with the test helper in spec/spec_helper.rb. However, running `rspec` now fails to generate the webpack bundle, and everything flops.

```
#<Sprockets::FileNotFound: couldn't find file 'webpack-bundle' with type 'application/javascript'
```

I managed to solve this by explicitly bundling before running tests:

```
rm -rf app/assets/webpack
cd client && npm run build:test
cd .. && rspec
```

But I guess I'm just a little confused as I thought this was the default behavior? What else might prevent the test helper from precompiling?

**Comment by justin808** [comment]
@djfdev Please see [rspec configuration](https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/rspec-configuration.md). Does that answer your questions?

**Comment by djfdev** [comment]
Hi @justin808 thanks, I have seen that documentation, but I'm still not getting built assets in test even with the test helper:

```rb
Rspec.configure do |config|
  ReactOnRails::TestHelper.configure_rspec_to_compile_assets
  ...
```

I imagine there is another issue with my config that might be causing this to fail. Regardless, am I missing out on something by using my above method to explicitly bundle assets before running my test command (i.e. without the test helper)?

**Comment by zinkkrysty** [comment]
I'm running into the same issue. Ran the generator with the default config, app works in dev mode with foreman, but running tests with RSpec ends up with this:

```
     Failure/Error: //= require webpack-bundle

     ActionView::Template::Error:
       couldn't find file 'webpack-bundle' with type 'application/javascript'
``` 

I can see that while the test is running, there is no generated asset in `app/assets/webpack`. 

I am having the same issue on CI, when I push my branch.

**Comment by mhuggins** [comment]
I'm also running into this problem.  Any updates?

**Comment by mhuggins** [comment]
Okay, I figured it out for my scenario.  My `application.scss` file had the following two lines:

```scss
@import "vendor-bundle";
@import "app-bundle";
```

However, I was not actually generating a `vendor-bundle.scss` file with webpack, just an `app-bundle.scss` file.  I removed the first line above, and that fixed it.
