### ISSUE TITLE
Tests example

### ISSUE THREAD

**Issue by alexvbush** [shakacode/react_on_rails#707]
Hi, is there an example of `react_on_rails` implementation with Rspec unit-tests, and Javascript unit-tests for React/Redux?

**Comment by justin808** [comment]
* https://github.com/shakacode/react-webpack-rails-tutorial/tree/master/spec
* https://github.com/shakacode/react-webpack-rails-tutorial/tree/master/spec/features
* Configuration to be sure Webpack bundles are built: https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/spec/rails_helper.rb#L42
* https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/rspec-configuration.md
