### ISSUE TITLE
ReactOnRails is not defined when including application.js at bottom of body

### ISSUE THREAD

**Issue by hisapy** [shakacode/react_on_rails#71]
When including application.js at bottom of body like this:

```erb
<body>
 <!-- some other stuff here (layouts/application.html.erb) -->
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true, 'data-turbolinks-eval' => false %>
</body>
```
and using react_component helper to render a component in a view (i.e.: /admin/purchases/new)
```erb
<%= react_component("PurchaseForm", {}, prerender: false, trace: true, generator_function: false) %>
```
I get a **Uncaught ReferenceError: ReactOnRails is not defined**.  Obviously this is because the Javascript written by the helper is executed when the DOM is loading, and before the **application.js** is included.

In order to avoid the error what I've done is the following:

```erb
<body>
  <!-- some other stuff here (layouts/application.html.erb) -->
  <div id="reactRoot"></div>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true, 'data-turbolinks-eval' => false %>
  <%= content_for :react_components %>
</body>
```

and in the view:

```erb
<% content_for(:react_components) do
    concat react_component("ClientApp", {}, id: 'reactRoot', prerender: false, trace: true, generator_function: false)
  end %>
```

I just wanted to share my experience using this gem... Is there any better approach for this? If not maybe you'd like to include this strategy in the README.

**Comment by justin808** [comment]
@hisapy application.js should be included in the head of the document. Any reason you're placing it in the body?

**Comment by justin808** [comment]
Feel free to re-open this ticket if you're sure that there's a case for putting application.js in the body.

**Comment by hisapy** [comment]
Actually, it seems no there is need anymore to move it out from the head.

**Comment by rupurt** [comment]
@justin808 Yahoo recommends [loading scripts](https://developer.yahoo.com/performance/rules.html#js_bottom) at the bottom of the page to avoid blocking parallel downloads.

**Comment by justin808** [comment]
@rupurt we did a little research and concluded that the Yahoo advice is no longer worthwhile due to typical caching of the bundled JS file as well as the use of turbolinks. That being said, if you can create a simple demo of a performance gain, we'd be very happy to change the way we're organizing the JS code.

**Comment by justin808** [comment]
@rupurt Please look at this: http://forum.shakacode.com/t/should-rails-apps-use-defer-when-loading-application-js/404/3?u=justin
