### ISSUE TITLE
ExecJS and Node.js

### ISSUE THREAD

**Issue by dijonkitchen** [shakacode/react_on_rails#711]
Is the server rendering on Node still needed (as mentioned here: https://github.com/shakacode/react_on_rails/blob/master/docs%2Fadditional-reading%2Fnode-server-rendering.md)? 

Based on ExecJS's Readme, it picks the best one and will use it: https://github.com/rails/execjs#execjs

**Comment by justin808** [comment]
Different strategy completely. Yes, still relevant. Suppose you want to completely have an independent Node server doing your rendering...This is how.
