### ISSUE TITLE
Add generator option to specify first component name rather than hello_world

### ISSUE THREAD

**Issue by oklas** [shakacode/react_on_rails#716]
The command:

    rails generate react_on_rails:install

create many things included `HelloWorld` component rails binding and view and so on.

In most cases (except demo) need not `HelloWorld` but need `App` or `Bundle` or `MainPage` or some practical useful name. It is need to rename about ten files and edit contents in some places. It is not difficult, but with this it will be not needed to do at all.

It may be command some like this:

    rails generate react_on_rails:install --name App

It will be good to change default value instead of `HelloWorld` may be `MainPage` or `App` may be somebody has another name to suggest or opinion which name to prefer.

**Comment by justin808** [comment]
@oklas Any chance that you can submit a PR for this? We've been planning on doing this for ages. It just hasn't been a blocker or priority. The community would ❤️ this!

**Comment by oklas** [comment]
I can not promise anything but try to identify a gap in the boundless number of tasks.

**Comment by justin808** [comment]
@oklas Thank you! I look forward to seeing what you get!

**Comment by justin808** [comment]
@oklas Any word on this one?

**Comment by oklas** [comment]
Hi Justin! I have no time currently. But I want to improve it definitely but I can not promise.

**Comment by oklas** [comment]
Rename HelloWorld to MainPage (like this [PR857](https://github.com/shakacode/react_on_rails/pull/857)) will be good step. You can imagine projects where there is MainPage. But it is unlikely that someone will want to have the HelloWorld in his power project. Therefore, each time everyone should rename several files and fix the code in them.

**Comment by ledestin** [comment]
Just to let you know I'm working on this feature.

**Comment by justin808** [comment]
@ledestin Please be sure to see the details in https://github.com/shakacode/react_on_rails/blob/master/CONTRIBUTING.md and feel free to ping me when you're ready for review.

Most importantly, we'll want to add an option to the super awesome generator testing developed by @robwise.

**Comment by justin808** [comment]
@ledestin is no longer working on this one. I'm open to somebody else picking this one up and creating a PR.

**Comment by rodrigobdz** [comment]
@justin808 I'll grab this one.

**Comment by justin808** [comment]
@rodrigobdz That would be awesome!

**Comment by justin808** [comment]
@rodrigobdz Please email me justin@shakacode.com to get in our Slack group. Maybe we could do #1089 first.

**Comment by splashinn** [comment]
@justin808 is this still up for grabs?

**Comment by rodrigobdz** [comment]
@splashinn It should be. I'm not working on this anymore.

**Comment by behraaang** [comment]
@justin808 Hello dear Justin, since this is more of a backend issue than front, I would like to take a try at this. 
P.S. I just filled out the google form for your hiring process, hope you like my responses.
