### ISSUE TITLE
npm shrinkwrap causes issues on setup

### ISSUE THREAD

**Issue by jbhatab** [shakacode/react_on_rails#72]
Every time I setup react_on_rails on my machine with the generators, the npm-shrinkwrap file breaks my setup. 

I cd into client, run npm install successfully. Then I cd up to the root and run foreman start -f Procfile.dev. Then it gives me an error involving the 'body-parser' module. 

I solve this by deleting the npm-shrinkwrap file and re running npm install in the client directory.

**Comment by justin808** [comment]
Most likely the issue is using the same version of npm and node that generated the shrinkwrap file.

@robwise We should make sure the generator installs the package.json, but runs the command to shrinkwrap.

**Comment by jbhatab** [comment]
Sounds good.
