### ISSUE TITLE
Gitbook Relative Links Broken

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#726]
https://github.com/GitbookIO/gitbook/issues/1684

I have been trying to do this with https://github.com/shakacode/react_on_rails, and the created links point to a markdown file and the gitbook site renders the file as raw text.

Please see the following:

* https://github.com/shakacode/react_on_rails  - github source
* Search for "Code Splitting" which points to https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/code-splitting.md

* Now try on the gitbook https://shakacode.gitbooks.io/react-on-rails/content/
* Search for "Code Splitting" which points to: https://shakacode.gitbooks.io/react-on-rails/content/docs/additional-reading/code-splitting.md

The gitbook case is suboptimal compared to just using github.com.

CC: @Judahmeek

**Comment by Judahmeek** [comment]
Looks to me like the gitbook is out of date. Both the `Code Splitting` and the `AngularJS` links are missing from the side bar.

![screen shot 2017-02-23 at 5 43 32 pm](https://cloud.githubusercontent.com/assets/8206741/23284171/b9143594-f9ef-11e6-85a8-9b0b36c1a79c.png)

**Comment by justin808** [comment]
Seems fixed @Judahmeek!
