### ISSUE TITLE
Is there a way to improve the first load time with the GEM?

### ISSUE THREAD

**Issue by xiaopow** [shakacode/react_on_rails#729]
Hey guys, is there a way to improve the page load speed when using react on rails?

**Comment by justin808** [comment]
@xiaopow this is a very involved question, possibly involving server rendering, code splitting, the sizes of your bundles and CSS files, caching of assets, etc. This question is probably better suited for https://forum.shakacode.com/.

**Comment by justin808** [comment]
@xiaopow BTW, besides the fact that React On Rails provides server rendering, none of this question is specific to React on Rails, but rather to general web apps written with Webpack and React.
