### ISSUE TITLE
Clarifying contributing.md

### ISSUE THREAD

**Issue by wanyamaman** [shakacode/react_on_rails#736]
Some parts of the [contributing.md](https://github.com/shakacode/react_on_rails/blob/master/CONTRIBUTING.md) file can be ambiguous and might benefit from some clarification.

---
### Directories
The following commands need clarification on where they should be run (_listed in chronological order as found in the file_):
> bundle && yarn && rake examples:prepare_all && rake node_package && rake

assumption: _gem root_

>yarn
yarn run build

assumption: _gem root_
>Use a relative path in your package.json, like this:
cd client
yarn add "react-on-rails\@../../react_on_rails"

assumption: _external testing app/client_
>yarn run install-react-on-rails

assumption: gem/spec/dummy
>yarn
npm build

assumption: _gem root_. Also `npm` should be `yarn`

### Order
Most of the ambiguity stems from having a section on using the gem with your own test app **before** the section detailing the default gem and dummy app setting that comes with the fork. It's then not immediately clear whether commands are being run within the gem hierarchy or in your external testing app. I suggest swapping this order of topics.

### Naming
>Because the **example** and dummy apps rely on the react-on-rails node package, they should link directly ....

Is the example app the external testing app that so far has been referred to as the test app or another app found within the gem hierarchy?
>To achieve this, switch to the **test** app's root directory and run this command below which runs something like this script

assumption: meant to say _dummy_ app instead of _test_.

Some commands still reference `npm` instead of `yarn`

---
I'm happy to submit a PR if the assumptions are correct.

**Comment by justin808** [comment]
@wanyamaman Those suggestions sound right. An example app might be testing this with https://github.com/shakacode/react-webpack-rails-tutorial or it might be running the generator on a new rails app, or some other "example" app.

**Comment by justin808** [comment]
@wanyamaman Please submit a PR.

**Comment by wanyamaman** [comment]
Submitted #737

**Comment by justin808** [comment]
Thanks @wanyamaman! We'll finish this up in #737!
