### ISSUE TITLE
Not reloading JSX for server rendering.

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#74]
We're working on a fix for this.

What happens is that the generated/server.js gets loaded once at startup, regardless of development or production mode.

For development, we'll reload server.js if the timestamp has changed.

Production mode will not check.

@jbhatab and @robwise are working on this.

**Comment by justin808** [comment]
The work around is to restart your rails server until we push a fix. Note, this only applies if you are using server rendering, which is the option `prerender: true`.

**Comment by justin808** [comment]
@rstudner, (CC: @jbhatab) please create branch with these 2 commits:

* https://github.com/shakacode/react_on_rails/commit/66b7408af616e40e6f871e2ec5360abac882b9b0
* https://github.com/shakacode/react_on_rails/commit/7a7dd689c589c53f3eb8ffd1fe03c416c7748ed9

This is a fix, but the logic needs to move: https://github.com/shakacode/react_on_rails/commit/66b7408af616e40e6f871e2ec5360abac882b9b0#diff-741e57aaaefab9559b7892657ec8c75eR175

@jbhatab can help.

We want to get this in ASAP and push a fix to the gem! Maybe even before the generator is done.

**Comment by jbhatab** [comment]
@rstudner here's the link to the commit where we auto reset the pool for server bundles. https://github.com/shakacode/react_on_rails/commit/66b7408af616e40e6f871e2ec5360abac882b9b0

**Comment by robwise** [comment]
Add this commit to the list as well: https://github.com/shakacode/react_on_rails/commit/534c9af266d72e5eb9a99ee03d9832eb2862238c

**Comment by rstudner** [comment]
Okay, quick question (sorry, I couldn't do this last night -- solo parent duty with 1 kid with pneumonia hah)

So, 7a7dd68 basically "is" the merge commit for the generators.
Then we have 66b7408 which appears to add the server.js reloading behavior for development.

So is this "branch" a branch off master, that has all the generator stuff merged into it, plus 66b7408, plus 534c9af.

Just want to make sure I'm reading the above right before I go smoosh it all together :)

**Comment by robwise** [comment]
@rstudner I don't know why 7a7dd68 is named what it is or why Justin said that it was involved with this issue as I don't think it actually is (unless I'm missing something @justin808 ?).

Basically what we're trying to do is separate the task of adding generators, which goes in the add-generators branch, with the task of fixing a bug that causes the server to not reload the server-bundle when it gets changed in development.

So the idea is to create a new branch based on the current master, something like `server-reload-bundle-fix` or whatever, then cherry pick the changes identified below. We are eventually going to squash everything in the add-generators branch, and the bug fix to the server-reloading is really not related so we don't want them to be stuck in the same branch together as they currently are.

+ https://github.com/shakacode/react_on_rails/commit/66b7408af616e40e6f871e2ec5360abac882b9b0 but only the changes in these files:
    + `app/helpers/react_on_rails_helper.rb`
    + `lib/react_on_rails/configuration.rb`
    + also see Justin's comments on that commit
+ https://github.com/shakacode/react_on_rails/commit/534c9af266d72e5eb9a99ee03d9832eb2862238c everything but:
    + `lib/generators/react_on_rails/generator_helper.rb`


@justin808 Be advised, this fix relies on https://github.com/shakacode/react_on_rails/commit/66b7408af616e40e6f871e2ec5360abac882b9b0#diff-9fd0fe78c2be3d73b04b3875942fd740R13 being in the users' initializer.

**Comment by rstudner** [comment]
@robwise thanks for the heads up.  I mostly have that done, I just have to clean out a couple things (generator_helper) etc.  Will push it up in just a bit.

**Comment by robwise** [comment]
@rstudner Nice!!!

**Comment by justin808** [comment]
Fixed.
