### ISSUE TITLE
RFC: Rapscallion to replace RenderToString for 50% decrease in render times

### ISSUE THREAD

**Issue by ColeTownsend** [shakacode/react_on_rails#744]
https://github.com/FormidableLabs/rapscallion

Rapscallion claims to be 50% faster than RenderToString. That alone might make it worthwhile to use?

```
Starting benchmark for 10 concurrent render operations...
renderToString took 2.138940631 seconds
rapscallion, no caching took 1.488518342 seconds; ~1.43x faster
rapscallion, caching DIVs took 0.295781047 seconds; ~7.23x faster
rapscallion, caching DIVs (second time) took 0.111968410 seconds; ~19.1x faster
rapscallion, caching Components took 0.186903500 seconds; ~11.44x faster
rapscallion, caching Components (second time) took 0.075220726 seconds; ~28.43x faster
```

**Comment by justin808** [comment]
@ColeTownsend does it work? Did you try it? Want to submit a PR demonstrating this? How do you configure which version of React it supports?

**Comment by ColeTownsend** [comment]
@justin808 I can give it a go on one of my local project – I'm more of a designer/front-end dev and came across this. Seems like right now it requires `react` and `react-dom` latest.

I can see if simply hot swapping instances of `RenderToString` with Rapscallion's `render` works.

**Comment by justin808** [comment]
@ColeTownsend Should we keep this issue open?

**Comment by ColeTownsend** [comment]
We can close it because I don't have the chops to handle
