### ISSUE TITLE
Remove node and yarn checks in install_generator (Docker integration)

### ISSUE THREAD

**Issue by jehupacheco** [shakacode/react_on_rails#756]
I'm making Docker containers for this app https://github.com/shakacode/react-webpack-rails-tutorial/ to run using docker-compose. The main idea is to have separated services, one for the rails application itself (that knows only about ruby and rails) and other one for the webpack-dev-server (that knows about node and yarn).

The problem is that install_generator checks if node and yarn are installed before generating the files so this forces me to add node and yarn as dependencies for the service that should have only needed ruby and rails as dependencies.

What I ask is if it would possible to add an option to the generator to avoid performing any node or yarn checks.

**Comment by justin808** [comment]
See https://github.com/shakacode/react_on_rails/blob/master/README.md#getting-started

Pass the `--ignore-warnings` flag.

If this is an issue, can you please submit a PR with a slight modification to the home page. Additionally, I'd love a doc PR to add a file here, called `docker.md`: https://github.com/shakacode/react_on_rails/tree/master/docs/additional-reading

```
Getting Started

For more detailed instructions, see the React on Rails Basic Tutorial.

Add the following to your Gemfile and bundle install.

gem "react_on_rails", "~> 6"
Commit this to git (you cannot run the generator unless you do this or pass the option --ignore-warnings).
```

CC: @dylangrafmyre as he's my Docker expert.
