### ISSUE TITLE
Prerender: true, server bundle multiple files

### ISSUE THREAD

**Issue by spheric** [shakacode/react_on_rails#758]
Hi,

Is there a way to set multiple bundles against the  config.server_bundle_js_file for prerender: true?
 
Cheers
Matt

**Comment by justin808** [comment]
@spheric We've discussed this a number of times and we don't see any need to have multiple bundles for server rendering. What would be the advantage?

**Comment by ened** [comment]
For my App, the bundle is split into frontend/backend. I can live with only the frontend being server-generated (SEO etc) while the backend is dynamic. Others might have a different setup, though?

**Comment by justin808** [comment]
@ened I'm not sure what you mean by the backend is dynamic.

**Comment by ened** [comment]
@Judahmeek Yes, bad choice of words. I use server generated components on search engine visible pages (I believe that's their purpose). As the entire bundle grew too big, I split it into frontend & backend. The backend is not using any server-rendered components.

**Comment by justin808** [comment]
> As the entire bundle grew too big, I split it into frontend & backend. 

There's no such thing as too big for server rendering, as far as we know.

Or is there? What makes you think the bundle is too big for server rendering?
