### ISSUE TITLE
Roadmap: Future plans with webpacker.

### ISSUE THREAD

**Issue by Matt-Butler** [shakacode/react_on_rails#759]
Now that rails is starting to support webpack, what are the plans for this project going forward? Will you adopt webpacker once it is matured?

**Comment by justin808** [comment]
Matt, version 7.0.0 is going to use webpacker! and not use the asset-pipeline at all!

Want to help?

**Comment by Matt-Butler** [comment]
Thank you for the quick reply @justin808. Do you have a list off issues needed to be done for 7.0.0?

**Comment by justin808** [comment]
@Matt-Butler Right now, Webpacker is the only one. We're about to merge #760 but that will probably be 6.8.0. We're using semantic versioning, so a major update is only when the upgrade requires some change.

**Comment by justin808** [comment]
See #786. This should be happening in the next few weeks.
