### ISSUE TITLE
Investigate Lack of "Server Bundle Not Found" Error and also Output to Console

### ISSUE THREAD

**Issue by robwise** [shakacode/react_on_rails#76]
When the user is not using server rendering and has forgotten to set `config.server_bundle_js_file` equal to empty quotes (`""`) inside of the [`app/config/initializers/react_on_rails.rb`](https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/config/initializers/react_on_rails.rb#L7) file, it is supposed to be logging an error. However, I'm not seeing this error. 

Relevant line of code: https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/server_rendering_pool.rb#L84

We need to investigate what is going on here.

In addition, it would be nice to have the error also output to the console.

**Comment by justin808** [comment]
@robwise I submitted a fix. Please review.

**Comment by robwise** [comment]
@justin808 change looks fine to me. But why is the Rails.logger line *not* working? 

```ruby
Rails.logger.warn msg
```
https://github.com/shakacode/react_on_rails/pull/77/files#diff-10c7b74a600ef3ecde9dca86ed42c16eR87

**Comment by justin808** [comment]
Fixed.
