### ISSUE TITLE
Cannot access railsContext in components

### ISSUE THREAD

**Issue by othierry** [shakacode/react_on_rails#763]
Congratulation for the great work on react_on_rails!  👍 

I have just started trying it out. I am facing an issue where I cannot access the `railsContext` in the constructors of my components. It is always an empty `Object {}`.

Tracking down the stack brings me to `node_package/src/createReactElement.js`, because my component is a react component and not a generator function that returns one, it uses `React.createElement(component, props)` thus, discarding the `railsContext`.

```javascript
export default class NavigationBar extends React.Component {

  constructor(props, _railsContext) {
    super(props)

    console.log(_railsContext) // Object {}
  }
  ...
}
```

```javascript
import ReactOnRails from 'react-on-rails'
import NavigationBar from '../containers/navigation-bar'

ReactOnRails.register({
  NavigationBar
})
```

```ruby
  <body>
    <%= react_component 'NavigationBar' %>
    ...
  </body>
```

What am I doing wrong ?

**Comment by justin808** [comment]
Hi @othierry, the docs specify your answer. You need to use a generator function.

https://github.com/shakacode/react_on_rails/blob/master/README.md#rails-context
