### ISSUE TITLE
Issues with release script

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#767]
I documented the problem [here](http://help.rubygems.org/discussions/problems/25897-after-i-yanked-a-version-i-can-never-push-without-an-error).

Essentially, the release script works, but there's an error.

**Comment by justin808** [comment]
Recommendation is to switch to using the bundler rake tasks: 

* https://www.schneems.com/blogs/2016-03-18-bundler-release-tasks/
* https://github.com/rubygems/rubygems.org/issues/1577#issuecomment-284389761

Any volunteers to help me with this one?

**Comment by isolo** [comment]
I'll do it

**Comment by isolo** [comment]
I've debugged gem-release a little. I think I found the reason why it tries to release a version twice. gem-release goes through every [gemspec file](https://github.com/svenfuchs/gem-release/blob/master/lib/gem_release/helpers.rb#L53) and applies a command to each of them. For example, for react_on_rails that method returns something like that: 
`[".", "spec/dummy/client/node_modules/react-on-rails/gen-examples/examples/basic/client/node_modules/react-on-rails", "spec/dummy/client/node_modules/react-on-rails/gen-examples/examples/basic-server-rendering/client/node_modules/react-on-rails", ...]`
As you can see, that gem tries to apply a command to all of this gemspecs. Consequently, when it release a version for current directory, it goes to the next and fails with `Repushing of gem versions is not allowed.`

**Comment by justin808** [comment]
@isolo can you maybe submit a PR to the gem-release, or maybe at least copy this comment there: https://github.com/svenfuchs/gem-release/issues/63

**Comment by dwradcliffe** [comment]
Great debugging @isolo!

**Comment by isolo** [comment]
Fixed that with https://github.com/shakacode/react_on_rails/pull/778

**Comment by justin808** [comment]
Great work @isolo! Moving the discuss to the PR!

**Comment by isolo** [comment]
Yeah, If we delete `./spec/dummy/client/node_modules/react-on-rails/react_on_rails.gemspec` I think it solves the problem (the other occurrences are deleted by Rake::Task["examples:clobber"].invoke), but it sounds a little bit shaky. gem-release does not look like a maintainable project, so we can assume (or freeze the version) that its behaviour wouldn't change and anyway we have a dependency on it (bumping version).
I think any of these variants are acceptable. What do you think @justin808 ? It's not hard to make any of these variants workable.

**Comment by justin808** [comment]
Longer term, we should follow the schneems article. I'd feel more comfortable keeping the script as-is with the addition of deleting the extra gemspecs, maybe via a find command that excludes the top level one.

**Comment by justin808** [comment]
@isolo Bonus points for following Richards article now.
