### ISSUE TITLE
Could not get react_on_rails to work in a Rails 5.0.2 Application. Any Reason why?

### ISSUE THREAD

**Issue by mayordwells** [shakacode/react_on_rails#769]
I followed this tutorial - https://shakacode.gitbooks.io/react-on-rails/content/docs/tutorial.html
Trying to integrate react with my rails application. But I got the following errors: Any suggestions on how to fix this please?

foreman start -f Procfile.dev
00:13:18 web.1    | started with pid 35013
00:13:18 client.1 | started with pid 35014
00:13:18 client.1 | rm: cannot remove 'app/assets/webpack/*': No such file or directory
00:13:20 client.1 | (in ***/***/project-folder)
00:13:21 web.1    | => Booting Puma
00:13:21 web.1    | => Rails 5.0.2 application starting in development on http://localhost:3000
00:13:21 web.1    | => Run `rails server -h` for more startup options
00:13:22 web.1    | Puma starting in single mode...
00:13:22 web.1    | * Version 3.8.2 (ruby 2.3.3-p222), codename: Sassy Salamander
00:13:22 web.1    | * Min threads: 5, max threads: 5
00:13:22 web.1    | * Environment: development
00:13:22 web.1    | * Listening on tcp://localhost:3000
00:13:22 web.1    | Use Ctrl-C to stop
00:13:22 client.1 | yarn run v0.17.10
00:13:22 client.1 | $ webpack -w --config webpack.config.js 
00:13:23 client.1 | Webpack dev build for Rails
00:13:23 client.1 | Invalid configuration object. Webpack has been initialised using a configuration object that does not match the API schema.
00:13:23 client.1 |  - configuration.output.path: The provided value "../app/assets/webpack" is not an absolute path!
00:13:23 client.1 | error Command failed with exit code 1.
00:13:23 client.1 | info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
00:13:23 client.1 | exited with code 1
00:13:23 system   | sending SIGTERM to all processes
00:13:23 web.1    | - Gracefully stopping, waiting for requests to finish
00:13:23 web.1    | === puma shutdown: 2017-03-23 00:13:23 +0800 ===
00:13:23 web.1    | - Goodbye!
00:13:23 web.1    | Exiting
00:13:24 web.1    | exited with code 0

**Comment by sauberia** [comment]
Change the line:

```
path: '../app/assets/webpack',
```

...in client/webpack.config.js to:

```
path: __dirname + '/../app/assets/webpack',
```

**Comment by mayordwells** [comment]
This worked for me. Thank you very much for your quick reply.
