### ISSUE TITLE
Support React-Hot-Loader v3

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#772]
Looks like React on Rails should allow this:

https://github.com/gaearon/react-hot-loader/tree/master/docs#migration-to-30

When we call ReactDOM.render, we could automatically create the AppContainer if a preference for hot relading is set.

```js
import React from 'react'
import ReactDOM from 'react-dom'
import { AppContainer } from 'react-hot-loader'
import App from './containers/App'

ReactDOM.render(
  <AppContainer>
    <App/>
  </AppContainer>,
  document.getElementById('root')
);

// Hot Module Replacement API
if (module.hot) {
  module.hot.accept('./containers/App', () => {
    const NextApp = require('./containers/App').default;
    ReactDOM.render(
      <AppContainer>
        <NextApp/>
      </AppContainer>,
      document.getElementById('root')
    );
  });
}
```

Anybody want to try this and submit a PR?

**Comment by justin808** [comment]
@Judahmeek does the new hot loader require any changes to React on Rails?

**Comment by Judahmeek** [comment]
No, it does not. React on Rails already supports hot reloading with RHL 3 ([Example](https://github.com/retroalgic/react-on-rails-hot-minimal perfectly demonstrates)).

**Comment by justin808** [comment]
@Judahmeek This looks more like a doc than a code issue.

**Comment by justin808** [comment]
We need to update https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/hot-reloading-rails-development.md with what was done on https://github.com/shakacode/react_on_rails/pull/865

Any volunteers?

**Comment by EEtancelin** [comment]
I go for it :-), i want easy hot module replacement on my project.

**Comment by justin808** [comment]
@EEtancelin I've changed the tag on this one to mark it as owned by you. Please get back to me soon to let me know of the progress and any questions.

**Comment by justin808** [comment]
Supporting hot loader changes is out of scope for React on Rails currently.
