### ISSUE TITLE
Error deploying on Heroku

### ISSUE THREAD

**Issue by mayordwells** [shakacode/react_on_rails#773]
I tried to deploy on Heroku by following this tutorial, but I got this error that yarn is not found. 
Please help, any Idea on how resolve this issue?

git push heroku master  
Counting objects: 184, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (160/160), done.
Writing objects: 100% (184/184), 73.27 KiB | 0 bytes/s, done.
Total 184 (delta 31), reused 0 (delta 0)
remote: Compressing source files... done.
remote: Building source:
remote: 
remote: -----> Node.js app detected
remote: 
remote: -----> Creating runtime environment
remote:        
remote:        NPM_CONFIG_LOGLEVEL=error
remote:        NPM_CONFIG_PRODUCTION=true
remote:        NODE_VERBOSE=false
remote:        NODE_ENV=production
remote:        NODE_MODULES_CACHE=true
remote: 
remote: -----> Installing binaries
remote:        engines.node (package.json):  6.9.0
remote:        engines.npm (package.json):   4.1.1
remote:        
remote:        Downloading and installing node 6.9.0...
remote:        Downloading and installing npm 4.1.1 (replacing version 3.10.8)...
remote: 
remote: -----> Restoring cache
remote:        Skipping cache restore (new runtime signature)
remote: 
remote: -----> Building dependencies
remote:        Installing node modules (package.json)
remote:        
remote:        > react-webpack-rails-tutorial@0.0.1 postinstall /tmp/build_6de0cf5e734ae153857b4df9278aef41
remote:        > cd client && yarn install
remote:        
remote:        sh: 1: yarn: not found
remote:        
remote:        npm ERR! Linux 3.13.0-112-generic
remote:        npm ERR! argv "/tmp/build_6de0cf5e734ae153857b4df9278aef41/.heroku/node/bin/node" "/tmp/build_6de0cf5e734ae153857b4df9278aef41/.heroku/node/bin/npm" "install" "--unsafe-perm" "--userconfig" "/tmp/build_6de0cf5e734ae153857b4df9278aef41/.npmrc"
remote:        npm ERR! node v6.9.0
remote:        npm ERR! npm  v4.1.1
remote:        npm ERR! file sh
remote:        npm ERR! code ELIFECYCLE
remote:        npm ERR! errno ENOENT
remote:        npm ERR! syscall spawn
remote:        npm ERR! react-webpack-rails-tutorial@0.0.1 postinstall: `cd client && yarn install`
remote:        npm ERR! spawn ENOENT
remote:        npm ERR!
remote:        npm ERR! Failed at the react-webpack-rails-tutorial@0.0.1 postinstall script 'cd client && yarn install'.
remote:        npm ERR! Make sure you have the latest version of node.js and npm installed.
remote:        npm ERR! If you do, this is most likely a problem with the react-webpack-rails-tutorial package,
remote:        npm ERR! not with npm itself.
remote:        npm ERR! Tell the author that this fails on your system:
remote:        npm ERR!     cd client && yarn install
remote:        npm ERR! You can get information on how to open an issue for this project with:
remote:        npm ERR!     npm bugs react-webpack-rails-tutorial
remote:        npm ERR! Or if that isn't available, you can get their info via:
remote:        npm ERR!     npm owner ls react-webpack-rails-tutorial
remote:        npm ERR! There is likely additional logging output above.
remote:        
remote:        npm ERR! Please include the following file with any support request:
remote:        npm ERR!     /tmp/build_6de0cf5e734ae153857b4df9278aef41/npm-debug.log
remote: 
remote: -----> Build failed
remote:        
remote:        We're sorry this build is failing! You can troubleshoot common issues here:
remote:        https://devcenter.heroku.com/articles/troubleshooting-node-deploys
remote:        
remote:        If you're stuck, please submit a ticket so we can help:
remote:        https://help.heroku.com/
remote:        
remote:        Love,
remote:        Heroku
remote:        
remote:  !     Push rejected, failed to compile Node.js app.
remote: 
remote:  !     Push failed
remote: Verifying deploy...
remote: 
remote: !       Push rejected to acqui-ng.
remote: 
To https://git.heroku.com/acqui-ng.git
 ! [remote rejected] master -> master (pre-receive hook declined)
error: failed to push some refs to 'https://git.heroku.com/acqui-ng.git'

**Comment by justin808** [comment]
Be sure to have installed the buildpack for node.

**Comment by mayordwells** [comment]
I did, I followed the tutorial. - https://shakacode.gitbooks.io/react-on-rails/content/docs/tutorial.html

**Comment by justin808** [comment]
@mayordwells The top level package.json causes yarn to run in the /client subdirectory.
