### ISSUE TITLE
Node package vs gem backwards compatability issues

### ISSUE THREAD

**Issue by eacaps** [shakacode/react_on_rails#781]
Using the latest react-on-rails(6.9.0) npm package with an older version of the ruby gem(in our case 6.1.1, waaay behind I know) causes some crazy issues. It seems related to the movement of the rails_context from a div tag to a script tag (https://github.com/shakacode/react_on_rails/commit/7ccd603683af377880d4e16f56752ac7587c38b7).

Updating to the latest gem fixed everything so this isn't really an issue more of a backwards compatibility warning if anyone else runs into something similar.

**Comment by justin808** [comment]
@eacaps Yes, you should keep the gem and npm package at the same version always. Often, both don't change, but we only support keeping them in sync.

**Comment by justin808** [comment]
@eacaps In 6.9.2, I changed the warning to an error regarding a version mismatch.

**Comment by eacaps** [comment]
Cool, we'll do a better job of keeping things in sync in the future but the error message should certainly help. Thanks.
