### ISSUE TITLE
Undefined method reload_server_js_every_request

### ISSUE THREAD

**Issue by rupurt** [shakacode/react_on_rails#79]
Nice work on the 1.0 release guys. Really appreaciate the work you guys have done to make running React and Rails easier.

We're currently running into an issue with the generator where it gives the following config option but it doesn't appear to be defined anywhere.

```ruby
config.reload_server_js_every_request = Rails.env.development?
```

Should this be the following instead?

```ruby
config.development_mode = Rails.env.development?
```

**Comment by yorzi** [comment]
I just got the same error minutes ago.

**Comment by rstudner** [comment]
Thanks for the heads up.

**Comment by justin808** [comment]
about to push 1.0.1 which will fix this.

**Comment by rupurt** [comment]
Cheers @justin808

**Comment by justin808** [comment]
Fixed!
