### ISSUE TITLE
Change introduced in a later version broke our webpages

### ISSUE THREAD

**Issue by sid141288** [shakacode/react_on_rails#796]
Awesome work react_on_rails.
Thank You. :)

Our Gemfile.lock had 6.8.0 and on running `npm install` react-on-rails package was updated to 6.9.3, we 're getting the JavaScript errors seen below and our pages aren't rendering.
<img width="618" alt="screen shot 2017-04-06 at 4 57 17 pm" src="https://cloud.githubusercontent.com/assets/9302440/24775297/340feafc-1aea-11e7-98ec-364186c634f4.png">
<img width="621" alt="screen shot 2017-04-06 at 4 57 29 pm" src="https://cloud.githubusercontent.com/assets/9302440/24775296/340f7482-1aea-11e7-8c3f-a5ada037228e.png">

Some preliminary investigation revealed that this was introduced as part of https://github.com/shakacode/react_on_rails/commit/7ccd603683af377880d4e16f56752ac7587c38b7#diff-2b02b66a19627ff0da5b8fed749a5742R140
and wasn't there earlier.

Temporarily downgrading back to 6.7.1 got our web-app working again.
Any advice on how to fix above issues?

**Comment by justin808** [comment]
@sid141288 can you please run the app locally and copy/paste the page's raw HTML source for at least the part that has the rails context in the script JSON tag. I need to see what it is.

Are you 100% sure that upgraded both the gem and the npm package simultaneously?

**Comment by sid141288** [comment]
Ok, here's what I found after looking at out dependencies.
npm promoted `react_on_rails` to `6.9.3`, but since our `Gemfile.lock` had 6.8.0, the version of the gem that was being used was `6.8.0`. 
I could see that the changes that JavaScript `react-on-rails` package expects (with respect to `div` tag being replaced by a `script` tag in the rails helper --> https://github.com/shakacode/react_on_rails/commit/7ccd603683af377880d4e16f56752ac7587c38b7#diff-741e57aaaefab9559b7892657ec8c75eL238 ) isn't there in 6.8.0 helper gem.

Bumping up the gem version to 6.9.3 to the npm package version solved the issue.
Do the `react_on_rails` gem and the npm package need to have exact same version always ?

**Comment by tiemevanveen** [comment]
I've got the same problem when using https://github.com/Limenius/ReactBundle which depends on just the npm package, not the ruby code. 

It would probably have been wise to bump to 7.0.0 instead of 6.9.0 since users might update the npm package and the gem (or php package) independently.

**Comment by justin808** [comment]
@sid141288:
> Does the react_on_rails gem and the npm package need to have exact same version always ?
Yes! it does!

@tiemevanveen: We now do a logger.error in Rails when the versions don't match. I'm not sure what to do about Limenius, as I don't have test cases on that.

We're doing semantic versioning, so we only change the major version when there's an incompatible change.

**Comment by teameh** [comment]
> We're doing semantic versioning, so we only change the major version when there's an incompatible change.

I think you could consider this an incompatible change since 6.9.0 of the node modules package is not compatible with 6.8.0 of the ruby / php package. 

Anyway

>We now do a logger.error in Rails when the versions don't match. I'm not sure what to do about Limenius, as I don't have test cases on that.

Yeah that is a smart thing to do. @nacmartin maybe the php client should do the same? @justin808 how do you check the version with Ruby, could you point us to the relevant code?

**Comment by justin808** [comment]
https://github.com/shakacode/react_on_rails/blob/master/lib/react_on_rails/version_checker.rb
