### ISSUE TITLE
React plugin installation and functionality (Material-UI)

### ISSUE THREAD

**Issue by rohrseric** [shakacode/react_on_rails#797]
I have been trying for a couple days to incorporate Material-UI into the react_on_rails example. There are several solutions out there but specifically for react_on_rails I have tried

`yarn add material-ui`

I have also tried adding material-ui as a rails-asset in the Gemfile

`gem 'rails-assets-material-ui', source: 'https://rails-assets.org'`
and run  `bundle install`

Tried adding `//= require rails-assets-material-ui` and also `//= require material-ui` seperately in application.js and neither could be found and had to be removed.

To test I added to client/app/bundles/HelloWorld/startup/registration.jsx code that is required for material-ui installation:

```
import injectTapEventPlugin from 'react-tap-event-plugin';
 
// Needed for onTouchTap 
// http://stackoverflow.com/a/34015469/988941 
injectTapEventPlugin();
```

At this point it could not find react-tap-event-plugin so:
`yarn add react-tap-event-plugin`

Now the page loads but I get the console error 
```
Uncaught Error: Cannot find module "react-tap-event-plugin" at webpackMissingModule (eval at <anonymous> (webpack-bundle.self-1234.js:1712), <anonymous>:11:92)
```

I am unfamiliar with yarn and foreman and have only used them in the context of fiddling with react_on_rails. I am still not sure what the difference is between running the server through foreman and running the server through rails s, but I have found it does not make a difference with this error specifically.

**Comment by justin808** [comment]
@rohrseric Your issues are general to React development rather than React on Rails. I'd recommend considering [our coaching plan](http://www.shakacode.com/work/shakacode-coaching-plan.pdf)
