### ISSUE TITLE
Putting back in pretty printing of JSON props?

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#799]
Any votes for putting pretty printing of the JSON props in the HTML page source? We were doing that at first, but this resulted in some bugs.

@cheremukhin23 is working on https://github.com/shakacode/react_on_rails/pull/787 which would put that back in, along with some tests. 

I’m not 100% sure we even want this, as it’s probably just as well to put a debugger statement or console log and see the props that way.

I’d really like some community feedback on this one.

Maybe if nobody here cares, it’s best to leave this one out?

**Comment by nratter** [comment]
I think it's unnecessary as you can use something like the following...
```
<pre>
  {JSON.stringify(this.props.data.toJS(), null, 2)}
</pre>
```

**Comment by squadette** [comment]
Pretty-printing was second reason behind me driving this change forward.

Of course you can do pre-thing, console thing, or just mentally interpret JSON from attributes, but showing pretty-printed JSON in your source makes it so much more convenient and useful.  You can do Ctrl-F in your view source easily, even if you don't have the same level of advanced developer console as is in Chrome (there are other browsers btw).

This is one of the small changes which increase developer happiness, which Ruby and Rails are famous for.

I do care.  As I said, to fix the ActiveRecord issue we could probably add `as_json` call.

Thank you,

**Comment by justin808** [comment]
@squadette can you help us with the change?

**Comment by justin808** [comment]
@squadette: Now that I merged https://github.com/shakacode/react_on_rails/pull/812, it would be very easy to do the pretty printing. Maybe this is the last thing before we go to beta for 7.0?

**Comment by justin808** [comment]
@squadette any interest in taking a crack at this one?

**Comment by ebauger** [comment]
@justin808  I'll check this week what I can do

**Comment by justin808** [comment]
@ebauger Let me know if you'd like an invite to our Slack. [Email me](mailto:justin@shakacode.com).
