### ISSUE TITLE
Updates to Node Renderer: Turbolinks: Uncaught Error: unmountComponentAtNode

### ISSUE THREAD

**Issue by 3den** [shakacode/react_on_rails#810]
I recently updated to the lattest React on Rails v6.10.0, which did fixed the blinking issue #706 of turbolinks reload. But the problem is that every time I navigate to any link react raises a `Uncaught Error: unmountComponentAtNode(...): Target container is not a DOM element.`. 

@szyablitsky @justin808  Is this a know issue?

**Comment by justin808** [comment]
@3den Please review all [issues and PRs regarding Turbolinks](https://github.com/shakacode/react_on_rails/issues?utf8=%E2%9C%93&q=is%3Aissue%20turbolinks) and let me know your thoughts.

Even better is to submit a PR that addresses the issue.

Thanks,

Justin

**Comment by 3den** [comment]
@justin808 seems like none of the issues address this problem, if I disable serverside rendering the pages wont even render. Below is the code of my `application.js`:

```
//= require turbolinks
//= require webpack-bundle

ReactOnRails.setOptions({
  traceTurbolinks: <%= Rails.env.development? %>
});
```

**Comment by 3den** [comment]
this is what i get on the logs

```
TURBO: USING TURBOLINKS 5: document added event listeners  turbolinks:before-visit and turbolinks:load.
TURBO: reactOnRailsPageLoaded
Clicked link
TURBO: reactOnRailsPageUnloaded
Uncaught Error: unmountComponentAtNode(...): Target container is not a DOM element.
...
```

**Comment by justin808** [comment]
I would not turn on and off turbolinks

https://github.com/shakacode/react_on_rails/blob/master/spec/dummy/app/assets/javascripts/application_static.js

https://github.com/shakacode/react_on_rails/blob/d5d579e7c1a24667eb5ccfbb34c17c0e898d6bf9/spec/dummy/client/app/startup/clientRegistration.jsx#L31

you cannot turn turbolinks on for server rendering, which is what you are doing by putting that JS code in your application.js

https://github.com/shakacode/react_on_rails/search?utf8=%E2%9C%93&q=traceTurbolinks&type=

**Comment by 3den** [comment]
@justin808 we are using node server, which will only load the webpack file that does not have turbolinks anywhere.

Is it posible to get turbolinks to work with server side rendering? I saw on the dummy app but is a bit  hard to understand how/if you guys got turbolinks working there.

**Comment by 3den** [comment]
Also even removing turbolinks the components don't render when serverside rendering is disabled, it was working fine on version 6.5.1 tho.

Was there any breaking change on the api?

**Comment by justin808** [comment]
@3den Hi! I'd love to get your feedback on the Node server for rendering! I sent you an invite to our slack room.

Turbolinks is a client side technology. @3den, how does it relate to server rendering for you?

Thanks,

Justin

**Comment by 3den** [comment]
The turbolinks problem has nothing todo with the node server. The node server works fine but I did some changes on it https://gist.github.com/3den/1416fc25a47208f73be8dbbc7e98ca52 .

The problems i have with the nodeserver is that it does not pick changes on the on the webpack file as it should, and I have to manually delete the `node.sock`.

```json
// client/package.json
{
  ...
  scripts: {
    ...
    node-server: rm -f node/node.sock && node ./server.js,
  }
}
```

**Comment by 3den** [comment]
thanks for the help @justin808, every think seems to be working fine now, the problem was because I forgot to update the node_module after updating the gem.

I noticed that the you replaced `npm` with `yarn` and that broke my tests, but i fixed it with this: 

```ruby
class NodeTester
  attr_reader :config

  def initialize(config)
    @config = config
  end

  def compile_and_launch
    compile_assets
    launch_node
  end

  def compile_assets
    ReactOnRails::TestHelper.configure_rspec_to_compile_assets(config)
  end

  def launch_node
    path = Rails.root.join('client', 'node')
    puts "Launching NodeJS server at #{path}"
    system("cd #{path} && npm start &")
    sleep(1)
  end
end
```

**Comment by justin808** [comment]
@3den @alleycat-at-git Should this get merged back into the main project? or maybe a file in /docs/additional-reading? Such as here:

https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/node-server-rendering.md
