### ISSUE TITLE
getting `Uncaught SyntaxError: Unexpected token i in JSON at position 1`

### ISSUE THREAD

**Issue by EdmundLeex** [shakacode/react_on_rails#815]
I am trying out this gem but getting this error in the hello world app.

A little bit of digging shows that it happens in parsing railsContext. It somehow is trying to parse a string that looks like already parsed.

I am still trying to just get the hello world to render before actually being able to do stuff. Any idea?

**Comment by EdmundLeex** [comment]
looks like `json_safe_and_pretty` is the suspect here. shouldn't we return a json string instead of an already parsed json object in a double quote?

or rather this

`"{\"inMailer\":false,\"i18nLocale\":\"en\",\"i18nDefaultLocale\":\"en\",\"href\":\"http://localhost:3000/hello_world\",\"location\":\"/hello_world\",\"scheme\":\"http\",\"host\":\"localhost\",\"port\":3000,\"pathname\":\"/hello_world\",\"search\":null,\"httpAcceptLanguage\":\"en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4,zh-TW;q=0.2\",\"serverSide\":false}"`

instead of 

`"{inMailer:false,i18nLocale:en,i18nDefaultLocale:en,href:http://localhost:3000/hello_world,location:/hello_world,scheme:http,host:localhost,port:3000,pathname:/hello_world,search:null,httpAcceptLanguage:en-US,en;q=0.8,zh-CN;q=0.6,zh;q=0.4,zh-TW;q=0.2,serverSide:false}"`

**Comment by justin808** [comment]
See my comments in: #816.

**Comment by justin808** [comment]
Should be fixed in 6.10.1. Please reopen the issue @EdmundLeex if it isn't.

**Comment by EdmundLeex** [comment]
👍
