### ISSUE TITLE
following turbolinks with ajax requests

### ISSUE THREAD

**Issue by jtmarmon** [shakacode/react_on_rails#817]
When making a post request in a component:

`fetch('/my_ajax_route')` I want to follow the turbolinks redirect response, but it doesn't seem to happen. How should I make this request to get turbolinks to work?

I already have turbolinks enabled as per the wiki (in application.js, and the layout.html.erb, etc)

**Comment by justin808** [comment]
@jtmarmon I'm not totally following your question.

FWIW, my team has been focused on code-splitting with React-Router v4, rather than using TurboLinks. Both TurboLinks and React-Router listen on the back/forward buttons, so that causes a conflict.

**Comment by jtmarmon** [comment]
@justin808 so I have the following ode on the frontend:

`fetch('/my_ajax_route')`

on the backend, the request is routed to the following controller action

```rb
def my_ajax_route
  redirect_to '/some_new_page'
end
```

The response body to the client is `HTTP 200` with the following body:

```

**Comment by jtmarmon** [comment]
ah, using jquery ujs (`$.ajax({...})`) rather than fetch fixed it for me. do you think this is worth adding to the docs? using fetch is sort of the react default so I didn't know not to use it

**Comment by justin808** [comment]
@jtmarmon Yes, I do believe it would be **AWESOME** to have a doc page:

/docs/additional-reading/rails-ujs.md

(don't forget to update this page https://github.com/shakacode/react_on_rails/blob/master/SUMMARY.md, and maybe the README.md)

If useful, I'd like to see some comparison to https://github.com/reactjs/react-rails#ujs.

**Comment by justin808** [comment]
@jtmarmon feel free to submit a doc PR.
