### ISSUE TITLE
Webpack - Deploy issue after i18n changes  

### ISSUE THREAD

**Issue by amf9t2** [shakacode/react_on_rails#818]
I tried using react_on_rails i18n setup and followed the instruction [here](https://github.com/shakacode/react_on_rails/blob/master/docs/basics/i18n.md)

It worked well in development environment. Compiling assets via webpack and creating the artifact was smooth. 

Now artifact doesn't have the client directory instead it has compiled js. When we deploy the artifact and tries to run the rails application it fails with the below error message.
" invalid value for config.i18n_dir. Directory does not exist:" 
Which make sense because client dir is not any more. 

I would appreciate if we come out with some alternate approach to configure the path or another way is we have to use the special path outside of client directory which is never compiled.

For more details -  https://github.com/shakacode/react_on_rails/issues/746

Thanks.

**Comment by justin808** [comment]
@amf9t2 What are you suggesting? Maybe you can make a PR for a better error message?

**Comment by amf9t2** [comment]
@justin808 Thank for going through it. I have updated the description.

**Comment by amf9t2** [comment]
We decided to include client folder in our snapshot which was not the case earlier. 

So I would say it is not an issue until-unless someone decide to scrap the client folder after running webpack.
Thanks.
