### ISSUE TITLE
How do you include react-bootstrap into reactonrails

### ISSUE THREAD

**Issue by Mahern-13** [shakacode/react_on_rails#826]
Adding additionally libraries breaks the rendering of components in react on rails. How do you import libraries to components?

**Comment by justin808** [comment]
@Mahern-13 See the https://github.com/shakacode/react-webpack-rails-tutorial.

If you need additional personalized help, please consider our [Coaching Plan](http://www.shakacode.com/work/shakacode-coaching-plan.pdf).
