### ISSUE TITLE
Connecting to React...

### ISSUE THREAD

**Issue by linojon** [shakacode/react_on_rails#827]
Hi this may not be an issue with react_on_rails but maybe you can help me. I implemented a small example project and it runs. But in Chrome when i go to the React tab it always is stuck on "Connecting to React..." Anyone else have this, know how to work around?

**Comment by justin808** [comment]
This sounds like a problem specific to your application. @linojon we can help you with our [Coaching Plan](http://www.shakacode.com/work/shakacode-coaching-plan.pdf).
