### ISSUE TITLE
env_stylesheet_link_tag set link domain instead of root /

### ISSUE THREAD

**Issue by xiaopow** [shakacode/react_on_rails#828]
Trying to use prerender.io to prerender our react on rails site. Since the stylesheet source link is set to root /, not the actual domain. Prerender will raise 404 when fetching stylesheet application_static.

```
/assets/application_static-31529a67d8ed4a81528e59c922580fd618e5dd227a3f3bb2dd5c4983151421ef.css Failed to load resource: the server responded with a status of 404 (Not Found)
```

You can see the 404 on http://service.prerender.io/https://www.altcademy.com/documents/

Is there anyway we can set the stylesheet link to the actual domain so it can be fetched?

**Comment by justin808** [comment]
@xiaopow Can you try out https://github.com/shakacode/react_on_rails/pull/822, the webpacker support? This should have what you need. 

**7.1.0.beta.3**

**Comment by xiaopow** [comment]
Hi @justin808, I figured we can set this in config/environments/production.rb

```
# Enable serving of images, stylesheets, and JavaScripts from an asset server.
  config.action_controller.asset_host = ENV['URL']
```

**Comment by justin808** [comment]
@xiaopow can we close this issue?

**Comment by xiaopow** [comment]
Yup.
