### ISSUE TITLE
React on Rails v7 is not totally being obvious if npm and gem versions differ

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#831]
This might be a bug here, in that we want "React on Rails" to totally stop the Rails app if the NPM and gem versions are different.

**Comment by alexfedoseev** [comment]
Details: I updated local gems incl `react_on_rails` from `6.10.1` to `7.0.4`, but DLL build had stale `6.10.1`. In this combination, SSR worked, but nothing was rendered on the client w/o any warnings or errors on both sides (rails/browser).

**Comment by EdmundLeex** [comment]
@alexfedoseev Having the same issue? What's the reason causing components not being rendered?

**Comment by justin808** [comment]
@EdmundLeex make sure the npm and gem versions of react-on-rails are the same.

**Comment by gotno** [comment]
surely there's a way either the gem or the node package could report an error when this happens? i've been debugging blindly all afternoon and finally found this.

**Comment by justin808** [comment]
@gotno what version are you on? In version 8.0.0, rather than Rails log.error, we're throwing to just crash.

**Comment by gotno** [comment]
@justin808 thanks! that's super helpful to know. i'm currently on 7.0.4.
