### ISSUE TITLE
How to set page title, description, etc

### ISSUE THREAD

**Issue by mattfordham** [shakacode/react_on_rails#832]
Is there a recommended way to set a page's title, description or other <head> meta tags based on the precompiled JS?

[React Helmet](https://github.com/nfl/react-helmet) works great for managing this on the client-side, but the [instructions on server usage](https://github.com/nfl/react-helmet#server-usage) don't seem compatible with React on Rails. 

Any thoughts on how to solve this problem?

**Comment by justin808** [comment]
@mattfordham recent updates support react-helmut!

https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/react-helmet.md

**Comment by mattfordham** [comment]
Oh sweet, thanks! So much for my Googl'ing skills ;)
