### ISSUE TITLE
Code splited js chunks cannot be fetched on production

### ISSUE THREAD

**Issue by xiaopow** [shakacode/react_on_rails#836]
Hey, I added code splitting to the app using [bundle loader](https://github.com/webpack-contrib/bundle-loader) and a bunch of chunks are outputted into "app/assets/webpack".

In the react app, components are lazy loaded with bundle loader

```
import loadPage from 'bundle-loader?lazy!../Page'
```

This creates a js chunk and is added to "app/assets/webpack". The chunks have names as '1.client-bundle.js', '2.client-bundle.js'. I include those files in asset precompile like this.

```
# Add folder with webpack generated assets to assets.paths
Rails.application.config.assets.paths << Rails.root.join("app", "assets", "webpack")

# Precompile additional assets.
# application.js, application.css, and all non-JS/CSS in app/assets folder are already added.
# Rails.application.config.assets.precompile += %w( search.js )
# Add client/assets/ folders to asset pipeline's search path.
# If you do not want to move existing images and fonts from your Rails app
# you could also consider creating symlinks there that point to the original
# rails directories. In that case, you would not add these paths here.
# If you have a different server bundle file than your client bundle, you'll
# need to add it here, like this:
# Rails.application.config.assets.precompile << "server-bundle.js"

hot = ENV["REACT_ON_RAILS_ENV"] == "HOT" ? true : false

if hot
  Rails.application.config.assets.precompile +=
    [
      "application_non_webpack.css"
    ]
else
  Rails.application.config.assets.precompile +=
    [
      "application_static.js",
      "application_static.css",
      "*.client-bundle.js"
    ]
end
```

In Webpack config, I added the public path like this.

```
  output: {
    filename: 'client-bundle.js',
    path: '../app/assets/webpack',
    publicPath: '/assets/'
  },
```

On local development, everything seems to work and chunks are fetched when needed. However on production, the chunks cannot be fetched because I get this error.

```
Refused to execute script from 'https://www.domain.com/assets/1.client-bundle.js' because its MIME type ('text/html') is not executable, and strict MIME type checking is enabled.
```

On local, when visiting the url 'localhost:3000/assets/1.client-bundle.js' the js file shows up as a document.

Any help will be much appreciated.

**Comment by xiaopow** [comment]
When the assets are precompiled, a hash is added to the end of the file name like this.

```
1.client-bundle-8ecea2b7f297cda29bb16819bd8ef9bd9549ea1fbaf9ef17398ef007291161e4.js
```

Could this be the reason why the file cannot be fetched on production? How can I let webpack know that the file name is actually different?

**Comment by justin808** [comment]
@xiaopow can you try with the 8.x beta and webpacker_lite?

**Comment by justin808** [comment]
`/app/assets` will not be used going forward.

**Comment by xiaopow** [comment]
@justin808 

Added js extensions to the following config in react_on_rails.rb and the issue is fixed.

```
config.symlink_non_digested_assets_regex = /\.(png|jpg|jpeg|gif|tiff|woff|ttf|eot|svg|js)/
```

**Comment by justin808** [comment]
FWIW, config.symlink_non_digested_assets_regex is not used when using webpacker_lite.

**Comment by aditya9026** [comment]
@xiaopow any solution for this?

**Comment by justin808** [comment]
@aditya9026 upgrade to latest React on Rails and install Shakapacker.
