### ISSUE TITLE
Referer prop is overwritten when the value contains '/users/'

### ISSUE THREAD

**Issue by figandbones** [shakacode/react_on_rails#837]
In my Rails view I have:

```
    <%= react_component('ReporterApp',
                     props: @init_props,
                     prerender: false) %>
```

@init_props has a value 'referer'. In certain cases, like when referer contains /users/, the referer prop in the react app contains my rails home page, instead of the value from @init_props.

Is there a setting I can use to stop this behavior?

**Comment by justin808** [comment]
@figandbones Please create a simple repro app based on the generator.

This sounds like a bug on your side.

If you want personalized attention for your app, please consider our [Coaching Plan](http://www.shakacode.com/work/shakacode-coaching-plan.pdf).
