### ISSUE TITLE
Add Javascript testing framework

### ISSUE THREAD

**Issue by rupurt** [shakacode/react_on_rails#84]
Howdy,

Do you plan on having an opinion on how to setup Javascript testing and what framework to use?

**Comment by alexfedoseev** [comment]
Hey @rupurt, our current setup is mocha + chai + sinon + jsdom. Also I want to play around with shallow render.

**Comment by rupurt** [comment]
@alexfedoseev cool. I've setup mocha + chai + sinon + testem (which can test multiple runtime environments). Good to know that I'm on roughly the same path.

Do you have any plans for shipping that by default in `react_on_rails`?

**Comment by justin808** [comment]
@rupurt we're going to pull this in here:

https://github.com/shakacode/react-webpack-rails-tutorial/pull/137

within a couple days, right @robwise?

**Comment by rupurt** [comment]
@justin808 sweet. There's a couple of ideas in there that I'll pinch for our project.

Cheers

**Comment by robwise** [comment]
@justin808 @rupurt yep! I could even extend these tests to be sanity checks that our generated results are working correctly, as currently I have to do go into each type of result and start up servers manually and look

**Comment by robwise** [comment]
Okay, JS tests were added to the tutorial in https://github.com/shakacode/react-webpack-rails-tutorial/pull/151

I will add this to my TODO list!

**Comment by justin808** [comment]
@jbhatab @aaronvb @robwise @rupurt @alexfedoseev @thewoolleyman I'm thinking maybe we should not have this be part of react_on_rails, and just part of the https://github.com/shakacode/react-webpack-rails-tutorial and other articles.

**Comment by thewoolleyman** [comment]
@justin808 Sure, as long as we have some article explaining and example repos showing how to add it easily and these are prominently linked in the main repo README.  Testing is important.  Perhaps it can be added as a generator option someday ;) (ducks any thrown objects)

**Comment by robwise** [comment]
This is stuff that is specific to webpack and React though, isn't it? Like this isn't related to anything that the gem is doing?

**Comment by thewoolleyman** [comment]
@robwise Hmm, that's a very good point.  I think that is correct?

But still from the perspective of being a framework that React/Redux newbies coming from Rails or other frameworks might use, it would still be good to have some simple but realistic examples of testing available in the example projects - or at a minimum pointers to other curated examples/tutorials on React/Redux testing that are known to work with react_on_rails.  E.g., that use the same container vs. component structure and categorization, etc...

If something like that made it into the README as a result of this issue, then I'd say that's sufficient.

**Comment by justin808** [comment]
Chad, does this help: https://github.com/shakacode/react-webpack-rails-tutorial/pull/151/files

Maybe look to see if these files changed. This is from a few months ago.

**Comment by thewoolleyman** [comment]
@justin808 Sure, that works, but I'd still like to see an explicit link to that in the react_on_rails readme.  A search of https://github.com/shakacode/react_on_rails for 'spec' or 'test' doesn't yield anything really useful for knowing how to write tests.

I'd be glad to add a blurb, but not positive where in the readme it should go, do you have a preference?

**Comment by justin808** [comment]
@thewoolleyman Please create a blurb here: https://github.com/shakacode/react_on_rails/tree/master/docs/additional_reading

**Comment by justin808** [comment]
The link goes right here in the README.md:

https://github.com/shakacode/react_on_rails#additional-reading

**Comment by justin808** [comment]
Closing for now. We've got an example here: https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client%2Fapp%2Fbundles%2Fcomments%2Fcomponents%2FCommentBox%2FCommentList%2FCommentList.spec.jsx
