### ISSUE TITLE
foreman start not working on windows

### ISSUE THREAD

**Issue by majercakdavid** [shakacode/react_on_rails#847]
When starting foreman on windows I get this error:

09:57:04 web.1    | started with pid 5296
09:57:04 client.1 | started with pid 17184
09:57:06 client.1 | (in D:/project/src)
09:57:14 web.1    | => Booting Puma
09:57:14 web.1    | => Rails 5.0.2 application starting in development on http://localhost:3000
09:57:14 web.1    | => Run `rails server -h` for more startup options
09:57:14 web.1    | *** SIGUSR2 not implemented, signal based restart unavailable!
09:57:14 web.1    | *** SIGUSR1 not implemented, signal based restart unavailable!
09:57:14 web.1    | *** SIGHUP not implemented, signal based logs reopening unavailable!
09:57:14 web.1    | Puma starting in single mode...
09:57:14 web.1    | * Version 3.8.0 (ruby 2.3.3-p222), codename: Sassy Salamander
09:57:14 web.1    | * Min threads: 5, max threads: 5
09:57:14 web.1    | * Environment: development
09:57:14 web.1    | * Listening on tcp://localhost:3000
09:57:14 web.1    | Use Ctrl-C to stop
09:57:15 client.1 | stdout is not a tty
09:57:16 client.1 | exited with code 1
09:57:16 system   | sending SIGKILL to all processes
09:57:16 system   | sending SIGKILL to web.1 at pid 5296
09:57:16 web.1    | exited with code 0

**Comment by justin808** [comment]
If foreman doesn't work on Windows, please google around for an alternative. Manually, you can just run the individual commands in separate command shells.
