### ISSUE TITLE
Generator Future Enhancements

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#85]
## List of Features to add to the Generator

* Install instructions should suggest running `bundle` after running the generator b/c of linters
* Important post generate messages should go to the bottom
```
** nvm is advised. Please consider installing it. https://github.com/creationix/nvm
** Need to run bundle and npm i 
```

**Comment by robwise** [comment]
Also:

+ linters should be split into two types, javascript and ruby, and the former should be enabled by default while the latter should not
+ generated javascript code should pass linting

**Comment by robwise** [comment]
If anyone wants to try Justin's points, either of those should be simple enough and a good way to get started

**Comment by justin808** [comment]
@robwise Should we keep this list open? or close this issue?
