### ISSUE TITLE
React on Rails says file has not changed but it has...

### ISSUE THREAD

**Issue by ceres629** [shakacode/react_on_rails#850]
I'm having a problem that I've only recently noticed and I'm not sure who or what is to blame.

If I change an image without changing its name, everything works fine on my local development machine but if I push to production the image is not updated. The only way I can get the new image to take effect is to rename it, which gets tiresome fast.

I'm not sure if it is a problem with react on rails. I'm pretty sure I never had this issue before though. Here is an example of the console output when deploying to heroku:

React On Rails: Digested version of image.jpg already exists indicating image-3243243.jpg did not change.

However the image did change... how do I force it to acknowledge that the image has changed?

**Comment by justin808** [comment]
Is this an issue with 8.x?

**Comment by ceres629** [comment]
It has been an issue for all react on rails versions from 6 to 9...

**Comment by ceres629** [comment]
It has been an issue on all react versions from 6 to 9.
