### ISSUE TITLE
Can't turn off client-side "trace"

### ISSUE THREAD

**Issue by mattfordham** [shakacode/react_on_rails#851]
Regardless of how I set "trace" in the React on Rails config (and in the `react_component` helper calls), I still get the trace. 

I believe this has to do with [this line](https://github.com/shakacode/react_on_rails/blob/master/node_package/src/clientStartup.js#L108),where the `trace` variable is pulled from an HTML data attribute. Because this is a string, it always evaluates "truthy", even if it is "false". 

If I make that line like so...

`var trace = el.getAttribute('data-trace') === 'true'`

... all works as expected. 

Is it possible I am misconfigured somewhere? It seems this would have been noticed by others. 

Thanks!

**Comment by justin808** [comment]
Fixed in 8.x
