### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by Ancinek** [shakacode/react_on_rails#852]
I was trying to implement server rendering on my website but this error kept showing up. I get to the point that I know that any module that imports (and does not have to use it) a package (like for example Vivus.js) that uses `window` variable, will be causing this problem.

Is there any way to overcome this? Any help appreciated.

**Comment by justin808** [comment]
You have to remove any code from your server side code that uses `window`. 

If you want personalized help on this, please consider our [Coaching Plan](http://www.shakacode.com/work/shakacode-coaching-plan.pdf).
