### ISSUE TITLE
Wrong link in the tutorial

### ISSUE THREAD

**Issue by jkgatt** [shakacode/react_on_rails#864]
While going through the tutorial there is the following written:

> Visit http://localhost:5000/hello_world and see your React On Rails app running! Note, foreman defaults to PORT 5000 unless you set the value of PORT in your environment.

But this should be changed to:

> Visit http://localhost:3000/hello_world and see your React On Rails app running! Note, foreman defaults to PORT 5000 but this has has been set to PORT 3000 in the Procfile.dev file.

**Comment by justin808** [comment]
Thanks! I updated:

![image](https://user-images.githubusercontent.com/1118459/26863106-56b6c012-4b05-11e7-80b6-f3f7bb2cb6c2.png)
