### ISSUE TITLE
react_on_rails 8.0.2 is NOT compatible with ruby 2.1

### ISSUE THREAD

**Issue by alainbloch** [shakacode/react_on_rails#870]
In `lib/react_on_rails/prerender_error.rb` lies the new [squiggly heredoc](https://infinum.co/the-capsized-eight/multiline-strings-ruby-2-3-0-the-squiggly-heredoc) syntax. This is only available in ruby 2.3 and above, and will throw an exception if ran on ruby 2.1

**Comment by justin808** [comment]
Fixing in #867.

`Rubocop -a` did that!

**Comment by justin808** [comment]
@alainbloch I think that rubocop may have done that...Please confirm 8.0.3 fixes the issues.

**Comment by justin808** [comment]
#867 was merged.
