### ISSUE TITLE
propTypes not working on functional components included directly in Rails view

### ISSUE THREAD

**Issue by ljphipps** [shakacode/react_on_rails#876]
I have a react function component being included in a Rails view as such: 
`#map = react_component('Map', props: { token: 'string', lat: 39.000, lng: -76.000, radius: 5.5 })`

And the component like this:
```javascript
import React, { PropTypes } from 'react';

RegionMap.propTypes = {
  token: PropTypes.string.isRequired,
  lat: PropTypes.number.isRequired,
  lng: PropTypes.number.isRequired,
  radius: PropTypes.number.isRequired,
};

export default function RegionMap({ token, lat, lng, radius }) {
  return (<div>Things</div>);
}
```

The problem is, no matter what I define the types as or send them as, none of the PropType validators are ever fired. However if I define this same component as a class, I get the expected validations and warnings. So that's the workaround for now for any component that is included directly in a Rails view. The PropType validation does work as expected for functional components not directly included from a Rails view.

On `3.0.5`
react `15.3.1`
rails `5.0.2`

**Comment by justin808** [comment]
FWIW, I put the propType validation afterward:

https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/app/bundles/comments/components/NavigationBar/CommentsCount.jsx

```js
import React, { PropTypes } from 'react';

const href = 'https://github.com/shakacode/react_on_rails/blob/master/README.md#multiple-react-' +
  'components-on-a-page-with-one-store';
const CommentsCount = (props) => (
  <li>
    <a id="js-comment-count" href={href}>
      Comments: {props.commentsCount}
    </a>
  </li>
);

CommentsCount.propTypes = {
  commentsCount: PropTypes.number.isRequired,
};

export default CommentsCount;
```

If you have addition React specific questions, please consider our [Coaching Plan](http://www.shakacode.com/work/shakacode-coaching-plan.pdf).
