### ISSUE TITLE
Preloading/fetch data in javascript for server rendering

### ISSUE THREAD

**Issue by kooinam** [shakacode/react_on_rails#880]
We are currently serving data from a third party service and I would like to preload/fetch the data in JS from the source at server rendering. We had able to serve ready template to our users, but our users would have to load the data from another source. Any way we can serve the template with ready data? Like serving a promise when registering component. 

One example im looking at
https://blog.tableflip.io/server-side-rendering-with-react-and-redux/

**Comment by justin808** [comment]
@kooinam I have never tried running an async call from server rendering. I don't think there is any need to. You can run the async call from your ruby code and pass in the values. And you can run the asynch call on the client only if you need to. In other words, don't re-run if you already have data.

Please let me know if this answers your question. I'll re-open this issue if there's further research needed.
