### ISSUE TITLE
Possible to use react-scripts instead of webpack ? And react-md integration ?

### ISSUE THREAD

**Issue by atinder** [shakacode/react_on_rails#881]
Hey guys,
thanks for the awesome gem, I was wondering if one can use react-scripts for build instead of webpack config.
Having hard time integrating react-md https://github.com/mlaursen/react-md css , files are not being generated.

**Comment by MiguelSavignano** [comment]
Hi @atinder.

React on Rails it's great for integrate other npm packages but each package must be configured differently.
The Css have many problems to integrate but the simple way it's copy the link url or css files and use i't with the rails asset pipeline.

``` html
<!-- application.html.erb -->
<link rel="stylesheet" href="https://unpkg.com/react-md/dist/react-md.indigo-pink.min.css">
```

See the github for react-md and copy all css files and use it with rails asset pipeline
https://github.com/mlaursen/react-md/tree/master/src/scss

You can use asset pipeline as it has always been done.

**Comment by atinder** [comment]
Hi @MiguelSavignano 
thanks for answering, I didn't want to use rails asset pipeline for react stuff. It clutters the rails app quickly. want to keep react separate so that its easier to detach later on if needed.

**Comment by MiguelSavignano** [comment]
Hi @atinder 
I would like to help you because I've had the same problems with other npm packages.
I miss a documentation of what is the best way to do something like this.

I have tried to make an example that works with React on rails and react-md see it in my github
https://github.com/MiguelSavignano/example-react-on-rails-react-md

I hope I could have helped you.

**Comment by justin808** [comment]
@MiguelSavignano @atinder The Asset Pipeline should not be in the discussion as React on Rails v8 deploys all webpack generated files directly to the /public directory.

In terms of using https://github.com/facebookincubator/create-react-app/tree/master/packages/react-scripts/scripts, that doesn't seem to make sense as you need to configure Webpack for React on Rails.
