### ISSUE TITLE
Nesting Yield

### ISSUE THREAD

**Issue by vpfaulkner** [shakacode/react_on_rails#887]
Hello,

I'm building an application that will always have a left side-menu present and so I'm trying to stick that logic for rendering this side-menu in `app/views/layouts/application.html.erb`. However, the side-menu I'm using is a React component (https://react.semantic-ui.com/modules/sidebar#sidebar-example-left-push) and is setup in such a way that all of the content that sits to the right of the side menu (in my case, the rest of the application content) needs to be nested within that component. Consequently, I'd like the content that is rendered from the `yield` in the application layout to be nested within that react component.

For example:
```
class Sidemenu extends React.Component {
  render () {
    return (
      <Sidebar.Pushable>
        <Sidebar as={Menu} visible>
          <h3>My side menu content</h3>
        </Sidebar>
        <Sidebar.Pusher>
          {/* Where the yielded content needs to go */}
        </Sidebar.Pusher>
      </Sidebar.Pushable>
    )
  }
}
```

Do you have any suggestions for how to do this?

**Comment by justin808** [comment]
@vpfaulkner I don't see a way that you can nest Rails rendering inside of your React component unless maybe doing some remote call to the rails server to retrieve HTML in a JSON response.

Please reopen this issue if you believe this to be appropriate. A better venue for this question would be on https://forum.shakacode.com.

**Comment by chhuang** [comment]
Is it possible to do something like this?

```ruby
<% react_component("AppLayout") %>
  <%= yield %>
<% end %>
```

And then in my component:

```javascript
const AppLayout = props => (
  <div>
    { props.children } // The yield content here
  </div>
);
```

**Comment by threepete** [comment]
@chhuang Did you ever find something that could achieve this?

**Comment by justin808** [comment]
@threepete you want to handle all that within React.
