### ISSUE TITLE
Generator Appends Hello World Route to Other Engines

### ISSUE THREAD

**Issue by robwise** [shakacode/react_on_rails#89]
In the case where users have multiple engines in their routes file, the built-in Rails generator helper, `route`, will add the route to *all* of the engines. It should only be appending the route once. 

I believe this is due to the helper's reliance on `gsub` and their use of `routes.draw do` instead of `Rails.application.routes.draw do`, since the former will result in false positives.

Relevant links: 
+ [Rails `route` helper API](http://api.rubyonrails.org/classes/Rails/Generators/Actions.html#method-i-route)
+ [Rails `route` helper source code](https://github.com/rails/rails/blob/82ed33e4ba7d76f35b80f81441fa6356c9c9352d/railties/lib/rails/generators/actions.rb#L221) I've linked directly to what I believe is the line, the definition of `sentinel` which uses a regex that is too loose
+ [Thor `inject_into_file` API](http://www.rubydoc.info/github/erikhuda/thor/master/Thor%2FActions%3Ainsert_into_file) (used by the `route_helper`)
+ [Thor `inject_into_file` source](https://github.com/erikhuda/thor/blob/master/lib/thor/actions/inject_into_file.rb#L24)

**Comment by justin808** [comment]
This is not incredibly serious as we ask user to commit files before running the generator, and this can be manually fixed.

**Comment by robwise** [comment]
@justin808 it's borderline whether we should even fix this here, as it's really a bug with Rails's `Generators::Helpers.route` IMO
