### ISSUE TITLE
Yarn cannot invoke webpack

### ISSUE THREAD

**Issue by monarajhans** [shakacode/react_on_rails#890]
I have followed the documentation and I am trying to deploy this from my capistrano server but I am getting the error "webpack: not found" (details listed on #error_message). 

#gemfile 
gem "react_on_rails", "8.0.0"
gem 'capistrano-yarn'

#client/package.json 
"scripts": {
    "build:server": "webpack --config webpack.server.rails.build.config.js",
    "build:test": "NODE_ENV=test webpack --config webpack.config.js",
    "build:production": "NODE_ENV=production webpack --config webpack.config.js",
    "build:development": "NODE_ENV=development webpack -w --config webpack.config.js"
  },
  "cacheDirectories": ["node_modules", "client/node_modules"],
  "dependencies": {
    "babel-cli": "^6.24.1",
    "babel-core": "^6.24.1",
    "babel-loader": "^6.3.2",
    "babel-runtime": "^6.23.0",
    "babel-polyfill": "^6.23.0",
    "babel-preset-es2015": "^6.24.1",
    "babel-preset-react": "^6.24.1",
    "babel-preset-stage-2": "^6.24.1",
    "es5-shim": "^4.5.9",
    "expose-loader": "^0.7.3",
    "imports-loader": "^0.7.1",
    "js-yaml": "^3.8.2",
    "react": "^15.5.4",
    "react-dom": "^15.5.4",
    "react-on-rails": "8.0.0",
    "webpack": "^2.3.3",
    "webpack-manifest-plugin": "^1.1.0",
    "node-sass": "^3.13.1",
    "postcss-loader": "^1.3.3",
    "style-loader": "^0.13.2",
    "sass-loader": "^4.1.1"
  },
  "devDependencies": {
  }

#error_message
cd client && yarn run build:production
warning ../package.json: "dependencies" has dependency "webpack" with range "^1.14.0" that collides with a dependency in "devDependencies" of the same name with version "^1.13.3"
sh: 1: webpack: not found
error Command failed with exit code 127.
rake aborted!
Command failed with status (1): [cd client && yarn run build:production...]

Can you please help?

**Comment by justin808** [comment]
> sh: 1: webpack: not found

You need to install Webpack.

If you want personalized help, please consider our [Coaching Plan](http://www.shakacode.com/work/shakacode-coaching-plan.pdf).

**Comment by monarajhans** [comment]
But I have yarn which should install webpack as it is a dependency mentioned in my package.json file. Why do I need to install webpack separately?

**Comment by justin808** [comment]
@monarajhans Take a look at your path. I've seen some issues where $(yarn bin) is not in the path when invoking scripts. Maybe you can put in some debug printing in the output?

**Comment by monarajhans** [comment]
Thank you @justin808, that fixed my issue! 👍

**Comment by justin808** [comment]
@monarajhans can you please post what fixed your issue?

**Comment by monarajhans** [comment]
I added "postinstall": "cd client && npm install && echo \"Postinstall running\"", to package.json
