### ISSUE TITLE
Accessing Assets in React on Rails 8.0.0

### ISSUE THREAD

**Issue by thebucknerlife** [shakacode/react_on_rails#892]
Hi, 

I'm trying to get images in the asset pipeline working in React on Rails 8.0.0. I noticed in the docs that they need updating:

> Note: this doc needs updating to reflect how v8.x+ no longer puts Webpack generated files through the asset pipeline. PR's welcome!

here: https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/rails-assets-relative-paths.md

I'd love to know how to do this but I don't fully understand to open up a PR myself.

Any guidance or a push in the right direction on how to access image assets being handled by Rails would be greatly appreciated! Thank you!

**Comment by justin808** [comment]
@thebucknerlife Any PRs to help me with the docs would be super welcome. Basically, there's a lot less "magic" when you have webpack configured to publish to your public directory. Things should "just work" with no special actions needed. Note, there's two main types of images:

1. Images used as background images in CSS.
2. Images used in image HTML tags (use the file-loader or url-loader from webpack).

**Comment by thebucknerlife** [comment]
@justin808 some questions:

1. is webpacker lite configured by default to publish to the public directory? (I'm not seeing this when I run foreman)
2. should images in `app/assets/images/` automatically be published to `public/`? or should image assets be placed elsewhere.
3. is the behavior different in development versus production? (I'm only running this locally right now).

Thank you for your very active OSS contributions and super start maintenance of this project and community!

**Comment by justin808** [comment]
> is webpacker lite configured by default to publish to the public directory? (I'm not seeing this when I run foreman)

Webpacker Lite is just the view helper. You configure Webpack on where to publish.

> should images in app/assets/images/ automatically be published to public/? or should image assets be placed elsewhere.

Take a look at https://github.com/shakacode/react_on_rails/tree/master/spec/dummy/client/app/assets/images 

That is how you want to do it. The images should be in the /client directory and Webpack will publish them to the /public directory.

> is the behavior different in development versus production? (I'm only running this locally right now).

Up to you. In production, assets **MUST** be hashed. In development, the assets are usually not hashed.


> Thank you for your very active OSS contributions and super start maintenance of this project and community!

You're welcome!
