### ISSUE TITLE
Unit-testing with Jasmine

### ISSUE THREAD

**Issue by monarajhans** [shakacode/react_on_rails#894]
Hi,

Do you have a documentation page that I can refer to add Jasmine unit-tests on top of my already available jasmine tests for the react code that I am writing?

I am continuously just seeing "Uncaught SyntaxError: Unexpected token import" for my files.

**Comment by justin808** [comment]
@monarajhans We don't have any client side docs. I'd consider posting this sort of question to https://forum.shakacode.com.

If you can submit a new doc page to https://github.com/shakacode/react_on_rails/tree/master/docs/additional-reading, my team will review this.

If you want personalized help on this, please consider our [Coaching Plan](http://www.shakacode.com/work/shakacode-coaching-plan.pdf). We can share the techniques that we're using to test our app https://www.friendsandguests.com.
