### ISSUE TITLE
react_on_rails deployed through marathon on EC2 container does not receive any requests

### ISSUE THREAD

**Issue by yankeehack** [shakacode/react_on_rails#900]
Hey, Shakacode team,
react_on_rails is such a nice gem that worked for us for the most part.

However, when we try to put it into production using marathon and EC2, we are having some hiccups
basically, after everything is built.
`AssetSync: using /app/config/initializers/asset_sync.rb
  [1m[36mActiveRecord::SchemaMigration Load (0.6ms)[0m  [1mSELECT "schema_migrations".* FROM "schema_migrations"[0m
== Starting server ==
[9] Puma starting in cluster mode...
[9] * Version 2.16.0 (ruby 2.3.3-p222), codename: Midwinter Nights Trance
[9] * Min threads: 8, max threads: 16
[9] * Environment: staging
[9] * Process workers: 2
[9] * Preloading application
AssetSync: using /app/config/initializers/asset_sync.rb
Cache read: table/ndaps/index/data
Dalli::Server#connect endor-cache.fobogb.0001.usw2.cache.amazonaws.com:11211
Cache fetch_hit: table/ndaps/index/data
[9] * Listening on tcp://0.0.0.0:31652
[9] * Listening on tcp://0.0.0.0:3030
[9] Use Ctrl-C to stop
[9] - Worker 0 (pid: 12) booted, phase: 0
[9] - Worker 1 (pid: 19) booted, phase: 0`

then he server start to not respond at all,  not receiving any requests.

We tried to build everything with same env on local (using docker-compose) no problems are all.

And if we remove this gem, everything will work again.

I'm wondering have you guys encountered this before?

**Comment by justin808** [comment]
@yankeehack Try to create a minimal reproduction case and let me know what you find.

If you want personalized help on this, please consider our [Coaching Plan](http://www.shakacode.com/work/shakacode-coaching-plan.pdf).

**Comment by justin808** [comment]
@yankeehack we can re-open if you find an issue. Feel free to get in touch directly.
