### ISSUE TITLE
Question: Does Non-Server-Rendering Need "therubyracer" and "execjs"?

### ISSUE THREAD

**Issue by robwise** [shakacode/react_on_rails#91]
If the user is not using the server-rendering feature, are `therubyracer` and `execjs` still needed? I have tried generating a fresh non-server-rendering app, commenting out therubyracer dependency, and bundle installing again. I was able to run the app with no errors. Perhaps we can explore removing these dependencies from the non-server-rendering generators.

However, even though we may not be executing the code, it nonetheless is still referring to the gem, so it seems a little strange that this actually works.

**Comment by justin808** [comment]
The gemspec includes:
```
  s.add_dependency "execjs", "~> 2.5"
``

So the gem depends on execjs, not therubyracer.

So yes, it's really not good to put in the gemfile.

We should add it as commented out and mention that you should set this if you plan to do server rendering.

Good catch.

We should have a file in the /docs directory on server rendering topics, BTW.

**Comment by justin808** [comment]
@robwise Can we close this issue? I see this as a doc only issue.

**Comment by robwise** [comment]
@justin808 It's up to you, I think I created this one a while back at your request. Right now the docs still say to manually include the `therubyracer` gem along with the `react_on_rails` gem in the Gemfile, and I'm still have the generator results script do that as well. If we want to remove that step, we should probably do some thorough testing and try to understand why it was put there in the first place.

**Comment by justin808** [comment]
I'd say check react-rails.

We have a peer dependency of execjs already in the gem.

I'm almost 100% sure that we should not be putting in the therubyracer for non pre-render generators (and doc'd as such).

**Comment by robwise** [comment]
@justin808 roger that, I will look into it and take it out if possible

**Comment by robwise** [comment]
@justin808 while we're talking gem dependencies, we really should have foreman in there instead of just assuming people are going to have it.

**Comment by justin808** [comment]
Probably. Maybe a non-production dependency. There's differing thoughts on including foreman in the gemfile.

**Comment by justin808** [comment]
@robwise can we close this one?

**Comment by robwise** [comment]
Yes, fixed in https://github.com/shakacode/react_on_rails/commit/c21012af1536f7c5d2eaa0375221df5696f10ea4
