### ISSUE TITLE
Webpack binstubs not found during production assets compilation

### ISSUE THREAD

**Issue by ndbroadbent** [shakacode/react_on_rails#917]
I'm trying to use react_on_rails `9.0.0.beta.8`, but I'm getting very confused. My Gemfile includes:

```ruby
gem 'react_on_rails', '9.0.0.beta.8'
gem 'mini_racer', platforms: :ruby
gem 'webpacker', git: "https://github.com/shakacode/webpacker.git",
                  branch: "issue-464-merge-webpacker-lite-into-webpacker-v2"
```

`cd client && yarn run build:development` works fine in development, and I'm able to use the `javascript_pack_tag` and `stylesheet_pack_tag` helpers. `react_component` and `redux_store_hydration_data` are also working fine in development.

When I run `rake assets:precompile`, I get the error: `Webpack binstubs not found. Have you run rails webpacker:install ?`

Do I need to run this command to use `react_on_rails` with webpacker? Because when I run it, I get a whole bunch of npm modules added to the `package.json` at the root of my app, instead of in the `client/` directory. It feels like the `webpacker` gem is duplicating a ton of things that `react_on_rails` is already handling. And I'm not sure what I'm supposed to do with all the files in `config/webpack/*`, etc.

Am I supposed to move everything out of the `client/` directory and start using this new webpack config, instead of the config at `client/webpack.config.js`?

After running `rails webpacker:install`, the build seems to work fine, but I'm still confused about how this is all supposed to work together. For example, `rails webpacker:install` created a file at `app/javascript/packs/application.js`, and I don't know where that fits in.

Thanks for your time, and any help would be greatly appreciated!

**Comment by justin808** [comment]
@ndbroadbent Webpacker is overriding the precompile from React on Rails. Thanks for letting me know about this issue. I'm going to try to fix this tonight.

**Comment by justin808** [comment]
see 9.0.0.beta.10

be sure to run `bundle update webpacker`

**Comment by ndbroadbent** [comment]
@justin808 Thanks for your help! I updated to `react_on_rails` version `9.0.0.beta.9`, and also updated the `webpacker` branch to `issue-464-merge-webpacker-lite-into-webpacker-v3`. I saw [this commit](https://github.com/shakacode/webpacker/commit/89a59a3ceb7d6e5c9eaab01b841efa568564d21d), so I added `custom_compile: true` to my `config/webpacker.yml`.

When I run `rake assets:precompile`, now I'm getting the following error:

```
$ cd client && yarn install
yarn install v0.24.6
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 1.09s.
✨  Done in 1.48s.
Compiling…
Compilation failed:

/Users/ndbroadbent/.rvm/rubies/ruby-2.4.0/bin/ruby: No such file or directory -- ./bin/webpack (LoadError)
```

**Comment by ndbroadbent** [comment]
P.S. I removed all of the files generated by `rails webpacker:install`, because it doesn't seem like those are necessary if there's a "custom compile".

**Comment by justin808** [comment]
@ndbroadbent My guess is that you added `custom_compile: true` to somewhere other than the default section. If you look at my commit in the webpacker branch, the code to do `/Users/ndbroadbent/.rvm/rubies/ruby-2.4.0/bin/ruby: No such file or directory -- ./bin/webpack (LoadError)` cannot run.

Please let me know what you see.

**Comment by justin808** [comment]
This is fixed in the latest beta, @ndbroadbent
