### ISSUE TITLE
Option for generating custom react_on_rails path instead of `./client` path

### ISSUE THREAD

**Issue by clthck** [shakacode/react_on_rails#918]
Since Rails 5.1, we have `package.json` and `node_modules` folder in the root path of the Rails app.
With `react_on_rails`, we are going to have another `package.json` and `node_modules` inside `client` folder. I've always thought of this folder structure not very intuitive and helpful while using `react_on_rails` gem.

Here's what my structure looks like when using this gem:

```
- app
  |-- assets
        |-- config
        |-- images
        |-- javascripts
        |-- stylesheets
        |-- webpack
             |-- components
             |-- .babelrc
             |-- application.js
             |-- components-registration.js
- ...
- node_modules
- package.json
- webpack.config.js
- yarn.lock
- ...
```

Although `react_on_rails` doesn't seem to provide any option to customize the whole path, I've managed to customize it to fit to my needs. However, I'm having a tiny issue regarding precompiling assets in production mode.

`config/react_on_rails.rb`
```rb
ReactOnRails.configure do |config|
  config.npm_build_production_command = "yarn run webpack:build:production"
end
```

I have `webpack:build:production` script in my the only `package.json` (in the root path).
When I run `bin/rails assets:precompile`, it looks like the gem hooks up the precompilation process and tries to run this:
`cd client && yarn run webpack:build:production`
This obviously fails, because I don't have `client` folder in my app root path.

So I had to do one of the following things:
- Set `config.npm_build_production_command = nil` and inject custom build script into `package.json`, e.g., `"build": "bin/rails assets:precompile && yarn webpack:build:production"`
- Make empty `client` folder on the root path and use single `bin/rails assets:precompile`.

These all both don't look quite nice and I'd really appreciate if I had an option to customize react_on_rails client folder path.

**Comment by justin808** [comment]
@clthck We could certainly make this customizable in the config/initializers/react_on_rails.rb.

I'd happily consider a PR for this.

**Comment by clthck** [comment]
@justin808 Maybe I didn't make it clear enough in my first comment. Having an option to customize `client` folder path is not a priority for me at the moment. I think it will make me a little happier if the gem doesn't prepend `cd client && ` to the `config.npm_build_production_command` while hooking precompiling assets process, and `react_on_reails` generator explicitly sets the `config.npm_build_production_command = "cd client && yarn run build:production"` in the `config/react_on_rails.rb` file. This will solve my headache for the time being.

**Comment by justin808** [comment]
See #925.

I'm in the middle of making this change for 9.0!
