### ISSUE TITLE
`examples` folder

### ISSUE THREAD

**Issue by robwise** [shakacode/react_on_rails#92]
The idea is to have a Rakefile script that runs through the generator with differing options, putting each result into an `examples` folder. We would then implement a hidden `dev_tests` (or whatever we want to call it) generator that the script makes sure to always pass. A hidden generator is one that is not visible to the public but is nonetheless able to be invoked if you know the command.

This generator will create general sanity tests to ensure various essential functionalities of each result application is working correctly. We could ensure that our CI environment re-generates these results and runs these tests, thereby preventing a scenario where we pull something that breaks the generator apps. 

Whether or not we include the `examples` directory in source control I guess is optional, but I'd be worried that they would sometimes be stale since they would rely on the user making sure to re-generate of their changes.

- [x] create Rakefile script to generate apps into `examples` folder
- [x] ensure that Coveralls, the various linters (actually, we could keep the JS linters), are set up to ignore it
- [x] create hidden `dev_test_generator`
- [x] have generator results script use this option when generating the apps
- [x] have Rakefile include generated app tests when running test suite
- [ ] *move spec/dummy tests to the `dev_test_generator` and delete dummy apps (optional because this wouldn't work as far as ensuring React v13 compatibility)*
- [x] ensure our CI environment handles all of this appropriately
- [x] refactor so that we do not unnecessarily rebuild the app, re-run bundle install, or re-run npm install when we don't need to do so
- [ ] incorporate the ability to generate the apps in a separate location and push them to a given GitHub (basically the generator results functionality)

**Comment by justin808** [comment]
@robwise No need to make it hidden probably. Useful to show what happens.

**Comment by justin808** [comment]
@robwise should we close this?

**Comment by robwise** [comment]
@justin808 this has been on hold while I've been working on other things, but it's actually just about ready to go after I make some performance optimizations. Should be really cool! This is what allows us to  have CI ensure the generator apps actually work!

**Comment by robwise** [comment]
You can preview the branch here: https://github.com/shakacode/react_on_rails/tree/examples-folder

**Comment by robwise** [comment]
Closing for now
