### ISSUE TITLE
Disabling rake tasks overrides of asset:precompile

### ISSUE THREAD

**Issue by monkseal** [shakacode/react_on_rails#924]
Hello, I have the latest from the `rails-webpacker` branch working in an existing project that has `webpacker` (with a ton of legacy jquery). My project setup has some differences from the react_on_rails defaults, specifically, it has all the js in `app/javascript`. Everything is building correctly with webpacker and  ReactOnRail, server-side rendering in development but I have to disable the overriding of `asset:precompile`. Do you guys have any plans to disable these tasks or at least make them optional? 

This is the only change I made to your branch in my fork: https://github.com/secondrotation/react_on_rails/commit/cb805cdc78e289482d5e0a197d89d6f7bf3c59cd

**Comment by justin808** [comment]
@monkseal I'm in the middle of the 9.x release. You can disable the precompile per the instructions in this doc: https://github.com/shakacode/react_on_rails/blob/master/docs/additional-reading/heroku-deployment.md

**Comment by justin808** [comment]
@monkseal I'm going to close this one for now. Please comment if you still need help with this issue.

**Comment by monkseal** [comment]
@justin808 yeah, I still need to try out your suggestion just got pulled away to other thing.  Once I have something working I'll paste up my solution, I think what you suggest would work for my use case. Thanks! 🤙
