### ISSUE TITLE
Flexibility in configuration of directories to better support rails/webpacker?

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#925]
I'm considering a couple of options for React on Rails regarding directory configuration to work better with rails/webpacker.

* *Client Side Code*: All files related to generation of client side bundles, including JS, CSS, images, webpack configuration, node modules, etc.
  * `/client/node_modules`
  * `/client/package.json`

* rails/webpacker directory structure:
  * `/app/config/webpacker.yml`
  * `/bin: binstubs of `webpack` and `webpack-dev-server`
  * `/package.json`
  * `/node_modules`

In my branch for 9.0, I've added this:

```
  config.node_modules_path = '' # Pre 9.0.0 used /client
```

And I'm going to change the default installer to use a top level `/node_modules`.

**Comment by nratter** [comment]
can you also add support for webpacker.yml.erb in case ruby code needs to be injected into the yml?

**Comment by justin808** [comment]
@nratter you sure can! try it and let me know how it works out.

This issue is closed as the flexibility to do any setup is just based on:

this for 8.0 and prior default:
```ruby
config.node_modules_location = "client" 
```

or for the 9.0 default:

```ruby
config.node_modules_location = "" 
```
