### ISSUE TITLE
CSS Modules SSR doesn't output anything

### ISSUE THREAD

**Issue by chhuang** [shakacode/react_on_rails#931]
I can see the class being applied, but the CSS is not there. I'm using the server config only:

https://github.com/shakacode/react-webpack-rails-tutorial/blob/master/client/webpack.server.rails.build.config.js#L55-L65

**Comment by justin808** [comment]
If you want personalized help on this, please consider our [Coaching Plan](http://www.shakacode.com/work/shakacode-coaching-plan.pdf).

Your question is specific to your project rather than this project, so it's best handled privately.
