### ISSUE TITLE
redux_store and immutable

### ISSUE THREAD

**Issue by addicted2sounds** [shakacode/react_on_rails#932]
Is there any way to register store within helper, either controller that contains immutable objects from `Immutable.js` library? I'd like to register simple store that'll be shared for several components on page, but I'd like that to use Immutable objects

**Comment by justin808** [comment]
@addicted2sounds Stores that use immutable are 100% supported.

I believe that the https://github.com/shakacode/react-webpack-rails-tutorial source uses that.

If you want personalized help on this, please consider our [Coaching Plan](http://www.shakacode.com/work/shakacode-coaching-plan.pdf).
