### ISSUE TITLE
Do we need Client folder in v9 ?

### ISSUE THREAD

**Issue by Shubham-Sinha** [shakacode/react_on_rails#935]
After migrating from v8 to v9. I get a ``app/javascript`` folder as well as ``Client`` folder. Do we need these two. I'm working on Rails 4 and the tutorial for that is highly confusing. Ex: If I am installing ``webpacker`` and configuring ``react`` with it, then why should I also install react_on_rails. How to change the default ``hello-world-bundle``

**Comment by justin808** [comment]
@Shubham-Sinha did you figure out your issues?

**Comment by Shubham-Sinha** [comment]
Yeah I got totally confused with the change
