### ISSUE TITLE
Draw a component with webpacker and npm-pipeline-rails

### ISSUE THREAD

**Issue by majioa** [shakacode/react_on_rails#937]
Hello, I'm trying to render React component from a file but the file just contain render and some other methods to  draw a dom code:

    @Calendaries = React.createClass
          render: ->
             React.DOM.div

I'm using 'webpacker' along with the 'npm-pipeline-rails' gems and my react (and other js) tree is placed at: `app/webpack/js/behaviors/`

So when I define the code to render the component as follows in a slim view:

    = react_component 'Calendaries', { props: { data: calendaries } }

It draws nothing. I see inthe resulted HTML just react definitions to apply a drawing then.
When I added the explicit declarations to JS as follows:
   
     import ReactOnRails from 'react-on-rails';
     ReactOnRails.register('Calendaries');

It draws nothing also. 

How correctly force to draw the component?

**Comment by justin808** [comment]
I'd look for errors in the browser. This doesn't look like a React on Rails issue. You definitely have to register the component.

**Comment by majioa** [comment]
There are no errors in the browser %(
