### ISSUE TITLE
Generated package.json in client folder has an error

### ISSUE THREAD

**Issue by iDev0urer** [shakacode/react_on_rails#94]
When I installed it and tried to run foreman it told me that package.json had a trailing comma. Sure enough when I looked it had one on line 32.

```
    "build:server": "NODE_ENV=production webpack --config webpack.server.rails.config.js",
    "build:dev:client": "webpack -w --config webpack.client.rails.config.js",
    "build:dev:server": "webpack -w --config webpack.server.rails.config.js", // Right here
  },
  "dependencies": {
    "babel-core": "^5.8.25",
```

**Comment by justin808** [comment]
@iDev0urer What version of node are you using? 

@robwise JSON, unlike JS should not have trailing commas. Please update your branch for which we'll push a new version ASAP.

**Comment by robwise** [comment]
@justin808 It's already been fixed

**Comment by iDev0urer** [comment]
@justin808 the latest stable release, v5.0.0

**Comment by robwise** [comment]
okay this is fixed in the published gem now, closing
