### ISSUE TITLE
Improve README structure

### ISSUE THREAD

**Issue by rodrigobdz** [shakacode/react_on_rails#941]
@justin808 I would like to help restructuring the README to comply with the [recommended format by Github](https://guides.github.com/features/wikis/#Formatting-a-readme). The current README can be pretty confusing.

**Comment by justin808** [comment]
@rodrigobdz That would be very awesome. Ideally, you could work with me and @Judahmeek on this. We also publish this to a gitbook.

Keep in mind that we need to keep the sales pitch for our services, as this project is the main way that we find clients which allows us to keep maintaining this project.

Please start a PR! and we'll discuss there.
