### ISSUE TITLE
Attempting to install react_on_rails in my project throws an error in old views

### ISSUE THREAD

**Issue by JarLowrey** [shakacode/react_on_rails#943]
The added `hello_word` works fine, but by old `.erb` views now crash with the following error. Has this been seen before? If I start a new project from scratch it seems to work fine but it causes these crashes in my main project that I am attempting to integrate with React. Using Rails 5.1.1, react_on_rails 9.0.0 and webpacker 3.0.

```
18:50:40 web.1    | Completed 500 Internal Server Error in 65842ms (ActiveRecord: 0.0ms)
18:50:40 web.1    | 
18:50:40 web.1    | 
18:50:40 web.1    |   
18:50:40 web.1    | ActionView::Template::Error (uninitialized constant ERB::Runner):
18:50:40 web.1    |     20:     <%= canonical_tag -%>
18:50:40 web.1    |     21: 
18:50:40 web.1    |     22: 
18:50:40 web.1    |     23:     <!-- general assets -->
...
```

**Comment by JarLowrey** [comment]
Occurs even if the ror gem is not present but webpacker is installed. Tried removing the following gems and their references in application.js and application.css - autoprefixer-rails, jquery-rails, jquery-ui-rails, bootstrapp-css, client_side_validations, client_side_validations-simple_form, cocoon. Error is still thrown

**Comment by justin808** [comment]
> Occurs even if the ror gem is not present but webpacker is installed. 

Please report to the https://github.com/rails/webpacker/issues then.

**Comment by JarLowrey** [comment]
Seemingly fixed by deleting local installation and re-pulling from VCS
