### ISSUE TITLE
[Q] Server side initial data loading (with ajax)

### ISSUE THREAD

**Issue by n23daniel** [shakacode/react_on_rails#948]
I'm using latest version of react_on_rails and react router v4 with redux.

I dispatch an action in the component to fetch with ajax like so:
```
componentWillMount() {
    this.props.getUsers()
}
```

Basically, I want the ```renderToString``` in my ServerRouter.js to wait until the ajax request finishes. Using redux-logger and the redux-promise-middleware, I can see on the server logs only the "-PENDING" action gets dispatched, never getting to the "-FULFILLED" one.

This is my ServerRouter.js:
```
import React from 'react'
import { renderToString } from 'react-dom/server'
import { StaticRouter } from 'react-router'
import { Provider } from 'react-redux'

import routes from '../config/routes'
import store from '../config/server-store'

export default (props, railsContext) => {

  let context = {}
  const { location } = railsContext

  let markup = renderToString(
    <Provider store={store}>
      <StaticRouter
        location={location}
        context={context}>
        {routes}
      </StaticRouter>
    </Provider>
  )

  if (context.url) {
    return {
      redirectLocation: result.redirect.pathname
    }
  } else {
    return { renderedHtml: markup }
  }
}
```

Thanks guys in advance!

**Comment by justin808** [comment]
Hi @n23daniel. What makes you believe that this issue is React on Rails related?

For server rendering, think of this as simply the Rails server executing a function and your function must return some markup.

If you want renderToString to wait, then you must use something like an ES7 style async/await function pattern:

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/async_function

**Comment by n23daniel** [comment]
I believe this is React on Rails related because at the moment I can't find a way to return a Promise from the server router. I can only return synchronously, otherwise I get the following error: "[SERVER] message: renderToString(): You must pass a valid ReactElement."

A really simple example of what I'm trying to achieve is

```
export default (props, railsContext) => {
  let context = {}
  const { location } = railsContext

  let markup = renderToString(
    <Provider store={store}>
      <StaticRouter
        location={location}
        context={context}>
        {routes}
      </StaticRouter>
    </Provider>
  )

  return new Promise(resolve => {
    setTimeout(() => {
      resolve({ 
        renderedHtml: renderToString(
          <Provider store={store}>
            <StaticRouter
              location={location}
              context={context}>
              {routes}
            </StaticRouter>
          </Provider>
        )
      })
    }, 1000)
  })
}
```

I think it's really important to be able to do this with React on Rails especially for SEO purposes so the dynamic data will be available in the rendered HTML. I've seen this can be done with Node backend as you can do `res.send(renderedHtml)` asynchronously.

**Comment by justin808** [comment]
> I think it's really important to be able to do this with React on Rails especially for SEO purposes so the dynamic data will be available in the rendered HTML. I've seen this can be done with Node backend as you can do res.send(renderedHtml) asynchronously.

How would you do that Asynch for a Rails request? @n23daniel

**Comment by n23daniel** [comment]
I'm not a rails developer. I only know the basics, but as I'm aware there are ways to make async requests with rails. Still, isn't React on Rails using MiniRacer to run the js? Can't it wait for a promise?

Maybe I'm talking non-sense, but that's because of the lack of rails knowledge I have. Thanks for your interest though! I'd want to know if it's possible to adapt somehow to work by returning a promise, calling a callback or something similar.

**Comment by n23daniel** [comment]
Ok, so I see the inability to render async react originates from ExecJS not supporting async eval of the js. My only solution left, as I really need to render async js, is to drop react on rails and make the rendering on a standalone node server.

**Comment by justin808** [comment]
@n23daniel are you sure that you can't wait until the promise executes? Did you try using async/await or another pattern so your function does not return until the remote call finishes?

**Comment by n23daniel** [comment]
@justin808 Using async/await, in the end the result is still a promise, like in the official example:
```
async function add2(x) {
  const p_a = resolveAfter2Seconds(20);
  const p_b = resolveAfter2Seconds(30);
  return x + await p_a + await p_b;
}

add2(10).then(v => {
  console.log(v);  // prints 60 after 2 seconds.
});
```
ExecJS wouldn't wait for the async function to resolve.

A solution would be to do something like bellow, but it is really bad because it blocks the whole thread.
```
export default (props, railsContext) => {
  let context = {}
  const { location } = railsContext
  let markup

  // Do initial render to dispatch async actions
  renderToString(
    <Provider store={store}>
      <StaticRouter
        location={location}
        context={context}>
        {routes}
      </StaticRouter>
    </Provider>
  )

  waitAsyncForStoreToPopulateWithData().then(() => {
    // Do second render with populated store
   markup = renderToString(
      <Provider store={store}>
        <StaticRouter
          location={location}
          context={context}>
          {routes}
        </StaticRouter>
      </Provider>
    )
  })

  // Block thread until markup gets a value async
  while (!markup) {}

  return markup
}
```
 So right now it could only work if ExecJS would be able to wait for a promise or have a callback, but it seems like this won't happen anytime soon: https://github.com/sstephenson/execjs/pull/35
This means the only solution is a dedicated node server. I think it would be cool if React on Rails would open a standalone node server in the background to communicate with the Rails server via http requests.
For example http://localhost:3020?component=MyApp would render MyApp registered component. This way something like this would do the job in the node server:
```
app.use((req, res) => {
  // Scenario when React on Rails component is a promise
  ReactOnRails.getComponent(req.query.component).then(data => {
    res.status(200).send(data)
  }, err => {
    res.status(500).send(err)
  })
})
```
It might not be the best solution performance-wise as on a large app you'd also need to scale the node server, but it could do the job done. Also the ExecJS isn't ideal as it's performing long synchronous tasks.

**Comment by justin808** [comment]
@n23daniel We have built a rendering engine using Node and Express. Maybe this is a good use for this? Nevertheless, the Rails view rendering response/request cycle would still need to wait...

**Comment by colinrcummings** [comment]
@n23daniel, were you ultimately able to execute server-side xhr requests with react_on_rails? If so, then how did you do so? Running into the same issue.

**Comment by n23daniel** [comment]
@colinrcummings Nope, after spending lots of time trying to find a solution with rails, I ended up making a node server to handle the server side rendering and using the Rails as a standalone API. There are lots of boilerplates to start from already available. There's also https://github.com/zeit/next.js/ which seems promising.

**Comment by colinrcummings** [comment]
Thanks, @n23daniel. That's what I suspected; I'm probably going to go down the same road. Have a couple questions about your approach. If you've got the time, hit me up at colinrcummingsATgmailDOTcom. Thanks!
