### ISSUE TITLE
Consumption of react component of a Rails Engine by an application

### ISSUE THREAD

**Issue by alexjose74** [shakacode/react_on_rails#954]
**NOTE: This is a question.**

I have written a rails engine which has a single component - `NewComponent`. It uses react_on_rails. This has been tested via the dummy application of the rails engine. I imported and registered the component in dummy application:
`/new_engine/test/dummy/client/app/Index.jsx`:

```
import NewComponent from '../../../../client/app/pages/user_home_page/NewComponent';

ReactOnRails.register({
NewComponent,
});
```
The above worked completely fine in the dummy app.

Now I am consuming this react component as a rails engine in a full fledged application. How can I import this component so that I can register it in the application? In the dummy application I was able to give a relative path to import the component. Such a relative path will not be possible in the application while consuming the gem.

I have checked online for an answer to this, but there seems to be very less documentation on react_on_rails with engines.

**Comment by alexjose74** [comment]
@justin808 could you please provide some on this? We have been blocked on this for a while now and we finally decided to ask you guys directly.

**Comment by justin808** [comment]
@alexjose74 We'd love to help you directly. However, we have to prioritize help requests by supporters of our project, such as https://egghead.io.

Would you be interested in a support contract, like Egghead has purchased? Please email me directly at justin@shakacode.com.

**Comment by alexjose74** [comment]
Thanks for your respose @justin808. Currently we are not looking for a support contract.

**Comment by justin808** [comment]
@alexjose74 If you find the answer, a doc PR is appreciated!

**Comment by alexjose74** [comment]
@joerodrig  that would be really helpful! I never went beyond this level of investigation.
