### ISSUE TITLE
deploy on elastic beanstalk: webpack-dev-server not started

### ISSUE THREAD

**Issue by MatthiasRMS** [shakacode/react_on_rails#958]
Hi,

I've followed your guide on how to deploy to elastic beanstalk, but I still get a 404 when my app tries to get the packs. 

It seems like yarn works fine, but webpack-dev-server isn't starting so it doesn't serves the JS files.

What additional setup should I do to get it to run ?
@chrisjones-tripletri I've followed your guide, any other input? 

Thanks

**Comment by justin808** [comment]
@MatthiasRMS I'm quite sure those docs apply to an older version. Please submit a PR with an update once you figure out the differences.

Also, the webpack-dev-server should only be run during development and never production.

**Comment by MatthiasRMS** [comment]
@justin808 I will !

If i'm not supposed to use webpack-dev-server, which process is supposed to serve the files ?

**Comment by justin808** [comment]
Use the compiled files. The "output" from webpack.
