### ISSUE TITLE
Bootstrap as an option

### ISSUE THREAD

**Issue by yorzi** [shakacode/react_on_rails#96]
My existing Rails application is using Foundation instead of Bootstrap. I am wondering if Bootstrap can be an option in generator, if so, that'd be great.

**Comment by justin808** [comment]
@yorzi We'd like to do that! Any chance you can help us with that?

**Comment by yorzi** [comment]
@justin808 sure, I'd like to contribute something to this gem, but I am not sure where to start.. This might be a good one. :)

**Comment by justin808** [comment]
@robwise and @jbhatab can give you some tips!

**Comment by yorzi** [comment]
@justin808 ok, I will ping them in slack room if I encounter problems.

**Comment by justin808** [comment]
@yorzi, actually @aaronvb would be a great guy to pair with on this one! @aaronvb did the amazing work of getting the generator code going.

**Comment by robwise** [comment]
@yorzi the way I wrote the generators, everything related to Bootstrap is already isolated and put inside its own generator called `bootstrap_generator`. Everything is initiated from the `install_generator`, so follow the lead from the other generator options in that file and you should be able to just not called the bootstrap_generator with a conditional that checks the options, just like the other ones (you'll see if you look at the file).

**Comment by yorzi** [comment]
@robwise let me try to work on that.
