### ISSUE TITLE
Server Side Rendering is not working?

### ISSUE THREAD

**Issue by risinglf** [shakacode/react_on_rails#964]
Hi,

I'm trying SSR with the hello_world_example:

- react_on_rails 10.0.0
- rails 5.1.4
- mini_racer 0.1.14

When i change views/hello_world/index.html.erb to:

`<%= react_component("HelloWorld", props: @hello_world_props, prerender: true) %>`

and I reload the page, I see this error:

`undefined local variable or method `e' for ReactOnRails::ServerRenderingPool::Exec:Class`

Is this a known bug?

Thanks a lot

**Comment by justin808** [comment]
See #963. We'll be releasing very shortly.

**Comment by railsme** [comment]
@justin808 This issue may be closed, I think?

**Comment by justin808** [comment]
Thanks @railsme!
