### ISSUE TITLE
What's the latest "stable" RoR version?

### ISSUE THREAD

**Issue by vfonic** [shakacode/react_on_rails#979]
First of all, thanks for incredible gem!!! :)

I'm just on-boarding and following documentation/tutorials. It seems that the latest released version is 10.0.2. However, I can't find many references to that gem version in the documentation:

https://github.com/shakacode/react_on_rails/tree/10.0.2#basic-installation-for-a-new-rails-app

https://github.com/shakacode/react_on_rails/blob/master/docs/tutorial.md#react-on-rails-basic-tutorial

Should I use 10.0.2 or 9.x?

Thanks!

**Comment by justin808** [comment]
@vfonic Could you please replace any references to 9.x to say "latest" and submit a PR?

Yes, the latest has critical bug fixes! Thanks for your support!
