### ISSUE TITLE
Component generated with --redux option does not use Redux

### ISSUE THREAD

**Issue by nicnilov** [shakacode/react_on_rails#986]
When using the `install` generator with `--redux` option as described in [generator.md](https://github.com/shakacode/react_on_rails/blame/3ca295bec2e4e4cce96b3941b7658794a06c931b/docs/basics/generator.md#L61) the generated HelloWorld component does not use Redux store and uses local state instead.

Specifically, [HelloWorld.jsx#L28](https://github.com/shakacode/react_on_rails/blob/4f58a66da9332f571b4fc890707c21569006d603/lib/generators/react_on_rails/templates/base/base/app/javascript/bundles/HelloWorld/components/HelloWorld.jsx#L28) line

```javascript
Hello, {this.state.name}!
```

should read 

```javascript
Hello, {this.props.name}!
```

and lines [HelloWorld.jsx#L38-L39](https://github.com/shakacode/react_on_rails/blob/4f58a66da9332f571b4fc890707c21569006d603/lib/generators/react_on_rails/templates/base/base/app/javascript/bundles/HelloWorld/components/HelloWorld.jsx#L38-L39)

```javascript
value={this.state.name}
onChange={(e) => this.updateName(e.target.value)}
```

should be

```javascript
value={this.props.name}
onChange={(e) => this.props.updateName(e.target.value)}
```

With integrated Redux the [this.updateName](https://github.com/shakacode/react_on_rails/blob/4f58a66da9332f571b4fc890707c21569006d603/lib/generators/react_on_rails/templates/base/base/app/javascript/bundles/HelloWorld/components/HelloWorld.jsx#L20-L22) arrow function is not needed as the Redux-enabled one is supplied by HelloWorldContainer through props.

[Constructor](https://github.com/shakacode/react_on_rails/blob/4f58a66da9332f571b4fc890707c21569006d603/lib/generators/react_on_rails/templates/base/base/app/javascript/bundles/HelloWorld/components/HelloWorld.jsx#L12) is also not strictly necessary.

Finally, comments mentioning props coming from the Rails view are misleading as the props now are coming from the Redux store.

**Comment by justin808** [comment]
@nicnilov Nice catch. Would you be interested in working together to help resolve this issue?

**Comment by justin808** [comment]
@nicnilov Please send me an email: justin@shakacode.com and I'll invite you to our Slack room.

**Comment by nicnilov** [comment]
@justin808 Sure, I can take a look although it might take some time because of my schedule. How do you want it, make HelloWorld.jsx a template and use placeholders or have a separate  HelloWorld.jsx to use with Redux?

**Comment by justin808** [comment]
@nicnilov Do you still want to own this one?

Does anybody else want to?

**Comment by nicnilov** [comment]
@justin808 It wouldn't be realistic to expect me get to it anytime soon, sorry! If no one takes it I might be able to take care of it in mid-January.

**Comment by lewaabahmad** [comment]
@justin808 I can own this!

**Comment by justin808** [comment]
@lewaabahmad Please get me a PR to review!

**Comment by lewaabahmad** [comment]
@justin808 https://github.com/shakacode/react_on_rails/pull/1006

I found that the file that @nicnilov pointed out is actually alright. What I found to be wrong was the file path in `lib/generators/react_on_rails/react_with_redux_generator.rb` - the root HelloWorld.jsx component was being copied from 'base/base' rather than 'redux/base' in the templates directory.

**Comment by radixhound** [comment]
@justin808 Seems that this bug can be closed
