### ISSUE TITLE
Router issue without Redux

### ISSUE THREAD

**Issue by white112** [shakacode/react_on_rails#988]
![screenshot 2017-11-21 22 59 31](https://user-images.githubusercontent.com/22128210/33096434-ac7522da-cf0f-11e7-8e03-e6dc3a2b30d1.png)
I have installed react_on_rails gem on new rails project.  And there was only hello_world component.
I am going to add router for this project.  I followed react-webpack-rails-tutorial and then I got this error.

Uncaught Error: ReactOnRails encountered an error while rendering component: App.
Original message: Could not find component registered with name App. Registered component names include [ RouterApp ]. Maybe you forgot to register the component?

![screenshot 2017-11-21 22 57 51](https://user-images.githubusercontent.com/22128210/33096382-7495c432-cf0f-11e7-9337-3cbc1baedfb9.png)
![screenshot 2017-11-21 22 59 15](https://user-images.githubusercontent.com/22128210/33096428-a777d070-cf0f-11e7-88e6-6b1cc8f61447.png)

My code structure is like this.
I want help

**Comment by justin808** [comment]
@white112, 
 
Would you be interested in our ShakaCode Pro Support plan? 

http://www.shakacode.com/work/shakacode-pro-support.pdf

If so, please schedule a complimentary 30-minute consultation:
https://calendly.com/justingordon

Thanks,

Justin

**Comment by justin808** [comment]
@white112 The message says that you're looking for `App` when your code is registerering `RouterApp`.
