### ISSUE TITLE
Need to (optionally) add defer to the inline script

### ISSUE THREAD

**Issue by justin808** [shakacode/react_on_rails#99]
See:
http://stackoverflow.com/questions/436411/where-is-the-best-place-to-put-script-tags-in-html-markup

If the head script includes "defer" in the application.js (which it should!), then we need to include defer in the body scripts!

CC: @robwise @mapreal19 @josiasds @alexfedoseev @dylangrafmyre @samnang @rstudner

**Comment by justin808** [comment]
How's this sound for the doc change:

 `script_options:` Anything passed to the inline script tags that we generate, such as “defer”, which would be necessary if you are using “defer” in your inclusion of `application.js`.

Like other rendering settings, this can be configured as a default in `config/initializers/react_on_rails.rb` or can be specified in the helper tag. We recommend that if you are always including `application.js` with 'defer', then you should set this value in your initializer.

**Comment by justin808** [comment]
Another reference:
http://stackoverflow.com/questions/22429724/how-can-i-defer-javascript-files-not-in-use-in-my-rails-app-to-make-the-app-run

We also need to consider if there's any interactions with turbolinks.

@alexfedoseev thoughts?

**Comment by justin808** [comment]
Posted discussion here: http://forum.shakacode.com/t/should-rails-apps-use-defer-when-loading-application-js/404/1

**Comment by robwise** [comment]
Is this necessary when using a react-heavy app? What's the advantage of having the page load before the React components have been rendered?

**Comment by justin808** [comment]
This is not the right strategy of using `defer`. Closing this as it will be addressed when addressing #105.

![2015-11-21_10-37-03](https://cloud.githubusercontent.com/assets/1118459/11320423/cfe9721c-903b-11e5-97e7-08674c6b64ea.png)
