### ISSUE TITLE
merging additional props into a "root" redux store

### ISSUE THREAD

**Issue by pRdm** [shakacode/react_on_rails#990]
Suppose you have a component (`Header`) that is rendered on every page and this is using a redux store `rootStore` as its source of data. The `rootStore` is hydrated with some rails data in the `application_controller` with a `before_action`.

You decide to add another component (`Form`) that's only used on _some_ pages, and requires an additional set of states to be hydrated by rails.

As far as I know (please correct me as I'm a noob around town), there are some imperfect ways to implement this:

1. include the `Form` data in the `application_controller` `before_action`, all the time, even if its not required. (introducing redundant data into the store, especially as the `Form` data is quite large)

2. implement a separate store for the data that's used by the `Form` component. (but this goes against the redux idiom of having a _single_ source of information

3. be explicit and remove the common `before_action`. Have each controller action hydrate the `rootStore` individually (depending on whether it needs to render the data for `Form`). Caveat is that this is super labor intensive if we have a lot of controllers / actions, and its not really DRY. (afaik this is the cleanest way)

Is there a better way to do this? Maybe allowing us to call `redux_store` in the controller multiple times and have the states be `deep_merge`d together into the `rootStore`?

Thanks in advance!

**Comment by justin808** [comment]
@pRdm we've got this scenario going for our app: https://www.hawaiichee.com. 

Would you be interested in our [ShakaCode Pro Support plan](http://www.shakacode.com/work/shakacode-pro-support.pdf)? 

We could definitely help you in this situation.

If so, please schedule a complimentary 30-minute consultation:
https://calendly.com/justingordon

Thanks,

Justin
