### ISSUE TITLE
Instructions to upgrade from v7.x => v10.x

### ISSUE THREAD

**Issue by evolve2k** [shakacode/react_on_rails#993]
Fantastic work on including webpacker, I've been following along on all your work on this project and on webpacker in discussions with the Rails team and it's admirable all the effort you folks have put in. 

I'm now keen to upgrade! 

In the blog post [Introducing React on Rails v9 with Webpacker Support](https://blog.shakacode.com/introducing-react-on-rails-v9-with-webpacker-support-f2584c6c8fa4) you announced "My next article will document migration details of moving from v7 or earlier to v9."

I think Im not alone in saying that migrating from the original react_on_rails to the new world that integrates with webpacker is daunting and would appreciate this step by step guide so I can get up-to-date with the project as I'm suddenly (for good reason) 3 versions behind.

Personally I've even (probably unnecessarily) held back to stay on Rails 5.0 so as not to have to worry about Webpacker in Rails 5.1 possibly interfering with React On Rails until I knew that the new React On Rails release was live.

Would love a step by step guide to migrating.

Thanks!

**Comment by justin808** [comment]
@evolve2k Let me know if is sufficient: https://github.com/shakacode/react_on_rails/blob/master/docs/basics/upgrading-react-on-rails.md

If not, I'll reopen this issue.
