### ISSUE TITLE
Unknown Error from React_on_rails webpack compile

### ISSUE THREAD

**Issue by Champer** [shakacode/react_on_rails#995]
I tried new version React On Rails v10.0.2 first time I open the server by  command ```foreman start -f Procfile.dev```  and I got ```Syntax Error:Unexpected token```
as following:
```
01:00:27 client.1 | ERROR in ./app/javascript/bundles/HelloWorld/components/HelloWorld.jsx
01:00:27 client.1 | Module build failed: SyntaxError: Unexpected token (26:6)
01:00:27 client.1 |
01:00:27 client.1 |   24 |   render() {
01:00:27 client.1 |   25 |     return (
01:00:27 client.1 | > 26 |       <div>
01:00:27 client.1 |      |       ^
01:00:27 client.1 |   27 |         <h3>hello</h3>
01:00:27 client.1 |   28 |       </div>
01:00:27 client.1 |   29 |     );
01:00:27 client.1 |
01:00:27 client.1 |  @ ./app/javascript/packs/hello-world-bundle.js 3:0-69
```

I can't understand why I got error, I written it before like it.
And I tried to find ```webpack.config.js``` file, to watch the problem, but there is no it.
The new version of react_on_rails has no ```webpack``` file?

**Comment by justin808** [comment]
You need way more information to report an issue. My guess is that you should try the tutorial steps again from scratch.
