### ISSUE TITLE
The file extension of `config.server_bundle_js_file` should be ignored

### ISSUE THREAD

**Issue by ttanimichi** [shakacode/react_on_rails#997]
Even if we have a pack file that has `.jsx` file extension like `app/javascript/packs/app.jsx`, webpacker compile it to a `.js` file like `public/packs/app-6c71877ae5cf6273d047.js`.

So, if we specify `config.server_bundle_js_file` like

```
config.server_bundle_js_file = "app.jsx"
```

We get an Error like

```
No such file or directory @ rb_file_s_mtime - /Users/tanimichi.tsukuru/Desktop/react_on_rails_example2/public/packs/app.jsx
```

We probably should ignore the file extension of `config.server_bundle_js_file`, because the only file extention we can specify as `config.server_bundle_js_file` is `.js`.

**Comment by justin808** [comment]
@ttanimichi using JSX for react files is an older standard. Webpack will always compile to a JS file. I don't think this is worth changing for now.
