### ISSUE TITLE
Problems installing the Gem

### ISSUE THREAD

**Issue by bruparelwdvg** [shakacode/react_on_rails#998]
I am having a tough time with the installation.  When I run
rails generate react_on_rails:install command, it fails with

Could not find gem 'mini_racer' in any of the gem sources listed in your Gemfile.

When I try to install the mini_racer gem with 'gem install mini_racer' gem, I get the libv8 install error message as shown below:

Building native extensions.  This could take a while...
ERROR:  Error installing mini_racer:
	ERROR: Failed to build gem native extension.

    current directory: /Users/Bharat/.rvm/gems/ruby-2.4.1/gems/libv8-5.9.211.38.1/ext/libv8
/Users/Bharat/.rvm/rubies/ruby-2.4.1/bin/ruby -r ./siteconf20171212-50567-1dwsyw0.rb extconf.rb
creating Makefile

v8 (ERROR)
----------------------------------------
[0:00:00] Started.
[0:00:00] 

I am on a mac with osx version 10.9.5.

**Comment by justin808** [comment]
Your issue should go to the miniracer repo.
