### ISSUE TITLE
Postinstall step not reading url from .npmrc registry

### ISSUE THREAD

**Issue by viren140290** [shakacode/react_on_rails#999]
Hello,

I have my project setup just like this [example](https://github.com/shakacode/react_on_rails-test-new-redux-generation/pull/17/files) mentioned in the [tutorial](https://github.com/shakacode/react_on_rails/blob/master/docs/tutorial.md). The postinstall step in my package.json, that lives on the parent level has "cd client yarn install" step just like the example's [package.json](https://github.com/shakacode/react_on_rails-test-new-redux-generation/pull/17/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R10). However, I have a .npmrc file that has a registry URL set up to an internal repo. When I run yarn install on the project, during the postinstall step it still tries to download packages from https://registry.yarnpkg.com instead of my internal repository. Is there a reason this happens? I tried testing it with npm and it does pull the dependencies from the internal repo, while with yarn it does not.

**Comment by justin808** [comment]
@viren140290 are you 100% sure that you're using the current version of React on Rails? and what version of Rails?

**Comment by railsme** [comment]
@viren140290 I'm pretty sure that this bug was fixed in previous releases. The latest version of react_on_rails is 10.0.2

**Comment by viren140290** [comment]
Thank you guys. At this point, my team has decided to push upgrading the gem task to the future. For now I switched npmrc to yarnrc and that solved the issue. Thanks for the suggestions though. This can be closed.
